define((
{ yestText: 'Oui',
  noText: 'Non',
  confirmOverwriteFileMsg: 'Vous avez un fichier importation sélectionné actuellement. Souhaitez-vous écraser ce fichier ?',
  importProgressCaption: 'Importation des résultats de processus',
  lblPrimaryProgress: 'Traitement du fichier importé, veuillez patienter...',
  lblTotalRecords: 'Nombre total de fiches :',
  lblTotalRecordsProcessed: 'Traitées :',
  lblTotalRecordsImported: 'Importées :',
  lblTotalRecordsMerged: 'Fusionnées :',
  lblTotalDuplicates: 'Doublons :',
  lblTotalProjectedDuplicates: 'Doublons projetés :',
  lblDuplicateRate: 'Taux de doublons :',
  lblTotalErrors: 'Erreurs :',
  calculatingText: 'Calcul en cours, veuillez patienter...',
  importStatusProcessing: 'Traitement en cours',
  importStatusCompleted: 'Terminé',
  abortImportProcessStatus: 'Abandonner',
  btnCancelText: 'Abandonner',
  btnCloseText: 'Fermer',
  lblImportHistoryLinkText: 'Pour voir les résultats de historique importation, cliquez sur le numéro importation ci-dessous :',
  lblImportLinkNumber: 'Numéro importation : ',
  errorRequestImportHistory: 'Une erreur est survenue lors de exécution de la demande sdata pour le point de terminaison HistoriqueImportation.' }
));