define((
{ titleText: 'Avancé',
  appearanceText: 'Apparence',
  behaviorText: 'Comportement',
  controlInfoText: 'Info contrôle',
  dataText: 'Données',
  controlIdText: 'ID de contrôle :',
  controlIdTooltipText: 'Identifiant pour ce contrôle.',
  controlTypeText: 'Type de contrôle :',
  controlTypeTooltipText: 'Type de contrôle Saleslogix.',
  dataSourceText: 'Source de données :',
  dataSourceTooltipText: 'Source des données de ce contrôle, par exemple un autre contrôle ou une entité.',
  emptyTableRowText: 'Texte de la ligne de la table vide :',
  emptyTableRowTooltipText: 'Texte à afficher si aucune donnée est affichée dans la grille.',
  expandableRowsText: 'Lignes extensibles :',
  expandableRowsTooltipText: 'Permet à utilisateur étendre les lignes de la grille pour afficher plus de texte.',
  renderVerticalText: 'Rendre vertical :',
  renderVerticalTooltipText: 'Afficher les lignes de la grille comme des colonnes.',
  showSortIconText: 'Afficher icône de tri :',
  showSortIconTooltipText: 'Afficher icône de tri sur les colonnes triables.',
  visibleText: 'Visible :',
  visibleTooltipText: 'Afficher ou masquer ce contrôle sur le formulaire.' }
));