define((
{ titleText: 'Avancé',
  appearanceText: 'Apparence',
  behaviorText: 'Comportement',
  controlInfoText: 'Info contrôle',
  dataText: 'Données',
  allowMultiplesText: 'Autoriser les sélections multiples :',
  allowMultiplesTooltipText: 'Permet à utilisateur de sélectionner plusieurs éléments.',
  canEditTextText: 'Peut modifier le texte :',
  canEditTextTooltipText: 'Permet à utilisateur de saisir une valeur.',
  controlIdText: 'ID de contrôle :',
  controlIdTooltipText: 'Identifiant pour ce contrôle.',
  controlLabelPlacementText: 'Placement des étiquettes :',
  controlLabelPlacementTooltipText: 'Position des étiquettes par rapport au contrôle.',
  controlTypeText: 'Type de contrôle :',
  controlTypeTooltipText: 'Type de contrôle Saleslogix.',
  defaultDataBindingText: 'Associations de données :',
  defaultDataBindingTooltipText: 'Champ(s) de données dans la base de données utilisée par ce contrôle.',
  displayModeText: 'Mode affichage :',
  displayModeTooltipText: 'Mode affichage du contrôle : zone de texte, lien hypertexte ou texte brut.',
  enabledText: 'Activé :',
  enabledTooltipText: 'Permet à utilisateur interagir avec ce contrôle.',
  maxLengthText: 'Longueur maxi :',
  maxLengthTooltipText: 'Nombre maximal de caractères que utilisateur peut saisir.',
  mustExistInListText: 'élément doit exister :',
  mustExistInListTooltipText: 'Nécessite que la valeur saisie soit dans la liste.',
  pickListNameText: 'Nom de la liste de sélection :',
  pickListNameTooltipText: 'Nom de la liste des valeurs que utilisateur peut sélectionner lors de la saisie des données.',
  requiredText: 'Obligatoire :',
  requiredTooltipText: 'Requiert une valeur lors de enregistrement des données.',
  storageModeText: 'Mode de stockage :',
  storageModeTooltipText: 'Façon dont la valeur est stockée : texte, id ou code.',
  visibleText: 'Visible :',
  visibleTooltipText: 'Afficher ou masquer ce contrôle sur le formulaire.',
  labelPlacementText: { left: 'Gauche', right: 'Droite', top: 'Haut', none: 'Aucun' },
  displayModeTypeText: 
   { AsControl: 'Comme contrôle',
     AsText: 'Comme texte',
     AsHyperlink: 'Comme lien hypertexte' },
  storageModeTypeText: { Text: 'Texte', Id: 'ID', Code: 'Code' },
  pickListRequestErrorText: 'Impossible de récupérer les listes de sélection du serveur.' }
));