require({cache:{
'Sage/Utility/File/nls/zh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/zh-hk/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh-hk/FallbackFilePicker',{});
},
'Sage/UI/nls/zh/Boolean':function(){
define('Sage/UI/nls/zh/Boolean',{});
},
'Sage/UI/nls/zh-hk/Boolean':function(){
define('Sage/UI/nls/zh-hk/Boolean',{});
},
'Sage/Services/nls/zh/ActivityService':function(){
define('Sage/Services/nls/zh/ActivityService',{});
},
'Sage/Services/nls/zh-hk/ActivityService':function(){
define('Sage/Services/nls/zh-hk/ActivityService',{});
},
'Sage/UI/Controls/nls/zh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/zh-hk/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh-hk/CopyToClipboard',{});
},
'Sage/Utility/nls/zh/Activity':function(){
define('Sage/Utility/nls/zh/Activity',{});
},
'Sage/Utility/nls/zh-hk/Activity':function(){
define('Sage/Utility/nls/zh-hk/Activity',{});
},
'Sage/QuickForms/Design/nls/zh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/zh-hk/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh-hk/DesignPanel',{});
},
'Sage/UI/nls/zh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh/TimelessActivitiesPane',{});
},
'Sage/UI/nls/zh-hk/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh-hk/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/zh/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/zh/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/zh-hk/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/zh-hk/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/zh/ActivityManager':function(){
define('Sage/MainView/nls/zh/ActivityManager',{});
},
'Sage/MainView/nls/zh-hk/ActivityManager':function(){
define('Sage/MainView/nls/zh-hk/ActivityManager',{});
},
'Sage/Services/nls/zh/JobService':function(){
define('Sage/Services/nls/zh/JobService',{});
},
'Sage/Services/nls/zh-hk/JobService':function(){
define('Sage/Services/nls/zh-hk/JobService',{});
},
'Sage/QuickForms/Design/nls/zh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/_PropertyEditor',{});
},
'Sage/Services/nls/zh/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh/ActivityActionProcessor',{});
},
'Sage/Services/nls/zh-hk/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh-hk/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/zh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh-hk/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh-hk/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/zh-hk/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh-hk/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPane',{});
},
'Sage/UI/Alarms/nls/zh-hk/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh-hk/AlarmPane',{});
},
'Sage/TaskPane/nls/zh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/zh-hk/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh-hk/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/zh-hk/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh-hk/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-hk/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-hk/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/zh/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh/FilterPanel',{});
},
'Sage/UI/Filters/nls/zh-hk/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh-hk/FilterPanel',{});
},
'Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/ReportManagerFormatter',{});
},
'Sage/UI/nls/zh/OwnerType':function(){
define('Sage/UI/nls/zh/OwnerType',{});
},
'Sage/UI/nls/zh-hk/OwnerType':function(){
define('Sage/UI/nls/zh-hk/OwnerType',{});
},
'Sage/TaskPane/nls/zh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-hk/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-hk/InvoiceRTDV',{});
},
'Sage/UI/nls/zh/SDataLookup':function(){
define('Sage/UI/nls/zh/SDataLookup',{});
},
'Sage/UI/nls/zh-hk/SDataLookup':function(){
define('Sage/UI/nls/zh-hk/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/zh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/RowDesigner',{});
},
'Sage/TaskPane/nls/zh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/zh-hk/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh-hk/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zh/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh/LibraryDocument',{});
},
'Sage/Utility/File/nls/zh-hk/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh-hk/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh-hk/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh-hk/SpeedSearchLookup',{});
},
'Sage/UI/nls/zh/ConditionManager':function(){
define('Sage/UI/nls/zh/ConditionManager',{});
},
'Sage/UI/nls/zh-hk/ConditionManager':function(){
define('Sage/UI/nls/zh-hk/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/zh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/zh-hk/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh-hk/WidgetDefinition',{});
},
'Sage/UI/nls/zh/SearchConditionWidget':function(){
define('Sage/UI/nls/zh/SearchConditionWidget',{});
},
'Sage/UI/nls/zh-hk/SearchConditionWidget':function(){
define('Sage/UI/nls/zh-hk/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zh/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/zh/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/zh-hk/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/zh-hk/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh-hk/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh-hk/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/zh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/zh-hk/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh-hk/DataSourcePanel',{});
},
'Sage/Library/nls/zh/Manager':function(){
define('Sage/Library/nls/zh/Manager',{});
},
'Sage/Library/nls/zh-hk/Manager':function(){
define('Sage/Library/nls/zh-hk/Manager',{});
},
'Sage/UI/nls/zh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/zh-hk/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh-hk/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/zh-hk/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh-hk/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/zh/Name':function(){
define('Sage/UI/Controls/nls/zh/Name',{});
},
'Sage/UI/Controls/nls/zh-hk/Name':function(){
define('Sage/UI/Controls/nls/zh-hk/Name',{});
},
'Sage/MainView/JobMgr/nls/zh/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/zh-hk/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh-hk/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/zh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/zh-hk/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh-hk/UpdateLeads',{});
},
'Sage/Library/nls/zh/FileHandler':function(){
define('Sage/Library/nls/zh/FileHandler',{});
},
'Sage/Library/nls/zh-hk/FileHandler':function(){
define('Sage/Library/nls/zh-hk/FileHandler',{});
},
'Sage/UI/nls/zh/ListPanel':function(){
define('Sage/UI/nls/zh/ListPanel',{});
},
'Sage/UI/nls/zh-hk/ListPanel':function(){
define('Sage/UI/nls/zh-hk/ListPanel',{});
},
'Sage/Utility/nls/zh/Sql':function(){
define('Sage/Utility/nls/zh/Sql',{});
},
'Sage/Utility/nls/zh-hk/Sql':function(){
define('Sage/Utility/nls/zh-hk/Sql',{});
},
'Sage/UI/Filters/nls/zh/EditFilters':function(){
define('Sage/UI/Filters/nls/zh/EditFilters',{});
},
'Sage/UI/Filters/nls/zh-hk/EditFilters':function(){
define('Sage/UI/Filters/nls/zh-hk/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh/DurationSelect',{});
},
'Sage/UI/Controls/nls/zh-hk/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh-hk/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/zh-hk/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh-hk/AlarmCountDown',{});
},
'Sage/UI/nls/zh/AttachmentList':function(){
define('Sage/UI/nls/zh/AttachmentList',{});
},
'Sage/UI/nls/zh-hk/AttachmentList':function(){
define('Sage/UI/nls/zh-hk/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zh/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/zh/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/zh-hk/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/zh-hk/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/zh-hk/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh-hk/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/Dialogs':function(){
define('Sage/UI/nls/zh/Dialogs',{});
},
'Sage/UI/nls/zh-hk/Dialogs':function(){
define('Sage/UI/nls/zh-hk/Dialogs',{});
},
'Sage/TaskPane/nls/zh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/zh-hk/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh-hk/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-hk/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-hk/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/zh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/UserControlDesigner',{});
},
'Sage/Groups/nls/zh/GroupNavigator':function(){
define('Sage/Groups/nls/zh/GroupNavigator',{});
},
'Sage/Groups/nls/zh-hk/GroupNavigator':function(){
define('Sage/Groups/nls/zh-hk/GroupNavigator',{});
},
'Sage/Utility/File/nls/zh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh/AddURLAttachment',{});
},
'Sage/Utility/File/nls/zh-hk/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh-hk/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh/EditFilterItems',{});
},
'Sage/UI/Filters/nls/zh-hk/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh-hk/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/zh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh/DragDropWatcher',{});
},
'Sage/Utility/File/nls/zh-hk/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh-hk/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/zh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/zh-hk/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh-hk/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zh/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zh/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zh-hk/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zh-hk/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/zh/ActivityScheduler':function(){
define('Sage/UI/nls/zh/ActivityScheduler',{});
},
'Sage/UI/nls/zh-hk/ActivityScheduler':function(){
define('Sage/UI/nls/zh-hk/ActivityScheduler',{});
},
'Sage/MainView/nls/zh/SecurityManager':function(){
define('Sage/MainView/nls/zh/SecurityManager',{});
},
'Sage/MainView/nls/zh-hk/SecurityManager':function(){
define('Sage/MainView/nls/zh-hk/SecurityManager',{});
},
'Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/zh-hk/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh-hk/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/zh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/zh-hk/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh-hk/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/zh/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/zh/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/zh-hk/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/zh-hk/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/zh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/zh-hk/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh-hk/UpdateOpportunities',{});
},
'Sage/UI/nls/zh/EditCalendarUsers':function(){
define('Sage/UI/nls/zh/EditCalendarUsers',{});
},
'Sage/UI/nls/zh-hk/EditCalendarUsers':function(){
define('Sage/UI/nls/zh-hk/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh/HelpMenu',{});
},
'Sage/UI/Controls/nls/zh-hk/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh-hk/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/UserTasklet':function(){
define('Sage/TaskPane/nls/zh/UserTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/UserTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/zh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/zh-hk/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh-hk/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/zh-hk/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh-hk/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/zh-hk/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh-hk/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/zh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/ColumnDesigner',{});
},
'Sage/UI/nls/zh/SearchMenuItem':function(){
define('Sage/UI/nls/zh/SearchMenuItem',{});
},
'Sage/UI/nls/zh-hk/SearchMenuItem':function(){
define('Sage/UI/nls/zh-hk/SearchMenuItem',{});
},
'Sage/Library/nls/zh/DocumentProperties':function(){
define('Sage/Library/nls/zh/DocumentProperties',{});
},
'Sage/Library/nls/zh-hk/DocumentProperties':function(){
define('Sage/Library/nls/zh-hk/DocumentProperties',{});
},
'Sage/UI/nls/zh/NotesHistoryList':function(){
define('Sage/UI/nls/zh/NotesHistoryList',{});
},
'Sage/UI/nls/zh-hk/NotesHistoryList':function(){
define('Sage/UI/nls/zh-hk/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/zh/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/zh/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/zh/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/zh/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/zh-hk/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/zh-hk/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/zh/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/zh-hk/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh-hk/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/zh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/zh-hk/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh-hk/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/HistoryEditor',{});
},
'Sage/Groups/nls/zh/GroupManager':function(){
define('Sage/Groups/nls/zh/GroupManager',{});
},
'Sage/Groups/nls/zh-hk/GroupManager':function(){
define('Sage/Groups/nls/zh-hk/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/zh/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/zh/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/zh-hk/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/zh-hk/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/zh/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/zh-hk/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh-hk/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/zh/FolderHandler':function(){
define('Sage/Library/nls/zh/FolderHandler',{});
},
'Sage/Library/nls/zh-hk/FolderHandler':function(){
define('Sage/Library/nls/zh-hk/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/zh-hk/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh-hk/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/EditableGrid':function(){
define('Sage/UI/nls/zh/EditableGrid',{});
},
'Sage/UI/nls/zh-hk/EditableGrid':function(){
define('Sage/UI/nls/zh-hk/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/zh/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-hk/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-hk/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/zh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/zh-hk/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh-hk/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/ReportManagerUtility',{});
},
'Sage/UI/nls/zh/SpeedSearch':function(){
define('Sage/UI/nls/zh/SpeedSearch',{});
},
'Sage/UI/nls/zh-hk/SpeedSearch':function(){
define('Sage/UI/nls/zh-hk/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/zh/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh/SLXPreviewGrid',{});
},
'Sage/UI/nls/zh-hk/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh-hk/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/zh-hk/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh-hk/UnconfirmedPane',{});
},
'Sage/Utility/nls/zh/Utility':function(){
define('Sage/Utility/nls/zh/Utility',{});
},
'Sage/Utility/nls/zh-hk/Utility':function(){
define('Sage/Utility/nls/zh-hk/Utility',{});
},
'Sage/QuickForms/Design/nls/zh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/ControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Address':function(){
define('Sage/UI/Controls/nls/zh/Address',{});
},
'Sage/UI/Controls/nls/zh-hk/Address':function(){
define('Sage/UI/Controls/nls/zh-hk/Address',{});
},
'Sage/MainView/JobMgr/nls/zh/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/zh/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/zh-hk/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/zh-hk/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/zh/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/zh/UserType':function(){
define('Sage/UI/nls/zh/UserType',{});
},
'Sage/UI/nls/zh-hk/UserType':function(){
define('Sage/UI/nls/zh-hk/UserType',{});
},
'Sage/QuickForms/Design/nls/zh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/ActivityCalendar',{});
},
'Sage/Utility/nls/zh/Jobs':function(){
define('Sage/Utility/nls/zh/Jobs',{});
},
'Sage/Utility/nls/zh-hk/Jobs':function(){
define('Sage/Utility/nls/zh-hk/Jobs',{});
},
'Sage/UI/Controls/nls/zh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/zh-hk/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh-hk/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/ActivityList':function(){
define('Sage/UI/nls/zh/ActivityList',{});
},
'Sage/UI/nls/zh-hk/ActivityList':function(){
define('Sage/UI/nls/zh-hk/ActivityList',{});
},
'Sage/UI/Alarms/nls/zh/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/zh/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/zh-hk/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/zh-hk/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh-hk/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh-hk/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/zh/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh/CalendarUsersListPane',{});
},
'Sage/UI/nls/zh-hk/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh-hk/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/zh-hk/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh-hk/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zh/Attachment':function(){
define('Sage/Utility/File/nls/zh/Attachment',{});
},
'Sage/Utility/File/nls/zh-hk/Attachment':function(){
define('Sage/Utility/File/nls/zh-hk/Attachment',{});
},
'Sage/QuickForms/Design/nls/zh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/zh-hk/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh-hk/PropertyEditorContainer',{});
},
'Sage/Services/nls/zh/ReportingService':function(){
define('Sage/Services/nls/zh/ReportingService',{});
},
'Sage/Services/nls/zh-hk/ReportingService':function(){
define('Sage/Services/nls/zh-hk/ReportingService',{});
},
'Sage/MailMerge/nls/zh/Helper':function(){
define('Sage/MailMerge/nls/zh/Helper',{});
},
'Sage/MailMerge/nls/zh-hk/Helper':function(){
define('Sage/MailMerge/nls/zh-hk/Helper',{});
},
'Sage/UI/Dashboard/nls/zh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh/Dashboard',{});
},
'Sage/UI/Dashboard/nls/zh-hk/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh-hk/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zh/PickList':function(){
define('Sage/UI/Controls/nls/zh/PickList',{});
},
'Sage/UI/Controls/nls/zh-hk/PickList':function(){
define('Sage/UI/Controls/nls/zh-hk/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/zh/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zh/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/zh/Email':function(){
define('Sage/Utility/nls/zh/Email',{});
},
'Sage/Utility/nls/zh-hk/Email':function(){
define('Sage/Utility/nls/zh-hk/Email',{});
},
'Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/zh/TimeZoneItem':function(){
define('Sage/UI/nls/zh/TimeZoneItem',{});
},
'Sage/UI/nls/zh-hk/TimeZoneItem':function(){
define('Sage/UI/nls/zh-hk/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/zh/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh/SlxEdit',{});
},
'Sage/UI/Columns/nls/zh-hk/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh-hk/SlxEdit',{});
},
'Sage/Reporting/nls/zh/Enumerations':function(){
define('Sage/Reporting/nls/zh/Enumerations',{});
},
'Sage/Reporting/nls/zh-hk/Enumerations':function(){
define('Sage/Reporting/nls/zh-hk/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zh/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zh/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zh-hk/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zh-hk/ActivityListPanelConfig',{});
},
'Sage/UI/nls/zh/JobSchedulingWidget':function(){
define('Sage/UI/nls/zh/JobSchedulingWidget',{});
},
'Sage/UI/nls/zh-hk/JobSchedulingWidget':function(){
define('Sage/UI/nls/zh-hk/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/zh/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh/LogOffButton',{});
},
'Sage/UI/Controls/nls/zh-hk/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh-hk/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh-hk/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh-hk/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-hk/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-hk/EditEventEditor',{});
},
'Sage/MailMerge/nls/zh/Loader':function(){
define('Sage/MailMerge/nls/zh/Loader',{});
},
'Sage/MailMerge/nls/zh-hk/Loader':function(){
define('Sage/MailMerge/nls/zh-hk/Loader',{});
},
'Sage/UI/Controls/nls/zh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh/DateTimePicker',{});
},
'Sage/UI/Controls/nls/zh-hk/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh-hk/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/zh-hk/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/zh-hk/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/zh-hk/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh-hk/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/zh/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/zh/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/zh-hk/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/zh-hk/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/zh-hk/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh-hk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-hk/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-hk/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Lookup':function(){
define('Sage/UI/Controls/nls/zh/Lookup',{});
},
'Sage/UI/Controls/nls/zh-hk/Lookup':function(){
define('Sage/UI/Controls/nls/zh-hk/Lookup',{});
},
'Sage/Utility/File/nls/zh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh/DescriptionsForm',{});
},
'Sage/Utility/File/nls/zh-hk/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh-hk/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-hk/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-hk/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-hk/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-hk/CommonTasksTasklet',{});
},
'Sage/Utility/nls/zh/Dashboard':function(){
define('Sage/Utility/nls/zh/Dashboard',{});
},
'Sage/Utility/nls/zh-hk/Dashboard':function(){
define('Sage/Utility/nls/zh-hk/Dashboard',{});
}}});
define("Sage/nls/Sage_zh-hk", [], 1);
