require({cache:{
'Sage/Utility/File/nls/ts/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ts/FallbackFilePicker',{});
},
'Sage/UI/nls/ts/Boolean':function(){
define('Sage/UI/nls/ts/Boolean',{});
},
'Sage/Services/nls/ts/ActivityService':function(){
define('Sage/Services/nls/ts/ActivityService',{});
},
'Sage/UI/Controls/nls/ts/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ts/CopyToClipboard',{});
},
'Sage/Utility/nls/ts/Activity':function(){
define('Sage/Utility/nls/ts/Activity',{});
},
'Sage/QuickForms/Design/nls/ts/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ts/DesignPanel',{});
},
'Sage/UI/nls/ts/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ts/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ts/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ts/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ts/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ts/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ts/ActivityManager':function(){
define('Sage/MainView/nls/ts/ActivityManager',{});
},
'Sage/Services/nls/ts/JobService':function(){
define('Sage/Services/nls/ts/JobService',{});
},
'Sage/QuickForms/Design/nls/ts/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/_PropertyEditor',{});
},
'Sage/Services/nls/ts/ActivityActionProcessor':function(){
define('Sage/Services/nls/ts/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ts/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ts/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ts/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ts/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ts/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ts/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ts/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ts/AlarmPane',{});
},
'Sage/TaskPane/nls/ts/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ts/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ts/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ts/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ts/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ts/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ts/FilterPanel':function(){
define('Sage/UI/Filters/nls/ts/FilterPanel',{});
},
'Sage/TaskPane/nls/ts/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ts/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ts/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ts/ReportManagerFormatter',{});
},
'Sage/UI/nls/ts/OwnerType':function(){
define('Sage/UI/nls/ts/OwnerType',{});
},
'Sage/TaskPane/nls/ts/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ts/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ts/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ts/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ts/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ts/InvoiceRTDV',{});
},
'Sage/UI/nls/ts/SDataLookup':function(){
define('Sage/UI/nls/ts/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ts/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/RowDesigner',{});
},
'Sage/TaskPane/nls/ts/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ts/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ts/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ts/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ts/LibraryDocument':function(){
define('Sage/Utility/File/nls/ts/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ts/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ts/SpeedSearchLookup',{});
},
'Sage/UI/nls/ts/ConditionManager':function(){
define('Sage/UI/nls/ts/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ts/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ts/WidgetDefinition',{});
},
'Sage/UI/nls/ts/SearchConditionWidget':function(){
define('Sage/UI/nls/ts/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ts/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ts/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ts/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ts/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ts/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ts/DataSourcePanel',{});
},
'Sage/Library/nls/ts/Manager':function(){
define('Sage/Library/nls/ts/Manager',{});
},
'Sage/UI/nls/ts/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ts/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ts/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ts/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ts/Name':function(){
define('Sage/UI/Controls/nls/ts/Name',{});
},
'Sage/MainView/JobMgr/nls/ts/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ts/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ts/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ts/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ts/UpdateLeads',{});
},
'Sage/Library/nls/ts/FileHandler':function(){
define('Sage/Library/nls/ts/FileHandler',{});
},
'Sage/UI/nls/ts/ListPanel':function(){
define('Sage/UI/nls/ts/ListPanel',{});
},
'Sage/Utility/nls/ts/Sql':function(){
define('Sage/Utility/nls/ts/Sql',{});
},
'Sage/UI/Filters/nls/ts/EditFilters':function(){
define('Sage/UI/Filters/nls/ts/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ts/DurationSelect':function(){
define('Sage/UI/Controls/nls/ts/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ts/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ts/AlarmCountDown',{});
},
'Sage/UI/nls/ts/AttachmentList':function(){
define('Sage/UI/nls/ts/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ts/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ts/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ts/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ts/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ts/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ts/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ts/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ts/Dialogs':function(){
define('Sage/UI/nls/ts/Dialogs',{});
},
'Sage/TaskPane/nls/ts/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ts/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ts/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ts/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ts/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ts/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ts/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/UserControlDesigner',{});
},
'Sage/Groups/nls/ts/GroupNavigator':function(){
define('Sage/Groups/nls/ts/GroupNavigator',{});
},
'Sage/Utility/File/nls/ts/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ts/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ts/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ts/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ts/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ts/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ts/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ts/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ts/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ts/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ts/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ts/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ts/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ts/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/ts/ActivityScheduler':function(){
define('Sage/UI/nls/ts/ActivityScheduler',{});
},
'Sage/MainView/nls/ts/SecurityManager':function(){
define('Sage/MainView/nls/ts/SecurityManager',{});
},
'Sage/TaskPane/nls/ts/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ts/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ts/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ts/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ts/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ts/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/ts/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ts/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/ts/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ts/UpdateOpportunities',{});
},
'Sage/UI/nls/ts/EditCalendarUsers':function(){
define('Sage/UI/nls/ts/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ts/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ts/HelpMenu':function(){
define('Sage/UI/Controls/nls/ts/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ts/UserTasklet':function(){
define('Sage/TaskPane/nls/ts/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/ts/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ts/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ts/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ts/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ts/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ts/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ts/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/ColumnDesigner',{});
},
'Sage/UI/nls/ts/SearchMenuItem':function(){
define('Sage/UI/nls/ts/SearchMenuItem',{});
},
'Sage/Library/nls/ts/DocumentProperties':function(){
define('Sage/Library/nls/ts/DocumentProperties',{});
},
'Sage/UI/nls/ts/NotesHistoryList':function(){
define('Sage/UI/nls/ts/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/ts/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ts/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ts/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ts/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ts/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/ts/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ts/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ts/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ts/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ts/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ts/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ts/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ts/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ts/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ts/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ts/HistoryEditor',{});
},
'Sage/Groups/nls/ts/GroupManager':function(){
define('Sage/Groups/nls/ts/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ts/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ts/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ts/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ts/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ts/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ts/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ts/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ts/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/ts/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ts/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ts/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ts/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ts/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ts/FolderHandler':function(){
define('Sage/Library/nls/ts/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ts/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ts/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ts/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ts/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ts/EditableGrid':function(){
define('Sage/UI/nls/ts/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ts/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ts/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ts/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ts/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ts/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ts/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ts/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ts/ReportManagerUtility',{});
},
'Sage/UI/nls/ts/SpeedSearch':function(){
define('Sage/UI/nls/ts/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ts/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ts/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ts/SLXPreviewGrid':function(){
define('Sage/UI/nls/ts/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ts/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ts/UnconfirmedPane',{});
},
'Sage/Utility/nls/ts/Utility':function(){
define('Sage/Utility/nls/ts/Utility',{});
},
'Sage/QuickForms/Design/nls/ts/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ts/Address':function(){
define('Sage/UI/Controls/nls/ts/Address',{});
},
'Sage/MainView/JobMgr/nls/ts/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ts/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ts/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ts/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ts/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ts/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ts/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ts/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ts/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ts/UserType':function(){
define('Sage/UI/nls/ts/UserType',{});
},
'Sage/QuickForms/Design/nls/ts/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ts/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ts/ActivityCalendar',{});
},
'Sage/Utility/nls/ts/Jobs':function(){
define('Sage/Utility/nls/ts/Jobs',{});
},
'Sage/UI/Controls/nls/ts/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ts/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ts/ActivityList':function(){
define('Sage/UI/nls/ts/ActivityList',{});
},
'Sage/UI/Alarms/nls/ts/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ts/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ts/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ts/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ts/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ts/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ts/CalendarUsersListPane':function(){
define('Sage/UI/nls/ts/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ts/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ts/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ts/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ts/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ts/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ts/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ts/Attachment':function(){
define('Sage/Utility/File/nls/ts/Attachment',{});
},
'Sage/QuickForms/Design/nls/ts/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ts/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ts/PropertyEditorContainer',{});
},
'Sage/Services/nls/ts/ReportingService':function(){
define('Sage/Services/nls/ts/ReportingService',{});
},
'Sage/MailMerge/nls/ts/Helper':function(){
define('Sage/MailMerge/nls/ts/Helper',{});
},
'Sage/UI/Dashboard/nls/ts/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ts/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ts/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ts/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ts/PickList':function(){
define('Sage/UI/Controls/nls/ts/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ts/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ts/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ts/Email':function(){
define('Sage/Utility/nls/ts/Email',{});
},
'Sage/TaskPane/nls/ts/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ts/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ts/TimeZoneItem':function(){
define('Sage/UI/nls/ts/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ts/SlxEdit':function(){
define('Sage/UI/Columns/nls/ts/SlxEdit',{});
},
'Sage/Reporting/nls/ts/Enumerations':function(){
define('Sage/Reporting/nls/ts/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ts/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ts/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ts/JobSchedulingWidget':function(){
define('Sage/UI/nls/ts/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ts/LogOffButton':function(){
define('Sage/UI/Controls/nls/ts/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ts/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ts/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ts/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ts/EditEventEditor',{});
},
'Sage/MailMerge/nls/ts/Loader':function(){
define('Sage/MailMerge/nls/ts/Loader',{});
},
'Sage/UI/Controls/nls/ts/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ts/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ts/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ts/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ts/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ts/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ts/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ts/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ts/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ts/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ts/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ts/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ts/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ts/Lookup':function(){
define('Sage/UI/Controls/nls/ts/Lookup',{});
},
'Sage/Utility/File/nls/ts/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ts/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ts/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ts/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ts/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ts/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ts/Dashboard':function(){
define('Sage/Utility/nls/ts/Dashboard',{});
}}});
define("Sage/nls/Sage_ts", [], 1);
