require({cache:{
'Sage/Utility/File/nls/bg/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/bg/FallbackFilePicker',{});
},
'Sage/UI/nls/bg/Boolean':function(){
define('Sage/UI/nls/bg/Boolean',{});
},
'Sage/Services/nls/bg/ActivityService':function(){
define('Sage/Services/nls/bg/ActivityService',{});
},
'Sage/UI/Controls/nls/bg/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/bg/CopyToClipboard',{});
},
'Sage/Utility/nls/bg/Activity':function(){
define('Sage/Utility/nls/bg/Activity',{});
},
'Sage/QuickForms/Design/nls/bg/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/bg/DesignPanel',{});
},
'Sage/UI/nls/bg/TimelessActivitiesPane':function(){
define('Sage/UI/nls/bg/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/bg/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/bg/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/bg/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/bg/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/bg/ActivityManager':function(){
define('Sage/MainView/nls/bg/ActivityManager',{});
},
'Sage/Services/nls/bg/JobService':function(){
define('Sage/Services/nls/bg/JobService',{});
},
'Sage/QuickForms/Design/nls/bg/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/_PropertyEditor',{});
},
'Sage/Services/nls/bg/ActivityActionProcessor':function(){
define('Sage/Services/nls/bg/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/bg/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/bg/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/bg/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/bg/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/bg/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/bg/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/bg/AlarmPane':function(){
define('Sage/UI/Alarms/nls/bg/AlarmPane',{});
},
'Sage/TaskPane/nls/bg/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/bg/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/bg/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/bg/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/bg/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/bg/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/bg/FilterPanel':function(){
define('Sage/UI/Filters/nls/bg/FilterPanel',{});
},
'Sage/TaskPane/nls/bg/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/bg/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/bg/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/bg/ReportManagerFormatter',{});
},
'Sage/UI/nls/bg/OwnerType':function(){
define('Sage/UI/nls/bg/OwnerType',{});
},
'Sage/TaskPane/nls/bg/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/bg/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/bg/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/bg/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/bg/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/bg/InvoiceRTDV',{});
},
'Sage/UI/nls/bg/SDataLookup':function(){
define('Sage/UI/nls/bg/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/bg/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/RowDesigner',{});
},
'Sage/TaskPane/nls/bg/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/bg/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/bg/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/bg/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/bg/LibraryDocument':function(){
define('Sage/Utility/File/nls/bg/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/bg/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/bg/SpeedSearchLookup',{});
},
'Sage/UI/nls/bg/ConditionManager':function(){
define('Sage/UI/nls/bg/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/bg/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/bg/WidgetDefinition',{});
},
'Sage/UI/nls/bg/SearchConditionWidget':function(){
define('Sage/UI/nls/bg/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/bg/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/bg/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/bg/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/bg/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/bg/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/bg/DataSourcePanel',{});
},
'Sage/Library/nls/bg/Manager':function(){
define('Sage/Library/nls/bg/Manager',{});
},
'Sage/UI/nls/bg/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/bg/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/bg/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/bg/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/bg/Name':function(){
define('Sage/UI/Controls/nls/bg/Name',{});
},
'Sage/MainView/JobMgr/nls/bg/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/bg/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/bg/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/bg/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/bg/UpdateLeads',{});
},
'Sage/Library/nls/bg/FileHandler':function(){
define('Sage/Library/nls/bg/FileHandler',{});
},
'Sage/UI/nls/bg/ListPanel':function(){
define('Sage/UI/nls/bg/ListPanel',{});
},
'Sage/Utility/nls/bg/Sql':function(){
define('Sage/Utility/nls/bg/Sql',{});
},
'Sage/UI/Filters/nls/bg/EditFilters':function(){
define('Sage/UI/Filters/nls/bg/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/bg/DurationSelect':function(){
define('Sage/UI/Controls/nls/bg/DurationSelect',{});
},
'Sage/UI/Alarms/nls/bg/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/bg/AlarmCountDown',{});
},
'Sage/UI/nls/bg/AttachmentList':function(){
define('Sage/UI/nls/bg/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/bg/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/bg/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/bg/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/bg/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/bg/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/bg/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/bg/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/bg/Dialogs':function(){
define('Sage/UI/nls/bg/Dialogs',{});
},
'Sage/TaskPane/nls/bg/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/bg/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/bg/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/bg/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/bg/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/bg/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/bg/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/UserControlDesigner',{});
},
'Sage/Groups/nls/bg/GroupNavigator':function(){
define('Sage/Groups/nls/bg/GroupNavigator',{});
},
'Sage/Utility/File/nls/bg/AddURLAttachment':function(){
define('Sage/Utility/File/nls/bg/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/bg/EditFilterItems':function(){
define('Sage/UI/Filters/nls/bg/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/bg/DragDropWatcher':function(){
define('Sage/Utility/File/nls/bg/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/bg/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/bg/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/bg/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/bg/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/bg/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/bg/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/bg/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/bg/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/bg/ActivityScheduler':function(){
define('Sage/UI/nls/bg/ActivityScheduler',{});
},
'Sage/MainView/nls/bg/SecurityManager':function(){
define('Sage/MainView/nls/bg/SecurityManager',{});
},
'Sage/TaskPane/nls/bg/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/bg/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/bg/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/bg/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/bg/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/bg/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/bg/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/bg/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/bg/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/bg/UpdateOpportunities',{});
},
'Sage/UI/nls/bg/EditCalendarUsers':function(){
define('Sage/UI/nls/bg/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/bg/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/bg/HelpMenu':function(){
define('Sage/UI/Controls/nls/bg/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/bg/UserTasklet':function(){
define('Sage/TaskPane/nls/bg/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/bg/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/bg/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/bg/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/bg/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/bg/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/bg/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/bg/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/ColumnDesigner',{});
},
'Sage/UI/nls/bg/SearchMenuItem':function(){
define('Sage/UI/nls/bg/SearchMenuItem',{});
},
'Sage/Library/nls/bg/DocumentProperties':function(){
define('Sage/Library/nls/bg/DocumentProperties',{});
},
'Sage/UI/nls/bg/NotesHistoryList':function(){
define('Sage/UI/nls/bg/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/bg/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/bg/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/bg/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/bg/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/bg/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/bg/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/bg/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/bg/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/bg/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/bg/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/bg/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/bg/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/bg/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/bg/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/bg/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/bg/HistoryEditor',{});
},
'Sage/Groups/nls/bg/GroupManager':function(){
define('Sage/Groups/nls/bg/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/bg/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/bg/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/bg/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/bg/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/bg/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/bg/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/bg/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/bg/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/bg/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/bg/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/bg/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/bg/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/bg/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/bg/FolderHandler':function(){
define('Sage/Library/nls/bg/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/bg/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/bg/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/bg/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/bg/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/bg/EditableGrid':function(){
define('Sage/UI/nls/bg/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/bg/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/bg/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/bg/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/bg/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/bg/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/bg/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/bg/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/bg/ReportManagerUtility',{});
},
'Sage/UI/nls/bg/SpeedSearch':function(){
define('Sage/UI/nls/bg/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/bg/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/bg/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/bg/SLXPreviewGrid':function(){
define('Sage/UI/nls/bg/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/bg/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/bg/UnconfirmedPane',{});
},
'Sage/Utility/nls/bg/Utility':function(){
define('Sage/Utility/nls/bg/Utility',{});
},
'Sage/QuickForms/Design/nls/bg/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/ControlDesigner',{});
},
'Sage/UI/Controls/nls/bg/Address':function(){
define('Sage/UI/Controls/nls/bg/Address',{});
},
'Sage/MainView/JobMgr/nls/bg/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/bg/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/bg/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/bg/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/bg/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/bg/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/bg/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/bg/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/bg/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/bg/UserType':function(){
define('Sage/UI/nls/bg/UserType',{});
},
'Sage/QuickForms/Design/nls/bg/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/bg/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/bg/ActivityCalendar',{});
},
'Sage/Utility/nls/bg/Jobs':function(){
define('Sage/Utility/nls/bg/Jobs',{});
},
'Sage/UI/Controls/nls/bg/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/bg/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/bg/ActivityList':function(){
define('Sage/UI/nls/bg/ActivityList',{});
},
'Sage/UI/Alarms/nls/bg/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/bg/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/bg/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/bg/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/bg/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/bg/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/bg/CalendarUsersListPane':function(){
define('Sage/UI/nls/bg/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/bg/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/bg/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/bg/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/bg/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/bg/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/bg/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/bg/Attachment':function(){
define('Sage/Utility/File/nls/bg/Attachment',{});
},
'Sage/QuickForms/Design/nls/bg/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/bg/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/bg/PropertyEditorContainer',{});
},
'Sage/Services/nls/bg/ReportingService':function(){
define('Sage/Services/nls/bg/ReportingService',{});
},
'Sage/MailMerge/nls/bg/Helper':function(){
define('Sage/MailMerge/nls/bg/Helper',{});
},
'Sage/UI/Dashboard/nls/bg/Dashboard':function(){
define('Sage/UI/Dashboard/nls/bg/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/bg/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/bg/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/bg/PickList':function(){
define('Sage/UI/Controls/nls/bg/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/bg/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/bg/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/bg/Email':function(){
define('Sage/Utility/nls/bg/Email',{});
},
'Sage/TaskPane/nls/bg/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/bg/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/bg/TimeZoneItem':function(){
define('Sage/UI/nls/bg/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/bg/SlxEdit':function(){
define('Sage/UI/Columns/nls/bg/SlxEdit',{});
},
'Sage/Reporting/nls/bg/Enumerations':function(){
define('Sage/Reporting/nls/bg/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/bg/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/bg/ActivityListPanelConfig',{});
},
'Sage/UI/nls/bg/JobSchedulingWidget':function(){
define('Sage/UI/nls/bg/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/bg/LogOffButton':function(){
define('Sage/UI/Controls/nls/bg/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/bg/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/bg/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/bg/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/bg/EditEventEditor',{});
},
'Sage/MailMerge/nls/bg/Loader':function(){
define('Sage/MailMerge/nls/bg/Loader',{});
},
'Sage/UI/Controls/nls/bg/DateTimePicker':function(){
define('Sage/UI/Controls/nls/bg/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/bg/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/bg/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/bg/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/bg/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/bg/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/bg/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/bg/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/bg/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/bg/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/bg/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/bg/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/bg/Lookup':function(){
define('Sage/UI/Controls/nls/bg/Lookup',{});
},
'Sage/Utility/File/nls/bg/DescriptionsForm':function(){
define('Sage/Utility/File/nls/bg/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/bg/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/bg/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/bg/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/bg/CommonTasksTasklet',{});
},
'Sage/Utility/nls/bg/Dashboard':function(){
define('Sage/Utility/nls/bg/Dashboard',{});
}}});
define("Sage/nls/Sage_bg", [], 1);
