require({cache:{
'Sage/Utility/File/nls/gd/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/gd/FallbackFilePicker',{});
},
'Sage/UI/nls/gd/Boolean':function(){
define('Sage/UI/nls/gd/Boolean',{});
},
'Sage/Services/nls/gd/ActivityService':function(){
define('Sage/Services/nls/gd/ActivityService',{});
},
'Sage/UI/Controls/nls/gd/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/gd/CopyToClipboard',{});
},
'Sage/Utility/nls/gd/Activity':function(){
define('Sage/Utility/nls/gd/Activity',{});
},
'Sage/QuickForms/Design/nls/gd/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/gd/DesignPanel',{});
},
'Sage/UI/nls/gd/TimelessActivitiesPane':function(){
define('Sage/UI/nls/gd/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/gd/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/gd/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/gd/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/gd/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/gd/ActivityManager':function(){
define('Sage/MainView/nls/gd/ActivityManager',{});
},
'Sage/Services/nls/gd/JobService':function(){
define('Sage/Services/nls/gd/JobService',{});
},
'Sage/QuickForms/Design/nls/gd/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/_PropertyEditor',{});
},
'Sage/Services/nls/gd/ActivityActionProcessor':function(){
define('Sage/Services/nls/gd/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/gd/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/gd/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/gd/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/gd/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/gd/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/gd/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/gd/AlarmPane':function(){
define('Sage/UI/Alarms/nls/gd/AlarmPane',{});
},
'Sage/TaskPane/nls/gd/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/gd/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/gd/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/gd/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/gd/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/gd/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/gd/FilterPanel':function(){
define('Sage/UI/Filters/nls/gd/FilterPanel',{});
},
'Sage/TaskPane/nls/gd/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/gd/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/gd/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/gd/ReportManagerFormatter',{});
},
'Sage/UI/nls/gd/OwnerType':function(){
define('Sage/UI/nls/gd/OwnerType',{});
},
'Sage/TaskPane/nls/gd/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/gd/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/gd/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/gd/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/gd/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/gd/InvoiceRTDV',{});
},
'Sage/UI/nls/gd/SDataLookup':function(){
define('Sage/UI/nls/gd/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/gd/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/RowDesigner',{});
},
'Sage/TaskPane/nls/gd/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/gd/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/gd/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/gd/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/gd/LibraryDocument':function(){
define('Sage/Utility/File/nls/gd/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/gd/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/gd/SpeedSearchLookup',{});
},
'Sage/UI/nls/gd/ConditionManager':function(){
define('Sage/UI/nls/gd/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/gd/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/gd/WidgetDefinition',{});
},
'Sage/UI/nls/gd/SearchConditionWidget':function(){
define('Sage/UI/nls/gd/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/gd/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/gd/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/gd/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/gd/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/gd/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/gd/DataSourcePanel',{});
},
'Sage/Library/nls/gd/Manager':function(){
define('Sage/Library/nls/gd/Manager',{});
},
'Sage/UI/nls/gd/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/gd/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/gd/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/gd/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/gd/Name':function(){
define('Sage/UI/Controls/nls/gd/Name',{});
},
'Sage/MainView/JobMgr/nls/gd/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/gd/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/gd/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/gd/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/gd/UpdateLeads',{});
},
'Sage/Library/nls/gd/FileHandler':function(){
define('Sage/Library/nls/gd/FileHandler',{});
},
'Sage/UI/nls/gd/ListPanel':function(){
define('Sage/UI/nls/gd/ListPanel',{});
},
'Sage/Utility/nls/gd/Sql':function(){
define('Sage/Utility/nls/gd/Sql',{});
},
'Sage/UI/Filters/nls/gd/EditFilters':function(){
define('Sage/UI/Filters/nls/gd/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/gd/DurationSelect':function(){
define('Sage/UI/Controls/nls/gd/DurationSelect',{});
},
'Sage/UI/Alarms/nls/gd/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/gd/AlarmCountDown',{});
},
'Sage/UI/nls/gd/AttachmentList':function(){
define('Sage/UI/nls/gd/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/gd/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/gd/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/gd/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/gd/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/gd/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/gd/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/gd/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/gd/Dialogs':function(){
define('Sage/UI/nls/gd/Dialogs',{});
},
'Sage/TaskPane/nls/gd/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/gd/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/gd/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/gd/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/gd/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/gd/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/gd/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/UserControlDesigner',{});
},
'Sage/Groups/nls/gd/GroupNavigator':function(){
define('Sage/Groups/nls/gd/GroupNavigator',{});
},
'Sage/Utility/File/nls/gd/AddURLAttachment':function(){
define('Sage/Utility/File/nls/gd/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/gd/EditFilterItems':function(){
define('Sage/UI/Filters/nls/gd/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/gd/DragDropWatcher':function(){
define('Sage/Utility/File/nls/gd/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/gd/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/gd/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/gd/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/gd/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/gd/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/gd/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/gd/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/gd/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/gd/ActivityScheduler':function(){
define('Sage/UI/nls/gd/ActivityScheduler',{});
},
'Sage/MainView/nls/gd/SecurityManager':function(){
define('Sage/MainView/nls/gd/SecurityManager',{});
},
'Sage/TaskPane/nls/gd/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/gd/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/gd/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/gd/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/gd/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/gd/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/gd/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/gd/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/gd/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/gd/UpdateOpportunities',{});
},
'Sage/UI/nls/gd/EditCalendarUsers':function(){
define('Sage/UI/nls/gd/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/gd/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/gd/HelpMenu':function(){
define('Sage/UI/Controls/nls/gd/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/gd/UserTasklet':function(){
define('Sage/TaskPane/nls/gd/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/gd/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/gd/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/gd/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/gd/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/gd/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/gd/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/gd/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/ColumnDesigner',{});
},
'Sage/UI/nls/gd/SearchMenuItem':function(){
define('Sage/UI/nls/gd/SearchMenuItem',{});
},
'Sage/Library/nls/gd/DocumentProperties':function(){
define('Sage/Library/nls/gd/DocumentProperties',{});
},
'Sage/UI/nls/gd/NotesHistoryList':function(){
define('Sage/UI/nls/gd/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/gd/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/gd/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/gd/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/gd/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/gd/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/gd/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/gd/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/gd/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/gd/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/gd/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/gd/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/gd/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/gd/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/gd/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/gd/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/gd/HistoryEditor',{});
},
'Sage/Groups/nls/gd/GroupManager':function(){
define('Sage/Groups/nls/gd/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/gd/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/gd/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/gd/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/gd/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/gd/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/gd/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/gd/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/gd/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/gd/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/gd/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/gd/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/gd/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/gd/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/gd/FolderHandler':function(){
define('Sage/Library/nls/gd/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/gd/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/gd/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/gd/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/gd/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/gd/EditableGrid':function(){
define('Sage/UI/nls/gd/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/gd/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/gd/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/gd/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/gd/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/gd/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/gd/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/gd/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/gd/ReportManagerUtility',{});
},
'Sage/UI/nls/gd/SpeedSearch':function(){
define('Sage/UI/nls/gd/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/gd/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/gd/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/gd/SLXPreviewGrid':function(){
define('Sage/UI/nls/gd/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/gd/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/gd/UnconfirmedPane',{});
},
'Sage/Utility/nls/gd/Utility':function(){
define('Sage/Utility/nls/gd/Utility',{});
},
'Sage/QuickForms/Design/nls/gd/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/ControlDesigner',{});
},
'Sage/UI/Controls/nls/gd/Address':function(){
define('Sage/UI/Controls/nls/gd/Address',{});
},
'Sage/MainView/JobMgr/nls/gd/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/gd/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/gd/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/gd/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/gd/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/gd/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/gd/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/gd/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/gd/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/gd/UserType':function(){
define('Sage/UI/nls/gd/UserType',{});
},
'Sage/QuickForms/Design/nls/gd/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/gd/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/gd/ActivityCalendar',{});
},
'Sage/Utility/nls/gd/Jobs':function(){
define('Sage/Utility/nls/gd/Jobs',{});
},
'Sage/UI/Controls/nls/gd/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/gd/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/gd/ActivityList':function(){
define('Sage/UI/nls/gd/ActivityList',{});
},
'Sage/UI/Alarms/nls/gd/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/gd/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/gd/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/gd/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/gd/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/gd/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/gd/CalendarUsersListPane':function(){
define('Sage/UI/nls/gd/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/gd/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/gd/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/gd/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/gd/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/gd/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/gd/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/gd/Attachment':function(){
define('Sage/Utility/File/nls/gd/Attachment',{});
},
'Sage/QuickForms/Design/nls/gd/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/gd/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/gd/PropertyEditorContainer',{});
},
'Sage/Services/nls/gd/ReportingService':function(){
define('Sage/Services/nls/gd/ReportingService',{});
},
'Sage/MailMerge/nls/gd/Helper':function(){
define('Sage/MailMerge/nls/gd/Helper',{});
},
'Sage/UI/Dashboard/nls/gd/Dashboard':function(){
define('Sage/UI/Dashboard/nls/gd/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/gd/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/gd/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/gd/PickList':function(){
define('Sage/UI/Controls/nls/gd/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/gd/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/gd/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/gd/Email':function(){
define('Sage/Utility/nls/gd/Email',{});
},
'Sage/TaskPane/nls/gd/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/gd/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/gd/TimeZoneItem':function(){
define('Sage/UI/nls/gd/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/gd/SlxEdit':function(){
define('Sage/UI/Columns/nls/gd/SlxEdit',{});
},
'Sage/Reporting/nls/gd/Enumerations':function(){
define('Sage/Reporting/nls/gd/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/gd/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/gd/ActivityListPanelConfig',{});
},
'Sage/UI/nls/gd/JobSchedulingWidget':function(){
define('Sage/UI/nls/gd/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/gd/LogOffButton':function(){
define('Sage/UI/Controls/nls/gd/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/gd/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/gd/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/gd/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/gd/EditEventEditor',{});
},
'Sage/MailMerge/nls/gd/Loader':function(){
define('Sage/MailMerge/nls/gd/Loader',{});
},
'Sage/UI/Controls/nls/gd/DateTimePicker':function(){
define('Sage/UI/Controls/nls/gd/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/gd/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/gd/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/gd/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/gd/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/gd/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/gd/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/gd/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/gd/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/gd/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/gd/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/gd/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/gd/Lookup':function(){
define('Sage/UI/Controls/nls/gd/Lookup',{});
},
'Sage/Utility/File/nls/gd/DescriptionsForm':function(){
define('Sage/Utility/File/nls/gd/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/gd/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/gd/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/gd/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/gd/CommonTasksTasklet',{});
},
'Sage/Utility/nls/gd/Dashboard':function(){
define('Sage/Utility/nls/gd/Dashboard',{});
}}});
define("Sage/nls/Sage_gd", [], 1);
