require({cache:{
'Sage/Utility/File/nls/zu/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zu/FallbackFilePicker',{});
},
'Sage/UI/nls/zu/Boolean':function(){
define('Sage/UI/nls/zu/Boolean',{});
},
'Sage/Services/nls/zu/ActivityService':function(){
define('Sage/Services/nls/zu/ActivityService',{});
},
'Sage/UI/Controls/nls/zu/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zu/CopyToClipboard',{});
},
'Sage/Utility/nls/zu/Activity':function(){
define('Sage/Utility/nls/zu/Activity',{});
},
'Sage/QuickForms/Design/nls/zu/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zu/DesignPanel',{});
},
'Sage/UI/nls/zu/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zu/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/zu/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/zu/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/zu/ActivityManager':function(){
define('Sage/MainView/nls/zu/ActivityManager',{});
},
'Sage/Services/nls/zu/JobService':function(){
define('Sage/Services/nls/zu/JobService',{});
},
'Sage/QuickForms/Design/nls/zu/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/_PropertyEditor',{});
},
'Sage/Services/nls/zu/ActivityActionProcessor':function(){
define('Sage/Services/nls/zu/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/zu/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zu/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zu/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zu/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zu/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zu/AlarmPane',{});
},
'Sage/TaskPane/nls/zu/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zu/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zu/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/zu/FilterPanel':function(){
define('Sage/UI/Filters/nls/zu/FilterPanel',{});
},
'Sage/TaskPane/nls/zu/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zu/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportManagerFormatter',{});
},
'Sage/UI/nls/zu/OwnerType':function(){
define('Sage/UI/nls/zu/OwnerType',{});
},
'Sage/TaskPane/nls/zu/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zu/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zu/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zu/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu/InvoiceRTDV',{});
},
'Sage/UI/nls/zu/SDataLookup':function(){
define('Sage/UI/nls/zu/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/zu/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/RowDesigner',{});
},
'Sage/TaskPane/nls/zu/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zu/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zu/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zu/LibraryDocument':function(){
define('Sage/Utility/File/nls/zu/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/SpeedSearchLookup',{});
},
'Sage/UI/nls/zu/ConditionManager':function(){
define('Sage/UI/nls/zu/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/zu/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zu/WidgetDefinition',{});
},
'Sage/UI/nls/zu/SearchConditionWidget':function(){
define('Sage/UI/nls/zu/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zu/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/zu/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/zu/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zu/DataSourcePanel',{});
},
'Sage/Library/nls/zu/Manager':function(){
define('Sage/Library/nls/zu/Manager',{});
},
'Sage/UI/nls/zu/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zu/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/zu/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zu/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/zu/Name':function(){
define('Sage/UI/Controls/nls/zu/Name',{});
},
'Sage/MainView/JobMgr/nls/zu/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zu/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/zu/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zu/UpdateLeads',{});
},
'Sage/Library/nls/zu/FileHandler':function(){
define('Sage/Library/nls/zu/FileHandler',{});
},
'Sage/UI/nls/zu/ListPanel':function(){
define('Sage/UI/nls/zu/ListPanel',{});
},
'Sage/Utility/nls/zu/Sql':function(){
define('Sage/Utility/nls/zu/Sql',{});
},
'Sage/UI/Filters/nls/zu/EditFilters':function(){
define('Sage/UI/Filters/nls/zu/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/zu/DurationSelect':function(){
define('Sage/UI/Controls/nls/zu/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zu/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zu/AlarmCountDown',{});
},
'Sage/UI/nls/zu/AttachmentList':function(){
define('Sage/UI/nls/zu/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zu/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/zu/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/zu/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/zu/Dialogs':function(){
define('Sage/UI/nls/zu/Dialogs',{});
},
'Sage/TaskPane/nls/zu/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zu/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/zu/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/zu/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/UserControlDesigner',{});
},
'Sage/Groups/nls/zu/GroupNavigator':function(){
define('Sage/Groups/nls/zu/GroupNavigator',{});
},
'Sage/Utility/File/nls/zu/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zu/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zu/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zu/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/zu/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zu/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/zu/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zu/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zu/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zu/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/zu/ActivityScheduler':function(){
define('Sage/UI/nls/zu/ActivityScheduler',{});
},
'Sage/MainView/nls/zu/SecurityManager':function(){
define('Sage/MainView/nls/zu/SecurityManager',{});
},
'Sage/TaskPane/nls/zu/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zu/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/zu/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zu/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/zu/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/zu/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/zu/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zu/UpdateOpportunities',{});
},
'Sage/UI/nls/zu/EditCalendarUsers':function(){
define('Sage/UI/nls/zu/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/zu/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/zu/HelpMenu':function(){
define('Sage/UI/Controls/nls/zu/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/zu/UserTasklet':function(){
define('Sage/TaskPane/nls/zu/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/zu/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zu/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zu/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zu/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zu/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zu/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/zu/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/ColumnDesigner',{});
},
'Sage/UI/nls/zu/SearchMenuItem':function(){
define('Sage/UI/nls/zu/SearchMenuItem',{});
},
'Sage/Library/nls/zu/DocumentProperties':function(){
define('Sage/Library/nls/zu/DocumentProperties',{});
},
'Sage/UI/nls/zu/NotesHistoryList':function(){
define('Sage/UI/nls/zu/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/zu/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zu/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/zu/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/zu/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/zu/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/zu/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/zu/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zu/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/zu/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zu/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/HistoryEditor',{});
},
'Sage/Groups/nls/zu/GroupManager':function(){
define('Sage/Groups/nls/zu/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/zu/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/zu/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/zu/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/zu/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zu/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/zu/FolderHandler':function(){
define('Sage/Library/nls/zu/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/zu/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zu/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zu/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/zu/EditableGrid':function(){
define('Sage/UI/nls/zu/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/zu/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zu/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/zu/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zu/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportManagerUtility',{});
},
'Sage/UI/nls/zu/SpeedSearch':function(){
define('Sage/UI/nls/zu/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/zu/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/zu/SLXPreviewGrid':function(){
define('Sage/UI/nls/zu/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zu/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zu/UnconfirmedPane',{});
},
'Sage/Utility/nls/zu/Utility':function(){
define('Sage/Utility/nls/zu/Utility',{});
},
'Sage/QuickForms/Design/nls/zu/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/ControlDesigner',{});
},
'Sage/UI/Controls/nls/zu/Address':function(){
define('Sage/UI/Controls/nls/zu/Address',{});
},
'Sage/MainView/JobMgr/nls/zu/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/zu/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zu/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zu/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/zu/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/zu/UserType':function(){
define('Sage/UI/nls/zu/UserType',{});
},
'Sage/QuickForms/Design/nls/zu/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityCalendar',{});
},
'Sage/Utility/nls/zu/Jobs':function(){
define('Sage/Utility/nls/zu/Jobs',{});
},
'Sage/UI/Controls/nls/zu/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zu/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zu/ActivityList':function(){
define('Sage/UI/nls/zu/ActivityList',{});
},
'Sage/UI/Alarms/nls/zu/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/zu/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zu/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/zu/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zu/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zu/CalendarUsersListPane':function(){
define('Sage/UI/nls/zu/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/zu/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zu/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zu/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zu/Attachment':function(){
define('Sage/Utility/File/nls/zu/Attachment',{});
},
'Sage/QuickForms/Design/nls/zu/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zu/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zu/PropertyEditorContainer',{});
},
'Sage/Services/nls/zu/ReportingService':function(){
define('Sage/Services/nls/zu/ReportingService',{});
},
'Sage/MailMerge/nls/zu/Helper':function(){
define('Sage/MailMerge/nls/zu/Helper',{});
},
'Sage/UI/Dashboard/nls/zu/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zu/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zu/PickList':function(){
define('Sage/UI/Controls/nls/zu/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/zu/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zu/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/zu/Email':function(){
define('Sage/Utility/nls/zu/Email',{});
},
'Sage/TaskPane/nls/zu/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/zu/TimeZoneItem':function(){
define('Sage/UI/nls/zu/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/zu/SlxEdit':function(){
define('Sage/UI/Columns/nls/zu/SlxEdit',{});
},
'Sage/Reporting/nls/zu/Enumerations':function(){
define('Sage/Reporting/nls/zu/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zu/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zu/ActivityListPanelConfig',{});
},
'Sage/UI/nls/zu/JobSchedulingWidget':function(){
define('Sage/UI/nls/zu/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/zu/LogOffButton':function(){
define('Sage/UI/Controls/nls/zu/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zu/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zu/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/EditEventEditor',{});
},
'Sage/MailMerge/nls/zu/Loader':function(){
define('Sage/MailMerge/nls/zu/Loader',{});
},
'Sage/UI/Controls/nls/zu/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zu/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/zu/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/zu/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/zu/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zu/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/zu/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/zu/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zu/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zu/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zu/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zu/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zu/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/zu/Lookup':function(){
define('Sage/UI/Controls/nls/zu/Lookup',{});
},
'Sage/Utility/File/nls/zu/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zu/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/zu/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zu/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zu/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/CommonTasksTasklet',{});
},
'Sage/Utility/nls/zu/Dashboard':function(){
define('Sage/Utility/nls/zu/Dashboard',{});
}}});
define("Sage/nls/Sage_zu", [], 1);
