require({cache:{
'Sage/Utility/File/nls/fi/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/fi/FallbackFilePicker',{});
},
'Sage/UI/nls/fi/Boolean':function(){
define('Sage/UI/nls/fi/Boolean',{});
},
'Sage/Services/nls/fi/ActivityService':function(){
define('Sage/Services/nls/fi/ActivityService',{});
},
'Sage/UI/Controls/nls/fi/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/fi/CopyToClipboard',{});
},
'Sage/Utility/nls/fi/Activity':function(){
define('Sage/Utility/nls/fi/Activity',{});
},
'Sage/QuickForms/Design/nls/fi/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/fi/DesignPanel',{});
},
'Sage/UI/nls/fi/TimelessActivitiesPane':function(){
define('Sage/UI/nls/fi/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/fi/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fi/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/fi/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/fi/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/fi/ActivityManager':function(){
define('Sage/MainView/nls/fi/ActivityManager',{});
},
'Sage/Services/nls/fi/JobService':function(){
define('Sage/Services/nls/fi/JobService',{});
},
'Sage/QuickForms/Design/nls/fi/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/_PropertyEditor',{});
},
'Sage/Services/nls/fi/ActivityActionProcessor':function(){
define('Sage/Services/nls/fi/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fi/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fi/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/fi/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/fi/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/fi/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/fi/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/fi/AlarmPane':function(){
define('Sage/UI/Alarms/nls/fi/AlarmPane',{});
},
'Sage/TaskPane/nls/fi/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/fi/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/fi/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/fi/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fi/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fi/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/fi/FilterPanel':function(){
define('Sage/UI/Filters/nls/fi/FilterPanel',{});
},
'Sage/TaskPane/nls/fi/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/fi/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/fi/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/fi/ReportManagerFormatter',{});
},
'Sage/UI/nls/fi/OwnerType':function(){
define('Sage/UI/nls/fi/OwnerType',{});
},
'Sage/TaskPane/nls/fi/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/fi/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/fi/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/fi/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fi/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fi/InvoiceRTDV',{});
},
'Sage/UI/nls/fi/SDataLookup':function(){
define('Sage/UI/nls/fi/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/fi/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/RowDesigner',{});
},
'Sage/TaskPane/nls/fi/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/fi/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/fi/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/fi/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/fi/LibraryDocument':function(){
define('Sage/Utility/File/nls/fi/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/fi/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/fi/SpeedSearchLookup',{});
},
'Sage/UI/nls/fi/ConditionManager':function(){
define('Sage/UI/nls/fi/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/fi/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/fi/WidgetDefinition',{});
},
'Sage/UI/nls/fi/SearchConditionWidget':function(){
define('Sage/UI/nls/fi/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/fi/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/fi/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/fi/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/fi/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/fi/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/fi/DataSourcePanel',{});
},
'Sage/Library/nls/fi/Manager':function(){
define('Sage/Library/nls/fi/Manager',{});
},
'Sage/UI/nls/fi/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/fi/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/fi/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/fi/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/fi/Name':function(){
define('Sage/UI/Controls/nls/fi/Name',{});
},
'Sage/MainView/JobMgr/nls/fi/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/fi/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/fi/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/fi/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/fi/UpdateLeads',{});
},
'Sage/Library/nls/fi/FileHandler':function(){
define('Sage/Library/nls/fi/FileHandler',{});
},
'Sage/UI/nls/fi/ListPanel':function(){
define('Sage/UI/nls/fi/ListPanel',{});
},
'Sage/Utility/nls/fi/Sql':function(){
define('Sage/Utility/nls/fi/Sql',{});
},
'Sage/UI/Filters/nls/fi/EditFilters':function(){
define('Sage/UI/Filters/nls/fi/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/fi/DurationSelect':function(){
define('Sage/UI/Controls/nls/fi/DurationSelect',{});
},
'Sage/UI/Alarms/nls/fi/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/fi/AlarmCountDown',{});
},
'Sage/UI/nls/fi/AttachmentList':function(){
define('Sage/UI/nls/fi/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/fi/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/fi/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/fi/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fi/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fi/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/fi/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/fi/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/fi/Dialogs':function(){
define('Sage/UI/nls/fi/Dialogs',{});
},
'Sage/TaskPane/nls/fi/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/fi/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/fi/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/fi/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/fi/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fi/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/fi/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/UserControlDesigner',{});
},
'Sage/Groups/nls/fi/GroupNavigator':function(){
define('Sage/Groups/nls/fi/GroupNavigator',{});
},
'Sage/Utility/File/nls/fi/AddURLAttachment':function(){
define('Sage/Utility/File/nls/fi/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/fi/EditFilterItems':function(){
define('Sage/UI/Filters/nls/fi/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/fi/DragDropWatcher':function(){
define('Sage/Utility/File/nls/fi/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/fi/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/fi/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/fi/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fi/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fi/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fi/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/fi/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/fi/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/fi/ActivityScheduler':function(){
define('Sage/UI/nls/fi/ActivityScheduler',{});
},
'Sage/MainView/nls/fi/SecurityManager':function(){
define('Sage/MainView/nls/fi/SecurityManager',{});
},
'Sage/TaskPane/nls/fi/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/fi/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/fi/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/fi/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/fi/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/fi/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/fi/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/fi/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/fi/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/fi/UpdateOpportunities',{});
},
'Sage/UI/nls/fi/EditCalendarUsers':function(){
define('Sage/UI/nls/fi/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/fi/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/fi/HelpMenu':function(){
define('Sage/UI/Controls/nls/fi/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/fi/UserTasklet':function(){
define('Sage/TaskPane/nls/fi/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/fi/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/fi/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/fi/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/fi/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fi/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/fi/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/fi/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/ColumnDesigner',{});
},
'Sage/UI/nls/fi/SearchMenuItem':function(){
define('Sage/UI/nls/fi/SearchMenuItem',{});
},
'Sage/Library/nls/fi/DocumentProperties':function(){
define('Sage/Library/nls/fi/DocumentProperties',{});
},
'Sage/UI/nls/fi/NotesHistoryList':function(){
define('Sage/UI/nls/fi/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/fi/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/fi/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/fi/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/fi/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/fi/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/fi/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/fi/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/fi/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/fi/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/fi/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/fi/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/fi/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/fi/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fi/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/fi/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fi/HistoryEditor',{});
},
'Sage/Groups/nls/fi/GroupManager':function(){
define('Sage/Groups/nls/fi/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/fi/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/fi/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/fi/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/fi/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/fi/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/fi/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/fi/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fi/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/fi/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/fi/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/fi/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fi/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fi/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/fi/FolderHandler':function(){
define('Sage/Library/nls/fi/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/fi/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/fi/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/fi/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/fi/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/fi/EditableGrid':function(){
define('Sage/UI/nls/fi/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/fi/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fi/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/fi/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/fi/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/fi/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/fi/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/fi/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/fi/ReportManagerUtility',{});
},
'Sage/UI/nls/fi/SpeedSearch':function(){
define('Sage/UI/nls/fi/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/fi/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/fi/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/fi/SLXPreviewGrid':function(){
define('Sage/UI/nls/fi/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/fi/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/fi/UnconfirmedPane',{});
},
'Sage/Utility/nls/fi/Utility':function(){
define('Sage/Utility/nls/fi/Utility',{});
},
'Sage/QuickForms/Design/nls/fi/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/ControlDesigner',{});
},
'Sage/UI/Controls/nls/fi/Address':function(){
define('Sage/UI/Controls/nls/fi/Address',{});
},
'Sage/MainView/JobMgr/nls/fi/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/fi/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/fi/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fi/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/fi/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/fi/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/fi/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/fi/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/fi/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/fi/UserType':function(){
define('Sage/UI/nls/fi/UserType',{});
},
'Sage/QuickForms/Design/nls/fi/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/fi/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/fi/ActivityCalendar',{});
},
'Sage/Utility/nls/fi/Jobs':function(){
define('Sage/Utility/nls/fi/Jobs',{});
},
'Sage/UI/Controls/nls/fi/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/fi/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fi/ActivityList':function(){
define('Sage/UI/nls/fi/ActivityList',{});
},
'Sage/UI/Alarms/nls/fi/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/fi/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/fi/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/fi/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/fi/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/fi/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fi/CalendarUsersListPane':function(){
define('Sage/UI/nls/fi/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/fi/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/fi/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/fi/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/fi/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fi/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/fi/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/fi/Attachment':function(){
define('Sage/Utility/File/nls/fi/Attachment',{});
},
'Sage/QuickForms/Design/nls/fi/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/fi/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/fi/PropertyEditorContainer',{});
},
'Sage/Services/nls/fi/ReportingService':function(){
define('Sage/Services/nls/fi/ReportingService',{});
},
'Sage/MailMerge/nls/fi/Helper':function(){
define('Sage/MailMerge/nls/fi/Helper',{});
},
'Sage/UI/Dashboard/nls/fi/Dashboard':function(){
define('Sage/UI/Dashboard/nls/fi/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/fi/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fi/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/fi/PickList':function(){
define('Sage/UI/Controls/nls/fi/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/fi/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/fi/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/fi/Email':function(){
define('Sage/Utility/nls/fi/Email',{});
},
'Sage/TaskPane/nls/fi/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/fi/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/fi/TimeZoneItem':function(){
define('Sage/UI/nls/fi/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/fi/SlxEdit':function(){
define('Sage/UI/Columns/nls/fi/SlxEdit',{});
},
'Sage/Reporting/nls/fi/Enumerations':function(){
define('Sage/Reporting/nls/fi/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/fi/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/fi/ActivityListPanelConfig',{});
},
'Sage/UI/nls/fi/JobSchedulingWidget':function(){
define('Sage/UI/nls/fi/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/fi/LogOffButton':function(){
define('Sage/UI/Controls/nls/fi/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/fi/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/fi/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fi/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fi/EditEventEditor',{});
},
'Sage/MailMerge/nls/fi/Loader':function(){
define('Sage/MailMerge/nls/fi/Loader',{});
},
'Sage/UI/Controls/nls/fi/DateTimePicker':function(){
define('Sage/UI/Controls/nls/fi/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/fi/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/fi/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/fi/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/fi/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/fi/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/fi/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/fi/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/fi/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/fi/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fi/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fi/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/fi/Lookup':function(){
define('Sage/UI/Controls/nls/fi/Lookup',{});
},
'Sage/Utility/File/nls/fi/DescriptionsForm':function(){
define('Sage/Utility/File/nls/fi/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/fi/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fi/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/fi/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/fi/CommonTasksTasklet',{});
},
'Sage/Utility/nls/fi/Dashboard':function(){
define('Sage/Utility/nls/fi/Dashboard',{});
}}});
define("Sage/nls/Sage_fi", [], 1);
