require({cache:{
'Sage/Utility/File/nls/kk/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/kk/FallbackFilePicker',{});
},
'Sage/UI/nls/kk/Boolean':function(){
define('Sage/UI/nls/kk/Boolean',{});
},
'Sage/Services/nls/kk/ActivityService':function(){
define('Sage/Services/nls/kk/ActivityService',{});
},
'Sage/UI/Controls/nls/kk/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/kk/CopyToClipboard',{});
},
'Sage/Utility/nls/kk/Activity':function(){
define('Sage/Utility/nls/kk/Activity',{});
},
'Sage/QuickForms/Design/nls/kk/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/kk/DesignPanel',{});
},
'Sage/UI/nls/kk/TimelessActivitiesPane':function(){
define('Sage/UI/nls/kk/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/kk/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/kk/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/kk/ActivityManager':function(){
define('Sage/MainView/nls/kk/ActivityManager',{});
},
'Sage/Services/nls/kk/JobService':function(){
define('Sage/Services/nls/kk/JobService',{});
},
'Sage/QuickForms/Design/nls/kk/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/_PropertyEditor',{});
},
'Sage/Services/nls/kk/ActivityActionProcessor':function(){
define('Sage/Services/nls/kk/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/kk/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/kk/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/kk/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/kk/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/kk/AlarmPane':function(){
define('Sage/UI/Alarms/nls/kk/AlarmPane',{});
},
'Sage/TaskPane/nls/kk/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/kk/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/kk/FilterPanel':function(){
define('Sage/UI/Filters/nls/kk/FilterPanel',{});
},
'Sage/TaskPane/nls/kk/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/kk/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportManagerFormatter',{});
},
'Sage/UI/nls/kk/OwnerType':function(){
define('Sage/UI/nls/kk/OwnerType',{});
},
'Sage/TaskPane/nls/kk/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/kk/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/kk/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/InvoiceRTDV',{});
},
'Sage/UI/nls/kk/SDataLookup':function(){
define('Sage/UI/nls/kk/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/kk/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/RowDesigner',{});
},
'Sage/TaskPane/nls/kk/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/kk/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/kk/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/kk/LibraryDocument':function(){
define('Sage/Utility/File/nls/kk/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/SpeedSearchLookup',{});
},
'Sage/UI/nls/kk/ConditionManager':function(){
define('Sage/UI/nls/kk/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/kk/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/kk/WidgetDefinition',{});
},
'Sage/UI/nls/kk/SearchConditionWidget':function(){
define('Sage/UI/nls/kk/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/kk/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/kk/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/kk/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/kk/DataSourcePanel',{});
},
'Sage/Library/nls/kk/Manager':function(){
define('Sage/Library/nls/kk/Manager',{});
},
'Sage/UI/nls/kk/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/kk/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/kk/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/kk/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/kk/Name':function(){
define('Sage/UI/Controls/nls/kk/Name',{});
},
'Sage/MainView/JobMgr/nls/kk/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/kk/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/kk/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/kk/UpdateLeads',{});
},
'Sage/Library/nls/kk/FileHandler':function(){
define('Sage/Library/nls/kk/FileHandler',{});
},
'Sage/UI/nls/kk/ListPanel':function(){
define('Sage/UI/nls/kk/ListPanel',{});
},
'Sage/Utility/nls/kk/Sql':function(){
define('Sage/Utility/nls/kk/Sql',{});
},
'Sage/UI/Filters/nls/kk/EditFilters':function(){
define('Sage/UI/Filters/nls/kk/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/kk/DurationSelect':function(){
define('Sage/UI/Controls/nls/kk/DurationSelect',{});
},
'Sage/UI/Alarms/nls/kk/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/kk/AlarmCountDown',{});
},
'Sage/UI/nls/kk/AttachmentList':function(){
define('Sage/UI/nls/kk/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/kk/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/kk/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/kk/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/kk/Dialogs':function(){
define('Sage/UI/nls/kk/Dialogs',{});
},
'Sage/TaskPane/nls/kk/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/kk/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/kk/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/kk/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/UserControlDesigner',{});
},
'Sage/Groups/nls/kk/GroupNavigator':function(){
define('Sage/Groups/nls/kk/GroupNavigator',{});
},
'Sage/Utility/File/nls/kk/AddURLAttachment':function(){
define('Sage/Utility/File/nls/kk/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/kk/EditFilterItems':function(){
define('Sage/UI/Filters/nls/kk/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/kk/DragDropWatcher':function(){
define('Sage/Utility/File/nls/kk/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/kk/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/kk/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/kk/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/kk/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/kk/ActivityScheduler':function(){
define('Sage/UI/nls/kk/ActivityScheduler',{});
},
'Sage/MainView/nls/kk/SecurityManager':function(){
define('Sage/MainView/nls/kk/SecurityManager',{});
},
'Sage/TaskPane/nls/kk/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/kk/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/kk/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/kk/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/kk/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/kk/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/kk/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/kk/UpdateOpportunities',{});
},
'Sage/UI/nls/kk/EditCalendarUsers':function(){
define('Sage/UI/nls/kk/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/kk/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/HelpMenu':function(){
define('Sage/UI/Controls/nls/kk/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/UserTasklet':function(){
define('Sage/TaskPane/nls/kk/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/kk/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/kk/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/kk/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/kk/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/kk/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/kk/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ColumnDesigner',{});
},
'Sage/UI/nls/kk/SearchMenuItem':function(){
define('Sage/UI/nls/kk/SearchMenuItem',{});
},
'Sage/Library/nls/kk/DocumentProperties':function(){
define('Sage/Library/nls/kk/DocumentProperties',{});
},
'Sage/UI/nls/kk/NotesHistoryList':function(){
define('Sage/UI/nls/kk/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/kk/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/kk/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/kk/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/kk/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/kk/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/kk/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/kk/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/kk/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/kk/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/kk/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/HistoryEditor',{});
},
'Sage/Groups/nls/kk/GroupManager':function(){
define('Sage/Groups/nls/kk/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/kk/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/kk/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/kk/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/kk/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/kk/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/kk/FolderHandler':function(){
define('Sage/Library/nls/kk/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/kk/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/kk/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/kk/EditableGrid':function(){
define('Sage/UI/nls/kk/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/kk/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/kk/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/kk/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportManagerUtility',{});
},
'Sage/UI/nls/kk/SpeedSearch':function(){
define('Sage/UI/nls/kk/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/kk/SLXPreviewGrid':function(){
define('Sage/UI/nls/kk/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/kk/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/kk/UnconfirmedPane',{});
},
'Sage/Utility/nls/kk/Utility':function(){
define('Sage/Utility/nls/kk/Utility',{});
},
'Sage/QuickForms/Design/nls/kk/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/Address':function(){
define('Sage/UI/Controls/nls/kk/Address',{});
},
'Sage/MainView/JobMgr/nls/kk/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/kk/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/kk/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/kk/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/kk/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/kk/UserType':function(){
define('Sage/UI/nls/kk/UserType',{});
},
'Sage/QuickForms/Design/nls/kk/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityCalendar',{});
},
'Sage/Utility/nls/kk/Jobs':function(){
define('Sage/Utility/nls/kk/Jobs',{});
},
'Sage/UI/Controls/nls/kk/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/kk/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/kk/ActivityList':function(){
define('Sage/UI/nls/kk/ActivityList',{});
},
'Sage/UI/Alarms/nls/kk/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/kk/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/kk/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/kk/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/kk/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/kk/CalendarUsersListPane':function(){
define('Sage/UI/nls/kk/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/kk/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/kk/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/kk/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/kk/Attachment':function(){
define('Sage/Utility/File/nls/kk/Attachment',{});
},
'Sage/QuickForms/Design/nls/kk/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/kk/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/kk/PropertyEditorContainer',{});
},
'Sage/Services/nls/kk/ReportingService':function(){
define('Sage/Services/nls/kk/ReportingService',{});
},
'Sage/MailMerge/nls/kk/Helper':function(){
define('Sage/MailMerge/nls/kk/Helper',{});
},
'Sage/UI/Dashboard/nls/kk/Dashboard':function(){
define('Sage/UI/Dashboard/nls/kk/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/kk/PickList':function(){
define('Sage/UI/Controls/nls/kk/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/kk/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/kk/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/kk/Email':function(){
define('Sage/Utility/nls/kk/Email',{});
},
'Sage/TaskPane/nls/kk/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/kk/TimeZoneItem':function(){
define('Sage/UI/nls/kk/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/kk/SlxEdit':function(){
define('Sage/UI/Columns/nls/kk/SlxEdit',{});
},
'Sage/Reporting/nls/kk/Enumerations':function(){
define('Sage/Reporting/nls/kk/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/kk/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/kk/ActivityListPanelConfig',{});
},
'Sage/UI/nls/kk/JobSchedulingWidget':function(){
define('Sage/UI/nls/kk/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/kk/LogOffButton':function(){
define('Sage/UI/Controls/nls/kk/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/kk/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/kk/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/EditEventEditor',{});
},
'Sage/MailMerge/nls/kk/Loader':function(){
define('Sage/MailMerge/nls/kk/Loader',{});
},
'Sage/UI/Controls/nls/kk/DateTimePicker':function(){
define('Sage/UI/Controls/nls/kk/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/kk/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/kk/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/kk/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/kk/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/kk/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/kk/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/kk/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/kk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/kk/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/Lookup':function(){
define('Sage/UI/Controls/nls/kk/Lookup',{});
},
'Sage/Utility/File/nls/kk/DescriptionsForm':function(){
define('Sage/Utility/File/nls/kk/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/CommonTasksTasklet',{});
},
'Sage/Utility/nls/kk/Dashboard':function(){
define('Sage/Utility/nls/kk/Dashboard',{});
}}});
define("Sage/nls/Sage_kk", [], 1);
