require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-ar/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-ar/Boolean':function(){
define('Sage/UI/nls/es-ar/Boolean',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-ar/ActivityService':function(){
define('Sage/Services/nls/es-ar/ActivityService',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-ar/CopyToClipboard',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-ar/Activity':function(){
define('Sage/Utility/nls/es-ar/Activity',{});
},
'Sage/QuickForms/Design/nls/es/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/es-ar/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es-ar/DesignPanel',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-ar/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/es/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/es-ar/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es-ar/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-ar/ActivityManager':function(){
define('Sage/MainView/nls/es-ar/ActivityManager',{});
},
'Sage/Services/nls/es/JobService':function(){
define('Sage/Services/nls/es/JobService',{});
},
'Sage/Services/nls/es-ar/JobService':function(){
define('Sage/Services/nls/es-ar/JobService',{});
},
'Sage/QuickForms/Design/nls/es/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/_PropertyEditor',{});
},
'Sage/Services/nls/es/ActivityActionProcessor':function(){
define('Sage/Services/nls/es/ActivityActionProcessor',{});
},
'Sage/Services/nls/es-ar/ActivityActionProcessor':function(){
define('Sage/Services/nls/es-ar/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-ar/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-ar/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-ar/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-ar/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ar/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ar/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-ar/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-ar/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/ReportManagerFormatter',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-ar/OwnerType':function(){
define('Sage/UI/nls/es-ar/OwnerType',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ar/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ar/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ar/InvoiceRTDV',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-ar/SDataLookup':function(){
define('Sage/UI/nls/es-ar/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/es/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/RowDesigner',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ar/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-ar/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-ar/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ar/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ar/SpeedSearchLookup',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-ar/ConditionManager':function(){
define('Sage/UI/nls/es-ar/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-ar/WidgetDefinition',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-ar/SearchConditionWidget':function(){
define('Sage/UI/nls/es-ar/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/es-ar/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es-ar/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ar/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ar/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/es/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/es-ar/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es-ar/DataSourcePanel',{});
},
'Sage/Library/nls/es/Manager':function(){
define('Sage/Library/nls/es/Manager',{});
},
'Sage/Library/nls/es-ar/Manager':function(){
define('Sage/Library/nls/es-ar/Manager',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/es/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/es-ar/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es-ar/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-ar/Name':function(){
define('Sage/UI/Controls/nls/es-ar/Name',{});
},
'Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ar/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ar/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-ar/UpdateLeads',{});
},
'Sage/Library/nls/es/FileHandler':function(){
define('Sage/Library/nls/es/FileHandler',{});
},
'Sage/Library/nls/es-ar/FileHandler':function(){
define('Sage/Library/nls/es-ar/FileHandler',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-ar/ListPanel':function(){
define('Sage/UI/nls/es-ar/ListPanel',{});
},
'Sage/Utility/nls/es/Sql':function(){
define('Sage/Utility/nls/es/Sql',{});
},
'Sage/Utility/nls/es-ar/Sql':function(){
define('Sage/Utility/nls/es-ar/Sql',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-ar/EditFilters':function(){
define('Sage/UI/Filters/nls/es-ar/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-ar/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-ar/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-ar/AttachmentList':function(){
define('Sage/UI/nls/es-ar/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/es-ar/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es-ar/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-ar/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/es/Dialogs':function(){
define('Sage/UI/nls/es/Dialogs',{});
},
'Sage/UI/nls/es-ar/Dialogs':function(){
define('Sage/UI/nls/es-ar/Dialogs',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-ar/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-ar/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ar/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ar/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/es/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/UserControlDesigner',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-ar/GroupNavigator':function(){
define('Sage/Groups/nls/es-ar/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-ar/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-ar/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/es/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es/DragDropWatcher',{});
},
'Sage/Utility/File/nls/es-ar/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es-ar/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/es/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/es-ar/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es-ar/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-ar/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-ar/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-ar/ActivityScheduler':function(){
define('Sage/UI/nls/es-ar/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-ar/SecurityManager':function(){
define('Sage/MainView/nls/es-ar/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-ar/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/es/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/es-ar/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es-ar/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-ar/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-ar/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-ar/UpdateOpportunities',{});
},
'Sage/UI/nls/es/EditCalendarUsers':function(){
define('Sage/UI/nls/es/EditCalendarUsers',{});
},
'Sage/UI/nls/es-ar/EditCalendarUsers':function(){
define('Sage/UI/nls/es-ar/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-ar/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-ar/UserTasklet':function(){
define('Sage/TaskPane/nls/es-ar/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-ar/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-ar/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/es-ar/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es-ar/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/es/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/ColumnDesigner',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-ar/SearchMenuItem':function(){
define('Sage/UI/nls/es-ar/SearchMenuItem',{});
},
'Sage/Library/nls/es/DocumentProperties':function(){
define('Sage/Library/nls/es/DocumentProperties',{});
},
'Sage/Library/nls/es-ar/DocumentProperties':function(){
define('Sage/Library/nls/es-ar/DocumentProperties',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-ar/NotesHistoryList':function(){
define('Sage/UI/nls/es-ar/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/es/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ar/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ar/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-ar/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-ar/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ar/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-ar/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-ar/GroupManager':function(){
define('Sage/Groups/nls/es-ar/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/es-ar/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es-ar/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ar/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ar/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/es/FolderHandler':function(){
define('Sage/Library/nls/es/FolderHandler',{});
},
'Sage/Library/nls/es-ar/FolderHandler':function(){
define('Sage/Library/nls/es-ar/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-ar/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ar/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-ar/EditableGrid':function(){
define('Sage/UI/nls/es-ar/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ar/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ar/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/es/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/es-ar/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es-ar/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/ReportManagerUtility',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-ar/SpeedSearch':function(){
define('Sage/UI/nls/es-ar/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/es/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ar/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ar/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-ar/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-ar/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-ar/Utility':function(){
define('Sage/Utility/nls/es-ar/Utility',{});
},
'Sage/QuickForms/Design/nls/es/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/ControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-ar/Address':function(){
define('Sage/UI/Controls/nls/es-ar/Address',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/es-ar/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es-ar/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/es/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ar/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ar/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-ar/UserType':function(){
define('Sage/UI/nls/es-ar/UserType',{});
},
'Sage/QuickForms/Design/nls/es/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/ActivityCalendar',{});
},
'Sage/Utility/nls/es/Jobs':function(){
define('Sage/Utility/nls/es/Jobs',{});
},
'Sage/Utility/nls/es-ar/Jobs':function(){
define('Sage/Utility/nls/es-ar/Jobs',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-ar/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-ar/ActivityList':function(){
define('Sage/UI/nls/es-ar/ActivityList',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/es-ar/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es-ar/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ar/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ar/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-ar/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/es-ar/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es-ar/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-ar/Attachment':function(){
define('Sage/Utility/File/nls/es-ar/Attachment',{});
},
'Sage/QuickForms/Design/nls/es/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/es-ar/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es-ar/PropertyEditorContainer',{});
},
'Sage/Services/nls/es/ReportingService':function(){
define('Sage/Services/nls/es/ReportingService',{});
},
'Sage/Services/nls/es-ar/ReportingService':function(){
define('Sage/Services/nls/es-ar/ReportingService',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-ar/Helper':function(){
define('Sage/MailMerge/nls/es-ar/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-ar/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-ar/PickList':function(){
define('Sage/UI/Controls/nls/es-ar/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-ar/Email':function(){
define('Sage/Utility/nls/es-ar/Email',{});
},
'Sage/TaskPane/nls/es/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ar/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ar/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-ar/TimeZoneItem':function(){
define('Sage/UI/nls/es-ar/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-ar/SlxEdit',{});
},
'Sage/Reporting/nls/es/Enumerations':function(){
define('Sage/Reporting/nls/es/Enumerations',{});
},
'Sage/Reporting/nls/es-ar/Enumerations':function(){
define('Sage/Reporting/nls/es-ar/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-ar/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-ar/ActivityListPanelConfig',{});
},
'Sage/UI/nls/es/JobSchedulingWidget':function(){
define('Sage/UI/nls/es/JobSchedulingWidget',{});
},
'Sage/UI/nls/es-ar/JobSchedulingWidget':function(){
define('Sage/UI/nls/es-ar/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-ar/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ar/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ar/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ar/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-ar/Loader':function(){
define('Sage/MailMerge/nls/es-ar/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-ar/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/es-ar/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es-ar/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-ar/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/es/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/es-ar/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es-ar/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ar/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ar/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ar/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ar/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-ar/Lookup':function(){
define('Sage/UI/Controls/nls/es-ar/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-ar/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ar/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ar/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ar/CommonTasksTasklet',{});
},
'Sage/Utility/nls/es/Dashboard':function(){
define('Sage/Utility/nls/es/Dashboard',{});
},
'Sage/Utility/nls/es-ar/Dashboard':function(){
define('Sage/Utility/nls/es-ar/Dashboard',{});
}}});
define("Sage/nls/Sage_es-ar", [], 1);
