require({cache:{
'Sage/Utility/File/nls/lv/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/lv/FallbackFilePicker',{});
},
'Sage/UI/nls/lv/Boolean':function(){
define('Sage/UI/nls/lv/Boolean',{});
},
'Sage/Services/nls/lv/ActivityService':function(){
define('Sage/Services/nls/lv/ActivityService',{});
},
'Sage/UI/Controls/nls/lv/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/lv/CopyToClipboard',{});
},
'Sage/Utility/nls/lv/Activity':function(){
define('Sage/Utility/nls/lv/Activity',{});
},
'Sage/QuickForms/Design/nls/lv/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/lv/DesignPanel',{});
},
'Sage/UI/nls/lv/TimelessActivitiesPane':function(){
define('Sage/UI/nls/lv/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/lv/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lv/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/lv/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/lv/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/lv/ActivityManager':function(){
define('Sage/MainView/nls/lv/ActivityManager',{});
},
'Sage/Services/nls/lv/JobService':function(){
define('Sage/Services/nls/lv/JobService',{});
},
'Sage/QuickForms/Design/nls/lv/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/_PropertyEditor',{});
},
'Sage/Services/nls/lv/ActivityActionProcessor':function(){
define('Sage/Services/nls/lv/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lv/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lv/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/lv/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/lv/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/lv/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/lv/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/lv/AlarmPane':function(){
define('Sage/UI/Alarms/nls/lv/AlarmPane',{});
},
'Sage/TaskPane/nls/lv/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/lv/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/lv/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/lv/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/lv/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/lv/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/lv/FilterPanel':function(){
define('Sage/UI/Filters/nls/lv/FilterPanel',{});
},
'Sage/TaskPane/nls/lv/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/lv/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/lv/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/lv/ReportManagerFormatter',{});
},
'Sage/UI/nls/lv/OwnerType':function(){
define('Sage/UI/nls/lv/OwnerType',{});
},
'Sage/TaskPane/nls/lv/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/lv/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/lv/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/lv/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/lv/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/lv/InvoiceRTDV',{});
},
'Sage/UI/nls/lv/SDataLookup':function(){
define('Sage/UI/nls/lv/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/lv/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/RowDesigner',{});
},
'Sage/TaskPane/nls/lv/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/lv/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/lv/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/lv/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/lv/LibraryDocument':function(){
define('Sage/Utility/File/nls/lv/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/lv/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/lv/SpeedSearchLookup',{});
},
'Sage/UI/nls/lv/ConditionManager':function(){
define('Sage/UI/nls/lv/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/lv/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/lv/WidgetDefinition',{});
},
'Sage/UI/nls/lv/SearchConditionWidget':function(){
define('Sage/UI/nls/lv/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/lv/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/lv/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/lv/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/lv/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/lv/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/lv/DataSourcePanel',{});
},
'Sage/Library/nls/lv/Manager':function(){
define('Sage/Library/nls/lv/Manager',{});
},
'Sage/UI/nls/lv/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/lv/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/lv/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/lv/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/lv/Name':function(){
define('Sage/UI/Controls/nls/lv/Name',{});
},
'Sage/MainView/JobMgr/nls/lv/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/lv/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/lv/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/lv/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/lv/UpdateLeads',{});
},
'Sage/Library/nls/lv/FileHandler':function(){
define('Sage/Library/nls/lv/FileHandler',{});
},
'Sage/UI/nls/lv/ListPanel':function(){
define('Sage/UI/nls/lv/ListPanel',{});
},
'Sage/Utility/nls/lv/Sql':function(){
define('Sage/Utility/nls/lv/Sql',{});
},
'Sage/UI/Filters/nls/lv/EditFilters':function(){
define('Sage/UI/Filters/nls/lv/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/lv/DurationSelect':function(){
define('Sage/UI/Controls/nls/lv/DurationSelect',{});
},
'Sage/UI/Alarms/nls/lv/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/lv/AlarmCountDown',{});
},
'Sage/UI/nls/lv/AttachmentList':function(){
define('Sage/UI/nls/lv/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/lv/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/lv/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/lv/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lv/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lv/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/lv/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/lv/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/lv/Dialogs':function(){
define('Sage/UI/nls/lv/Dialogs',{});
},
'Sage/TaskPane/nls/lv/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/lv/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/lv/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/lv/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/lv/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/lv/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/lv/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/UserControlDesigner',{});
},
'Sage/Groups/nls/lv/GroupNavigator':function(){
define('Sage/Groups/nls/lv/GroupNavigator',{});
},
'Sage/Utility/File/nls/lv/AddURLAttachment':function(){
define('Sage/Utility/File/nls/lv/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/lv/EditFilterItems':function(){
define('Sage/UI/Filters/nls/lv/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/lv/DragDropWatcher':function(){
define('Sage/Utility/File/nls/lv/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/lv/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/lv/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/lv/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lv/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lv/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lv/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/lv/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/lv/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/lv/ActivityScheduler':function(){
define('Sage/UI/nls/lv/ActivityScheduler',{});
},
'Sage/MainView/nls/lv/SecurityManager':function(){
define('Sage/MainView/nls/lv/SecurityManager',{});
},
'Sage/TaskPane/nls/lv/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/lv/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/lv/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/lv/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/lv/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/lv/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/lv/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/lv/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/lv/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/lv/UpdateOpportunities',{});
},
'Sage/UI/nls/lv/EditCalendarUsers':function(){
define('Sage/UI/nls/lv/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/lv/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/lv/HelpMenu':function(){
define('Sage/UI/Controls/nls/lv/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/lv/UserTasklet':function(){
define('Sage/TaskPane/nls/lv/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/lv/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/lv/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/lv/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/lv/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/lv/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/lv/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/lv/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/ColumnDesigner',{});
},
'Sage/UI/nls/lv/SearchMenuItem':function(){
define('Sage/UI/nls/lv/SearchMenuItem',{});
},
'Sage/Library/nls/lv/DocumentProperties':function(){
define('Sage/Library/nls/lv/DocumentProperties',{});
},
'Sage/UI/nls/lv/NotesHistoryList':function(){
define('Sage/UI/nls/lv/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/lv/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/lv/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/lv/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/lv/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/lv/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/lv/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/lv/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/lv/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/lv/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/lv/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/lv/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/lv/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/lv/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lv/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/lv/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lv/HistoryEditor',{});
},
'Sage/Groups/nls/lv/GroupManager':function(){
define('Sage/Groups/nls/lv/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/lv/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/lv/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/lv/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/lv/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/lv/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/lv/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/lv/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lv/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/lv/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/lv/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/lv/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lv/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lv/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/lv/FolderHandler':function(){
define('Sage/Library/nls/lv/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/lv/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/lv/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/lv/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/lv/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/lv/EditableGrid':function(){
define('Sage/UI/nls/lv/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/lv/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/lv/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/lv/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/lv/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/lv/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/lv/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/lv/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/lv/ReportManagerUtility',{});
},
'Sage/UI/nls/lv/SpeedSearch':function(){
define('Sage/UI/nls/lv/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/lv/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/lv/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/lv/SLXPreviewGrid':function(){
define('Sage/UI/nls/lv/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/lv/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/lv/UnconfirmedPane',{});
},
'Sage/Utility/nls/lv/Utility':function(){
define('Sage/Utility/nls/lv/Utility',{});
},
'Sage/QuickForms/Design/nls/lv/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/ControlDesigner',{});
},
'Sage/UI/Controls/nls/lv/Address':function(){
define('Sage/UI/Controls/nls/lv/Address',{});
},
'Sage/MainView/JobMgr/nls/lv/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/lv/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/lv/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lv/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/lv/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/lv/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/lv/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/lv/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/lv/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/lv/UserType':function(){
define('Sage/UI/nls/lv/UserType',{});
},
'Sage/QuickForms/Design/nls/lv/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/lv/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/lv/ActivityCalendar',{});
},
'Sage/Utility/nls/lv/Jobs':function(){
define('Sage/Utility/nls/lv/Jobs',{});
},
'Sage/UI/Controls/nls/lv/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/lv/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/lv/ActivityList':function(){
define('Sage/UI/nls/lv/ActivityList',{});
},
'Sage/UI/Alarms/nls/lv/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/lv/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/lv/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/lv/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/lv/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/lv/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/lv/CalendarUsersListPane':function(){
define('Sage/UI/nls/lv/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/lv/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/lv/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/lv/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/lv/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lv/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/lv/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/lv/Attachment':function(){
define('Sage/Utility/File/nls/lv/Attachment',{});
},
'Sage/QuickForms/Design/nls/lv/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/lv/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/lv/PropertyEditorContainer',{});
},
'Sage/Services/nls/lv/ReportingService':function(){
define('Sage/Services/nls/lv/ReportingService',{});
},
'Sage/MailMerge/nls/lv/Helper':function(){
define('Sage/MailMerge/nls/lv/Helper',{});
},
'Sage/UI/Dashboard/nls/lv/Dashboard':function(){
define('Sage/UI/Dashboard/nls/lv/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/lv/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lv/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/lv/PickList':function(){
define('Sage/UI/Controls/nls/lv/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/lv/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/lv/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/lv/Email':function(){
define('Sage/Utility/nls/lv/Email',{});
},
'Sage/TaskPane/nls/lv/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/lv/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/lv/TimeZoneItem':function(){
define('Sage/UI/nls/lv/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/lv/SlxEdit':function(){
define('Sage/UI/Columns/nls/lv/SlxEdit',{});
},
'Sage/Reporting/nls/lv/Enumerations':function(){
define('Sage/Reporting/nls/lv/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/lv/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/lv/ActivityListPanelConfig',{});
},
'Sage/UI/nls/lv/JobSchedulingWidget':function(){
define('Sage/UI/nls/lv/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/lv/LogOffButton':function(){
define('Sage/UI/Controls/nls/lv/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/lv/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/lv/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lv/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lv/EditEventEditor',{});
},
'Sage/MailMerge/nls/lv/Loader':function(){
define('Sage/MailMerge/nls/lv/Loader',{});
},
'Sage/UI/Controls/nls/lv/DateTimePicker':function(){
define('Sage/UI/Controls/nls/lv/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/lv/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/lv/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/lv/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/lv/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/lv/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/lv/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/lv/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/lv/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/lv/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lv/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lv/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/lv/Lookup':function(){
define('Sage/UI/Controls/nls/lv/Lookup',{});
},
'Sage/Utility/File/nls/lv/DescriptionsForm':function(){
define('Sage/Utility/File/nls/lv/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/lv/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lv/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/lv/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/lv/CommonTasksTasklet',{});
},
'Sage/Utility/nls/lv/Dashboard':function(){
define('Sage/Utility/nls/lv/Dashboard',{});
}}});
define("Sage/nls/Sage_lv", [], 1);
