require({cache:{
'Sage/Utility/File/nls/mt/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/mt/FallbackFilePicker',{});
},
'Sage/UI/nls/mt/Boolean':function(){
define('Sage/UI/nls/mt/Boolean',{});
},
'Sage/Services/nls/mt/ActivityService':function(){
define('Sage/Services/nls/mt/ActivityService',{});
},
'Sage/UI/Controls/nls/mt/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/mt/CopyToClipboard',{});
},
'Sage/Utility/nls/mt/Activity':function(){
define('Sage/Utility/nls/mt/Activity',{});
},
'Sage/QuickForms/Design/nls/mt/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/mt/DesignPanel',{});
},
'Sage/UI/nls/mt/TimelessActivitiesPane':function(){
define('Sage/UI/nls/mt/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/mt/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mt/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/mt/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/mt/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/mt/ActivityManager':function(){
define('Sage/MainView/nls/mt/ActivityManager',{});
},
'Sage/Services/nls/mt/JobService':function(){
define('Sage/Services/nls/mt/JobService',{});
},
'Sage/QuickForms/Design/nls/mt/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/_PropertyEditor',{});
},
'Sage/Services/nls/mt/ActivityActionProcessor':function(){
define('Sage/Services/nls/mt/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mt/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mt/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/mt/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/mt/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/mt/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/mt/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/mt/AlarmPane':function(){
define('Sage/UI/Alarms/nls/mt/AlarmPane',{});
},
'Sage/TaskPane/nls/mt/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/mt/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/mt/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/mt/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mt/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mt/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/mt/FilterPanel':function(){
define('Sage/UI/Filters/nls/mt/FilterPanel',{});
},
'Sage/TaskPane/nls/mt/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/mt/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/mt/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/mt/ReportManagerFormatter',{});
},
'Sage/UI/nls/mt/OwnerType':function(){
define('Sage/UI/nls/mt/OwnerType',{});
},
'Sage/TaskPane/nls/mt/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/mt/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/mt/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/mt/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mt/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mt/InvoiceRTDV',{});
},
'Sage/UI/nls/mt/SDataLookup':function(){
define('Sage/UI/nls/mt/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/mt/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/RowDesigner',{});
},
'Sage/TaskPane/nls/mt/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/mt/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/mt/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/mt/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/mt/LibraryDocument':function(){
define('Sage/Utility/File/nls/mt/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/mt/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/mt/SpeedSearchLookup',{});
},
'Sage/UI/nls/mt/ConditionManager':function(){
define('Sage/UI/nls/mt/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/mt/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/mt/WidgetDefinition',{});
},
'Sage/UI/nls/mt/SearchConditionWidget':function(){
define('Sage/UI/nls/mt/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/mt/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/mt/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/mt/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/mt/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/mt/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/mt/DataSourcePanel',{});
},
'Sage/Library/nls/mt/Manager':function(){
define('Sage/Library/nls/mt/Manager',{});
},
'Sage/UI/nls/mt/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/mt/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/mt/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/mt/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/mt/Name':function(){
define('Sage/UI/Controls/nls/mt/Name',{});
},
'Sage/MainView/JobMgr/nls/mt/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/mt/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/mt/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/mt/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/mt/UpdateLeads',{});
},
'Sage/Library/nls/mt/FileHandler':function(){
define('Sage/Library/nls/mt/FileHandler',{});
},
'Sage/UI/nls/mt/ListPanel':function(){
define('Sage/UI/nls/mt/ListPanel',{});
},
'Sage/Utility/nls/mt/Sql':function(){
define('Sage/Utility/nls/mt/Sql',{});
},
'Sage/UI/Filters/nls/mt/EditFilters':function(){
define('Sage/UI/Filters/nls/mt/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/mt/DurationSelect':function(){
define('Sage/UI/Controls/nls/mt/DurationSelect',{});
},
'Sage/UI/Alarms/nls/mt/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/mt/AlarmCountDown',{});
},
'Sage/UI/nls/mt/AttachmentList':function(){
define('Sage/UI/nls/mt/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/mt/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/mt/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/mt/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mt/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mt/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/mt/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/mt/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/mt/Dialogs':function(){
define('Sage/UI/nls/mt/Dialogs',{});
},
'Sage/TaskPane/nls/mt/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/mt/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/mt/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/mt/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/mt/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mt/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/mt/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/UserControlDesigner',{});
},
'Sage/Groups/nls/mt/GroupNavigator':function(){
define('Sage/Groups/nls/mt/GroupNavigator',{});
},
'Sage/Utility/File/nls/mt/AddURLAttachment':function(){
define('Sage/Utility/File/nls/mt/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/mt/EditFilterItems':function(){
define('Sage/UI/Filters/nls/mt/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/mt/DragDropWatcher':function(){
define('Sage/Utility/File/nls/mt/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/mt/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/mt/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/mt/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mt/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mt/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mt/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/mt/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/mt/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/mt/ActivityScheduler':function(){
define('Sage/UI/nls/mt/ActivityScheduler',{});
},
'Sage/MainView/nls/mt/SecurityManager':function(){
define('Sage/MainView/nls/mt/SecurityManager',{});
},
'Sage/TaskPane/nls/mt/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/mt/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/mt/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/mt/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/mt/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/mt/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/mt/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/mt/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/mt/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/mt/UpdateOpportunities',{});
},
'Sage/UI/nls/mt/EditCalendarUsers':function(){
define('Sage/UI/nls/mt/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/mt/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/mt/HelpMenu':function(){
define('Sage/UI/Controls/nls/mt/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/mt/UserTasklet':function(){
define('Sage/TaskPane/nls/mt/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/mt/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/mt/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/mt/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/mt/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mt/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/mt/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/mt/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/ColumnDesigner',{});
},
'Sage/UI/nls/mt/SearchMenuItem':function(){
define('Sage/UI/nls/mt/SearchMenuItem',{});
},
'Sage/Library/nls/mt/DocumentProperties':function(){
define('Sage/Library/nls/mt/DocumentProperties',{});
},
'Sage/UI/nls/mt/NotesHistoryList':function(){
define('Sage/UI/nls/mt/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/mt/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/mt/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/mt/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/mt/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/mt/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/mt/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/mt/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/mt/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/mt/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/mt/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/mt/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/mt/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/mt/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mt/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/mt/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mt/HistoryEditor',{});
},
'Sage/Groups/nls/mt/GroupManager':function(){
define('Sage/Groups/nls/mt/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/mt/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/mt/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/mt/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/mt/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/mt/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/mt/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/mt/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mt/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/mt/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/mt/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/mt/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mt/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mt/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/mt/FolderHandler':function(){
define('Sage/Library/nls/mt/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/mt/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/mt/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/mt/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/mt/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/mt/EditableGrid':function(){
define('Sage/UI/nls/mt/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/mt/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mt/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/mt/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/mt/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/mt/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/mt/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/mt/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/mt/ReportManagerUtility',{});
},
'Sage/UI/nls/mt/SpeedSearch':function(){
define('Sage/UI/nls/mt/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/mt/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/mt/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/mt/SLXPreviewGrid':function(){
define('Sage/UI/nls/mt/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/mt/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/mt/UnconfirmedPane',{});
},
'Sage/Utility/nls/mt/Utility':function(){
define('Sage/Utility/nls/mt/Utility',{});
},
'Sage/QuickForms/Design/nls/mt/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/ControlDesigner',{});
},
'Sage/UI/Controls/nls/mt/Address':function(){
define('Sage/UI/Controls/nls/mt/Address',{});
},
'Sage/MainView/JobMgr/nls/mt/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/mt/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/mt/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mt/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/mt/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/mt/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/mt/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/mt/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/mt/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/mt/UserType':function(){
define('Sage/UI/nls/mt/UserType',{});
},
'Sage/QuickForms/Design/nls/mt/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/mt/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/mt/ActivityCalendar',{});
},
'Sage/Utility/nls/mt/Jobs':function(){
define('Sage/Utility/nls/mt/Jobs',{});
},
'Sage/UI/Controls/nls/mt/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/mt/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/mt/ActivityList':function(){
define('Sage/UI/nls/mt/ActivityList',{});
},
'Sage/UI/Alarms/nls/mt/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/mt/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/mt/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/mt/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/mt/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/mt/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/mt/CalendarUsersListPane':function(){
define('Sage/UI/nls/mt/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/mt/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/mt/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/mt/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/mt/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mt/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/mt/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/mt/Attachment':function(){
define('Sage/Utility/File/nls/mt/Attachment',{});
},
'Sage/QuickForms/Design/nls/mt/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/mt/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/mt/PropertyEditorContainer',{});
},
'Sage/Services/nls/mt/ReportingService':function(){
define('Sage/Services/nls/mt/ReportingService',{});
},
'Sage/MailMerge/nls/mt/Helper':function(){
define('Sage/MailMerge/nls/mt/Helper',{});
},
'Sage/UI/Dashboard/nls/mt/Dashboard':function(){
define('Sage/UI/Dashboard/nls/mt/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/mt/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mt/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/mt/PickList':function(){
define('Sage/UI/Controls/nls/mt/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/mt/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/mt/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/mt/Email':function(){
define('Sage/Utility/nls/mt/Email',{});
},
'Sage/TaskPane/nls/mt/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/mt/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/mt/TimeZoneItem':function(){
define('Sage/UI/nls/mt/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/mt/SlxEdit':function(){
define('Sage/UI/Columns/nls/mt/SlxEdit',{});
},
'Sage/Reporting/nls/mt/Enumerations':function(){
define('Sage/Reporting/nls/mt/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/mt/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/mt/ActivityListPanelConfig',{});
},
'Sage/UI/nls/mt/JobSchedulingWidget':function(){
define('Sage/UI/nls/mt/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/mt/LogOffButton':function(){
define('Sage/UI/Controls/nls/mt/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/mt/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/mt/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mt/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mt/EditEventEditor',{});
},
'Sage/MailMerge/nls/mt/Loader':function(){
define('Sage/MailMerge/nls/mt/Loader',{});
},
'Sage/UI/Controls/nls/mt/DateTimePicker':function(){
define('Sage/UI/Controls/nls/mt/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/mt/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/mt/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/mt/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/mt/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/mt/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/mt/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/mt/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/mt/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/mt/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mt/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mt/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/mt/Lookup':function(){
define('Sage/UI/Controls/nls/mt/Lookup',{});
},
'Sage/Utility/File/nls/mt/DescriptionsForm':function(){
define('Sage/Utility/File/nls/mt/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/mt/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mt/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/mt/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/mt/CommonTasksTasklet',{});
},
'Sage/Utility/nls/mt/Dashboard':function(){
define('Sage/Utility/nls/mt/Dashboard',{});
}}});
define("Sage/nls/Sage_mt", [], 1);
