require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-dz/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-dz/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-dz/Boolean':function(){
define('Sage/UI/nls/ar-dz/Boolean',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-dz/ActivityService':function(){
define('Sage/Services/nls/ar-dz/ActivityService',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-dz/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-dz/CopyToClipboard',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-dz/Activity':function(){
define('Sage/Utility/nls/ar-dz/Activity',{});
},
'Sage/QuickForms/Design/nls/ar/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/ar-dz/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar-dz/DesignPanel',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-dz/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-dz/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/ar-dz/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar-dz/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-dz/ActivityManager':function(){
define('Sage/MainView/nls/ar-dz/ActivityManager',{});
},
'Sage/Services/nls/ar/JobService':function(){
define('Sage/Services/nls/ar/JobService',{});
},
'Sage/Services/nls/ar-dz/JobService':function(){
define('Sage/Services/nls/ar-dz/JobService',{});
},
'Sage/QuickForms/Design/nls/ar/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/_PropertyEditor',{});
},
'Sage/Services/nls/ar/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar/ActivityActionProcessor',{});
},
'Sage/Services/nls/ar-dz/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar-dz/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-dz/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-dz/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-dz/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-dz/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-dz/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-dz/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-dz/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-dz/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-dz/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-dz/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-dz/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-dz/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-dz/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-dz/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/ReportManagerFormatter',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-dz/OwnerType':function(){
define('Sage/UI/nls/ar-dz/OwnerType',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-dz/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-dz/InvoiceRTDV',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-dz/SDataLookup':function(){
define('Sage/UI/nls/ar-dz/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ar/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/RowDesigner',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-dz/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-dz/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-dz/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-dz/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-dz/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-dz/SpeedSearchLookup',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-dz/ConditionManager':function(){
define('Sage/UI/nls/ar-dz/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-dz/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-dz/WidgetDefinition',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-dz/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-dz/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/ar-dz/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar-dz/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-dz/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-dz/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ar/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/ar-dz/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar-dz/DataSourcePanel',{});
},
'Sage/Library/nls/ar/Manager':function(){
define('Sage/Library/nls/ar/Manager',{});
},
'Sage/Library/nls/ar-dz/Manager':function(){
define('Sage/Library/nls/ar-dz/Manager',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-dz/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-dz/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/ar-dz/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar-dz/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-dz/Name':function(){
define('Sage/UI/Controls/nls/ar-dz/Name',{});
},
'Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-dz/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-dz/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-dz/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-dz/UpdateLeads',{});
},
'Sage/Library/nls/ar/FileHandler':function(){
define('Sage/Library/nls/ar/FileHandler',{});
},
'Sage/Library/nls/ar-dz/FileHandler':function(){
define('Sage/Library/nls/ar-dz/FileHandler',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-dz/ListPanel':function(){
define('Sage/UI/nls/ar-dz/ListPanel',{});
},
'Sage/Utility/nls/ar/Sql':function(){
define('Sage/Utility/nls/ar/Sql',{});
},
'Sage/Utility/nls/ar-dz/Sql':function(){
define('Sage/Utility/nls/ar-dz/Sql',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-dz/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-dz/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-dz/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-dz/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-dz/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-dz/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-dz/AttachmentList':function(){
define('Sage/UI/nls/ar-dz/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/ar-dz/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar-dz/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-dz/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-dz/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/Dialogs':function(){
define('Sage/UI/nls/ar/Dialogs',{});
},
'Sage/UI/nls/ar-dz/Dialogs':function(){
define('Sage/UI/nls/ar-dz/Dialogs',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-dz/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-dz/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-dz/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-dz/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ar/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/UserControlDesigner',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-dz/GroupNavigator':function(){
define('Sage/Groups/nls/ar-dz/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-dz/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-dz/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-dz/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-dz/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ar/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar/DragDropWatcher',{});
},
'Sage/Utility/File/nls/ar-dz/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar-dz/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ar/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/ar-dz/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar-dz/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-dz/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-dz/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-dz/ActivityScheduler':function(){
define('Sage/UI/nls/ar-dz/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-dz/SecurityManager':function(){
define('Sage/MainView/nls/ar-dz/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-dz/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-dz/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ar/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/ar-dz/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar-dz/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-dz/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-dz/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-dz/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-dz/UpdateOpportunities',{});
},
'Sage/UI/nls/ar/EditCalendarUsers':function(){
define('Sage/UI/nls/ar/EditCalendarUsers',{});
},
'Sage/UI/nls/ar-dz/EditCalendarUsers':function(){
define('Sage/UI/nls/ar-dz/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-dz/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-dz/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-dz/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-dz/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-dz/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-dz/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/ar-dz/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar-dz/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ar/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/ColumnDesigner',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-dz/SearchMenuItem':function(){
define('Sage/UI/nls/ar-dz/SearchMenuItem',{});
},
'Sage/Library/nls/ar/DocumentProperties':function(){
define('Sage/Library/nls/ar/DocumentProperties',{});
},
'Sage/Library/nls/ar-dz/DocumentProperties':function(){
define('Sage/Library/nls/ar-dz/DocumentProperties',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-dz/NotesHistoryList':function(){
define('Sage/UI/nls/ar-dz/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ar/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ar/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar-dz/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar-dz/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-dz/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-dz/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-dz/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-dz/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-dz/GroupManager':function(){
define('Sage/Groups/nls/ar-dz/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/ar-dz/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar-dz/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-dz/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-dz/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ar/FolderHandler':function(){
define('Sage/Library/nls/ar/FolderHandler',{});
},
'Sage/Library/nls/ar-dz/FolderHandler':function(){
define('Sage/Library/nls/ar-dz/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-dz/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-dz/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-dz/EditableGrid':function(){
define('Sage/UI/nls/ar-dz/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/ar-dz/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar-dz/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ar/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/ar-dz/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar-dz/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/ReportManagerUtility',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-dz/SpeedSearch':function(){
define('Sage/UI/nls/ar-dz/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-dz/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-dz/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-dz/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-dz/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-dz/Utility':function(){
define('Sage/Utility/nls/ar-dz/Utility',{});
},
'Sage/QuickForms/Design/nls/ar/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-dz/Address':function(){
define('Sage/UI/Controls/nls/ar-dz/Address',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/ar-dz/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar-dz/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ar/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-dz/UserType':function(){
define('Sage/UI/nls/ar-dz/UserType',{});
},
'Sage/QuickForms/Design/nls/ar/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/ActivityCalendar',{});
},
'Sage/Utility/nls/ar/Jobs':function(){
define('Sage/Utility/nls/ar/Jobs',{});
},
'Sage/Utility/nls/ar-dz/Jobs':function(){
define('Sage/Utility/nls/ar-dz/Jobs',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-dz/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-dz/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-dz/ActivityList':function(){
define('Sage/UI/nls/ar-dz/ActivityList',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/ar-dz/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar-dz/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-dz/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar-dz/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-dz/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-dz/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/ar-dz/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar-dz/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-dz/Attachment':function(){
define('Sage/Utility/File/nls/ar-dz/Attachment',{});
},
'Sage/QuickForms/Design/nls/ar/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ar/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/ar-dz/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar-dz/PropertyEditorContainer',{});
},
'Sage/Services/nls/ar/ReportingService':function(){
define('Sage/Services/nls/ar/ReportingService',{});
},
'Sage/Services/nls/ar-dz/ReportingService':function(){
define('Sage/Services/nls/ar-dz/ReportingService',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-dz/Helper':function(){
define('Sage/MailMerge/nls/ar-dz/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-dz/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-dz/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-dz/PickList':function(){
define('Sage/UI/Controls/nls/ar-dz/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-dz/Email':function(){
define('Sage/Utility/nls/ar-dz/Email',{});
},
'Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-dz/TimeZoneItem':function(){
define('Sage/UI/nls/ar-dz/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-dz/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-dz/SlxEdit',{});
},
'Sage/Reporting/nls/ar/Enumerations':function(){
define('Sage/Reporting/nls/ar/Enumerations',{});
},
'Sage/Reporting/nls/ar-dz/Enumerations':function(){
define('Sage/Reporting/nls/ar-dz/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar-dz/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar-dz/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ar/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar/JobSchedulingWidget',{});
},
'Sage/UI/nls/ar-dz/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar-dz/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-dz/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-dz/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar-dz/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar-dz/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-dz/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-dz/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-dz/Loader':function(){
define('Sage/MailMerge/nls/ar-dz/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-dz/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-dz/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/ar-dz/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar-dz/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-dz/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-dz/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/ar-dz/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar-dz/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/ar-dz/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar-dz/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar-dz/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar-dz/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-dz/Lookup':function(){
define('Sage/UI/Controls/nls/ar-dz/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-dz/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-dz/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar-dz/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar-dz/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-dz/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-dz/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ar/Dashboard':function(){
define('Sage/Utility/nls/ar/Dashboard',{});
},
'Sage/Utility/nls/ar-dz/Dashboard':function(){
define('Sage/Utility/nls/ar-dz/Dashboard',{});
}}});
define("Sage/nls/Sage_ar-dz", [], 1);
