require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-ve/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-ve/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-ve/Boolean':function(){
define('Sage/UI/nls/es-ve/Boolean',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-ve/ActivityService':function(){
define('Sage/Services/nls/es-ve/ActivityService',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-ve/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-ve/CopyToClipboard',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-ve/Activity':function(){
define('Sage/Utility/nls/es-ve/Activity',{});
},
'Sage/QuickForms/Design/nls/es/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/es-ve/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es-ve/DesignPanel',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-ve/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-ve/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/es/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/es-ve/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es-ve/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-ve/ActivityManager':function(){
define('Sage/MainView/nls/es-ve/ActivityManager',{});
},
'Sage/Services/nls/es/JobService':function(){
define('Sage/Services/nls/es/JobService',{});
},
'Sage/Services/nls/es-ve/JobService':function(){
define('Sage/Services/nls/es-ve/JobService',{});
},
'Sage/QuickForms/Design/nls/es/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/_PropertyEditor',{});
},
'Sage/Services/nls/es/ActivityActionProcessor':function(){
define('Sage/Services/nls/es/ActivityActionProcessor',{});
},
'Sage/Services/nls/es-ve/ActivityActionProcessor':function(){
define('Sage/Services/nls/es-ve/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-ve/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-ve/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-ve/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-ve/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-ve/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-ve/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-ve/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-ve/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-ve/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-ve/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ve/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ve/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-ve/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-ve/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-ve/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-ve/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/ReportManagerFormatter',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-ve/OwnerType':function(){
define('Sage/UI/nls/es-ve/OwnerType',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ve/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ve/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ve/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ve/InvoiceRTDV',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-ve/SDataLookup':function(){
define('Sage/UI/nls/es-ve/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/es/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/RowDesigner',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ve/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ve/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-ve/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-ve/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-ve/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-ve/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ve/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ve/SpeedSearchLookup',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-ve/ConditionManager':function(){
define('Sage/UI/nls/es-ve/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-ve/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-ve/WidgetDefinition',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-ve/SearchConditionWidget':function(){
define('Sage/UI/nls/es-ve/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/es-ve/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es-ve/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ve/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ve/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/es/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/es-ve/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es-ve/DataSourcePanel',{});
},
'Sage/Library/nls/es/Manager':function(){
define('Sage/Library/nls/es/Manager',{});
},
'Sage/Library/nls/es-ve/Manager':function(){
define('Sage/Library/nls/es-ve/Manager',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-ve/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-ve/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/es/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/es-ve/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es-ve/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-ve/Name':function(){
define('Sage/UI/Controls/nls/es-ve/Name',{});
},
'Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ve/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ve/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-ve/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-ve/UpdateLeads',{});
},
'Sage/Library/nls/es/FileHandler':function(){
define('Sage/Library/nls/es/FileHandler',{});
},
'Sage/Library/nls/es-ve/FileHandler':function(){
define('Sage/Library/nls/es-ve/FileHandler',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-ve/ListPanel':function(){
define('Sage/UI/nls/es-ve/ListPanel',{});
},
'Sage/Utility/nls/es/Sql':function(){
define('Sage/Utility/nls/es/Sql',{});
},
'Sage/Utility/nls/es-ve/Sql':function(){
define('Sage/Utility/nls/es-ve/Sql',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-ve/EditFilters':function(){
define('Sage/UI/Filters/nls/es-ve/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-ve/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-ve/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-ve/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-ve/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-ve/AttachmentList':function(){
define('Sage/UI/nls/es-ve/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/es-ve/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es-ve/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-ve/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-ve/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/es/Dialogs':function(){
define('Sage/UI/nls/es/Dialogs',{});
},
'Sage/UI/nls/es-ve/Dialogs':function(){
define('Sage/UI/nls/es-ve/Dialogs',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-ve/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-ve/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-ve/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-ve/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ve/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ve/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/es/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/UserControlDesigner',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-ve/GroupNavigator':function(){
define('Sage/Groups/nls/es-ve/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-ve/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-ve/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-ve/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-ve/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/es/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es/DragDropWatcher',{});
},
'Sage/Utility/File/nls/es-ve/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es-ve/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/es/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/es-ve/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es-ve/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-ve/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-ve/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-ve/ActivityScheduler':function(){
define('Sage/UI/nls/es-ve/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-ve/SecurityManager':function(){
define('Sage/MainView/nls/es-ve/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-ve/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-ve/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/es/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/es-ve/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es-ve/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-ve/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-ve/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-ve/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-ve/UpdateOpportunities',{});
},
'Sage/UI/nls/es/EditCalendarUsers':function(){
define('Sage/UI/nls/es/EditCalendarUsers',{});
},
'Sage/UI/nls/es-ve/EditCalendarUsers':function(){
define('Sage/UI/nls/es-ve/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-ve/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-ve/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-ve/UserTasklet':function(){
define('Sage/TaskPane/nls/es-ve/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-ve/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-ve/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-ve/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-ve/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/es-ve/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es-ve/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/es/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/ColumnDesigner',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-ve/SearchMenuItem':function(){
define('Sage/UI/nls/es-ve/SearchMenuItem',{});
},
'Sage/Library/nls/es/DocumentProperties':function(){
define('Sage/Library/nls/es/DocumentProperties',{});
},
'Sage/Library/nls/es-ve/DocumentProperties':function(){
define('Sage/Library/nls/es-ve/DocumentProperties',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-ve/NotesHistoryList':function(){
define('Sage/UI/nls/es-ve/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/es/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ve/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ve/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-ve/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-ve/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ve/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ve/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-ve/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-ve/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-ve/GroupManager':function(){
define('Sage/Groups/nls/es-ve/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/es-ve/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es-ve/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ve/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ve/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/es/FolderHandler':function(){
define('Sage/Library/nls/es/FolderHandler',{});
},
'Sage/Library/nls/es-ve/FolderHandler':function(){
define('Sage/Library/nls/es-ve/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-ve/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-ve/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ve/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ve/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-ve/EditableGrid':function(){
define('Sage/UI/nls/es-ve/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ve/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ve/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/es/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/es-ve/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es-ve/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/ReportManagerUtility',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-ve/SpeedSearch':function(){
define('Sage/UI/nls/es-ve/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/es/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ve/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ve/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-ve/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-ve/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-ve/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-ve/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-ve/Utility':function(){
define('Sage/Utility/nls/es-ve/Utility',{});
},
'Sage/QuickForms/Design/nls/es/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/ControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-ve/Address':function(){
define('Sage/UI/Controls/nls/es-ve/Address',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/es-ve/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es-ve/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/es/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ve/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ve/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-ve/UserType':function(){
define('Sage/UI/nls/es-ve/UserType',{});
},
'Sage/QuickForms/Design/nls/es/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/ActivityCalendar',{});
},
'Sage/Utility/nls/es/Jobs':function(){
define('Sage/Utility/nls/es/Jobs',{});
},
'Sage/Utility/nls/es-ve/Jobs':function(){
define('Sage/Utility/nls/es-ve/Jobs',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-ve/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-ve/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-ve/ActivityList':function(){
define('Sage/UI/nls/es-ve/ActivityList',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/es-ve/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es-ve/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ve/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ve/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-ve/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-ve/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/es-ve/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es-ve/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-ve/Attachment':function(){
define('Sage/Utility/File/nls/es-ve/Attachment',{});
},
'Sage/QuickForms/Design/nls/es/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/es-ve/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es-ve/PropertyEditorContainer',{});
},
'Sage/Services/nls/es/ReportingService':function(){
define('Sage/Services/nls/es/ReportingService',{});
},
'Sage/Services/nls/es-ve/ReportingService':function(){
define('Sage/Services/nls/es-ve/ReportingService',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-ve/Helper':function(){
define('Sage/MailMerge/nls/es-ve/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-ve/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-ve/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-ve/PickList':function(){
define('Sage/UI/Controls/nls/es-ve/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-ve/Email':function(){
define('Sage/Utility/nls/es-ve/Email',{});
},
'Sage/TaskPane/nls/es/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ve/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ve/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-ve/TimeZoneItem':function(){
define('Sage/UI/nls/es-ve/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-ve/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-ve/SlxEdit',{});
},
'Sage/Reporting/nls/es/Enumerations':function(){
define('Sage/Reporting/nls/es/Enumerations',{});
},
'Sage/Reporting/nls/es-ve/Enumerations':function(){
define('Sage/Reporting/nls/es-ve/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-ve/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-ve/ActivityListPanelConfig',{});
},
'Sage/UI/nls/es/JobSchedulingWidget':function(){
define('Sage/UI/nls/es/JobSchedulingWidget',{});
},
'Sage/UI/nls/es-ve/JobSchedulingWidget':function(){
define('Sage/UI/nls/es-ve/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-ve/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-ve/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ve/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ve/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ve/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ve/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-ve/Loader':function(){
define('Sage/MailMerge/nls/es-ve/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-ve/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-ve/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/es-ve/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es-ve/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-ve/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-ve/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/es/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/es-ve/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es-ve/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ve/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ve/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ve/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ve/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-ve/Lookup':function(){
define('Sage/UI/Controls/nls/es-ve/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-ve/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-ve/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ve/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ve/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ve/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ve/CommonTasksTasklet',{});
},
'Sage/Utility/nls/es/Dashboard':function(){
define('Sage/Utility/nls/es/Dashboard',{});
},
'Sage/Utility/nls/es-ve/Dashboard':function(){
define('Sage/Utility/nls/es-ve/Dashboard',{});
}}});
define("Sage/nls/Sage_es-ve", [], 1);
