require({cache:{
'Sage/Utility/File/nls/ur/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ur/FallbackFilePicker',{});
},
'Sage/UI/nls/ur/Boolean':function(){
define('Sage/UI/nls/ur/Boolean',{});
},
'Sage/Services/nls/ur/ActivityService':function(){
define('Sage/Services/nls/ur/ActivityService',{});
},
'Sage/UI/Controls/nls/ur/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ur/CopyToClipboard',{});
},
'Sage/Utility/nls/ur/Activity':function(){
define('Sage/Utility/nls/ur/Activity',{});
},
'Sage/QuickForms/Design/nls/ur/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ur/DesignPanel',{});
},
'Sage/UI/nls/ur/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ur/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ur/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ur/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ur/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ur/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ur/ActivityManager':function(){
define('Sage/MainView/nls/ur/ActivityManager',{});
},
'Sage/Services/nls/ur/JobService':function(){
define('Sage/Services/nls/ur/JobService',{});
},
'Sage/QuickForms/Design/nls/ur/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/_PropertyEditor',{});
},
'Sage/Services/nls/ur/ActivityActionProcessor':function(){
define('Sage/Services/nls/ur/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ur/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ur/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ur/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ur/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ur/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ur/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ur/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ur/AlarmPane',{});
},
'Sage/TaskPane/nls/ur/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ur/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ur/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ur/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ur/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ur/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ur/FilterPanel':function(){
define('Sage/UI/Filters/nls/ur/FilterPanel',{});
},
'Sage/TaskPane/nls/ur/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ur/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ur/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ur/ReportManagerFormatter',{});
},
'Sage/UI/nls/ur/OwnerType':function(){
define('Sage/UI/nls/ur/OwnerType',{});
},
'Sage/TaskPane/nls/ur/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ur/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ur/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ur/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ur/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ur/InvoiceRTDV',{});
},
'Sage/UI/nls/ur/SDataLookup':function(){
define('Sage/UI/nls/ur/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ur/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/RowDesigner',{});
},
'Sage/TaskPane/nls/ur/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ur/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ur/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ur/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ur/LibraryDocument':function(){
define('Sage/Utility/File/nls/ur/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ur/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ur/SpeedSearchLookup',{});
},
'Sage/UI/nls/ur/ConditionManager':function(){
define('Sage/UI/nls/ur/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ur/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ur/WidgetDefinition',{});
},
'Sage/UI/nls/ur/SearchConditionWidget':function(){
define('Sage/UI/nls/ur/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ur/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ur/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ur/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ur/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ur/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ur/DataSourcePanel',{});
},
'Sage/Library/nls/ur/Manager':function(){
define('Sage/Library/nls/ur/Manager',{});
},
'Sage/UI/nls/ur/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ur/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ur/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ur/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ur/Name':function(){
define('Sage/UI/Controls/nls/ur/Name',{});
},
'Sage/MainView/JobMgr/nls/ur/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ur/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ur/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ur/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ur/UpdateLeads',{});
},
'Sage/Library/nls/ur/FileHandler':function(){
define('Sage/Library/nls/ur/FileHandler',{});
},
'Sage/UI/nls/ur/ListPanel':function(){
define('Sage/UI/nls/ur/ListPanel',{});
},
'Sage/Utility/nls/ur/Sql':function(){
define('Sage/Utility/nls/ur/Sql',{});
},
'Sage/UI/Filters/nls/ur/EditFilters':function(){
define('Sage/UI/Filters/nls/ur/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ur/DurationSelect':function(){
define('Sage/UI/Controls/nls/ur/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ur/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ur/AlarmCountDown',{});
},
'Sage/UI/nls/ur/AttachmentList':function(){
define('Sage/UI/nls/ur/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ur/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ur/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ur/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ur/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ur/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ur/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ur/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ur/Dialogs':function(){
define('Sage/UI/nls/ur/Dialogs',{});
},
'Sage/TaskPane/nls/ur/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ur/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ur/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ur/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ur/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ur/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ur/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/UserControlDesigner',{});
},
'Sage/Groups/nls/ur/GroupNavigator':function(){
define('Sage/Groups/nls/ur/GroupNavigator',{});
},
'Sage/Utility/File/nls/ur/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ur/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ur/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ur/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ur/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ur/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ur/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ur/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ur/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ur/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ur/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ur/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ur/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ur/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/ur/ActivityScheduler':function(){
define('Sage/UI/nls/ur/ActivityScheduler',{});
},
'Sage/MainView/nls/ur/SecurityManager':function(){
define('Sage/MainView/nls/ur/SecurityManager',{});
},
'Sage/TaskPane/nls/ur/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ur/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ur/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ur/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ur/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ur/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/ur/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ur/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/ur/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ur/UpdateOpportunities',{});
},
'Sage/UI/nls/ur/EditCalendarUsers':function(){
define('Sage/UI/nls/ur/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ur/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ur/HelpMenu':function(){
define('Sage/UI/Controls/nls/ur/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ur/UserTasklet':function(){
define('Sage/TaskPane/nls/ur/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/ur/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ur/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ur/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ur/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ur/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ur/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ur/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/ColumnDesigner',{});
},
'Sage/UI/nls/ur/SearchMenuItem':function(){
define('Sage/UI/nls/ur/SearchMenuItem',{});
},
'Sage/Library/nls/ur/DocumentProperties':function(){
define('Sage/Library/nls/ur/DocumentProperties',{});
},
'Sage/UI/nls/ur/NotesHistoryList':function(){
define('Sage/UI/nls/ur/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/ur/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ur/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ur/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ur/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ur/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/ur/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ur/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ur/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ur/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ur/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ur/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ur/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ur/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ur/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ur/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ur/HistoryEditor',{});
},
'Sage/Groups/nls/ur/GroupManager':function(){
define('Sage/Groups/nls/ur/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ur/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ur/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ur/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ur/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ur/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ur/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ur/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ur/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/ur/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ur/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ur/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ur/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ur/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ur/FolderHandler':function(){
define('Sage/Library/nls/ur/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ur/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ur/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ur/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ur/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ur/EditableGrid':function(){
define('Sage/UI/nls/ur/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ur/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ur/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ur/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ur/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ur/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ur/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ur/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ur/ReportManagerUtility',{});
},
'Sage/UI/nls/ur/SpeedSearch':function(){
define('Sage/UI/nls/ur/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ur/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ur/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ur/SLXPreviewGrid':function(){
define('Sage/UI/nls/ur/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ur/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ur/UnconfirmedPane',{});
},
'Sage/Utility/nls/ur/Utility':function(){
define('Sage/Utility/nls/ur/Utility',{});
},
'Sage/QuickForms/Design/nls/ur/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ur/Address':function(){
define('Sage/UI/Controls/nls/ur/Address',{});
},
'Sage/MainView/JobMgr/nls/ur/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ur/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ur/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ur/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ur/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ur/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ur/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ur/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ur/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ur/UserType':function(){
define('Sage/UI/nls/ur/UserType',{});
},
'Sage/QuickForms/Design/nls/ur/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ur/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ur/ActivityCalendar',{});
},
'Sage/Utility/nls/ur/Jobs':function(){
define('Sage/Utility/nls/ur/Jobs',{});
},
'Sage/UI/Controls/nls/ur/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ur/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ur/ActivityList':function(){
define('Sage/UI/nls/ur/ActivityList',{});
},
'Sage/UI/Alarms/nls/ur/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ur/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ur/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ur/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ur/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ur/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ur/CalendarUsersListPane':function(){
define('Sage/UI/nls/ur/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ur/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ur/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ur/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ur/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ur/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ur/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ur/Attachment':function(){
define('Sage/Utility/File/nls/ur/Attachment',{});
},
'Sage/QuickForms/Design/nls/ur/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ur/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ur/PropertyEditorContainer',{});
},
'Sage/Services/nls/ur/ReportingService':function(){
define('Sage/Services/nls/ur/ReportingService',{});
},
'Sage/MailMerge/nls/ur/Helper':function(){
define('Sage/MailMerge/nls/ur/Helper',{});
},
'Sage/UI/Dashboard/nls/ur/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ur/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ur/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ur/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ur/PickList':function(){
define('Sage/UI/Controls/nls/ur/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ur/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ur/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ur/Email':function(){
define('Sage/Utility/nls/ur/Email',{});
},
'Sage/TaskPane/nls/ur/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ur/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ur/TimeZoneItem':function(){
define('Sage/UI/nls/ur/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ur/SlxEdit':function(){
define('Sage/UI/Columns/nls/ur/SlxEdit',{});
},
'Sage/Reporting/nls/ur/Enumerations':function(){
define('Sage/Reporting/nls/ur/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ur/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ur/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ur/JobSchedulingWidget':function(){
define('Sage/UI/nls/ur/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ur/LogOffButton':function(){
define('Sage/UI/Controls/nls/ur/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ur/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ur/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ur/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ur/EditEventEditor',{});
},
'Sage/MailMerge/nls/ur/Loader':function(){
define('Sage/MailMerge/nls/ur/Loader',{});
},
'Sage/UI/Controls/nls/ur/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ur/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ur/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ur/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ur/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ur/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ur/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ur/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ur/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ur/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ur/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ur/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ur/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ur/Lookup':function(){
define('Sage/UI/Controls/nls/ur/Lookup',{});
},
'Sage/Utility/File/nls/ur/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ur/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ur/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ur/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ur/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ur/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ur/Dashboard':function(){
define('Sage/Utility/nls/ur/Dashboard',{});
}}});
define("Sage/nls/Sage_ur", [], 1);
