require({cache:{
'Sage/Utility/File/nls/ko/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ko/FallbackFilePicker',{});
},
'Sage/UI/nls/ko/Boolean':function(){
define('Sage/UI/nls/ko/Boolean',{});
},
'Sage/Services/nls/ko/ActivityService':function(){
define('Sage/Services/nls/ko/ActivityService',{});
},
'Sage/UI/Controls/nls/ko/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ko/CopyToClipboard',{});
},
'Sage/Utility/nls/ko/Activity':function(){
define('Sage/Utility/nls/ko/Activity',{});
},
'Sage/QuickForms/Design/nls/ko/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ko/DesignPanel',{});
},
'Sage/UI/nls/ko/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ko/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ko/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ko/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ko/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ko/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ko/ActivityManager':function(){
define('Sage/MainView/nls/ko/ActivityManager',{});
},
'Sage/Services/nls/ko/JobService':function(){
define('Sage/Services/nls/ko/JobService',{});
},
'Sage/QuickForms/Design/nls/ko/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/_PropertyEditor',{});
},
'Sage/Services/nls/ko/ActivityActionProcessor':function(){
define('Sage/Services/nls/ko/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ko/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ko/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ko/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ko/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ko/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ko/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ko/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ko/AlarmPane',{});
},
'Sage/TaskPane/nls/ko/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ko/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ko/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ko/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ko/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ko/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ko/FilterPanel':function(){
define('Sage/UI/Filters/nls/ko/FilterPanel',{});
},
'Sage/TaskPane/nls/ko/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ko/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ko/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ko/ReportManagerFormatter',{});
},
'Sage/UI/nls/ko/OwnerType':function(){
define('Sage/UI/nls/ko/OwnerType',{});
},
'Sage/TaskPane/nls/ko/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ko/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ko/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ko/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ko/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ko/InvoiceRTDV',{});
},
'Sage/UI/nls/ko/SDataLookup':function(){
define('Sage/UI/nls/ko/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ko/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/RowDesigner',{});
},
'Sage/TaskPane/nls/ko/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ko/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ko/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ko/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ko/LibraryDocument':function(){
define('Sage/Utility/File/nls/ko/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ko/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ko/SpeedSearchLookup',{});
},
'Sage/UI/nls/ko/ConditionManager':function(){
define('Sage/UI/nls/ko/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ko/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ko/WidgetDefinition',{});
},
'Sage/UI/nls/ko/SearchConditionWidget':function(){
define('Sage/UI/nls/ko/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ko/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ko/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ko/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ko/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ko/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ko/DataSourcePanel',{});
},
'Sage/Library/nls/ko/Manager':function(){
define('Sage/Library/nls/ko/Manager',{});
},
'Sage/UI/nls/ko/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ko/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ko/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ko/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ko/Name':function(){
define('Sage/UI/Controls/nls/ko/Name',{});
},
'Sage/MainView/JobMgr/nls/ko/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ko/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ko/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ko/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ko/UpdateLeads',{});
},
'Sage/Library/nls/ko/FileHandler':function(){
define('Sage/Library/nls/ko/FileHandler',{});
},
'Sage/UI/nls/ko/ListPanel':function(){
define('Sage/UI/nls/ko/ListPanel',{});
},
'Sage/Utility/nls/ko/Sql':function(){
define('Sage/Utility/nls/ko/Sql',{});
},
'Sage/UI/Filters/nls/ko/EditFilters':function(){
define('Sage/UI/Filters/nls/ko/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ko/DurationSelect':function(){
define('Sage/UI/Controls/nls/ko/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ko/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ko/AlarmCountDown',{});
},
'Sage/UI/nls/ko/AttachmentList':function(){
define('Sage/UI/nls/ko/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ko/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ko/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ko/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ko/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ko/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ko/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ko/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ko/Dialogs':function(){
define('Sage/UI/nls/ko/Dialogs',{});
},
'Sage/TaskPane/nls/ko/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ko/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ko/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ko/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ko/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ko/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ko/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/UserControlDesigner',{});
},
'Sage/Groups/nls/ko/GroupNavigator':function(){
define('Sage/Groups/nls/ko/GroupNavigator',{});
},
'Sage/Utility/File/nls/ko/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ko/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ko/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ko/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ko/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ko/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ko/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ko/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ko/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ko/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ko/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ko/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ko/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ko/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/ko/ActivityScheduler':function(){
define('Sage/UI/nls/ko/ActivityScheduler',{});
},
'Sage/MainView/nls/ko/SecurityManager':function(){
define('Sage/MainView/nls/ko/SecurityManager',{});
},
'Sage/TaskPane/nls/ko/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ko/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ko/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ko/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ko/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ko/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/ko/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ko/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/ko/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ko/UpdateOpportunities',{});
},
'Sage/UI/nls/ko/EditCalendarUsers':function(){
define('Sage/UI/nls/ko/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ko/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ko/HelpMenu':function(){
define('Sage/UI/Controls/nls/ko/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ko/UserTasklet':function(){
define('Sage/TaskPane/nls/ko/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/ko/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ko/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ko/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ko/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ko/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ko/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ko/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/ColumnDesigner',{});
},
'Sage/UI/nls/ko/SearchMenuItem':function(){
define('Sage/UI/nls/ko/SearchMenuItem',{});
},
'Sage/Library/nls/ko/DocumentProperties':function(){
define('Sage/Library/nls/ko/DocumentProperties',{});
},
'Sage/UI/nls/ko/NotesHistoryList':function(){
define('Sage/UI/nls/ko/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/ko/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ko/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ko/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ko/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ko/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/ko/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ko/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ko/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ko/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ko/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ko/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ko/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ko/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ko/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ko/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ko/HistoryEditor',{});
},
'Sage/Groups/nls/ko/GroupManager':function(){
define('Sage/Groups/nls/ko/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ko/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ko/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ko/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ko/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ko/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ko/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ko/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ko/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/ko/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ko/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ko/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ko/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ko/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ko/FolderHandler':function(){
define('Sage/Library/nls/ko/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ko/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ko/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ko/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ko/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ko/EditableGrid':function(){
define('Sage/UI/nls/ko/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ko/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ko/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ko/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ko/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ko/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ko/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ko/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ko/ReportManagerUtility',{});
},
'Sage/UI/nls/ko/SpeedSearch':function(){
define('Sage/UI/nls/ko/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ko/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ko/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ko/SLXPreviewGrid':function(){
define('Sage/UI/nls/ko/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ko/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ko/UnconfirmedPane',{});
},
'Sage/Utility/nls/ko/Utility':function(){
define('Sage/Utility/nls/ko/Utility',{});
},
'Sage/QuickForms/Design/nls/ko/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ko/Address':function(){
define('Sage/UI/Controls/nls/ko/Address',{});
},
'Sage/MainView/JobMgr/nls/ko/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ko/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ko/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ko/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ko/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ko/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ko/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ko/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ko/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ko/UserType':function(){
define('Sage/UI/nls/ko/UserType',{});
},
'Sage/QuickForms/Design/nls/ko/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ko/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ko/ActivityCalendar',{});
},
'Sage/Utility/nls/ko/Jobs':function(){
define('Sage/Utility/nls/ko/Jobs',{});
},
'Sage/UI/Controls/nls/ko/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ko/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ko/ActivityList':function(){
define('Sage/UI/nls/ko/ActivityList',{});
},
'Sage/UI/Alarms/nls/ko/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ko/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ko/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ko/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ko/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ko/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ko/CalendarUsersListPane':function(){
define('Sage/UI/nls/ko/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ko/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ko/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ko/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ko/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ko/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ko/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ko/Attachment':function(){
define('Sage/Utility/File/nls/ko/Attachment',{});
},
'Sage/QuickForms/Design/nls/ko/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ko/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ko/PropertyEditorContainer',{});
},
'Sage/Services/nls/ko/ReportingService':function(){
define('Sage/Services/nls/ko/ReportingService',{});
},
'Sage/MailMerge/nls/ko/Helper':function(){
define('Sage/MailMerge/nls/ko/Helper',{});
},
'Sage/UI/Dashboard/nls/ko/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ko/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ko/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ko/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ko/PickList':function(){
define('Sage/UI/Controls/nls/ko/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ko/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ko/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ko/Email':function(){
define('Sage/Utility/nls/ko/Email',{});
},
'Sage/TaskPane/nls/ko/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ko/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ko/TimeZoneItem':function(){
define('Sage/UI/nls/ko/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ko/SlxEdit':function(){
define('Sage/UI/Columns/nls/ko/SlxEdit',{});
},
'Sage/Reporting/nls/ko/Enumerations':function(){
define('Sage/Reporting/nls/ko/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ko/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ko/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ko/JobSchedulingWidget':function(){
define('Sage/UI/nls/ko/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ko/LogOffButton':function(){
define('Sage/UI/Controls/nls/ko/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ko/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ko/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ko/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ko/EditEventEditor',{});
},
'Sage/MailMerge/nls/ko/Loader':function(){
define('Sage/MailMerge/nls/ko/Loader',{});
},
'Sage/UI/Controls/nls/ko/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ko/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ko/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ko/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ko/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ko/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ko/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ko/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ko/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ko/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ko/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ko/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ko/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ko/Lookup':function(){
define('Sage/UI/Controls/nls/ko/Lookup',{});
},
'Sage/Utility/File/nls/ko/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ko/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ko/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ko/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ko/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ko/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ko/Dashboard':function(){
define('Sage/Utility/nls/ko/Dashboard',{});
}}});
define("Sage/nls/Sage_ko", [], 1);
