require({cache:{
'Sage/Utility/File/nls/az/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/az/FallbackFilePicker',{});
},
'Sage/UI/nls/az/Boolean':function(){
define('Sage/UI/nls/az/Boolean',{});
},
'Sage/Services/nls/az/ActivityService':function(){
define('Sage/Services/nls/az/ActivityService',{});
},
'Sage/UI/Controls/nls/az/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/az/CopyToClipboard',{});
},
'Sage/Utility/nls/az/Activity':function(){
define('Sage/Utility/nls/az/Activity',{});
},
'Sage/QuickForms/Design/nls/az/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/az/DesignPanel',{});
},
'Sage/UI/nls/az/TimelessActivitiesPane':function(){
define('Sage/UI/nls/az/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/az/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/az/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/az/ActivityManager':function(){
define('Sage/MainView/nls/az/ActivityManager',{});
},
'Sage/Services/nls/az/JobService':function(){
define('Sage/Services/nls/az/JobService',{});
},
'Sage/QuickForms/Design/nls/az/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/az/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/_PropertyEditor',{});
},
'Sage/Services/nls/az/ActivityActionProcessor':function(){
define('Sage/Services/nls/az/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/az/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/az/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/az/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/az/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/az/AlarmPane':function(){
define('Sage/UI/Alarms/nls/az/AlarmPane',{});
},
'Sage/TaskPane/nls/az/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/az/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/az/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/az/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/az/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/az/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/az/FilterPanel':function(){
define('Sage/UI/Filters/nls/az/FilterPanel',{});
},
'Sage/TaskPane/nls/az/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/az/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportManagerFormatter',{});
},
'Sage/UI/nls/az/OwnerType':function(){
define('Sage/UI/nls/az/OwnerType',{});
},
'Sage/TaskPane/nls/az/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/az/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/az/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/az/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/az/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/az/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az/InvoiceRTDV',{});
},
'Sage/UI/nls/az/SDataLookup':function(){
define('Sage/UI/nls/az/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/az/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/az/RowDesigner',{});
},
'Sage/TaskPane/nls/az/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/az/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/az/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/az/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/az/LibraryDocument':function(){
define('Sage/Utility/File/nls/az/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/SpeedSearchLookup',{});
},
'Sage/UI/nls/az/ConditionManager':function(){
define('Sage/UI/nls/az/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/az/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/az/WidgetDefinition',{});
},
'Sage/UI/nls/az/SearchConditionWidget':function(){
define('Sage/UI/nls/az/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/az/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/az/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/az/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/az/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/az/DataSourcePanel',{});
},
'Sage/Library/nls/az/Manager':function(){
define('Sage/Library/nls/az/Manager',{});
},
'Sage/UI/nls/az/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/az/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/az/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/az/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/az/Name':function(){
define('Sage/UI/Controls/nls/az/Name',{});
},
'Sage/MainView/JobMgr/nls/az/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/az/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/az/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/az/UpdateLeads',{});
},
'Sage/Library/nls/az/FileHandler':function(){
define('Sage/Library/nls/az/FileHandler',{});
},
'Sage/UI/nls/az/ListPanel':function(){
define('Sage/UI/nls/az/ListPanel',{});
},
'Sage/Utility/nls/az/Sql':function(){
define('Sage/Utility/nls/az/Sql',{});
},
'Sage/UI/Filters/nls/az/EditFilters':function(){
define('Sage/UI/Filters/nls/az/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/az/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/az/DurationSelect':function(){
define('Sage/UI/Controls/nls/az/DurationSelect',{});
},
'Sage/UI/Alarms/nls/az/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/az/AlarmCountDown',{});
},
'Sage/UI/nls/az/AttachmentList':function(){
define('Sage/UI/nls/az/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/az/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/az/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/az/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/az/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/az/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/az/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/az/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/az/Dialogs':function(){
define('Sage/UI/nls/az/Dialogs',{});
},
'Sage/TaskPane/nls/az/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/az/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/az/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/az/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/az/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/az/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/UserControlDesigner',{});
},
'Sage/Groups/nls/az/GroupNavigator':function(){
define('Sage/Groups/nls/az/GroupNavigator',{});
},
'Sage/Utility/File/nls/az/AddURLAttachment':function(){
define('Sage/Utility/File/nls/az/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/az/EditFilterItems':function(){
define('Sage/UI/Filters/nls/az/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/az/DragDropWatcher':function(){
define('Sage/Utility/File/nls/az/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/az/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/az/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/az/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/az/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/az/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/az/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/az/ActivityScheduler':function(){
define('Sage/UI/nls/az/ActivityScheduler',{});
},
'Sage/MainView/nls/az/SecurityManager':function(){
define('Sage/MainView/nls/az/SecurityManager',{});
},
'Sage/TaskPane/nls/az/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/az/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/az/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/az/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/az/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/az/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/az/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/az/UpdateOpportunities',{});
},
'Sage/UI/nls/az/EditCalendarUsers':function(){
define('Sage/UI/nls/az/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/az/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/az/HelpMenu':function(){
define('Sage/UI/Controls/nls/az/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/az/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/az/UserTasklet':function(){
define('Sage/TaskPane/nls/az/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/az/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/az/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/az/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/az/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/az/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/az/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/az/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/az/ColumnDesigner',{});
},
'Sage/UI/nls/az/SearchMenuItem':function(){
define('Sage/UI/nls/az/SearchMenuItem',{});
},
'Sage/Library/nls/az/DocumentProperties':function(){
define('Sage/Library/nls/az/DocumentProperties',{});
},
'Sage/UI/nls/az/NotesHistoryList':function(){
define('Sage/UI/nls/az/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/az/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/az/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/az/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/az/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/az/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/az/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/az/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/az/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/az/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/az/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/az/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/HistoryEditor',{});
},
'Sage/Groups/nls/az/GroupManager':function(){
define('Sage/Groups/nls/az/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/az/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/az/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/az/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/az/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/az/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/az/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/az/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/az/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/az/FolderHandler':function(){
define('Sage/Library/nls/az/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/az/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/az/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/az/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/az/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/az/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/az/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/az/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/az/EditableGrid':function(){
define('Sage/UI/nls/az/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/az/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/az/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/az/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/az/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/az/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportManagerUtility',{});
},
'Sage/UI/nls/az/SpeedSearch':function(){
define('Sage/UI/nls/az/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/az/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/az/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/az/SLXPreviewGrid':function(){
define('Sage/UI/nls/az/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/az/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/az/UnconfirmedPane',{});
},
'Sage/Utility/nls/az/Utility':function(){
define('Sage/Utility/nls/az/Utility',{});
},
'Sage/QuickForms/Design/nls/az/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/ControlDesigner',{});
},
'Sage/UI/Controls/nls/az/Address':function(){
define('Sage/UI/Controls/nls/az/Address',{});
},
'Sage/MainView/JobMgr/nls/az/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/az/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/az/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/az/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/az/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/az/UserType':function(){
define('Sage/UI/nls/az/UserType',{});
},
'Sage/QuickForms/Design/nls/az/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/az/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityCalendar',{});
},
'Sage/Utility/nls/az/Jobs':function(){
define('Sage/Utility/nls/az/Jobs',{});
},
'Sage/UI/Controls/nls/az/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/az/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/az/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/az/ActivityList':function(){
define('Sage/UI/nls/az/ActivityList',{});
},
'Sage/UI/Alarms/nls/az/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/az/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/az/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/az/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/az/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/az/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/az/CalendarUsersListPane':function(){
define('Sage/UI/nls/az/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/az/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/az/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/az/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/az/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/az/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/az/Attachment':function(){
define('Sage/Utility/File/nls/az/Attachment',{});
},
'Sage/QuickForms/Design/nls/az/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/az/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/az/PropertyEditorContainer',{});
},
'Sage/Services/nls/az/ReportingService':function(){
define('Sage/Services/nls/az/ReportingService',{});
},
'Sage/MailMerge/nls/az/Helper':function(){
define('Sage/MailMerge/nls/az/Helper',{});
},
'Sage/UI/Dashboard/nls/az/Dashboard':function(){
define('Sage/UI/Dashboard/nls/az/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/az/PickList':function(){
define('Sage/UI/Controls/nls/az/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/az/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/az/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/az/Email':function(){
define('Sage/Utility/nls/az/Email',{});
},
'Sage/TaskPane/nls/az/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/az/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/az/TimeZoneItem':function(){
define('Sage/UI/nls/az/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/az/SlxEdit':function(){
define('Sage/UI/Columns/nls/az/SlxEdit',{});
},
'Sage/Reporting/nls/az/Enumerations':function(){
define('Sage/Reporting/nls/az/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/az/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/az/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/az/ActivityListPanelConfig',{});
},
'Sage/UI/nls/az/JobSchedulingWidget':function(){
define('Sage/UI/nls/az/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/az/LogOffButton':function(){
define('Sage/UI/Controls/nls/az/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/az/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/az/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/az/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/EditEventEditor',{});
},
'Sage/MailMerge/nls/az/Loader':function(){
define('Sage/MailMerge/nls/az/Loader',{});
},
'Sage/UI/Controls/nls/az/DateTimePicker':function(){
define('Sage/UI/Controls/nls/az/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/az/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/az/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/az/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/az/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/az/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/az/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/az/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/az/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/az/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/az/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/az/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/az/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/az/Lookup':function(){
define('Sage/UI/Controls/nls/az/Lookup',{});
},
'Sage/Utility/File/nls/az/DescriptionsForm':function(){
define('Sage/Utility/File/nls/az/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/az/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/az/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/az/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/az/CommonTasksTasklet',{});
},
'Sage/Utility/nls/az/Dashboard':function(){
define('Sage/Utility/nls/az/Dashboard',{});
}}});
define("Sage/nls/Sage_az", [], 1);
