require({cache:{
'Sage/Utility/File/nls/is/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/is/FallbackFilePicker',{});
},
'Sage/UI/nls/is/Boolean':function(){
define('Sage/UI/nls/is/Boolean',{});
},
'Sage/Services/nls/is/ActivityService':function(){
define('Sage/Services/nls/is/ActivityService',{});
},
'Sage/UI/Controls/nls/is/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/is/CopyToClipboard',{});
},
'Sage/Utility/nls/is/Activity':function(){
define('Sage/Utility/nls/is/Activity',{});
},
'Sage/QuickForms/Design/nls/is/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/is/DesignPanel',{});
},
'Sage/UI/nls/is/TimelessActivitiesPane':function(){
define('Sage/UI/nls/is/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/is/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/is/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/is/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/is/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/is/ActivityManager':function(){
define('Sage/MainView/nls/is/ActivityManager',{});
},
'Sage/Services/nls/is/JobService':function(){
define('Sage/Services/nls/is/JobService',{});
},
'Sage/QuickForms/Design/nls/is/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/is/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/_PropertyEditor',{});
},
'Sage/Services/nls/is/ActivityActionProcessor':function(){
define('Sage/Services/nls/is/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/is/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/is/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/is/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/is/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/is/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/is/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/is/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/is/AlarmPane':function(){
define('Sage/UI/Alarms/nls/is/AlarmPane',{});
},
'Sage/TaskPane/nls/is/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/is/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/is/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/is/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/is/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/is/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/is/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/is/FilterPanel':function(){
define('Sage/UI/Filters/nls/is/FilterPanel',{});
},
'Sage/TaskPane/nls/is/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/is/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/is/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/is/ReportManagerFormatter',{});
},
'Sage/UI/nls/is/OwnerType':function(){
define('Sage/UI/nls/is/OwnerType',{});
},
'Sage/TaskPane/nls/is/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/is/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/is/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/is/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/is/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/is/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/is/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/is/InvoiceRTDV',{});
},
'Sage/UI/nls/is/SDataLookup':function(){
define('Sage/UI/nls/is/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/is/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/is/RowDesigner',{});
},
'Sage/TaskPane/nls/is/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/is/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/is/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/is/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/is/LibraryDocument':function(){
define('Sage/Utility/File/nls/is/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/is/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/is/SpeedSearchLookup',{});
},
'Sage/UI/nls/is/ConditionManager':function(){
define('Sage/UI/nls/is/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/is/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/is/WidgetDefinition',{});
},
'Sage/UI/nls/is/SearchConditionWidget':function(){
define('Sage/UI/nls/is/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/is/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/is/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/is/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/is/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/is/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/is/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/is/DataSourcePanel',{});
},
'Sage/Library/nls/is/Manager':function(){
define('Sage/Library/nls/is/Manager',{});
},
'Sage/UI/nls/is/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/is/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/is/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/is/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/is/Name':function(){
define('Sage/UI/Controls/nls/is/Name',{});
},
'Sage/MainView/JobMgr/nls/is/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/is/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/is/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/is/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/is/UpdateLeads',{});
},
'Sage/Library/nls/is/FileHandler':function(){
define('Sage/Library/nls/is/FileHandler',{});
},
'Sage/UI/nls/is/ListPanel':function(){
define('Sage/UI/nls/is/ListPanel',{});
},
'Sage/Utility/nls/is/Sql':function(){
define('Sage/Utility/nls/is/Sql',{});
},
'Sage/UI/Filters/nls/is/EditFilters':function(){
define('Sage/UI/Filters/nls/is/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/is/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/is/DurationSelect':function(){
define('Sage/UI/Controls/nls/is/DurationSelect',{});
},
'Sage/UI/Alarms/nls/is/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/is/AlarmCountDown',{});
},
'Sage/UI/nls/is/AttachmentList':function(){
define('Sage/UI/nls/is/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/is/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/is/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/is/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/is/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/is/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/is/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/is/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/is/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/is/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/is/Dialogs':function(){
define('Sage/UI/nls/is/Dialogs',{});
},
'Sage/TaskPane/nls/is/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/is/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/is/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/is/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/is/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/is/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/is/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/UserControlDesigner',{});
},
'Sage/Groups/nls/is/GroupNavigator':function(){
define('Sage/Groups/nls/is/GroupNavigator',{});
},
'Sage/Utility/File/nls/is/AddURLAttachment':function(){
define('Sage/Utility/File/nls/is/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/is/EditFilterItems':function(){
define('Sage/UI/Filters/nls/is/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/is/DragDropWatcher':function(){
define('Sage/Utility/File/nls/is/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/is/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/is/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/is/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/is/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/is/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/is/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/is/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/is/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/is/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/is/ActivityScheduler':function(){
define('Sage/UI/nls/is/ActivityScheduler',{});
},
'Sage/MainView/nls/is/SecurityManager':function(){
define('Sage/MainView/nls/is/SecurityManager',{});
},
'Sage/TaskPane/nls/is/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/is/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/is/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/is/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/is/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/is/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/is/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/is/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/is/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/is/UpdateOpportunities',{});
},
'Sage/UI/nls/is/EditCalendarUsers':function(){
define('Sage/UI/nls/is/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/is/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/is/HelpMenu':function(){
define('Sage/UI/Controls/nls/is/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/is/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/is/UserTasklet':function(){
define('Sage/TaskPane/nls/is/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/is/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/is/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/is/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/is/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/is/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/is/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/is/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/is/ColumnDesigner',{});
},
'Sage/UI/nls/is/SearchMenuItem':function(){
define('Sage/UI/nls/is/SearchMenuItem',{});
},
'Sage/Library/nls/is/DocumentProperties':function(){
define('Sage/Library/nls/is/DocumentProperties',{});
},
'Sage/UI/nls/is/NotesHistoryList':function(){
define('Sage/UI/nls/is/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/is/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/is/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/is/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/is/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/is/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/is/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/is/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/is/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/is/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/is/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/is/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/is/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/is/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/is/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/is/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/is/HistoryEditor',{});
},
'Sage/Groups/nls/is/GroupManager':function(){
define('Sage/Groups/nls/is/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/is/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/is/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/is/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/is/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/is/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/is/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/is/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/is/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/is/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/is/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/is/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/is/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/is/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/is/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/is/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/is/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/is/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/is/FolderHandler':function(){
define('Sage/Library/nls/is/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/is/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/is/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/is/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/is/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/is/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/is/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/is/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/is/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/is/EditableGrid':function(){
define('Sage/UI/nls/is/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/is/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/is/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/is/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/is/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/is/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/is/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/is/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/is/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/is/ReportManagerUtility',{});
},
'Sage/UI/nls/is/SpeedSearch':function(){
define('Sage/UI/nls/is/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/is/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/is/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/is/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/is/SLXPreviewGrid':function(){
define('Sage/UI/nls/is/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/is/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/is/UnconfirmedPane',{});
},
'Sage/Utility/nls/is/Utility':function(){
define('Sage/Utility/nls/is/Utility',{});
},
'Sage/QuickForms/Design/nls/is/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/ControlDesigner',{});
},
'Sage/UI/Controls/nls/is/Address':function(){
define('Sage/UI/Controls/nls/is/Address',{});
},
'Sage/MainView/JobMgr/nls/is/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/is/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/is/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/is/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/is/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/is/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/is/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/is/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/is/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/is/UserType':function(){
define('Sage/UI/nls/is/UserType',{});
},
'Sage/QuickForms/Design/nls/is/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/is/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/is/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/is/ActivityCalendar',{});
},
'Sage/Utility/nls/is/Jobs':function(){
define('Sage/Utility/nls/is/Jobs',{});
},
'Sage/UI/Controls/nls/is/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/is/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/is/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/is/ActivityList':function(){
define('Sage/UI/nls/is/ActivityList',{});
},
'Sage/UI/Alarms/nls/is/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/is/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/is/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/is/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/is/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/is/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/is/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/is/CalendarUsersListPane':function(){
define('Sage/UI/nls/is/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/is/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/is/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/is/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/is/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/is/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/is/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/is/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/is/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/is/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/is/Attachment':function(){
define('Sage/Utility/File/nls/is/Attachment',{});
},
'Sage/QuickForms/Design/nls/is/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/is/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/is/PropertyEditorContainer',{});
},
'Sage/Services/nls/is/ReportingService':function(){
define('Sage/Services/nls/is/ReportingService',{});
},
'Sage/MailMerge/nls/is/Helper':function(){
define('Sage/MailMerge/nls/is/Helper',{});
},
'Sage/UI/Dashboard/nls/is/Dashboard':function(){
define('Sage/UI/Dashboard/nls/is/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/is/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/is/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/is/PickList':function(){
define('Sage/UI/Controls/nls/is/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/is/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/is/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/is/Email':function(){
define('Sage/Utility/nls/is/Email',{});
},
'Sage/TaskPane/nls/is/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/is/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/is/TimeZoneItem':function(){
define('Sage/UI/nls/is/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/is/SlxEdit':function(){
define('Sage/UI/Columns/nls/is/SlxEdit',{});
},
'Sage/Reporting/nls/is/Enumerations':function(){
define('Sage/Reporting/nls/is/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/is/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/is/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/is/ActivityListPanelConfig',{});
},
'Sage/UI/nls/is/JobSchedulingWidget':function(){
define('Sage/UI/nls/is/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/is/LogOffButton':function(){
define('Sage/UI/Controls/nls/is/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/is/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/is/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/is/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/is/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/is/EditEventEditor',{});
},
'Sage/MailMerge/nls/is/Loader':function(){
define('Sage/MailMerge/nls/is/Loader',{});
},
'Sage/UI/Controls/nls/is/DateTimePicker':function(){
define('Sage/UI/Controls/nls/is/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/is/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/is/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/is/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/is/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/is/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/is/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/is/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/is/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/is/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/is/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/is/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/is/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/is/Lookup':function(){
define('Sage/UI/Controls/nls/is/Lookup',{});
},
'Sage/Utility/File/nls/is/DescriptionsForm':function(){
define('Sage/Utility/File/nls/is/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/is/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/is/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/is/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/is/CommonTasksTasklet',{});
},
'Sage/Utility/nls/is/Dashboard':function(){
define('Sage/Utility/nls/is/Dashboard',{});
}}});
define("Sage/nls/Sage_is", [], 1);
