require({cache:{
'Sage/Utility/File/nls/sv/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sv/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/sv-fi/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sv-fi/FallbackFilePicker',{});
},
'Sage/UI/nls/sv/Boolean':function(){
define('Sage/UI/nls/sv/Boolean',{});
},
'Sage/UI/nls/sv-fi/Boolean':function(){
define('Sage/UI/nls/sv-fi/Boolean',{});
},
'Sage/Services/nls/sv/ActivityService':function(){
define('Sage/Services/nls/sv/ActivityService',{});
},
'Sage/Services/nls/sv-fi/ActivityService':function(){
define('Sage/Services/nls/sv-fi/ActivityService',{});
},
'Sage/UI/Controls/nls/sv/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sv/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/sv-fi/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sv-fi/CopyToClipboard',{});
},
'Sage/Utility/nls/sv/Activity':function(){
define('Sage/Utility/nls/sv/Activity',{});
},
'Sage/Utility/nls/sv-fi/Activity':function(){
define('Sage/Utility/nls/sv-fi/Activity',{});
},
'Sage/QuickForms/Design/nls/sv/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sv/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/sv-fi/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sv-fi/DesignPanel',{});
},
'Sage/UI/nls/sv/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sv/TimelessActivitiesPane',{});
},
'Sage/UI/nls/sv-fi/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sv-fi/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/sv/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/sv/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/sv-fi/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/sv-fi/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/sv/ActivityManager':function(){
define('Sage/MainView/nls/sv/ActivityManager',{});
},
'Sage/MainView/nls/sv-fi/ActivityManager':function(){
define('Sage/MainView/nls/sv-fi/ActivityManager',{});
},
'Sage/Services/nls/sv/JobService':function(){
define('Sage/Services/nls/sv/JobService',{});
},
'Sage/Services/nls/sv-fi/JobService':function(){
define('Sage/Services/nls/sv-fi/JobService',{});
},
'Sage/QuickForms/Design/nls/sv/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/_PropertyEditor',{});
},
'Sage/Services/nls/sv/ActivityActionProcessor':function(){
define('Sage/Services/nls/sv/ActivityActionProcessor',{});
},
'Sage/Services/nls/sv-fi/ActivityActionProcessor':function(){
define('Sage/Services/nls/sv-fi/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/sv/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sv/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sv-fi/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sv-fi/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sv/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sv/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/sv-fi/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sv-fi/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sv/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sv/AlarmPane',{});
},
'Sage/UI/Alarms/nls/sv-fi/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sv-fi/AlarmPane',{});
},
'Sage/TaskPane/nls/sv/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sv/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/sv-fi/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sv-fi/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sv/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sv/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/sv-fi/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sv-fi/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sv/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/sv-fi/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv-fi/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sv/FilterPanel':function(){
define('Sage/UI/Filters/nls/sv/FilterPanel',{});
},
'Sage/UI/Filters/nls/sv-fi/FilterPanel':function(){
define('Sage/UI/Filters/nls/sv-fi/FilterPanel',{});
},
'Sage/TaskPane/nls/sv/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sv/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/ReportManagerFormatter',{});
},
'Sage/UI/nls/sv/OwnerType':function(){
define('Sage/UI/nls/sv/OwnerType',{});
},
'Sage/UI/nls/sv-fi/OwnerType':function(){
define('Sage/UI/nls/sv-fi/OwnerType',{});
},
'Sage/TaskPane/nls/sv/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sv/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sv/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sv/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/sv-fi/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv-fi/InvoiceRTDV',{});
},
'Sage/UI/nls/sv/SDataLookup':function(){
define('Sage/UI/nls/sv/SDataLookup',{});
},
'Sage/UI/nls/sv-fi/SDataLookup':function(){
define('Sage/UI/nls/sv-fi/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sv/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/RowDesigner',{});
},
'Sage/TaskPane/nls/sv/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sv/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sv/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/sv-fi/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sv-fi/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sv/LibraryDocument':function(){
define('Sage/Utility/File/nls/sv/LibraryDocument',{});
},
'Sage/Utility/File/nls/sv-fi/LibraryDocument':function(){
define('Sage/Utility/File/nls/sv-fi/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv-fi/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv-fi/SpeedSearchLookup',{});
},
'Sage/UI/nls/sv/ConditionManager':function(){
define('Sage/UI/nls/sv/ConditionManager',{});
},
'Sage/UI/nls/sv-fi/ConditionManager':function(){
define('Sage/UI/nls/sv-fi/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sv/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sv/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/sv-fi/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sv-fi/WidgetDefinition',{});
},
'Sage/UI/nls/sv/SearchConditionWidget':function(){
define('Sage/UI/nls/sv/SearchConditionWidget',{});
},
'Sage/UI/nls/sv-fi/SearchConditionWidget':function(){
define('Sage/UI/nls/sv-fi/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sv/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/sv/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/sv-fi/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/sv-fi/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv-fi/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv-fi/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/sv/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sv/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/sv-fi/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sv-fi/DataSourcePanel',{});
},
'Sage/Library/nls/sv/Manager':function(){
define('Sage/Library/nls/sv/Manager',{});
},
'Sage/Library/nls/sv-fi/Manager':function(){
define('Sage/Library/nls/sv-fi/Manager',{});
},
'Sage/UI/nls/sv/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sv/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/sv-fi/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sv-fi/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sv/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sv/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/sv-fi/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sv-fi/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sv/Name':function(){
define('Sage/UI/Controls/nls/sv/Name',{});
},
'Sage/UI/Controls/nls/sv-fi/Name':function(){
define('Sage/UI/Controls/nls/sv-fi/Name',{});
},
'Sage/MainView/JobMgr/nls/sv/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/sv-fi/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv-fi/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sv/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sv/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sv/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/sv-fi/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sv-fi/UpdateLeads',{});
},
'Sage/Library/nls/sv/FileHandler':function(){
define('Sage/Library/nls/sv/FileHandler',{});
},
'Sage/Library/nls/sv-fi/FileHandler':function(){
define('Sage/Library/nls/sv-fi/FileHandler',{});
},
'Sage/UI/nls/sv/ListPanel':function(){
define('Sage/UI/nls/sv/ListPanel',{});
},
'Sage/UI/nls/sv-fi/ListPanel':function(){
define('Sage/UI/nls/sv-fi/ListPanel',{});
},
'Sage/Utility/nls/sv/Sql':function(){
define('Sage/Utility/nls/sv/Sql',{});
},
'Sage/Utility/nls/sv-fi/Sql':function(){
define('Sage/Utility/nls/sv-fi/Sql',{});
},
'Sage/UI/Filters/nls/sv/EditFilters':function(){
define('Sage/UI/Filters/nls/sv/EditFilters',{});
},
'Sage/UI/Filters/nls/sv-fi/EditFilters':function(){
define('Sage/UI/Filters/nls/sv-fi/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sv/DurationSelect':function(){
define('Sage/UI/Controls/nls/sv/DurationSelect',{});
},
'Sage/UI/Controls/nls/sv-fi/DurationSelect':function(){
define('Sage/UI/Controls/nls/sv-fi/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sv/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sv/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/sv-fi/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sv-fi/AlarmCountDown',{});
},
'Sage/UI/nls/sv/AttachmentList':function(){
define('Sage/UI/nls/sv/AttachmentList',{});
},
'Sage/UI/nls/sv-fi/AttachmentList':function(){
define('Sage/UI/nls/sv-fi/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sv/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/sv/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/sv-fi/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/sv-fi/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/sv/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sv/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sv/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/sv-fi/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sv-fi/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sv/Dialogs':function(){
define('Sage/UI/nls/sv/Dialogs',{});
},
'Sage/UI/nls/sv-fi/Dialogs':function(){
define('Sage/UI/nls/sv-fi/Dialogs',{});
},
'Sage/TaskPane/nls/sv/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sv/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sv/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sv/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/sv-fi/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sv-fi/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sv/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/sv-fi/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv-fi/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sv/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/UserControlDesigner',{});
},
'Sage/Groups/nls/sv/GroupNavigator':function(){
define('Sage/Groups/nls/sv/GroupNavigator',{});
},
'Sage/Groups/nls/sv-fi/GroupNavigator':function(){
define('Sage/Groups/nls/sv-fi/GroupNavigator',{});
},
'Sage/Utility/File/nls/sv/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sv/AddURLAttachment',{});
},
'Sage/Utility/File/nls/sv-fi/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sv-fi/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sv/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sv/EditFilterItems',{});
},
'Sage/UI/Filters/nls/sv-fi/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sv-fi/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/sv/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sv/DragDropWatcher',{});
},
'Sage/Utility/File/nls/sv-fi/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sv-fi/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/sv/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sv/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/sv-fi/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sv-fi/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sv/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sv/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sv-fi/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sv-fi/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/sv/ActivityScheduler':function(){
define('Sage/UI/nls/sv/ActivityScheduler',{});
},
'Sage/UI/nls/sv-fi/ActivityScheduler':function(){
define('Sage/UI/nls/sv-fi/ActivityScheduler',{});
},
'Sage/MainView/nls/sv/SecurityManager':function(){
define('Sage/MainView/nls/sv/SecurityManager',{});
},
'Sage/MainView/nls/sv-fi/SecurityManager':function(){
define('Sage/MainView/nls/sv-fi/SecurityManager',{});
},
'Sage/TaskPane/nls/sv/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sv/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/sv-fi/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sv-fi/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sv/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sv/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/sv-fi/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sv-fi/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/sv/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/sv/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/sv-fi/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/sv-fi/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/sv/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sv/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/sv-fi/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sv-fi/UpdateOpportunities',{});
},
'Sage/UI/nls/sv/EditCalendarUsers':function(){
define('Sage/UI/nls/sv/EditCalendarUsers',{});
},
'Sage/UI/nls/sv-fi/EditCalendarUsers':function(){
define('Sage/UI/nls/sv-fi/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/sv/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sv/HelpMenu':function(){
define('Sage/UI/Controls/nls/sv/HelpMenu',{});
},
'Sage/UI/Controls/nls/sv-fi/HelpMenu':function(){
define('Sage/UI/Controls/nls/sv-fi/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sv/UserTasklet':function(){
define('Sage/TaskPane/nls/sv/UserTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/UserTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/sv/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sv/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/sv-fi/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sv-fi/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sv/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sv/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/sv-fi/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sv-fi/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sv/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sv/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/sv-fi/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sv-fi/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sv/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/ColumnDesigner',{});
},
'Sage/UI/nls/sv/SearchMenuItem':function(){
define('Sage/UI/nls/sv/SearchMenuItem',{});
},
'Sage/UI/nls/sv-fi/SearchMenuItem':function(){
define('Sage/UI/nls/sv-fi/SearchMenuItem',{});
},
'Sage/Library/nls/sv/DocumentProperties':function(){
define('Sage/Library/nls/sv/DocumentProperties',{});
},
'Sage/Library/nls/sv-fi/DocumentProperties':function(){
define('Sage/Library/nls/sv-fi/DocumentProperties',{});
},
'Sage/UI/nls/sv/NotesHistoryList':function(){
define('Sage/UI/nls/sv/NotesHistoryList',{});
},
'Sage/UI/nls/sv-fi/NotesHistoryList':function(){
define('Sage/UI/nls/sv-fi/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/sv/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sv/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/sv/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/sv/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/sv/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/sv-fi/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/sv-fi/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/sv/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/sv-fi/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv-fi/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/sv/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sv/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/sv-fi/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sv-fi/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sv/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sv/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/HistoryEditor',{});
},
'Sage/Groups/nls/sv/GroupManager':function(){
define('Sage/Groups/nls/sv/GroupManager',{});
},
'Sage/Groups/nls/sv-fi/GroupManager':function(){
define('Sage/Groups/nls/sv-fi/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/sv/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/sv/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/sv-fi/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/sv-fi/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/sv/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/sv-fi/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv-fi/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/sv/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sv/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/sv/FolderHandler':function(){
define('Sage/Library/nls/sv/FolderHandler',{});
},
'Sage/Library/nls/sv-fi/FolderHandler':function(){
define('Sage/Library/nls/sv-fi/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sv/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sv/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/sv-fi/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sv-fi/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sv/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sv/EditableGrid':function(){
define('Sage/UI/nls/sv/EditableGrid',{});
},
'Sage/UI/nls/sv-fi/EditableGrid':function(){
define('Sage/UI/nls/sv-fi/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/sv/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/sv-fi/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv-fi/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/sv/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sv/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/sv-fi/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sv-fi/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/ReportManagerUtility',{});
},
'Sage/UI/nls/sv/SpeedSearch':function(){
define('Sage/UI/nls/sv/SpeedSearch',{});
},
'Sage/UI/nls/sv-fi/SpeedSearch':function(){
define('Sage/UI/nls/sv-fi/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/sv/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/sv/SLXPreviewGrid':function(){
define('Sage/UI/nls/sv/SLXPreviewGrid',{});
},
'Sage/UI/nls/sv-fi/SLXPreviewGrid':function(){
define('Sage/UI/nls/sv-fi/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sv/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sv/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/sv-fi/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sv-fi/UnconfirmedPane',{});
},
'Sage/Utility/nls/sv/Utility':function(){
define('Sage/Utility/nls/sv/Utility',{});
},
'Sage/Utility/nls/sv-fi/Utility':function(){
define('Sage/Utility/nls/sv-fi/Utility',{});
},
'Sage/QuickForms/Design/nls/sv/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sv/Address':function(){
define('Sage/UI/Controls/nls/sv/Address',{});
},
'Sage/UI/Controls/nls/sv-fi/Address':function(){
define('Sage/UI/Controls/nls/sv-fi/Address',{});
},
'Sage/MainView/JobMgr/nls/sv/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/sv/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/sv-fi/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/sv-fi/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/sv/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sv/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/sv/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/sv/UserType':function(){
define('Sage/UI/nls/sv/UserType',{});
},
'Sage/UI/nls/sv-fi/UserType':function(){
define('Sage/UI/nls/sv-fi/UserType',{});
},
'Sage/QuickForms/Design/nls/sv/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/ActivityCalendar',{});
},
'Sage/Utility/nls/sv/Jobs':function(){
define('Sage/Utility/nls/sv/Jobs',{});
},
'Sage/Utility/nls/sv-fi/Jobs':function(){
define('Sage/Utility/nls/sv-fi/Jobs',{});
},
'Sage/UI/Controls/nls/sv/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sv/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/sv-fi/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sv-fi/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sv/ActivityList':function(){
define('Sage/UI/nls/sv/ActivityList',{});
},
'Sage/UI/nls/sv-fi/ActivityList':function(){
define('Sage/UI/nls/sv-fi/ActivityList',{});
},
'Sage/UI/Alarms/nls/sv/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/sv/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/sv-fi/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/sv-fi/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv-fi/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv-fi/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/sv/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sv/CalendarUsersListPane':function(){
define('Sage/UI/nls/sv/CalendarUsersListPane',{});
},
'Sage/UI/nls/sv-fi/CalendarUsersListPane':function(){
define('Sage/UI/nls/sv-fi/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/sv/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sv/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/sv-fi/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sv-fi/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sv/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sv/Attachment':function(){
define('Sage/Utility/File/nls/sv/Attachment',{});
},
'Sage/Utility/File/nls/sv-fi/Attachment':function(){
define('Sage/Utility/File/nls/sv-fi/Attachment',{});
},
'Sage/QuickForms/Design/nls/sv/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sv/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sv/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/sv-fi/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sv-fi/PropertyEditorContainer',{});
},
'Sage/Services/nls/sv/ReportingService':function(){
define('Sage/Services/nls/sv/ReportingService',{});
},
'Sage/Services/nls/sv-fi/ReportingService':function(){
define('Sage/Services/nls/sv-fi/ReportingService',{});
},
'Sage/MailMerge/nls/sv/Helper':function(){
define('Sage/MailMerge/nls/sv/Helper',{});
},
'Sage/MailMerge/nls/sv-fi/Helper':function(){
define('Sage/MailMerge/nls/sv-fi/Helper',{});
},
'Sage/UI/Dashboard/nls/sv/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sv/Dashboard',{});
},
'Sage/UI/Dashboard/nls/sv-fi/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sv-fi/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sv/PickList':function(){
define('Sage/UI/Controls/nls/sv/PickList',{});
},
'Sage/UI/Controls/nls/sv-fi/PickList':function(){
define('Sage/UI/Controls/nls/sv-fi/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/sv/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sv/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/sv/Email':function(){
define('Sage/Utility/nls/sv/Email',{});
},
'Sage/Utility/nls/sv-fi/Email':function(){
define('Sage/Utility/nls/sv-fi/Email',{});
},
'Sage/TaskPane/nls/sv/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sv/TimeZoneItem':function(){
define('Sage/UI/nls/sv/TimeZoneItem',{});
},
'Sage/UI/nls/sv-fi/TimeZoneItem':function(){
define('Sage/UI/nls/sv-fi/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sv/SlxEdit':function(){
define('Sage/UI/Columns/nls/sv/SlxEdit',{});
},
'Sage/UI/Columns/nls/sv-fi/SlxEdit':function(){
define('Sage/UI/Columns/nls/sv-fi/SlxEdit',{});
},
'Sage/Reporting/nls/sv/Enumerations':function(){
define('Sage/Reporting/nls/sv/Enumerations',{});
},
'Sage/Reporting/nls/sv-fi/Enumerations':function(){
define('Sage/Reporting/nls/sv-fi/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sv/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sv/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sv-fi/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sv-fi/ActivityListPanelConfig',{});
},
'Sage/UI/nls/sv/JobSchedulingWidget':function(){
define('Sage/UI/nls/sv/JobSchedulingWidget',{});
},
'Sage/UI/nls/sv-fi/JobSchedulingWidget':function(){
define('Sage/UI/nls/sv-fi/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/sv/LogOffButton':function(){
define('Sage/UI/Controls/nls/sv/LogOffButton',{});
},
'Sage/UI/Controls/nls/sv-fi/LogOffButton':function(){
define('Sage/UI/Controls/nls/sv-fi/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv-fi/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv-fi/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv-fi/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv-fi/EditEventEditor',{});
},
'Sage/MailMerge/nls/sv/Loader':function(){
define('Sage/MailMerge/nls/sv/Loader',{});
},
'Sage/MailMerge/nls/sv-fi/Loader':function(){
define('Sage/MailMerge/nls/sv-fi/Loader',{});
},
'Sage/UI/Controls/nls/sv/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sv/DateTimePicker',{});
},
'Sage/UI/Controls/nls/sv-fi/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sv-fi/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/sv-fi/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/sv-fi/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/sv/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sv/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/sv-fi/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sv-fi/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/sv/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/sv/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/sv-fi/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/sv-fi/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sv/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/sv-fi/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv-fi/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sv/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv-fi/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv-fi/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sv/Lookup':function(){
define('Sage/UI/Controls/nls/sv/Lookup',{});
},
'Sage/UI/Controls/nls/sv-fi/Lookup':function(){
define('Sage/UI/Controls/nls/sv-fi/Lookup',{});
},
'Sage/Utility/File/nls/sv/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sv/DescriptionsForm',{});
},
'Sage/Utility/File/nls/sv-fi/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sv-fi/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv-fi/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv-fi/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sv/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/sv-fi/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sv-fi/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sv/Dashboard':function(){
define('Sage/Utility/nls/sv/Dashboard',{});
},
'Sage/Utility/nls/sv-fi/Dashboard':function(){
define('Sage/Utility/nls/sv-fi/Dashboard',{});
}}});
define("Sage/nls/Sage_sv-fi", [], 1);
