require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-ec/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-ec/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-ec/Boolean':function(){
define('Sage/UI/nls/es-ec/Boolean',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-ec/ActivityService':function(){
define('Sage/Services/nls/es-ec/ActivityService',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-ec/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-ec/CopyToClipboard',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-ec/Activity':function(){
define('Sage/Utility/nls/es-ec/Activity',{});
},
'Sage/QuickForms/Design/nls/es/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/es-ec/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es-ec/DesignPanel',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-ec/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-ec/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/es/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/es-ec/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es-ec/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-ec/ActivityManager':function(){
define('Sage/MainView/nls/es-ec/ActivityManager',{});
},
'Sage/Services/nls/es/JobService':function(){
define('Sage/Services/nls/es/JobService',{});
},
'Sage/Services/nls/es-ec/JobService':function(){
define('Sage/Services/nls/es-ec/JobService',{});
},
'Sage/QuickForms/Design/nls/es/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/_PropertyEditor',{});
},
'Sage/Services/nls/es/ActivityActionProcessor':function(){
define('Sage/Services/nls/es/ActivityActionProcessor',{});
},
'Sage/Services/nls/es-ec/ActivityActionProcessor':function(){
define('Sage/Services/nls/es-ec/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-ec/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-ec/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-ec/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-ec/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-ec/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-ec/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-ec/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-ec/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-ec/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-ec/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ec/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ec/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-ec/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-ec/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-ec/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-ec/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/ReportManagerFormatter',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-ec/OwnerType':function(){
define('Sage/UI/nls/es-ec/OwnerType',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ec/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ec/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ec/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ec/InvoiceRTDV',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-ec/SDataLookup':function(){
define('Sage/UI/nls/es-ec/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/es/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/RowDesigner',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ec/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ec/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-ec/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-ec/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-ec/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-ec/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ec/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ec/SpeedSearchLookup',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-ec/ConditionManager':function(){
define('Sage/UI/nls/es-ec/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-ec/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-ec/WidgetDefinition',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-ec/SearchConditionWidget':function(){
define('Sage/UI/nls/es-ec/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/es-ec/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es-ec/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ec/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ec/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/es/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/es-ec/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es-ec/DataSourcePanel',{});
},
'Sage/Library/nls/es/Manager':function(){
define('Sage/Library/nls/es/Manager',{});
},
'Sage/Library/nls/es-ec/Manager':function(){
define('Sage/Library/nls/es-ec/Manager',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-ec/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-ec/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/es/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/es-ec/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es-ec/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-ec/Name':function(){
define('Sage/UI/Controls/nls/es-ec/Name',{});
},
'Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ec/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ec/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-ec/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-ec/UpdateLeads',{});
},
'Sage/Library/nls/es/FileHandler':function(){
define('Sage/Library/nls/es/FileHandler',{});
},
'Sage/Library/nls/es-ec/FileHandler':function(){
define('Sage/Library/nls/es-ec/FileHandler',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-ec/ListPanel':function(){
define('Sage/UI/nls/es-ec/ListPanel',{});
},
'Sage/Utility/nls/es/Sql':function(){
define('Sage/Utility/nls/es/Sql',{});
},
'Sage/Utility/nls/es-ec/Sql':function(){
define('Sage/Utility/nls/es-ec/Sql',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-ec/EditFilters':function(){
define('Sage/UI/Filters/nls/es-ec/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-ec/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-ec/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-ec/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-ec/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-ec/AttachmentList':function(){
define('Sage/UI/nls/es-ec/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/es-ec/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es-ec/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-ec/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-ec/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/es/Dialogs':function(){
define('Sage/UI/nls/es/Dialogs',{});
},
'Sage/UI/nls/es-ec/Dialogs':function(){
define('Sage/UI/nls/es-ec/Dialogs',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-ec/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-ec/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-ec/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-ec/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ec/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ec/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/es/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/UserControlDesigner',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-ec/GroupNavigator':function(){
define('Sage/Groups/nls/es-ec/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-ec/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-ec/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-ec/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-ec/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/es/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es/DragDropWatcher',{});
},
'Sage/Utility/File/nls/es-ec/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es-ec/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/es/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/es-ec/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es-ec/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-ec/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-ec/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-ec/ActivityScheduler':function(){
define('Sage/UI/nls/es-ec/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-ec/SecurityManager':function(){
define('Sage/MainView/nls/es-ec/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-ec/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-ec/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/es/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/es-ec/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es-ec/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-ec/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-ec/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-ec/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-ec/UpdateOpportunities',{});
},
'Sage/UI/nls/es/EditCalendarUsers':function(){
define('Sage/UI/nls/es/EditCalendarUsers',{});
},
'Sage/UI/nls/es-ec/EditCalendarUsers':function(){
define('Sage/UI/nls/es-ec/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-ec/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-ec/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-ec/UserTasklet':function(){
define('Sage/TaskPane/nls/es-ec/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-ec/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-ec/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-ec/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-ec/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/es-ec/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es-ec/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/es/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/ColumnDesigner',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-ec/SearchMenuItem':function(){
define('Sage/UI/nls/es-ec/SearchMenuItem',{});
},
'Sage/Library/nls/es/DocumentProperties':function(){
define('Sage/Library/nls/es/DocumentProperties',{});
},
'Sage/Library/nls/es-ec/DocumentProperties':function(){
define('Sage/Library/nls/es-ec/DocumentProperties',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-ec/NotesHistoryList':function(){
define('Sage/UI/nls/es-ec/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/es/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ec/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ec/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-ec/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-ec/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ec/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ec/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-ec/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-ec/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-ec/GroupManager':function(){
define('Sage/Groups/nls/es-ec/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/es-ec/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es-ec/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ec/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ec/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/es/FolderHandler':function(){
define('Sage/Library/nls/es/FolderHandler',{});
},
'Sage/Library/nls/es-ec/FolderHandler':function(){
define('Sage/Library/nls/es-ec/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-ec/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-ec/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ec/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ec/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-ec/EditableGrid':function(){
define('Sage/UI/nls/es-ec/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-ec/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-ec/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/es/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/es-ec/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es-ec/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/ReportManagerUtility',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-ec/SpeedSearch':function(){
define('Sage/UI/nls/es-ec/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/es/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ec/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ec/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-ec/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-ec/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-ec/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-ec/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-ec/Utility':function(){
define('Sage/Utility/nls/es-ec/Utility',{});
},
'Sage/QuickForms/Design/nls/es/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/ControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-ec/Address':function(){
define('Sage/UI/Controls/nls/es-ec/Address',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/es-ec/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es-ec/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/es/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ec/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ec/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-ec/UserType':function(){
define('Sage/UI/nls/es-ec/UserType',{});
},
'Sage/QuickForms/Design/nls/es/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/ActivityCalendar',{});
},
'Sage/Utility/nls/es/Jobs':function(){
define('Sage/Utility/nls/es/Jobs',{});
},
'Sage/Utility/nls/es-ec/Jobs':function(){
define('Sage/Utility/nls/es-ec/Jobs',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-ec/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-ec/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-ec/ActivityList':function(){
define('Sage/UI/nls/es-ec/ActivityList',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/es-ec/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es-ec/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ec/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-ec/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-ec/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-ec/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/es-ec/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es-ec/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-ec/Attachment':function(){
define('Sage/Utility/File/nls/es-ec/Attachment',{});
},
'Sage/QuickForms/Design/nls/es/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/es-ec/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es-ec/PropertyEditorContainer',{});
},
'Sage/Services/nls/es/ReportingService':function(){
define('Sage/Services/nls/es/ReportingService',{});
},
'Sage/Services/nls/es-ec/ReportingService':function(){
define('Sage/Services/nls/es-ec/ReportingService',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-ec/Helper':function(){
define('Sage/MailMerge/nls/es-ec/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-ec/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-ec/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-ec/PickList':function(){
define('Sage/UI/Controls/nls/es-ec/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-ec/Email':function(){
define('Sage/Utility/nls/es-ec/Email',{});
},
'Sage/TaskPane/nls/es/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ec/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ec/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-ec/TimeZoneItem':function(){
define('Sage/UI/nls/es-ec/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-ec/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-ec/SlxEdit',{});
},
'Sage/Reporting/nls/es/Enumerations':function(){
define('Sage/Reporting/nls/es/Enumerations',{});
},
'Sage/Reporting/nls/es-ec/Enumerations':function(){
define('Sage/Reporting/nls/es-ec/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-ec/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-ec/ActivityListPanelConfig',{});
},
'Sage/UI/nls/es/JobSchedulingWidget':function(){
define('Sage/UI/nls/es/JobSchedulingWidget',{});
},
'Sage/UI/nls/es-ec/JobSchedulingWidget':function(){
define('Sage/UI/nls/es-ec/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-ec/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-ec/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-ec/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-ec/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ec/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ec/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-ec/Loader':function(){
define('Sage/MailMerge/nls/es-ec/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-ec/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-ec/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/es-ec/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es-ec/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-ec/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-ec/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/es/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/es-ec/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es-ec/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-ec/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-ec/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-ec/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-ec/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-ec/Lookup':function(){
define('Sage/UI/Controls/nls/es-ec/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-ec/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-ec/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-ec/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-ec/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ec/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ec/CommonTasksTasklet',{});
},
'Sage/Utility/nls/es/Dashboard':function(){
define('Sage/Utility/nls/es/Dashboard',{});
},
'Sage/Utility/nls/es-ec/Dashboard':function(){
define('Sage/Utility/nls/es-ec/Dashboard',{});
}}});
define("Sage/nls/Sage_es-ec", [], 1);
