define({
    lblCreateSchedule: 'Erstellen des Auftragszeitplans zur Ausführung',
    lblEveryText: 'Jede(n)',
    lblOnText: 'am',
    lblOnTheText: 'am',
    lblAtText: 'um',
    lblMinutesPastHour: 'Minuten nach der vollen Stunde',
    lblFromTimeText: 'Ausführen von',
    lblToTimeText: 'bis',
    lblMinutesFrequency: 'Minuten',
    lblHourlyFrequency: 'Stunde(n)',
    lblDailyFrequency: 'Tag',
    lblWeekDayFrequency: 'Wochentag',
    lblWeeklyFrequency: 'Woche',
    lblMonthlyFrequency: 'Monat',
    lblYearlyFrequency: 'Jahr',
    lblSunday: 'Sonntag',
    lblMonday: 'Montag',
    lblTuesday: 'Dienstag',
    lblWednesday: 'Mittwoch',
    lblThursday: 'Donnerstag',
    lblFriday: 'Freitag',
    lblSaturday: 'Samstag',
    lblFirstDay: 'ersten',
    lblSecondDay: 'zweiten',
    lblThirdDay: 'dritten',
    lblFourthDay: 'vierten',
    lblCronExpressionText: 'Cron-Ausdruck',
    txtInvalidScheduleTitle: 'Invalid Schedule',
    txtInvalidDatesMessage: 'The end time must be after the start time. Please correct this information before continuing.',
    txtInvalidScheduleTime: 'The start and end times specified will prevent this schedule from running. Please correct this information before continuing.',
    txtInvalidStartDate: 'A start date is required. Please specify a start date before continuing.',
    txtInvalidEndDate: 'A end date is required. Please specify a end date before continuing'
});