define((
{ layoutTabText: 'Présentation',
  propertiesTabText: 'Propriétés',
  toolsTabText: 'Barre outils',
  usageTabText: 'Utilisation par page',
  columnText: 'Colonne',
  rowText: 'Ligne',
  fieldNameText: 'Nom du champ',
  displayNameText: 'Nom affichage',
  visibleText: 'Visible',
  rowspanText: 'Largeur de ligne',
  colspanText: 'Largeur de colonne',
  controlTypeText: 'Type de contrôle',
  buttonAlignmentText: 'Bouton allignement :',
  rightText: 'Droite',
  centerText: 'Centre',
  leftText: 'Gauche',
  helpText: 'Aide',
  positionText: 'Emplacement',
  portalText: 'Portail',
  pageText: 'Page',
  entityText: 'Entité',
  workspaceText: 'Espace de travail cible',
  modeText: 'Afficher en mode',
  rolesText: 'Rôle' }
));