define({
    lblCreateSchedule: 'Crea pianificazione lavori da eseguire',
    lblEveryText: 'Ogni',
    lblOnText: 'di',
    lblOnTheText: 'il',
    lblAtText: 'a',
    lblMinutesPastHour: 'minuti dopo ora',
    lblFromTimeText: 'Esegui da',
    lblToTimeText: 'a',
    lblMinutesFrequency: 'minuti',
    lblHourlyFrequency: 'ora/e',
    lblDailyFrequency: 'giorno',
    lblWeekDayFrequency: 'giorno feriale',
    lblWeeklyFrequency: 'settimana',
    lblMonthlyFrequency: 'mese',
    lblYearlyFrequency: 'anno',
    lblSunday: 'Domenica',
    lblMonday: 'Lunedì',
    lblTuesday: 'Martedì',
    lblWednesday: 'Mercoledì',
    lblThursday: 'Giovedì',
    lblFriday: 'Venerdì',
    lblSaturday: 'Sabato',
    lblFirstDay: 'primo',
    lblSecondDay: 'secondo',
    lblThirdDay: 'terzo',
    lblFourthDay: 'quarto',
    lblCronExpressionText: 'Espressione Cron',
    txtInvalidScheduleTitle: 'Invalid Schedule',
    txtInvalidDatesMessage: 'The end time must be after the start time. Please correct this information before continuing.',
    txtInvalidScheduleTime: 'The start and end times specified will prevent this schedule from running. Please correct this information before continuing.',
    txtInvalidStartDate: 'A start date is required. Please specify a start date before continuing.',
    txtInvalidEndDate: 'A end date is required. Please specify a end date before continuing'
});