require({cache:{
'Sage/Utility/File/nls/be/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/be/FallbackFilePicker',{});
},
'Sage/UI/nls/be/Boolean':function(){
define('Sage/UI/nls/be/Boolean',{});
},
'Sage/Services/nls/be/ActivityService':function(){
define('Sage/Services/nls/be/ActivityService',{});
},
'Sage/UI/Controls/nls/be/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/be/CopyToClipboard',{});
},
'Sage/Utility/nls/be/Activity':function(){
define('Sage/Utility/nls/be/Activity',{});
},
'Sage/QuickForms/Design/nls/be/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/be/DesignPanel',{});
},
'Sage/UI/nls/be/TimelessActivitiesPane':function(){
define('Sage/UI/nls/be/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/be/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/be/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/be/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/be/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/be/ActivityManager':function(){
define('Sage/MainView/nls/be/ActivityManager',{});
},
'Sage/Services/nls/be/JobService':function(){
define('Sage/Services/nls/be/JobService',{});
},
'Sage/QuickForms/Design/nls/be/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/be/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/_PropertyEditor',{});
},
'Sage/Services/nls/be/ActivityActionProcessor':function(){
define('Sage/Services/nls/be/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/be/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/be/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/be/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/be/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/be/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/be/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/be/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/be/AlarmPane':function(){
define('Sage/UI/Alarms/nls/be/AlarmPane',{});
},
'Sage/TaskPane/nls/be/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/be/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/be/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/be/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/be/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/be/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/be/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/be/FilterPanel':function(){
define('Sage/UI/Filters/nls/be/FilterPanel',{});
},
'Sage/TaskPane/nls/be/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/be/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/be/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/be/ReportManagerFormatter',{});
},
'Sage/UI/nls/be/OwnerType':function(){
define('Sage/UI/nls/be/OwnerType',{});
},
'Sage/TaskPane/nls/be/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/be/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/be/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/be/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/be/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/be/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/be/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/be/InvoiceRTDV',{});
},
'Sage/UI/nls/be/SDataLookup':function(){
define('Sage/UI/nls/be/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/be/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/be/RowDesigner',{});
},
'Sage/TaskPane/nls/be/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/be/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/be/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/be/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/be/LibraryDocument':function(){
define('Sage/Utility/File/nls/be/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/be/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/be/SpeedSearchLookup',{});
},
'Sage/UI/nls/be/ConditionManager':function(){
define('Sage/UI/nls/be/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/be/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/be/WidgetDefinition',{});
},
'Sage/UI/nls/be/SearchConditionWidget':function(){
define('Sage/UI/nls/be/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/be/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/be/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/be/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/be/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/be/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/be/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/be/DataSourcePanel',{});
},
'Sage/Library/nls/be/Manager':function(){
define('Sage/Library/nls/be/Manager',{});
},
'Sage/UI/nls/be/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/be/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/be/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/be/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/be/Name':function(){
define('Sage/UI/Controls/nls/be/Name',{});
},
'Sage/MainView/JobMgr/nls/be/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/be/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/be/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/be/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/be/UpdateLeads',{});
},
'Sage/Library/nls/be/FileHandler':function(){
define('Sage/Library/nls/be/FileHandler',{});
},
'Sage/UI/nls/be/ListPanel':function(){
define('Sage/UI/nls/be/ListPanel',{});
},
'Sage/Utility/nls/be/Sql':function(){
define('Sage/Utility/nls/be/Sql',{});
},
'Sage/UI/Filters/nls/be/EditFilters':function(){
define('Sage/UI/Filters/nls/be/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/be/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/be/DurationSelect':function(){
define('Sage/UI/Controls/nls/be/DurationSelect',{});
},
'Sage/UI/Alarms/nls/be/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/be/AlarmCountDown',{});
},
'Sage/UI/nls/be/AttachmentList':function(){
define('Sage/UI/nls/be/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/be/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/be/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/be/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/be/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/be/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/be/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/be/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/be/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/be/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/be/Dialogs':function(){
define('Sage/UI/nls/be/Dialogs',{});
},
'Sage/TaskPane/nls/be/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/be/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/be/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/be/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/be/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/be/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/be/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/UserControlDesigner',{});
},
'Sage/Groups/nls/be/GroupNavigator':function(){
define('Sage/Groups/nls/be/GroupNavigator',{});
},
'Sage/Utility/File/nls/be/AddURLAttachment':function(){
define('Sage/Utility/File/nls/be/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/be/EditFilterItems':function(){
define('Sage/UI/Filters/nls/be/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/be/DragDropWatcher':function(){
define('Sage/Utility/File/nls/be/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/be/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/be/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/be/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/be/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/be/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/be/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/be/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/be/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/be/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/be/ActivityScheduler':function(){
define('Sage/UI/nls/be/ActivityScheduler',{});
},
'Sage/MainView/nls/be/SecurityManager':function(){
define('Sage/MainView/nls/be/SecurityManager',{});
},
'Sage/TaskPane/nls/be/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/be/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/be/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/be/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/be/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/be/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/be/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/be/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/be/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/be/UpdateOpportunities',{});
},
'Sage/UI/nls/be/EditCalendarUsers':function(){
define('Sage/UI/nls/be/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/be/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/be/HelpMenu':function(){
define('Sage/UI/Controls/nls/be/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/be/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/be/UserTasklet':function(){
define('Sage/TaskPane/nls/be/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/be/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/be/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/be/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/be/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/be/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/be/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/be/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/be/ColumnDesigner',{});
},
'Sage/UI/nls/be/SearchMenuItem':function(){
define('Sage/UI/nls/be/SearchMenuItem',{});
},
'Sage/Library/nls/be/DocumentProperties':function(){
define('Sage/Library/nls/be/DocumentProperties',{});
},
'Sage/UI/nls/be/NotesHistoryList':function(){
define('Sage/UI/nls/be/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/be/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/be/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/be/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/be/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/be/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/be/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/be/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/be/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/be/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/be/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/be/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/be/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/be/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/be/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/be/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/be/HistoryEditor',{});
},
'Sage/Groups/nls/be/GroupManager':function(){
define('Sage/Groups/nls/be/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/be/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/be/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/be/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/be/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/be/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/be/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/be/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/be/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/be/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/be/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/be/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/be/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/be/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/be/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/be/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/be/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/be/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/be/FolderHandler':function(){
define('Sage/Library/nls/be/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/be/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/be/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/be/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/be/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/be/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/be/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/be/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/be/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/be/EditableGrid':function(){
define('Sage/UI/nls/be/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/be/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/be/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/be/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/be/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/be/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/be/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/be/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/be/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/be/ReportManagerUtility',{});
},
'Sage/UI/nls/be/SpeedSearch':function(){
define('Sage/UI/nls/be/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/be/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/be/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/be/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/be/SLXPreviewGrid':function(){
define('Sage/UI/nls/be/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/be/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/be/UnconfirmedPane',{});
},
'Sage/Utility/nls/be/Utility':function(){
define('Sage/Utility/nls/be/Utility',{});
},
'Sage/QuickForms/Design/nls/be/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/ControlDesigner',{});
},
'Sage/UI/Controls/nls/be/Address':function(){
define('Sage/UI/Controls/nls/be/Address',{});
},
'Sage/MainView/JobMgr/nls/be/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/be/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/be/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/be/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/be/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/be/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/be/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/be/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/be/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/be/UserType':function(){
define('Sage/UI/nls/be/UserType',{});
},
'Sage/QuickForms/Design/nls/be/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/be/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/be/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/be/ActivityCalendar',{});
},
'Sage/Utility/nls/be/Jobs':function(){
define('Sage/Utility/nls/be/Jobs',{});
},
'Sage/UI/Controls/nls/be/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/be/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/be/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/be/ActivityList':function(){
define('Sage/UI/nls/be/ActivityList',{});
},
'Sage/UI/Alarms/nls/be/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/be/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/be/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/be/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/be/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/be/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/be/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/be/CalendarUsersListPane':function(){
define('Sage/UI/nls/be/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/be/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/be/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/be/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/be/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/be/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/be/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/be/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/be/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/be/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/be/Attachment':function(){
define('Sage/Utility/File/nls/be/Attachment',{});
},
'Sage/QuickForms/Design/nls/be/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/be/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/be/PropertyEditorContainer',{});
},
'Sage/Services/nls/be/ReportingService':function(){
define('Sage/Services/nls/be/ReportingService',{});
},
'Sage/MailMerge/nls/be/Helper':function(){
define('Sage/MailMerge/nls/be/Helper',{});
},
'Sage/UI/Dashboard/nls/be/Dashboard':function(){
define('Sage/UI/Dashboard/nls/be/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/be/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/be/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/be/PickList':function(){
define('Sage/UI/Controls/nls/be/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/be/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/be/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/be/Email':function(){
define('Sage/Utility/nls/be/Email',{});
},
'Sage/TaskPane/nls/be/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/be/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/be/TimeZoneItem':function(){
define('Sage/UI/nls/be/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/be/SlxEdit':function(){
define('Sage/UI/Columns/nls/be/SlxEdit',{});
},
'Sage/Reporting/nls/be/Enumerations':function(){
define('Sage/Reporting/nls/be/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/be/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/be/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/be/ActivityListPanelConfig',{});
},
'Sage/UI/nls/be/JobSchedulingWidget':function(){
define('Sage/UI/nls/be/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/be/LogOffButton':function(){
define('Sage/UI/Controls/nls/be/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/be/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/be/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/be/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/be/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/be/EditEventEditor',{});
},
'Sage/MailMerge/nls/be/Loader':function(){
define('Sage/MailMerge/nls/be/Loader',{});
},
'Sage/UI/Controls/nls/be/DateTimePicker':function(){
define('Sage/UI/Controls/nls/be/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/be/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/be/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/be/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/be/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/be/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/be/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/be/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/be/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/be/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/be/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/be/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/be/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/be/Lookup':function(){
define('Sage/UI/Controls/nls/be/Lookup',{});
},
'Sage/Utility/File/nls/be/DescriptionsForm':function(){
define('Sage/Utility/File/nls/be/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/be/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/be/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/be/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/be/CommonTasksTasklet',{});
},
'Sage/Utility/nls/be/Dashboard':function(){
define('Sage/Utility/nls/be/Dashboard',{});
}}});
define("Sage/nls/Sage_be", [], 1);
