require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/QuickForms/Design/nls/ar/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ar/DesignPanel',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/Services/nls/ar/JobService':function(){
define('Sage/Services/nls/ar/JobService',{});
},
'Sage/QuickForms/Design/nls/ar/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/_PropertyEditor',{});
},
'Sage/Services/nls/ar/ActivityActionProcessor':function(){
define('Sage/Services/nls/ar/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerFormatter',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ar/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/InvoiceRTDV',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ar/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/RowDesigner',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/SpeedSearchLookup',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ar/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ar/DataSourcePanel',{});
},
'Sage/Library/nls/ar/Manager':function(){
define('Sage/Library/nls/ar/Manager',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ar/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/Library/nls/ar/FileHandler':function(){
define('Sage/Library/nls/ar/FileHandler',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/Utility/nls/ar/Sql':function(){
define('Sage/Utility/nls/ar/Sql',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ar/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/Dialogs':function(){
define('Sage/UI/nls/ar/Dialogs',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ar/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UserControlDesigner',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ar/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ar/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ar/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ar/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ar/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ar/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/UI/nls/ar/EditCalendarUsers':function(){
define('Sage/UI/nls/ar/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ar/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ar/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ColumnDesigner',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/Library/nls/ar/DocumentProperties':function(){
define('Sage/Library/nls/ar/DocumentProperties',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ar/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ar/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ar/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ar/FolderHandler':function(){
define('Sage/Library/nls/ar/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ar/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ar/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ar/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerUtility',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/QuickForms/Design/nls/ar/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ar/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ar/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/QuickForms/Design/nls/ar/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/Utility/nls/ar/Jobs':function(){
define('Sage/Utility/nls/ar/Jobs',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/Alarms/nls/ar/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ar/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ar/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ar/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ar/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/QuickForms/Design/nls/ar/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ar/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ar/PropertyEditorContainer',{});
},
'Sage/Services/nls/ar/ReportingService':function(){
define('Sage/Services/nls/ar/ReportingService',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/Reporting/nls/ar/Enumerations':function(){
define('Sage/Reporting/nls/ar/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ar/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ar/JobSchedulingWidget':function(){
define('Sage/UI/nls/ar/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ar/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ar/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ar/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ar/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ar/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ar/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ar/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ar/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ar/Dashboard':function(){
define('Sage/Utility/nls/ar/Dashboard',{});
}}});
define("Sage/nls/Sage_ar", [], 1);
