require({cache:{
'Sage/Utility/File/nls/nl/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/nl/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/nl-be/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/nl-be/FallbackFilePicker',{});
},
'Sage/UI/nls/nl/Boolean':function(){
define('Sage/UI/nls/nl/Boolean',{});
},
'Sage/UI/nls/nl-be/Boolean':function(){
define('Sage/UI/nls/nl-be/Boolean',{});
},
'Sage/Services/nls/nl/ActivityService':function(){
define('Sage/Services/nls/nl/ActivityService',{});
},
'Sage/Services/nls/nl-be/ActivityService':function(){
define('Sage/Services/nls/nl-be/ActivityService',{});
},
'Sage/UI/Controls/nls/nl/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/nl/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/nl-be/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/nl-be/CopyToClipboard',{});
},
'Sage/Utility/nls/nl/Activity':function(){
define('Sage/Utility/nls/nl/Activity',{});
},
'Sage/Utility/nls/nl-be/Activity':function(){
define('Sage/Utility/nls/nl-be/Activity',{});
},
'Sage/QuickForms/Design/nls/nl/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/nl/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/nl-be/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/nl-be/DesignPanel',{});
},
'Sage/UI/nls/nl/TimelessActivitiesPane':function(){
define('Sage/UI/nls/nl/TimelessActivitiesPane',{});
},
'Sage/UI/nls/nl-be/TimelessActivitiesPane':function(){
define('Sage/UI/nls/nl-be/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/nl/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/nl/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/nl/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/nl-be/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/nl-be/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/nl/ActivityManager':function(){
define('Sage/MainView/nls/nl/ActivityManager',{});
},
'Sage/MainView/nls/nl-be/ActivityManager':function(){
define('Sage/MainView/nls/nl-be/ActivityManager',{});
},
'Sage/Services/nls/nl/JobService':function(){
define('Sage/Services/nls/nl/JobService',{});
},
'Sage/Services/nls/nl-be/JobService':function(){
define('Sage/Services/nls/nl-be/JobService',{});
},
'Sage/QuickForms/Design/nls/nl/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/_PropertyEditor',{});
},
'Sage/Services/nls/nl/ActivityActionProcessor':function(){
define('Sage/Services/nls/nl/ActivityActionProcessor',{});
},
'Sage/Services/nls/nl-be/ActivityActionProcessor':function(){
define('Sage/Services/nls/nl-be/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/nl/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/nl/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/nl-be/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/nl-be/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/nl/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/nl/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/nl-be/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/nl-be/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/nl/AlarmPane':function(){
define('Sage/UI/Alarms/nls/nl/AlarmPane',{});
},
'Sage/UI/Alarms/nls/nl-be/AlarmPane':function(){
define('Sage/UI/Alarms/nls/nl-be/AlarmPane',{});
},
'Sage/TaskPane/nls/nl/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/nl/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/nl-be/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/nl-be/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/nl/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/nl/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/nl-be/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/nl-be/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nl/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nl/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/nl-be/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nl-be/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/nl/FilterPanel':function(){
define('Sage/UI/Filters/nls/nl/FilterPanel',{});
},
'Sage/UI/Filters/nls/nl-be/FilterPanel':function(){
define('Sage/UI/Filters/nls/nl-be/FilterPanel',{});
},
'Sage/TaskPane/nls/nl/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/nl/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/nl-be/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/nl-be/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/nl/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/nl/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/ReportManagerFormatter',{});
},
'Sage/UI/nls/nl/OwnerType':function(){
define('Sage/UI/nls/nl/OwnerType',{});
},
'Sage/UI/nls/nl-be/OwnerType':function(){
define('Sage/UI/nls/nl-be/OwnerType',{});
},
'Sage/TaskPane/nls/nl/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/nl/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/nl-be/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/nl-be/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/nl/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/nl/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nl/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nl/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/nl-be/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nl-be/InvoiceRTDV',{});
},
'Sage/UI/nls/nl/SDataLookup':function(){
define('Sage/UI/nls/nl/SDataLookup',{});
},
'Sage/UI/nls/nl-be/SDataLookup':function(){
define('Sage/UI/nls/nl-be/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/nl/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/RowDesigner',{});
},
'Sage/TaskPane/nls/nl/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/nl/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/nl-be/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/nl-be/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/nl/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/nl/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/nl-be/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/nl-be/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/nl/LibraryDocument':function(){
define('Sage/Utility/File/nls/nl/LibraryDocument',{});
},
'Sage/Utility/File/nls/nl-be/LibraryDocument':function(){
define('Sage/Utility/File/nls/nl-be/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl-be/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl-be/SpeedSearchLookup',{});
},
'Sage/UI/nls/nl/ConditionManager':function(){
define('Sage/UI/nls/nl/ConditionManager',{});
},
'Sage/UI/nls/nl-be/ConditionManager':function(){
define('Sage/UI/nls/nl-be/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/nl/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/nl/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/nl-be/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/nl-be/WidgetDefinition',{});
},
'Sage/UI/nls/nl/SearchConditionWidget':function(){
define('Sage/UI/nls/nl/SearchConditionWidget',{});
},
'Sage/UI/nls/nl-be/SearchConditionWidget':function(){
define('Sage/UI/nls/nl-be/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/nl/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/nl/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/nl-be/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/nl-be/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl-be/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl-be/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/nl/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/nl/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/nl-be/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/nl-be/DataSourcePanel',{});
},
'Sage/Library/nls/nl/Manager':function(){
define('Sage/Library/nls/nl/Manager',{});
},
'Sage/Library/nls/nl-be/Manager':function(){
define('Sage/Library/nls/nl-be/Manager',{});
},
'Sage/UI/nls/nl/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/nl/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/nl-be/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/nl-be/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/nl/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/nl/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/nl-be/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/nl-be/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/nl/Name':function(){
define('Sage/UI/Controls/nls/nl/Name',{});
},
'Sage/UI/Controls/nls/nl-be/Name':function(){
define('Sage/UI/Controls/nls/nl-be/Name',{});
},
'Sage/MainView/JobMgr/nls/nl/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nl/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/nl-be/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nl-be/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/nl/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/nl/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/nl/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/nl-be/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/nl-be/UpdateLeads',{});
},
'Sage/Library/nls/nl/FileHandler':function(){
define('Sage/Library/nls/nl/FileHandler',{});
},
'Sage/Library/nls/nl-be/FileHandler':function(){
define('Sage/Library/nls/nl-be/FileHandler',{});
},
'Sage/UI/nls/nl/ListPanel':function(){
define('Sage/UI/nls/nl/ListPanel',{});
},
'Sage/UI/nls/nl-be/ListPanel':function(){
define('Sage/UI/nls/nl-be/ListPanel',{});
},
'Sage/Utility/nls/nl/Sql':function(){
define('Sage/Utility/nls/nl/Sql',{});
},
'Sage/Utility/nls/nl-be/Sql':function(){
define('Sage/Utility/nls/nl-be/Sql',{});
},
'Sage/UI/Filters/nls/nl/EditFilters':function(){
define('Sage/UI/Filters/nls/nl/EditFilters',{});
},
'Sage/UI/Filters/nls/nl-be/EditFilters':function(){
define('Sage/UI/Filters/nls/nl-be/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/nl/DurationSelect':function(){
define('Sage/UI/Controls/nls/nl/DurationSelect',{});
},
'Sage/UI/Controls/nls/nl-be/DurationSelect':function(){
define('Sage/UI/Controls/nls/nl-be/DurationSelect',{});
},
'Sage/UI/Alarms/nls/nl/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/nl/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/nl-be/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/nl-be/AlarmCountDown',{});
},
'Sage/UI/nls/nl/AttachmentList':function(){
define('Sage/UI/nls/nl/AttachmentList',{});
},
'Sage/UI/nls/nl-be/AttachmentList':function(){
define('Sage/UI/nls/nl-be/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/nl/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/nl/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/nl-be/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/nl-be/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/nl/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/nl/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/nl/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/nl-be/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/nl-be/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/nl/Dialogs':function(){
define('Sage/UI/nls/nl/Dialogs',{});
},
'Sage/UI/nls/nl-be/Dialogs':function(){
define('Sage/UI/nls/nl-be/Dialogs',{});
},
'Sage/TaskPane/nls/nl/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/nl/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/nl-be/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/nl-be/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/nl/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/nl/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/nl-be/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/nl-be/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/nl/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nl/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/nl-be/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nl-be/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/nl/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/UserControlDesigner',{});
},
'Sage/Groups/nls/nl/GroupNavigator':function(){
define('Sage/Groups/nls/nl/GroupNavigator',{});
},
'Sage/Groups/nls/nl-be/GroupNavigator':function(){
define('Sage/Groups/nls/nl-be/GroupNavigator',{});
},
'Sage/Utility/File/nls/nl/AddURLAttachment':function(){
define('Sage/Utility/File/nls/nl/AddURLAttachment',{});
},
'Sage/Utility/File/nls/nl-be/AddURLAttachment':function(){
define('Sage/Utility/File/nls/nl-be/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/nl/EditFilterItems':function(){
define('Sage/UI/Filters/nls/nl/EditFilterItems',{});
},
'Sage/UI/Filters/nls/nl-be/EditFilterItems':function(){
define('Sage/UI/Filters/nls/nl-be/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/nl/DragDropWatcher':function(){
define('Sage/Utility/File/nls/nl/DragDropWatcher',{});
},
'Sage/Utility/File/nls/nl-be/DragDropWatcher':function(){
define('Sage/Utility/File/nls/nl-be/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/nl/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/nl/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/nl-be/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/nl-be/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/nl/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/nl/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/nl/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/nl-be/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/nl-be/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/nl/ActivityScheduler':function(){
define('Sage/UI/nls/nl/ActivityScheduler',{});
},
'Sage/UI/nls/nl-be/ActivityScheduler':function(){
define('Sage/UI/nls/nl-be/ActivityScheduler',{});
},
'Sage/MainView/nls/nl/SecurityManager':function(){
define('Sage/MainView/nls/nl/SecurityManager',{});
},
'Sage/MainView/nls/nl-be/SecurityManager':function(){
define('Sage/MainView/nls/nl-be/SecurityManager',{});
},
'Sage/TaskPane/nls/nl/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/nl/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/nl-be/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/nl-be/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/nl/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/nl/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/nl-be/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/nl-be/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/nl/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/nl/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/nl/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/nl/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/nl-be/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/nl-be/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/nl/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/nl/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/nl-be/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/nl-be/UpdateOpportunities',{});
},
'Sage/UI/nls/nl/EditCalendarUsers':function(){
define('Sage/UI/nls/nl/EditCalendarUsers',{});
},
'Sage/UI/nls/nl-be/EditCalendarUsers':function(){
define('Sage/UI/nls/nl-be/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/nl/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/nl/HelpMenu':function(){
define('Sage/UI/Controls/nls/nl/HelpMenu',{});
},
'Sage/UI/Controls/nls/nl-be/HelpMenu':function(){
define('Sage/UI/Controls/nls/nl-be/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/nl/UserTasklet':function(){
define('Sage/TaskPane/nls/nl/UserTasklet',{});
},
'Sage/TaskPane/nls/nl-be/UserTasklet':function(){
define('Sage/TaskPane/nls/nl-be/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/nl/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/nl/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/nl-be/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/nl-be/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/nl/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/nl/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/nl-be/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/nl-be/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nl/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/nl/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/nl-be/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/nl-be/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/nl/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/ColumnDesigner',{});
},
'Sage/UI/nls/nl/SearchMenuItem':function(){
define('Sage/UI/nls/nl/SearchMenuItem',{});
},
'Sage/UI/nls/nl-be/SearchMenuItem':function(){
define('Sage/UI/nls/nl-be/SearchMenuItem',{});
},
'Sage/Library/nls/nl/DocumentProperties':function(){
define('Sage/Library/nls/nl/DocumentProperties',{});
},
'Sage/Library/nls/nl-be/DocumentProperties':function(){
define('Sage/Library/nls/nl-be/DocumentProperties',{});
},
'Sage/UI/nls/nl/NotesHistoryList':function(){
define('Sage/UI/nls/nl/NotesHistoryList',{});
},
'Sage/UI/nls/nl-be/NotesHistoryList':function(){
define('Sage/UI/nls/nl-be/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/nl/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nl/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/nl/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/nl/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/nl/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/nl-be/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/nl-be/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/nl/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/nl/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/nl-be/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/nl-be/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/nl/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nl/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/nl-be/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nl-be/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/nl/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/nl/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/nl-be/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/nl-be/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/nl/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/nl/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nl/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/HistoryEditor',{});
},
'Sage/Groups/nls/nl/GroupManager':function(){
define('Sage/Groups/nls/nl/GroupManager',{});
},
'Sage/Groups/nls/nl-be/GroupManager':function(){
define('Sage/Groups/nls/nl-be/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/nl/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nl/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/nl/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/nl/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/nl-be/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/nl-be/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/nl/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nl/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/nl-be/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nl-be/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nl/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/nl/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nl/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/nl/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/nl/FolderHandler':function(){
define('Sage/Library/nls/nl/FolderHandler',{});
},
'Sage/Library/nls/nl-be/FolderHandler':function(){
define('Sage/Library/nls/nl-be/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/nl/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/nl/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/nl-be/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/nl-be/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/nl/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/nl/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/nl-be/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/nl-be/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/nl/EditableGrid':function(){
define('Sage/UI/nls/nl/EditableGrid',{});
},
'Sage/UI/nls/nl-be/EditableGrid':function(){
define('Sage/UI/nls/nl-be/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/nl/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nl/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/nl-be/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nl-be/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/nl/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/nl/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/nl-be/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/nl-be/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/nl/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/nl/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/nl/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/nl/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/ReportManagerUtility',{});
},
'Sage/UI/nls/nl/SpeedSearch':function(){
define('Sage/UI/nls/nl/SpeedSearch',{});
},
'Sage/UI/nls/nl-be/SpeedSearch':function(){
define('Sage/UI/nls/nl-be/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/nl/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nl/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/nl-be/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nl-be/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/nl/SLXPreviewGrid':function(){
define('Sage/UI/nls/nl/SLXPreviewGrid',{});
},
'Sage/UI/nls/nl-be/SLXPreviewGrid':function(){
define('Sage/UI/nls/nl-be/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/nl/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/nl/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/nl-be/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/nl-be/UnconfirmedPane',{});
},
'Sage/Utility/nls/nl/Utility':function(){
define('Sage/Utility/nls/nl/Utility',{});
},
'Sage/Utility/nls/nl-be/Utility':function(){
define('Sage/Utility/nls/nl-be/Utility',{});
},
'Sage/QuickForms/Design/nls/nl/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/ControlDesigner',{});
},
'Sage/UI/Controls/nls/nl/Address':function(){
define('Sage/UI/Controls/nls/nl/Address',{});
},
'Sage/UI/Controls/nls/nl-be/Address':function(){
define('Sage/UI/Controls/nls/nl-be/Address',{});
},
'Sage/MainView/JobMgr/nls/nl/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/nl/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/nl-be/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/nl-be/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/nl/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/nl/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/nl/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nl/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/nl-be/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nl-be/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/nl/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/nl/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/nl/UserType':function(){
define('Sage/UI/nls/nl/UserType',{});
},
'Sage/UI/nls/nl-be/UserType':function(){
define('Sage/UI/nls/nl-be/UserType',{});
},
'Sage/QuickForms/Design/nls/nl/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/nl/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/nl/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/ActivityCalendar',{});
},
'Sage/Utility/nls/nl/Jobs':function(){
define('Sage/Utility/nls/nl/Jobs',{});
},
'Sage/Utility/nls/nl-be/Jobs':function(){
define('Sage/Utility/nls/nl-be/Jobs',{});
},
'Sage/UI/Controls/nls/nl/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/nl/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/nl-be/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/nl-be/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/nl/ActivityList':function(){
define('Sage/UI/nls/nl/ActivityList',{});
},
'Sage/UI/nls/nl-be/ActivityList':function(){
define('Sage/UI/nls/nl-be/ActivityList',{});
},
'Sage/UI/Alarms/nls/nl/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/nl/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/nl-be/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/nl-be/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl-be/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/nl-be/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/nl/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nl/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/nl/CalendarUsersListPane':function(){
define('Sage/UI/nls/nl/CalendarUsersListPane',{});
},
'Sage/UI/nls/nl-be/CalendarUsersListPane':function(){
define('Sage/UI/nls/nl-be/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/nl/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/nl/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/nl/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/nl/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/nl-be/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/nl-be/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/nl/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/nl/Attachment':function(){
define('Sage/Utility/File/nls/nl/Attachment',{});
},
'Sage/Utility/File/nls/nl-be/Attachment':function(){
define('Sage/Utility/File/nls/nl-be/Attachment',{});
},
'Sage/QuickForms/Design/nls/nl/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/nl/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/nl/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/nl-be/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/nl-be/PropertyEditorContainer',{});
},
'Sage/Services/nls/nl/ReportingService':function(){
define('Sage/Services/nls/nl/ReportingService',{});
},
'Sage/Services/nls/nl-be/ReportingService':function(){
define('Sage/Services/nls/nl-be/ReportingService',{});
},
'Sage/MailMerge/nls/nl/Helper':function(){
define('Sage/MailMerge/nls/nl/Helper',{});
},
'Sage/MailMerge/nls/nl-be/Helper':function(){
define('Sage/MailMerge/nls/nl-be/Helper',{});
},
'Sage/UI/Dashboard/nls/nl/Dashboard':function(){
define('Sage/UI/Dashboard/nls/nl/Dashboard',{});
},
'Sage/UI/Dashboard/nls/nl-be/Dashboard':function(){
define('Sage/UI/Dashboard/nls/nl-be/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/nl/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/nl/PickList':function(){
define('Sage/UI/Controls/nls/nl/PickList',{});
},
'Sage/UI/Controls/nls/nl-be/PickList':function(){
define('Sage/UI/Controls/nls/nl-be/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/nl/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/nl/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/nl/Email':function(){
define('Sage/Utility/nls/nl/Email',{});
},
'Sage/Utility/nls/nl-be/Email':function(){
define('Sage/Utility/nls/nl-be/Email',{});
},
'Sage/TaskPane/nls/nl/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nl/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/nl-be/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nl-be/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/nl/TimeZoneItem':function(){
define('Sage/UI/nls/nl/TimeZoneItem',{});
},
'Sage/UI/nls/nl-be/TimeZoneItem':function(){
define('Sage/UI/nls/nl-be/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/nl/SlxEdit':function(){
define('Sage/UI/Columns/nls/nl/SlxEdit',{});
},
'Sage/UI/Columns/nls/nl-be/SlxEdit':function(){
define('Sage/UI/Columns/nls/nl-be/SlxEdit',{});
},
'Sage/Reporting/nls/nl/Enumerations':function(){
define('Sage/Reporting/nls/nl/Enumerations',{});
},
'Sage/Reporting/nls/nl-be/Enumerations':function(){
define('Sage/Reporting/nls/nl-be/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/nl/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/nl/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/nl-be/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/nl-be/ActivityListPanelConfig',{});
},
'Sage/UI/nls/nl/JobSchedulingWidget':function(){
define('Sage/UI/nls/nl/JobSchedulingWidget',{});
},
'Sage/UI/nls/nl-be/JobSchedulingWidget':function(){
define('Sage/UI/nls/nl-be/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/nl/LogOffButton':function(){
define('Sage/UI/Controls/nls/nl/LogOffButton',{});
},
'Sage/UI/Controls/nls/nl-be/LogOffButton':function(){
define('Sage/UI/Controls/nls/nl-be/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/nl-be/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/nl-be/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nl-be/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nl-be/EditEventEditor',{});
},
'Sage/MailMerge/nls/nl/Loader':function(){
define('Sage/MailMerge/nls/nl/Loader',{});
},
'Sage/MailMerge/nls/nl-be/Loader':function(){
define('Sage/MailMerge/nls/nl-be/Loader',{});
},
'Sage/UI/Controls/nls/nl/DateTimePicker':function(){
define('Sage/UI/Controls/nls/nl/DateTimePicker',{});
},
'Sage/UI/Controls/nls/nl-be/DateTimePicker':function(){
define('Sage/UI/Controls/nls/nl-be/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/nl/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/nl/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/nl-be/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/nl-be/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/nl/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/nl/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/nl-be/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/nl-be/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/nl/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/nl/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/nl-be/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/nl-be/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/nl/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nl/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/nl-be/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/nl-be/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/nl/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nl-be/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nl-be/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/nl/Lookup':function(){
define('Sage/UI/Controls/nls/nl/Lookup',{});
},
'Sage/UI/Controls/nls/nl-be/Lookup':function(){
define('Sage/UI/Controls/nls/nl-be/Lookup',{});
},
'Sage/Utility/File/nls/nl/DescriptionsForm':function(){
define('Sage/Utility/File/nls/nl/DescriptionsForm',{});
},
'Sage/Utility/File/nls/nl-be/DescriptionsForm':function(){
define('Sage/Utility/File/nls/nl-be/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/nl/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nl-be/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nl-be/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/nl/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/nl/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/nl-be/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/nl-be/CommonTasksTasklet',{});
},
'Sage/Utility/nls/nl/Dashboard':function(){
define('Sage/Utility/nls/nl/Dashboard',{});
},
'Sage/Utility/nls/nl-be/Dashboard':function(){
define('Sage/Utility/nls/nl-be/Dashboard',{});
}}});
define("Sage/nls/Sage_nl-be", [], 1);
