require({cache:{
'Sage/Utility/File/nls/pt/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/pt/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/pt-br/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/pt-br/FallbackFilePicker',{});
},
'Sage/UI/nls/pt/Boolean':function(){
define('Sage/UI/nls/pt/Boolean',{});
},
'Sage/UI/nls/pt-br/Boolean':function(){
define('Sage/UI/nls/pt-br/Boolean',{});
},
'Sage/Services/nls/pt/ActivityService':function(){
define('Sage/Services/nls/pt/ActivityService',{});
},
'Sage/Services/nls/pt-br/ActivityService':function(){
define('Sage/Services/nls/pt-br/ActivityService',{});
},
'Sage/UI/Controls/nls/pt/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/pt/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/pt-br/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/pt-br/CopyToClipboard',{});
},
'Sage/Utility/nls/pt/Activity':function(){
define('Sage/Utility/nls/pt/Activity',{});
},
'Sage/Utility/nls/pt-br/Activity':function(){
define('Sage/Utility/nls/pt-br/Activity',{});
},
'Sage/QuickForms/Design/nls/pt/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/pt/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/pt-br/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/pt-br/DesignPanel',{});
},
'Sage/UI/nls/pt/TimelessActivitiesPane':function(){
define('Sage/UI/nls/pt/TimelessActivitiesPane',{});
},
'Sage/UI/nls/pt-br/TimelessActivitiesPane':function(){
define('Sage/UI/nls/pt-br/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/pt/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/pt/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/pt-br/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/pt-br/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/pt/ActivityManager':function(){
define('Sage/MainView/nls/pt/ActivityManager',{});
},
'Sage/MainView/nls/pt-br/ActivityManager':function(){
define('Sage/MainView/nls/pt-br/ActivityManager',{});
},
'Sage/Services/nls/pt/JobService':function(){
define('Sage/Services/nls/pt/JobService',{});
},
'Sage/Services/nls/pt-br/JobService':function(){
define('Sage/Services/nls/pt-br/JobService',{});
},
'Sage/QuickForms/Design/nls/pt/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/_PropertyEditor',{});
},
'Sage/Services/nls/pt/ActivityActionProcessor':function(){
define('Sage/Services/nls/pt/ActivityActionProcessor',{});
},
'Sage/Services/nls/pt-br/ActivityActionProcessor':function(){
define('Sage/Services/nls/pt-br/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/pt/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/pt/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/pt-br/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/pt-br/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/pt/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/pt/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/pt-br/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/pt-br/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/pt/AlarmPane':function(){
define('Sage/UI/Alarms/nls/pt/AlarmPane',{});
},
'Sage/UI/Alarms/nls/pt-br/AlarmPane':function(){
define('Sage/UI/Alarms/nls/pt-br/AlarmPane',{});
},
'Sage/TaskPane/nls/pt/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/pt/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/pt-br/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/pt-br/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/pt-br/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/pt-br/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/pt-br/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt-br/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/pt/FilterPanel':function(){
define('Sage/UI/Filters/nls/pt/FilterPanel',{});
},
'Sage/UI/Filters/nls/pt-br/FilterPanel':function(){
define('Sage/UI/Filters/nls/pt-br/FilterPanel',{});
},
'Sage/TaskPane/nls/pt/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/pt/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/pt-br/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/pt-br/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/ReportManagerFormatter',{});
},
'Sage/UI/nls/pt/OwnerType':function(){
define('Sage/UI/nls/pt/OwnerType',{});
},
'Sage/UI/nls/pt-br/OwnerType':function(){
define('Sage/UI/nls/pt-br/OwnerType',{});
},
'Sage/TaskPane/nls/pt/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-br/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-br/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/pt/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/pt/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/pt-br/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt-br/InvoiceRTDV',{});
},
'Sage/UI/nls/pt/SDataLookup':function(){
define('Sage/UI/nls/pt/SDataLookup',{});
},
'Sage/UI/nls/pt-br/SDataLookup':function(){
define('Sage/UI/nls/pt-br/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/pt/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/RowDesigner',{});
},
'Sage/TaskPane/nls/pt/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-br/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-br/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/pt/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/pt/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/pt-br/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/pt-br/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/pt/LibraryDocument':function(){
define('Sage/Utility/File/nls/pt/LibraryDocument',{});
},
'Sage/Utility/File/nls/pt-br/LibraryDocument':function(){
define('Sage/Utility/File/nls/pt-br/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt-br/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt-br/SpeedSearchLookup',{});
},
'Sage/UI/nls/pt/ConditionManager':function(){
define('Sage/UI/nls/pt/ConditionManager',{});
},
'Sage/UI/nls/pt-br/ConditionManager':function(){
define('Sage/UI/nls/pt-br/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/pt/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/pt/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/pt-br/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/pt-br/WidgetDefinition',{});
},
'Sage/UI/nls/pt/SearchConditionWidget':function(){
define('Sage/UI/nls/pt/SearchConditionWidget',{});
},
'Sage/UI/nls/pt-br/SearchConditionWidget':function(){
define('Sage/UI/nls/pt-br/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/pt/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/pt/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/pt-br/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/pt-br/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt-br/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt-br/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/pt/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/pt/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/pt-br/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/pt-br/DataSourcePanel',{});
},
'Sage/Library/nls/pt/Manager':function(){
define('Sage/Library/nls/pt/Manager',{});
},
'Sage/Library/nls/pt-br/Manager':function(){
define('Sage/Library/nls/pt-br/Manager',{});
},
'Sage/UI/nls/pt/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/pt/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/pt-br/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/pt-br/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/pt/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/pt/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/pt-br/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/pt-br/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/pt/Name':function(){
define('Sage/UI/Controls/nls/pt/Name',{});
},
'Sage/UI/Controls/nls/pt-br/Name':function(){
define('Sage/UI/Controls/nls/pt-br/Name',{});
},
'Sage/MainView/JobMgr/nls/pt/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/pt-br/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt-br/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/pt/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/pt/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/pt/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/pt-br/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/pt-br/UpdateLeads',{});
},
'Sage/Library/nls/pt/FileHandler':function(){
define('Sage/Library/nls/pt/FileHandler',{});
},
'Sage/Library/nls/pt-br/FileHandler':function(){
define('Sage/Library/nls/pt-br/FileHandler',{});
},
'Sage/UI/nls/pt/ListPanel':function(){
define('Sage/UI/nls/pt/ListPanel',{});
},
'Sage/UI/nls/pt-br/ListPanel':function(){
define('Sage/UI/nls/pt-br/ListPanel',{});
},
'Sage/Utility/nls/pt/Sql':function(){
define('Sage/Utility/nls/pt/Sql',{});
},
'Sage/Utility/nls/pt-br/Sql':function(){
define('Sage/Utility/nls/pt-br/Sql',{});
},
'Sage/UI/Filters/nls/pt/EditFilters':function(){
define('Sage/UI/Filters/nls/pt/EditFilters',{});
},
'Sage/UI/Filters/nls/pt-br/EditFilters':function(){
define('Sage/UI/Filters/nls/pt-br/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/pt/DurationSelect':function(){
define('Sage/UI/Controls/nls/pt/DurationSelect',{});
},
'Sage/UI/Controls/nls/pt-br/DurationSelect':function(){
define('Sage/UI/Controls/nls/pt-br/DurationSelect',{});
},
'Sage/UI/Alarms/nls/pt/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/pt/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/pt-br/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/pt-br/AlarmCountDown',{});
},
'Sage/UI/nls/pt/AttachmentList':function(){
define('Sage/UI/nls/pt/AttachmentList',{});
},
'Sage/UI/nls/pt-br/AttachmentList':function(){
define('Sage/UI/nls/pt-br/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/pt/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/pt/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/pt-br/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/pt-br/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/pt/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/pt-br/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/pt-br/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/pt/Dialogs':function(){
define('Sage/UI/nls/pt/Dialogs',{});
},
'Sage/UI/nls/pt-br/Dialogs':function(){
define('Sage/UI/nls/pt-br/Dialogs',{});
},
'Sage/TaskPane/nls/pt/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/pt/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/pt-br/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/pt-br/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/pt-br/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/pt-br/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/pt/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/pt-br/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt-br/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/pt/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/UserControlDesigner',{});
},
'Sage/Groups/nls/pt/GroupNavigator':function(){
define('Sage/Groups/nls/pt/GroupNavigator',{});
},
'Sage/Groups/nls/pt-br/GroupNavigator':function(){
define('Sage/Groups/nls/pt-br/GroupNavigator',{});
},
'Sage/Utility/File/nls/pt/AddURLAttachment':function(){
define('Sage/Utility/File/nls/pt/AddURLAttachment',{});
},
'Sage/Utility/File/nls/pt-br/AddURLAttachment':function(){
define('Sage/Utility/File/nls/pt-br/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/pt/EditFilterItems':function(){
define('Sage/UI/Filters/nls/pt/EditFilterItems',{});
},
'Sage/UI/Filters/nls/pt-br/EditFilterItems':function(){
define('Sage/UI/Filters/nls/pt-br/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/pt/DragDropWatcher':function(){
define('Sage/Utility/File/nls/pt/DragDropWatcher',{});
},
'Sage/Utility/File/nls/pt-br/DragDropWatcher':function(){
define('Sage/Utility/File/nls/pt-br/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/pt/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/pt/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/pt-br/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/pt-br/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/pt/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/pt/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/pt-br/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/pt-br/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/pt/ActivityScheduler':function(){
define('Sage/UI/nls/pt/ActivityScheduler',{});
},
'Sage/UI/nls/pt-br/ActivityScheduler':function(){
define('Sage/UI/nls/pt-br/ActivityScheduler',{});
},
'Sage/MainView/nls/pt/SecurityManager':function(){
define('Sage/MainView/nls/pt/SecurityManager',{});
},
'Sage/MainView/nls/pt-br/SecurityManager':function(){
define('Sage/MainView/nls/pt-br/SecurityManager',{});
},
'Sage/TaskPane/nls/pt/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/pt/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/pt-br/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/pt-br/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/pt/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/pt/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/pt-br/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/pt-br/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/pt/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/pt/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/pt-br/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/pt-br/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/pt/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/pt/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/pt-br/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/pt-br/UpdateOpportunities',{});
},
'Sage/UI/nls/pt/EditCalendarUsers':function(){
define('Sage/UI/nls/pt/EditCalendarUsers',{});
},
'Sage/UI/nls/pt-br/EditCalendarUsers':function(){
define('Sage/UI/nls/pt-br/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/pt/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/HelpMenu':function(){
define('Sage/UI/Controls/nls/pt/HelpMenu',{});
},
'Sage/UI/Controls/nls/pt-br/HelpMenu':function(){
define('Sage/UI/Controls/nls/pt-br/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/UserTasklet':function(){
define('Sage/TaskPane/nls/pt/UserTasklet',{});
},
'Sage/TaskPane/nls/pt-br/UserTasklet':function(){
define('Sage/TaskPane/nls/pt-br/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/pt/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/pt/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/pt-br/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/pt-br/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/pt/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/pt/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/pt-br/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/pt-br/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/pt/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/pt-br/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/pt-br/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/pt/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/ColumnDesigner',{});
},
'Sage/UI/nls/pt/SearchMenuItem':function(){
define('Sage/UI/nls/pt/SearchMenuItem',{});
},
'Sage/UI/nls/pt-br/SearchMenuItem':function(){
define('Sage/UI/nls/pt-br/SearchMenuItem',{});
},
'Sage/Library/nls/pt/DocumentProperties':function(){
define('Sage/Library/nls/pt/DocumentProperties',{});
},
'Sage/Library/nls/pt-br/DocumentProperties':function(){
define('Sage/Library/nls/pt-br/DocumentProperties',{});
},
'Sage/UI/nls/pt/NotesHistoryList':function(){
define('Sage/UI/nls/pt/NotesHistoryList',{});
},
'Sage/UI/nls/pt-br/NotesHistoryList':function(){
define('Sage/UI/nls/pt-br/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/pt/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/pt/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/pt/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-br/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-br/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/pt/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/pt/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/pt-br/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/pt-br/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/pt/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/pt-br/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt-br/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/pt/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/pt/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/pt-br/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/pt-br/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/pt/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/pt/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/HistoryEditor',{});
},
'Sage/Groups/nls/pt/GroupManager':function(){
define('Sage/Groups/nls/pt/GroupManager',{});
},
'Sage/Groups/nls/pt-br/GroupManager':function(){
define('Sage/Groups/nls/pt-br/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/pt/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/pt/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/pt-br/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/pt-br/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/pt/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/pt-br/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt-br/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/pt/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/pt/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/pt/FolderHandler':function(){
define('Sage/Library/nls/pt/FolderHandler',{});
},
'Sage/Library/nls/pt-br/FolderHandler':function(){
define('Sage/Library/nls/pt-br/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/pt/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/pt/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/pt-br/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/pt-br/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-br/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-br/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/pt/EditableGrid':function(){
define('Sage/UI/nls/pt/EditableGrid',{});
},
'Sage/UI/nls/pt-br/EditableGrid':function(){
define('Sage/UI/nls/pt-br/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/pt/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/pt-br/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt-br/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/pt/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/pt/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/pt-br/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/pt-br/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/ReportManagerUtility',{});
},
'Sage/UI/nls/pt/SpeedSearch':function(){
define('Sage/UI/nls/pt/SpeedSearch',{});
},
'Sage/UI/nls/pt-br/SpeedSearch':function(){
define('Sage/UI/nls/pt-br/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-br/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-br/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/pt/SLXPreviewGrid':function(){
define('Sage/UI/nls/pt/SLXPreviewGrid',{});
},
'Sage/UI/nls/pt-br/SLXPreviewGrid':function(){
define('Sage/UI/nls/pt-br/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/pt/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/pt/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/pt-br/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/pt-br/UnconfirmedPane',{});
},
'Sage/Utility/nls/pt/Utility':function(){
define('Sage/Utility/nls/pt/Utility',{});
},
'Sage/Utility/nls/pt-br/Utility':function(){
define('Sage/Utility/nls/pt-br/Utility',{});
},
'Sage/QuickForms/Design/nls/pt/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/ControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/Address':function(){
define('Sage/UI/Controls/nls/pt/Address',{});
},
'Sage/UI/Controls/nls/pt-br/Address':function(){
define('Sage/UI/Controls/nls/pt-br/Address',{});
},
'Sage/MainView/JobMgr/nls/pt/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/pt/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/pt-br/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/pt-br/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/pt/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/pt/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/pt/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-br/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-br/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/pt/UserType':function(){
define('Sage/UI/nls/pt/UserType',{});
},
'Sage/UI/nls/pt-br/UserType':function(){
define('Sage/UI/nls/pt-br/UserType',{});
},
'Sage/QuickForms/Design/nls/pt/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/ActivityCalendar',{});
},
'Sage/Utility/nls/pt/Jobs':function(){
define('Sage/Utility/nls/pt/Jobs',{});
},
'Sage/Utility/nls/pt-br/Jobs':function(){
define('Sage/Utility/nls/pt-br/Jobs',{});
},
'Sage/UI/Controls/nls/pt/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/pt/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/pt-br/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/pt-br/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pt/ActivityList':function(){
define('Sage/UI/nls/pt/ActivityList',{});
},
'Sage/UI/nls/pt-br/ActivityList':function(){
define('Sage/UI/nls/pt-br/ActivityList',{});
},
'Sage/UI/Alarms/nls/pt/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/pt/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/pt-br/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/pt-br/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt-br/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt-br/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/pt/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pt/CalendarUsersListPane':function(){
define('Sage/UI/nls/pt/CalendarUsersListPane',{});
},
'Sage/UI/nls/pt-br/CalendarUsersListPane':function(){
define('Sage/UI/nls/pt-br/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/pt/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/pt/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/pt-br/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/pt-br/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/pt/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/pt/Attachment':function(){
define('Sage/Utility/File/nls/pt/Attachment',{});
},
'Sage/Utility/File/nls/pt-br/Attachment':function(){
define('Sage/Utility/File/nls/pt-br/Attachment',{});
},
'Sage/QuickForms/Design/nls/pt/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/pt/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/pt/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/pt-br/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/pt-br/PropertyEditorContainer',{});
},
'Sage/Services/nls/pt/ReportingService':function(){
define('Sage/Services/nls/pt/ReportingService',{});
},
'Sage/Services/nls/pt-br/ReportingService':function(){
define('Sage/Services/nls/pt-br/ReportingService',{});
},
'Sage/MailMerge/nls/pt/Helper':function(){
define('Sage/MailMerge/nls/pt/Helper',{});
},
'Sage/MailMerge/nls/pt-br/Helper':function(){
define('Sage/MailMerge/nls/pt-br/Helper',{});
},
'Sage/UI/Dashboard/nls/pt/Dashboard':function(){
define('Sage/UI/Dashboard/nls/pt/Dashboard',{});
},
'Sage/UI/Dashboard/nls/pt-br/Dashboard':function(){
define('Sage/UI/Dashboard/nls/pt-br/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/pt/PickList':function(){
define('Sage/UI/Controls/nls/pt/PickList',{});
},
'Sage/UI/Controls/nls/pt-br/PickList':function(){
define('Sage/UI/Controls/nls/pt-br/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/pt/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/pt/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/pt/Email':function(){
define('Sage/Utility/nls/pt/Email',{});
},
'Sage/Utility/nls/pt-br/Email':function(){
define('Sage/Utility/nls/pt-br/Email',{});
},
'Sage/TaskPane/nls/pt/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-br/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-br/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/pt/TimeZoneItem':function(){
define('Sage/UI/nls/pt/TimeZoneItem',{});
},
'Sage/UI/nls/pt-br/TimeZoneItem':function(){
define('Sage/UI/nls/pt-br/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/pt/SlxEdit':function(){
define('Sage/UI/Columns/nls/pt/SlxEdit',{});
},
'Sage/UI/Columns/nls/pt-br/SlxEdit':function(){
define('Sage/UI/Columns/nls/pt-br/SlxEdit',{});
},
'Sage/Reporting/nls/pt/Enumerations':function(){
define('Sage/Reporting/nls/pt/Enumerations',{});
},
'Sage/Reporting/nls/pt-br/Enumerations':function(){
define('Sage/Reporting/nls/pt-br/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/pt/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/pt/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/pt-br/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/pt-br/ActivityListPanelConfig',{});
},
'Sage/UI/nls/pt/JobSchedulingWidget':function(){
define('Sage/UI/nls/pt/JobSchedulingWidget',{});
},
'Sage/UI/nls/pt-br/JobSchedulingWidget':function(){
define('Sage/UI/nls/pt-br/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/pt/LogOffButton':function(){
define('Sage/UI/Controls/nls/pt/LogOffButton',{});
},
'Sage/UI/Controls/nls/pt-br/LogOffButton':function(){
define('Sage/UI/Controls/nls/pt-br/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt-br/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt-br/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-br/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-br/EditEventEditor',{});
},
'Sage/MailMerge/nls/pt/Loader':function(){
define('Sage/MailMerge/nls/pt/Loader',{});
},
'Sage/MailMerge/nls/pt-br/Loader':function(){
define('Sage/MailMerge/nls/pt-br/Loader',{});
},
'Sage/UI/Controls/nls/pt/DateTimePicker':function(){
define('Sage/UI/Controls/nls/pt/DateTimePicker',{});
},
'Sage/UI/Controls/nls/pt-br/DateTimePicker':function(){
define('Sage/UI/Controls/nls/pt-br/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/pt-br/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/pt-br/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/pt/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/pt/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/pt-br/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/pt-br/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/pt/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/pt/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/pt-br/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/pt-br/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/pt/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/pt-br/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt-br/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/pt/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-br/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-br/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/Lookup':function(){
define('Sage/UI/Controls/nls/pt/Lookup',{});
},
'Sage/UI/Controls/nls/pt-br/Lookup':function(){
define('Sage/UI/Controls/nls/pt-br/Lookup',{});
},
'Sage/Utility/File/nls/pt/DescriptionsForm':function(){
define('Sage/Utility/File/nls/pt/DescriptionsForm',{});
},
'Sage/Utility/File/nls/pt-br/DescriptionsForm':function(){
define('Sage/Utility/File/nls/pt-br/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-br/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-br/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-br/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-br/CommonTasksTasklet',{});
},
'Sage/Utility/nls/pt/Dashboard':function(){
define('Sage/Utility/nls/pt/Dashboard',{});
},
'Sage/Utility/nls/pt-br/Dashboard':function(){
define('Sage/Utility/nls/pt-br/Dashboard',{});
}}});
define("Sage/nls/Sage_pt-br", [], 1);
