require({cache:{
'Sage/Utility/File/nls/pt/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/pt/FallbackFilePicker',{});
},
'Sage/UI/nls/pt/Boolean':function(){
define('Sage/UI/nls/pt/Boolean',{});
},
'Sage/Services/nls/pt/ActivityService':function(){
define('Sage/Services/nls/pt/ActivityService',{});
},
'Sage/UI/Controls/nls/pt/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/pt/CopyToClipboard',{});
},
'Sage/Utility/nls/pt/Activity':function(){
define('Sage/Utility/nls/pt/Activity',{});
},
'Sage/QuickForms/Design/nls/pt/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/pt/DesignPanel',{});
},
'Sage/UI/nls/pt/TimelessActivitiesPane':function(){
define('Sage/UI/nls/pt/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/pt/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/pt/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/pt/ActivityManager':function(){
define('Sage/MainView/nls/pt/ActivityManager',{});
},
'Sage/Services/nls/pt/JobService':function(){
define('Sage/Services/nls/pt/JobService',{});
},
'Sage/QuickForms/Design/nls/pt/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/_PropertyEditor',{});
},
'Sage/Services/nls/pt/ActivityActionProcessor':function(){
define('Sage/Services/nls/pt/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/pt/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/pt/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/pt/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/pt/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/pt/AlarmPane':function(){
define('Sage/UI/Alarms/nls/pt/AlarmPane',{});
},
'Sage/TaskPane/nls/pt/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/pt/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/pt/FilterPanel':function(){
define('Sage/UI/Filters/nls/pt/FilterPanel',{});
},
'Sage/TaskPane/nls/pt/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/pt/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportManagerFormatter',{});
},
'Sage/UI/nls/pt/OwnerType':function(){
define('Sage/UI/nls/pt/OwnerType',{});
},
'Sage/TaskPane/nls/pt/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/pt/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/pt/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/InvoiceRTDV',{});
},
'Sage/UI/nls/pt/SDataLookup':function(){
define('Sage/UI/nls/pt/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/pt/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/RowDesigner',{});
},
'Sage/TaskPane/nls/pt/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/pt/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/pt/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/pt/LibraryDocument':function(){
define('Sage/Utility/File/nls/pt/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/SpeedSearchLookup',{});
},
'Sage/UI/nls/pt/ConditionManager':function(){
define('Sage/UI/nls/pt/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/pt/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/pt/WidgetDefinition',{});
},
'Sage/UI/nls/pt/SearchConditionWidget':function(){
define('Sage/UI/nls/pt/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/pt/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/pt/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/pt/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/pt/DataSourcePanel',{});
},
'Sage/Library/nls/pt/Manager':function(){
define('Sage/Library/nls/pt/Manager',{});
},
'Sage/UI/nls/pt/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/pt/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/pt/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/pt/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/pt/Name':function(){
define('Sage/UI/Controls/nls/pt/Name',{});
},
'Sage/MainView/JobMgr/nls/pt/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/pt/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/pt/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/pt/UpdateLeads',{});
},
'Sage/Library/nls/pt/FileHandler':function(){
define('Sage/Library/nls/pt/FileHandler',{});
},
'Sage/UI/nls/pt/ListPanel':function(){
define('Sage/UI/nls/pt/ListPanel',{});
},
'Sage/Utility/nls/pt/Sql':function(){
define('Sage/Utility/nls/pt/Sql',{});
},
'Sage/UI/Filters/nls/pt/EditFilters':function(){
define('Sage/UI/Filters/nls/pt/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/pt/DurationSelect':function(){
define('Sage/UI/Controls/nls/pt/DurationSelect',{});
},
'Sage/UI/Alarms/nls/pt/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/pt/AlarmCountDown',{});
},
'Sage/UI/nls/pt/AttachmentList':function(){
define('Sage/UI/nls/pt/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/pt/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/pt/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/pt/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/pt/Dialogs':function(){
define('Sage/UI/nls/pt/Dialogs',{});
},
'Sage/TaskPane/nls/pt/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/pt/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/pt/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/pt/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/UserControlDesigner',{});
},
'Sage/Groups/nls/pt/GroupNavigator':function(){
define('Sage/Groups/nls/pt/GroupNavigator',{});
},
'Sage/Utility/File/nls/pt/AddURLAttachment':function(){
define('Sage/Utility/File/nls/pt/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/pt/EditFilterItems':function(){
define('Sage/UI/Filters/nls/pt/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/pt/DragDropWatcher':function(){
define('Sage/Utility/File/nls/pt/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/pt/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/pt/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/pt/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/pt/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/pt/ActivityScheduler':function(){
define('Sage/UI/nls/pt/ActivityScheduler',{});
},
'Sage/MainView/nls/pt/SecurityManager':function(){
define('Sage/MainView/nls/pt/SecurityManager',{});
},
'Sage/TaskPane/nls/pt/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/pt/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/pt/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/pt/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/pt/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/pt/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/pt/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/pt/UpdateOpportunities',{});
},
'Sage/UI/nls/pt/EditCalendarUsers':function(){
define('Sage/UI/nls/pt/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/pt/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/HelpMenu':function(){
define('Sage/UI/Controls/nls/pt/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/UserTasklet':function(){
define('Sage/TaskPane/nls/pt/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/pt/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/pt/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/pt/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/pt/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/pt/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/pt/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ColumnDesigner',{});
},
'Sage/UI/nls/pt/SearchMenuItem':function(){
define('Sage/UI/nls/pt/SearchMenuItem',{});
},
'Sage/Library/nls/pt/DocumentProperties':function(){
define('Sage/Library/nls/pt/DocumentProperties',{});
},
'Sage/UI/nls/pt/NotesHistoryList':function(){
define('Sage/UI/nls/pt/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/pt/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/pt/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/pt/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/pt/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/pt/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/pt/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/pt/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/pt/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/pt/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/pt/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/HistoryEditor',{});
},
'Sage/Groups/nls/pt/GroupManager':function(){
define('Sage/Groups/nls/pt/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/pt/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/pt/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/pt/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/pt/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/pt/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/pt/FolderHandler':function(){
define('Sage/Library/nls/pt/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/pt/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/pt/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/pt/EditableGrid':function(){
define('Sage/UI/nls/pt/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/pt/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/pt/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/pt/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportManagerUtility',{});
},
'Sage/UI/nls/pt/SpeedSearch':function(){
define('Sage/UI/nls/pt/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/pt/SLXPreviewGrid':function(){
define('Sage/UI/nls/pt/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/pt/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/pt/UnconfirmedPane',{});
},
'Sage/Utility/nls/pt/Utility':function(){
define('Sage/Utility/nls/pt/Utility',{});
},
'Sage/QuickForms/Design/nls/pt/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/Address':function(){
define('Sage/UI/Controls/nls/pt/Address',{});
},
'Sage/MainView/JobMgr/nls/pt/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/pt/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/pt/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/pt/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/pt/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/pt/UserType':function(){
define('Sage/UI/nls/pt/UserType',{});
},
'Sage/QuickForms/Design/nls/pt/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityCalendar',{});
},
'Sage/Utility/nls/pt/Jobs':function(){
define('Sage/Utility/nls/pt/Jobs',{});
},
'Sage/UI/Controls/nls/pt/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/pt/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pt/ActivityList':function(){
define('Sage/UI/nls/pt/ActivityList',{});
},
'Sage/UI/Alarms/nls/pt/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/pt/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/pt/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/pt/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/pt/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pt/CalendarUsersListPane':function(){
define('Sage/UI/nls/pt/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/pt/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/pt/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/pt/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/pt/Attachment':function(){
define('Sage/Utility/File/nls/pt/Attachment',{});
},
'Sage/QuickForms/Design/nls/pt/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/pt/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/pt/PropertyEditorContainer',{});
},
'Sage/Services/nls/pt/ReportingService':function(){
define('Sage/Services/nls/pt/ReportingService',{});
},
'Sage/MailMerge/nls/pt/Helper':function(){
define('Sage/MailMerge/nls/pt/Helper',{});
},
'Sage/UI/Dashboard/nls/pt/Dashboard':function(){
define('Sage/UI/Dashboard/nls/pt/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/pt/PickList':function(){
define('Sage/UI/Controls/nls/pt/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/pt/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/pt/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/pt/Email':function(){
define('Sage/Utility/nls/pt/Email',{});
},
'Sage/TaskPane/nls/pt/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/pt/TimeZoneItem':function(){
define('Sage/UI/nls/pt/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/pt/SlxEdit':function(){
define('Sage/UI/Columns/nls/pt/SlxEdit',{});
},
'Sage/Reporting/nls/pt/Enumerations':function(){
define('Sage/Reporting/nls/pt/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/pt/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/pt/ActivityListPanelConfig',{});
},
'Sage/UI/nls/pt/JobSchedulingWidget':function(){
define('Sage/UI/nls/pt/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/pt/LogOffButton':function(){
define('Sage/UI/Controls/nls/pt/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/pt/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/pt/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/EditEventEditor',{});
},
'Sage/MailMerge/nls/pt/Loader':function(){
define('Sage/MailMerge/nls/pt/Loader',{});
},
'Sage/UI/Controls/nls/pt/DateTimePicker':function(){
define('Sage/UI/Controls/nls/pt/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/pt/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/pt/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/pt/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/pt/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/pt/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/pt/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/pt/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/pt/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/pt/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/Lookup':function(){
define('Sage/UI/Controls/nls/pt/Lookup',{});
},
'Sage/Utility/File/nls/pt/DescriptionsForm':function(){
define('Sage/Utility/File/nls/pt/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/CommonTasksTasklet',{});
},
'Sage/Utility/nls/pt/Dashboard':function(){
define('Sage/Utility/nls/pt/Dashboard',{});
}}});
define("Sage/nls/Sage_pt", [], 1);
