require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-pe/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-pe/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-pe/Boolean':function(){
define('Sage/UI/nls/es-pe/Boolean',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-pe/ActivityService':function(){
define('Sage/Services/nls/es-pe/ActivityService',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-pe/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-pe/CopyToClipboard',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-pe/Activity':function(){
define('Sage/Utility/nls/es-pe/Activity',{});
},
'Sage/QuickForms/Design/nls/es/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/es-pe/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es-pe/DesignPanel',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-pe/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-pe/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/es/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/es-pe/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es-pe/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-pe/ActivityManager':function(){
define('Sage/MainView/nls/es-pe/ActivityManager',{});
},
'Sage/Services/nls/es/JobService':function(){
define('Sage/Services/nls/es/JobService',{});
},
'Sage/Services/nls/es-pe/JobService':function(){
define('Sage/Services/nls/es-pe/JobService',{});
},
'Sage/QuickForms/Design/nls/es/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/_PropertyEditor',{});
},
'Sage/Services/nls/es/ActivityActionProcessor':function(){
define('Sage/Services/nls/es/ActivityActionProcessor',{});
},
'Sage/Services/nls/es-pe/ActivityActionProcessor':function(){
define('Sage/Services/nls/es-pe/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-pe/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-pe/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-pe/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-pe/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-pe/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-pe/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-pe/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-pe/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-pe/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-pe/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-pe/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-pe/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-pe/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-pe/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-pe/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-pe/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/ReportManagerFormatter',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-pe/OwnerType':function(){
define('Sage/UI/nls/es-pe/OwnerType',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-pe/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-pe/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-pe/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-pe/InvoiceRTDV',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-pe/SDataLookup':function(){
define('Sage/UI/nls/es-pe/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/es/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/RowDesigner',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-pe/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-pe/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-pe/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-pe/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-pe/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-pe/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-pe/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-pe/SpeedSearchLookup',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-pe/ConditionManager':function(){
define('Sage/UI/nls/es-pe/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-pe/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-pe/WidgetDefinition',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-pe/SearchConditionWidget':function(){
define('Sage/UI/nls/es-pe/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/es-pe/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es-pe/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-pe/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-pe/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/es/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/es-pe/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es-pe/DataSourcePanel',{});
},
'Sage/Library/nls/es/Manager':function(){
define('Sage/Library/nls/es/Manager',{});
},
'Sage/Library/nls/es-pe/Manager':function(){
define('Sage/Library/nls/es-pe/Manager',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-pe/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-pe/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/es/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/es-pe/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es-pe/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-pe/Name':function(){
define('Sage/UI/Controls/nls/es-pe/Name',{});
},
'Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-pe/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-pe/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-pe/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-pe/UpdateLeads',{});
},
'Sage/Library/nls/es/FileHandler':function(){
define('Sage/Library/nls/es/FileHandler',{});
},
'Sage/Library/nls/es-pe/FileHandler':function(){
define('Sage/Library/nls/es-pe/FileHandler',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-pe/ListPanel':function(){
define('Sage/UI/nls/es-pe/ListPanel',{});
},
'Sage/Utility/nls/es/Sql':function(){
define('Sage/Utility/nls/es/Sql',{});
},
'Sage/Utility/nls/es-pe/Sql':function(){
define('Sage/Utility/nls/es-pe/Sql',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-pe/EditFilters':function(){
define('Sage/UI/Filters/nls/es-pe/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-pe/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-pe/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-pe/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-pe/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-pe/AttachmentList':function(){
define('Sage/UI/nls/es-pe/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/es-pe/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es-pe/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-pe/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-pe/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/es/Dialogs':function(){
define('Sage/UI/nls/es/Dialogs',{});
},
'Sage/UI/nls/es-pe/Dialogs':function(){
define('Sage/UI/nls/es-pe/Dialogs',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-pe/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-pe/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-pe/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-pe/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-pe/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-pe/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/es/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/UserControlDesigner',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-pe/GroupNavigator':function(){
define('Sage/Groups/nls/es-pe/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-pe/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-pe/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-pe/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-pe/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/es/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es/DragDropWatcher',{});
},
'Sage/Utility/File/nls/es-pe/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es-pe/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/es/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/es-pe/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es-pe/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-pe/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-pe/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-pe/ActivityScheduler':function(){
define('Sage/UI/nls/es-pe/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-pe/SecurityManager':function(){
define('Sage/MainView/nls/es-pe/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-pe/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-pe/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/es/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/es-pe/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es-pe/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-pe/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-pe/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-pe/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-pe/UpdateOpportunities',{});
},
'Sage/UI/nls/es/EditCalendarUsers':function(){
define('Sage/UI/nls/es/EditCalendarUsers',{});
},
'Sage/UI/nls/es-pe/EditCalendarUsers':function(){
define('Sage/UI/nls/es-pe/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-pe/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-pe/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-pe/UserTasklet':function(){
define('Sage/TaskPane/nls/es-pe/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-pe/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-pe/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-pe/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-pe/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/es-pe/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es-pe/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/es/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/ColumnDesigner',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-pe/SearchMenuItem':function(){
define('Sage/UI/nls/es-pe/SearchMenuItem',{});
},
'Sage/Library/nls/es/DocumentProperties':function(){
define('Sage/Library/nls/es/DocumentProperties',{});
},
'Sage/Library/nls/es-pe/DocumentProperties':function(){
define('Sage/Library/nls/es-pe/DocumentProperties',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-pe/NotesHistoryList':function(){
define('Sage/UI/nls/es-pe/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/es/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/es-pe/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es-pe/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-pe/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-pe/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-pe/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-pe/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-pe/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-pe/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-pe/GroupManager':function(){
define('Sage/Groups/nls/es-pe/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/es-pe/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es-pe/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-pe/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-pe/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/es/FolderHandler':function(){
define('Sage/Library/nls/es/FolderHandler',{});
},
'Sage/Library/nls/es-pe/FolderHandler':function(){
define('Sage/Library/nls/es-pe/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-pe/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-pe/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-pe/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-pe/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-pe/EditableGrid':function(){
define('Sage/UI/nls/es-pe/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-pe/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-pe/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/es/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/es-pe/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es-pe/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/ReportManagerUtility',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-pe/SpeedSearch':function(){
define('Sage/UI/nls/es-pe/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/es/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-pe/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-pe/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-pe/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-pe/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-pe/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-pe/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-pe/Utility':function(){
define('Sage/Utility/nls/es-pe/Utility',{});
},
'Sage/QuickForms/Design/nls/es/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/ControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-pe/Address':function(){
define('Sage/UI/Controls/nls/es-pe/Address',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/es-pe/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es-pe/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/es/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-pe/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-pe/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-pe/UserType':function(){
define('Sage/UI/nls/es-pe/UserType',{});
},
'Sage/QuickForms/Design/nls/es/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/ActivityCalendar',{});
},
'Sage/Utility/nls/es/Jobs':function(){
define('Sage/Utility/nls/es/Jobs',{});
},
'Sage/Utility/nls/es-pe/Jobs':function(){
define('Sage/Utility/nls/es-pe/Jobs',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-pe/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-pe/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-pe/ActivityList':function(){
define('Sage/UI/nls/es-pe/ActivityList',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/es-pe/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es-pe/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-pe/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-pe/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-pe/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-pe/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/es-pe/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es-pe/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-pe/Attachment':function(){
define('Sage/Utility/File/nls/es-pe/Attachment',{});
},
'Sage/QuickForms/Design/nls/es/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/es-pe/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es-pe/PropertyEditorContainer',{});
},
'Sage/Services/nls/es/ReportingService':function(){
define('Sage/Services/nls/es/ReportingService',{});
},
'Sage/Services/nls/es-pe/ReportingService':function(){
define('Sage/Services/nls/es-pe/ReportingService',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-pe/Helper':function(){
define('Sage/MailMerge/nls/es-pe/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-pe/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-pe/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-pe/PickList':function(){
define('Sage/UI/Controls/nls/es-pe/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-pe/Email':function(){
define('Sage/Utility/nls/es-pe/Email',{});
},
'Sage/TaskPane/nls/es/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-pe/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-pe/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-pe/TimeZoneItem':function(){
define('Sage/UI/nls/es-pe/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-pe/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-pe/SlxEdit',{});
},
'Sage/Reporting/nls/es/Enumerations':function(){
define('Sage/Reporting/nls/es/Enumerations',{});
},
'Sage/Reporting/nls/es-pe/Enumerations':function(){
define('Sage/Reporting/nls/es-pe/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-pe/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-pe/ActivityListPanelConfig',{});
},
'Sage/UI/nls/es/JobSchedulingWidget':function(){
define('Sage/UI/nls/es/JobSchedulingWidget',{});
},
'Sage/UI/nls/es-pe/JobSchedulingWidget':function(){
define('Sage/UI/nls/es-pe/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-pe/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-pe/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-pe/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-pe/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-pe/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-pe/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-pe/Loader':function(){
define('Sage/MailMerge/nls/es-pe/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-pe/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-pe/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/es-pe/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es-pe/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-pe/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-pe/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/es/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/es-pe/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es-pe/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-pe/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-pe/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-pe/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-pe/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-pe/Lookup':function(){
define('Sage/UI/Controls/nls/es-pe/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-pe/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-pe/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-pe/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-pe/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-pe/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-pe/CommonTasksTasklet',{});
},
'Sage/Utility/nls/es/Dashboard':function(){
define('Sage/Utility/nls/es/Dashboard',{});
},
'Sage/Utility/nls/es-pe/Dashboard':function(){
define('Sage/Utility/nls/es-pe/Dashboard',{});
}}});
define("Sage/nls/Sage_es-pe", [], 1);
