require({cache:{
'Sage/Utility/File/nls/sk/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sk/FallbackFilePicker',{});
},
'Sage/UI/nls/sk/Boolean':function(){
define('Sage/UI/nls/sk/Boolean',{});
},
'Sage/Services/nls/sk/ActivityService':function(){
define('Sage/Services/nls/sk/ActivityService',{});
},
'Sage/UI/Controls/nls/sk/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sk/CopyToClipboard',{});
},
'Sage/Utility/nls/sk/Activity':function(){
define('Sage/Utility/nls/sk/Activity',{});
},
'Sage/QuickForms/Design/nls/sk/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sk/DesignPanel',{});
},
'Sage/UI/nls/sk/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sk/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sk/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sk/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/sk/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/sk/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/sk/ActivityManager':function(){
define('Sage/MainView/nls/sk/ActivityManager',{});
},
'Sage/Services/nls/sk/JobService':function(){
define('Sage/Services/nls/sk/JobService',{});
},
'Sage/QuickForms/Design/nls/sk/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/_PropertyEditor',{});
},
'Sage/Services/nls/sk/ActivityActionProcessor':function(){
define('Sage/Services/nls/sk/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sk/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sk/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/sk/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sk/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sk/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sk/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sk/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sk/AlarmPane',{});
},
'Sage/TaskPane/nls/sk/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sk/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sk/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sk/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sk/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sk/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sk/FilterPanel':function(){
define('Sage/UI/Filters/nls/sk/FilterPanel',{});
},
'Sage/TaskPane/nls/sk/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sk/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/sk/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/sk/ReportManagerFormatter',{});
},
'Sage/UI/nls/sk/OwnerType':function(){
define('Sage/UI/nls/sk/OwnerType',{});
},
'Sage/TaskPane/nls/sk/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sk/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sk/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sk/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sk/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sk/InvoiceRTDV',{});
},
'Sage/UI/nls/sk/SDataLookup':function(){
define('Sage/UI/nls/sk/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sk/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/RowDesigner',{});
},
'Sage/TaskPane/nls/sk/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sk/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sk/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sk/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sk/LibraryDocument':function(){
define('Sage/Utility/File/nls/sk/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sk/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sk/SpeedSearchLookup',{});
},
'Sage/UI/nls/sk/ConditionManager':function(){
define('Sage/UI/nls/sk/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sk/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sk/WidgetDefinition',{});
},
'Sage/UI/nls/sk/SearchConditionWidget':function(){
define('Sage/UI/nls/sk/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sk/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/sk/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sk/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sk/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/sk/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sk/DataSourcePanel',{});
},
'Sage/Library/nls/sk/Manager':function(){
define('Sage/Library/nls/sk/Manager',{});
},
'Sage/UI/nls/sk/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sk/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sk/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sk/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sk/Name':function(){
define('Sage/UI/Controls/nls/sk/Name',{});
},
'Sage/MainView/JobMgr/nls/sk/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sk/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sk/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sk/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sk/UpdateLeads',{});
},
'Sage/Library/nls/sk/FileHandler':function(){
define('Sage/Library/nls/sk/FileHandler',{});
},
'Sage/UI/nls/sk/ListPanel':function(){
define('Sage/UI/nls/sk/ListPanel',{});
},
'Sage/Utility/nls/sk/Sql':function(){
define('Sage/Utility/nls/sk/Sql',{});
},
'Sage/UI/Filters/nls/sk/EditFilters':function(){
define('Sage/UI/Filters/nls/sk/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sk/DurationSelect':function(){
define('Sage/UI/Controls/nls/sk/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sk/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sk/AlarmCountDown',{});
},
'Sage/UI/nls/sk/AttachmentList':function(){
define('Sage/UI/nls/sk/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sk/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/sk/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/sk/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sk/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sk/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sk/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sk/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sk/Dialogs':function(){
define('Sage/UI/nls/sk/Dialogs',{});
},
'Sage/TaskPane/nls/sk/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sk/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sk/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sk/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sk/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sk/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sk/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/UserControlDesigner',{});
},
'Sage/Groups/nls/sk/GroupNavigator':function(){
define('Sage/Groups/nls/sk/GroupNavigator',{});
},
'Sage/Utility/File/nls/sk/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sk/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sk/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sk/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/sk/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sk/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/sk/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sk/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/sk/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sk/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sk/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sk/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sk/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sk/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/sk/ActivityScheduler':function(){
define('Sage/UI/nls/sk/ActivityScheduler',{});
},
'Sage/MainView/nls/sk/SecurityManager':function(){
define('Sage/MainView/nls/sk/SecurityManager',{});
},
'Sage/TaskPane/nls/sk/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sk/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sk/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sk/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sk/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sk/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/sk/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/sk/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/sk/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sk/UpdateOpportunities',{});
},
'Sage/UI/nls/sk/EditCalendarUsers':function(){
define('Sage/UI/nls/sk/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/sk/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sk/HelpMenu':function(){
define('Sage/UI/Controls/nls/sk/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sk/UserTasklet':function(){
define('Sage/TaskPane/nls/sk/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/sk/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sk/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sk/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sk/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sk/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sk/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sk/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/ColumnDesigner',{});
},
'Sage/UI/nls/sk/SearchMenuItem':function(){
define('Sage/UI/nls/sk/SearchMenuItem',{});
},
'Sage/Library/nls/sk/DocumentProperties':function(){
define('Sage/Library/nls/sk/DocumentProperties',{});
},
'Sage/UI/nls/sk/NotesHistoryList':function(){
define('Sage/UI/nls/sk/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/sk/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sk/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sk/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/sk/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/sk/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/sk/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/sk/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/sk/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sk/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/sk/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sk/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sk/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sk/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sk/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sk/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sk/HistoryEditor',{});
},
'Sage/Groups/nls/sk/GroupManager':function(){
define('Sage/Groups/nls/sk/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sk/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sk/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/sk/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/sk/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/sk/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sk/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sk/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sk/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/sk/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sk/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sk/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sk/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sk/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/sk/FolderHandler':function(){
define('Sage/Library/nls/sk/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sk/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sk/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sk/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sk/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sk/EditableGrid':function(){
define('Sage/UI/nls/sk/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/sk/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sk/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/sk/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sk/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/sk/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/sk/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sk/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/sk/ReportManagerUtility',{});
},
'Sage/UI/nls/sk/SpeedSearch':function(){
define('Sage/UI/nls/sk/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/sk/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sk/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/sk/SLXPreviewGrid':function(){
define('Sage/UI/nls/sk/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sk/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sk/UnconfirmedPane',{});
},
'Sage/Utility/nls/sk/Utility':function(){
define('Sage/Utility/nls/sk/Utility',{});
},
'Sage/QuickForms/Design/nls/sk/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sk/Address':function(){
define('Sage/UI/Controls/nls/sk/Address',{});
},
'Sage/MainView/JobMgr/nls/sk/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/sk/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/sk/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sk/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/sk/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sk/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sk/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sk/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/sk/UserType':function(){
define('Sage/UI/nls/sk/UserType',{});
},
'Sage/QuickForms/Design/nls/sk/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sk/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sk/ActivityCalendar',{});
},
'Sage/Utility/nls/sk/Jobs':function(){
define('Sage/Utility/nls/sk/Jobs',{});
},
'Sage/UI/Controls/nls/sk/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sk/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sk/ActivityList':function(){
define('Sage/UI/nls/sk/ActivityList',{});
},
'Sage/UI/Alarms/nls/sk/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/sk/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sk/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sk/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/sk/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sk/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sk/CalendarUsersListPane':function(){
define('Sage/UI/nls/sk/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sk/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/sk/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/sk/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sk/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sk/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sk/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sk/Attachment':function(){
define('Sage/Utility/File/nls/sk/Attachment',{});
},
'Sage/QuickForms/Design/nls/sk/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sk/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sk/PropertyEditorContainer',{});
},
'Sage/Services/nls/sk/ReportingService':function(){
define('Sage/Services/nls/sk/ReportingService',{});
},
'Sage/MailMerge/nls/sk/Helper':function(){
define('Sage/MailMerge/nls/sk/Helper',{});
},
'Sage/UI/Dashboard/nls/sk/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sk/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sk/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sk/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sk/PickList':function(){
define('Sage/UI/Controls/nls/sk/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/sk/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sk/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/sk/Email':function(){
define('Sage/Utility/nls/sk/Email',{});
},
'Sage/TaskPane/nls/sk/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sk/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sk/TimeZoneItem':function(){
define('Sage/UI/nls/sk/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sk/SlxEdit':function(){
define('Sage/UI/Columns/nls/sk/SlxEdit',{});
},
'Sage/Reporting/nls/sk/Enumerations':function(){
define('Sage/Reporting/nls/sk/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sk/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sk/ActivityListPanelConfig',{});
},
'Sage/UI/nls/sk/JobSchedulingWidget':function(){
define('Sage/UI/nls/sk/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/sk/LogOffButton':function(){
define('Sage/UI/Controls/nls/sk/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sk/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sk/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sk/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sk/EditEventEditor',{});
},
'Sage/MailMerge/nls/sk/Loader':function(){
define('Sage/MailMerge/nls/sk/Loader',{});
},
'Sage/UI/Controls/nls/sk/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sk/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/sk/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/sk/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/sk/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sk/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/sk/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/sk/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sk/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sk/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sk/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sk/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sk/Lookup':function(){
define('Sage/UI/Controls/nls/sk/Lookup',{});
},
'Sage/Utility/File/nls/sk/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sk/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sk/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sk/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sk/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sk/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sk/Dashboard':function(){
define('Sage/Utility/nls/sk/Dashboard',{});
}}});
define("Sage/nls/Sage_sk", [], 1);
