require({cache:{
'Sage/Utility/File/nls/sq/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sq/FallbackFilePicker',{});
},
'Sage/UI/nls/sq/Boolean':function(){
define('Sage/UI/nls/sq/Boolean',{});
},
'Sage/Services/nls/sq/ActivityService':function(){
define('Sage/Services/nls/sq/ActivityService',{});
},
'Sage/UI/Controls/nls/sq/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sq/CopyToClipboard',{});
},
'Sage/Utility/nls/sq/Activity':function(){
define('Sage/Utility/nls/sq/Activity',{});
},
'Sage/QuickForms/Design/nls/sq/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sq/DesignPanel',{});
},
'Sage/UI/nls/sq/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sq/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/sq/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/sq/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/sq/ActivityManager':function(){
define('Sage/MainView/nls/sq/ActivityManager',{});
},
'Sage/Services/nls/sq/JobService':function(){
define('Sage/Services/nls/sq/JobService',{});
},
'Sage/QuickForms/Design/nls/sq/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/_PropertyEditor',{});
},
'Sage/Services/nls/sq/ActivityActionProcessor':function(){
define('Sage/Services/nls/sq/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/sq/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sq/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sq/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sq/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sq/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sq/AlarmPane',{});
},
'Sage/TaskPane/nls/sq/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sq/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sq/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sq/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sq/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sq/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sq/FilterPanel':function(){
define('Sage/UI/Filters/nls/sq/FilterPanel',{});
},
'Sage/TaskPane/nls/sq/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sq/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/sq/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/sq/ReportManagerFormatter',{});
},
'Sage/UI/nls/sq/OwnerType':function(){
define('Sage/UI/nls/sq/OwnerType',{});
},
'Sage/TaskPane/nls/sq/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sq/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sq/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sq/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sq/InvoiceRTDV',{});
},
'Sage/UI/nls/sq/SDataLookup':function(){
define('Sage/UI/nls/sq/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sq/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/RowDesigner',{});
},
'Sage/TaskPane/nls/sq/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sq/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sq/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sq/LibraryDocument':function(){
define('Sage/Utility/File/nls/sq/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sq/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sq/SpeedSearchLookup',{});
},
'Sage/UI/nls/sq/ConditionManager':function(){
define('Sage/UI/nls/sq/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sq/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sq/WidgetDefinition',{});
},
'Sage/UI/nls/sq/SearchConditionWidget':function(){
define('Sage/UI/nls/sq/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sq/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/sq/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sq/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sq/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/sq/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sq/DataSourcePanel',{});
},
'Sage/Library/nls/sq/Manager':function(){
define('Sage/Library/nls/sq/Manager',{});
},
'Sage/UI/nls/sq/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sq/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sq/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sq/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sq/Name':function(){
define('Sage/UI/Controls/nls/sq/Name',{});
},
'Sage/MainView/JobMgr/nls/sq/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sq/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sq/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sq/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sq/UpdateLeads',{});
},
'Sage/Library/nls/sq/FileHandler':function(){
define('Sage/Library/nls/sq/FileHandler',{});
},
'Sage/UI/nls/sq/ListPanel':function(){
define('Sage/UI/nls/sq/ListPanel',{});
},
'Sage/Utility/nls/sq/Sql':function(){
define('Sage/Utility/nls/sq/Sql',{});
},
'Sage/UI/Filters/nls/sq/EditFilters':function(){
define('Sage/UI/Filters/nls/sq/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sq/DurationSelect':function(){
define('Sage/UI/Controls/nls/sq/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sq/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sq/AlarmCountDown',{});
},
'Sage/UI/nls/sq/AttachmentList':function(){
define('Sage/UI/nls/sq/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sq/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/sq/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/sq/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sq/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sq/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sq/Dialogs':function(){
define('Sage/UI/nls/sq/Dialogs',{});
},
'Sage/TaskPane/nls/sq/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sq/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sq/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sq/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sq/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sq/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sq/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/UserControlDesigner',{});
},
'Sage/Groups/nls/sq/GroupNavigator':function(){
define('Sage/Groups/nls/sq/GroupNavigator',{});
},
'Sage/Utility/File/nls/sq/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sq/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sq/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sq/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/sq/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sq/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/sq/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sq/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sq/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sq/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/sq/ActivityScheduler':function(){
define('Sage/UI/nls/sq/ActivityScheduler',{});
},
'Sage/MainView/nls/sq/SecurityManager':function(){
define('Sage/MainView/nls/sq/SecurityManager',{});
},
'Sage/TaskPane/nls/sq/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sq/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sq/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sq/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/sq/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/sq/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/sq/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sq/UpdateOpportunities',{});
},
'Sage/UI/nls/sq/EditCalendarUsers':function(){
define('Sage/UI/nls/sq/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/sq/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sq/HelpMenu':function(){
define('Sage/UI/Controls/nls/sq/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sq/UserTasklet':function(){
define('Sage/TaskPane/nls/sq/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/sq/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sq/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sq/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sq/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sq/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sq/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sq/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/ColumnDesigner',{});
},
'Sage/UI/nls/sq/SearchMenuItem':function(){
define('Sage/UI/nls/sq/SearchMenuItem',{});
},
'Sage/Library/nls/sq/DocumentProperties':function(){
define('Sage/Library/nls/sq/DocumentProperties',{});
},
'Sage/UI/nls/sq/NotesHistoryList':function(){
define('Sage/UI/nls/sq/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/sq/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sq/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sq/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/sq/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/sq/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/sq/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/sq/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sq/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/sq/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sq/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sq/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sq/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sq/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/HistoryEditor',{});
},
'Sage/Groups/nls/sq/GroupManager':function(){
define('Sage/Groups/nls/sq/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sq/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sq/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/sq/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/sq/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/sq/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sq/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sq/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/sq/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sq/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sq/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/sq/FolderHandler':function(){
define('Sage/Library/nls/sq/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sq/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sq/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sq/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sq/EditableGrid':function(){
define('Sage/UI/nls/sq/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/sq/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sq/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/sq/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sq/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/sq/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/sq/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sq/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/sq/ReportManagerUtility',{});
},
'Sage/UI/nls/sq/SpeedSearch':function(){
define('Sage/UI/nls/sq/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/sq/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/sq/SLXPreviewGrid':function(){
define('Sage/UI/nls/sq/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sq/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sq/UnconfirmedPane',{});
},
'Sage/Utility/nls/sq/Utility':function(){
define('Sage/Utility/nls/sq/Utility',{});
},
'Sage/QuickForms/Design/nls/sq/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sq/Address':function(){
define('Sage/UI/Controls/nls/sq/Address',{});
},
'Sage/MainView/JobMgr/nls/sq/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/sq/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/sq/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sq/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/sq/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/sq/UserType':function(){
define('Sage/UI/nls/sq/UserType',{});
},
'Sage/QuickForms/Design/nls/sq/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityCalendar',{});
},
'Sage/Utility/nls/sq/Jobs':function(){
define('Sage/Utility/nls/sq/Jobs',{});
},
'Sage/UI/Controls/nls/sq/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sq/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sq/ActivityList':function(){
define('Sage/UI/nls/sq/ActivityList',{});
},
'Sage/UI/Alarms/nls/sq/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/sq/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sq/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sq/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/sq/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sq/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sq/CalendarUsersListPane':function(){
define('Sage/UI/nls/sq/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sq/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/sq/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/sq/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sq/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sq/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sq/Attachment':function(){
define('Sage/Utility/File/nls/sq/Attachment',{});
},
'Sage/QuickForms/Design/nls/sq/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sq/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sq/PropertyEditorContainer',{});
},
'Sage/Services/nls/sq/ReportingService':function(){
define('Sage/Services/nls/sq/ReportingService',{});
},
'Sage/MailMerge/nls/sq/Helper':function(){
define('Sage/MailMerge/nls/sq/Helper',{});
},
'Sage/UI/Dashboard/nls/sq/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sq/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sq/PickList':function(){
define('Sage/UI/Controls/nls/sq/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/sq/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sq/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/sq/Email':function(){
define('Sage/Utility/nls/sq/Email',{});
},
'Sage/TaskPane/nls/sq/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sq/TimeZoneItem':function(){
define('Sage/UI/nls/sq/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sq/SlxEdit':function(){
define('Sage/UI/Columns/nls/sq/SlxEdit',{});
},
'Sage/Reporting/nls/sq/Enumerations':function(){
define('Sage/Reporting/nls/sq/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sq/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sq/ActivityListPanelConfig',{});
},
'Sage/UI/nls/sq/JobSchedulingWidget':function(){
define('Sage/UI/nls/sq/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/sq/LogOffButton':function(){
define('Sage/UI/Controls/nls/sq/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sq/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sq/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/EditEventEditor',{});
},
'Sage/MailMerge/nls/sq/Loader':function(){
define('Sage/MailMerge/nls/sq/Loader',{});
},
'Sage/UI/Controls/nls/sq/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sq/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/sq/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/sq/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/sq/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sq/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/sq/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/sq/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sq/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sq/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sq/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sq/Lookup':function(){
define('Sage/UI/Controls/nls/sq/Lookup',{});
},
'Sage/Utility/File/nls/sq/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sq/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sq/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sq/Dashboard':function(){
define('Sage/Utility/nls/sq/Dashboard',{});
}}});
define("Sage/nls/Sage_sq", [], 1);
