require({cache:{
'Sage/Utility/File/nls/tr/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/tr/FallbackFilePicker',{});
},
'Sage/UI/nls/tr/Boolean':function(){
define('Sage/UI/nls/tr/Boolean',{});
},
'Sage/Services/nls/tr/ActivityService':function(){
define('Sage/Services/nls/tr/ActivityService',{});
},
'Sage/UI/Controls/nls/tr/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/tr/CopyToClipboard',{});
},
'Sage/Utility/nls/tr/Activity':function(){
define('Sage/Utility/nls/tr/Activity',{});
},
'Sage/QuickForms/Design/nls/tr/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/tr/DesignPanel',{});
},
'Sage/UI/nls/tr/TimelessActivitiesPane':function(){
define('Sage/UI/nls/tr/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/tr/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tr/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/tr/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/tr/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/tr/ActivityManager':function(){
define('Sage/MainView/nls/tr/ActivityManager',{});
},
'Sage/Services/nls/tr/JobService':function(){
define('Sage/Services/nls/tr/JobService',{});
},
'Sage/QuickForms/Design/nls/tr/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/_PropertyEditor',{});
},
'Sage/Services/nls/tr/ActivityActionProcessor':function(){
define('Sage/Services/nls/tr/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tr/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tr/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/tr/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/tr/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/tr/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/tr/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/tr/AlarmPane':function(){
define('Sage/UI/Alarms/nls/tr/AlarmPane',{});
},
'Sage/TaskPane/nls/tr/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/tr/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/tr/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/tr/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tr/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tr/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/tr/FilterPanel':function(){
define('Sage/UI/Filters/nls/tr/FilterPanel',{});
},
'Sage/TaskPane/nls/tr/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/tr/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/tr/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/tr/ReportManagerFormatter',{});
},
'Sage/UI/nls/tr/OwnerType':function(){
define('Sage/UI/nls/tr/OwnerType',{});
},
'Sage/TaskPane/nls/tr/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/tr/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/tr/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/tr/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tr/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tr/InvoiceRTDV',{});
},
'Sage/UI/nls/tr/SDataLookup':function(){
define('Sage/UI/nls/tr/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/tr/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/RowDesigner',{});
},
'Sage/TaskPane/nls/tr/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/tr/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/tr/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/tr/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/tr/LibraryDocument':function(){
define('Sage/Utility/File/nls/tr/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/tr/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/tr/SpeedSearchLookup',{});
},
'Sage/UI/nls/tr/ConditionManager':function(){
define('Sage/UI/nls/tr/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/tr/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/tr/WidgetDefinition',{});
},
'Sage/UI/nls/tr/SearchConditionWidget':function(){
define('Sage/UI/nls/tr/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/tr/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/tr/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/tr/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/tr/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/tr/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/tr/DataSourcePanel',{});
},
'Sage/Library/nls/tr/Manager':function(){
define('Sage/Library/nls/tr/Manager',{});
},
'Sage/UI/nls/tr/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/tr/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/tr/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/tr/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/tr/Name':function(){
define('Sage/UI/Controls/nls/tr/Name',{});
},
'Sage/MainView/JobMgr/nls/tr/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/tr/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/tr/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/tr/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/tr/UpdateLeads',{});
},
'Sage/Library/nls/tr/FileHandler':function(){
define('Sage/Library/nls/tr/FileHandler',{});
},
'Sage/UI/nls/tr/ListPanel':function(){
define('Sage/UI/nls/tr/ListPanel',{});
},
'Sage/Utility/nls/tr/Sql':function(){
define('Sage/Utility/nls/tr/Sql',{});
},
'Sage/UI/Filters/nls/tr/EditFilters':function(){
define('Sage/UI/Filters/nls/tr/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/tr/DurationSelect':function(){
define('Sage/UI/Controls/nls/tr/DurationSelect',{});
},
'Sage/UI/Alarms/nls/tr/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/tr/AlarmCountDown',{});
},
'Sage/UI/nls/tr/AttachmentList':function(){
define('Sage/UI/nls/tr/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/tr/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/tr/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/tr/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tr/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tr/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/tr/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/tr/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/tr/Dialogs':function(){
define('Sage/UI/nls/tr/Dialogs',{});
},
'Sage/TaskPane/nls/tr/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/tr/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/tr/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/tr/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/tr/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tr/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/tr/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/UserControlDesigner',{});
},
'Sage/Groups/nls/tr/GroupNavigator':function(){
define('Sage/Groups/nls/tr/GroupNavigator',{});
},
'Sage/Utility/File/nls/tr/AddURLAttachment':function(){
define('Sage/Utility/File/nls/tr/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/tr/EditFilterItems':function(){
define('Sage/UI/Filters/nls/tr/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/tr/DragDropWatcher':function(){
define('Sage/Utility/File/nls/tr/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/tr/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/tr/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/tr/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tr/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tr/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tr/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/tr/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/tr/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/tr/ActivityScheduler':function(){
define('Sage/UI/nls/tr/ActivityScheduler',{});
},
'Sage/MainView/nls/tr/SecurityManager':function(){
define('Sage/MainView/nls/tr/SecurityManager',{});
},
'Sage/TaskPane/nls/tr/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/tr/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/tr/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/tr/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/tr/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/tr/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/tr/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/tr/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/tr/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/tr/UpdateOpportunities',{});
},
'Sage/UI/nls/tr/EditCalendarUsers':function(){
define('Sage/UI/nls/tr/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/tr/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/tr/HelpMenu':function(){
define('Sage/UI/Controls/nls/tr/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/tr/UserTasklet':function(){
define('Sage/TaskPane/nls/tr/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/tr/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/tr/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/tr/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/tr/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tr/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/tr/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/tr/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/ColumnDesigner',{});
},
'Sage/UI/nls/tr/SearchMenuItem':function(){
define('Sage/UI/nls/tr/SearchMenuItem',{});
},
'Sage/Library/nls/tr/DocumentProperties':function(){
define('Sage/Library/nls/tr/DocumentProperties',{});
},
'Sage/UI/nls/tr/NotesHistoryList':function(){
define('Sage/UI/nls/tr/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/tr/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/tr/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/tr/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/tr/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/tr/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/tr/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/tr/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/tr/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/tr/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/tr/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/tr/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/tr/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/tr/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tr/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/tr/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tr/HistoryEditor',{});
},
'Sage/Groups/nls/tr/GroupManager':function(){
define('Sage/Groups/nls/tr/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/tr/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/tr/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/tr/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/tr/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/tr/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/tr/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/tr/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tr/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/tr/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/tr/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/tr/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tr/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tr/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/tr/FolderHandler':function(){
define('Sage/Library/nls/tr/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/tr/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/tr/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/tr/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/tr/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/tr/EditableGrid':function(){
define('Sage/UI/nls/tr/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/tr/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tr/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/tr/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/tr/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/tr/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/tr/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/tr/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/tr/ReportManagerUtility',{});
},
'Sage/UI/nls/tr/SpeedSearch':function(){
define('Sage/UI/nls/tr/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/tr/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/tr/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/tr/SLXPreviewGrid':function(){
define('Sage/UI/nls/tr/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/tr/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/tr/UnconfirmedPane',{});
},
'Sage/Utility/nls/tr/Utility':function(){
define('Sage/Utility/nls/tr/Utility',{});
},
'Sage/QuickForms/Design/nls/tr/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/ControlDesigner',{});
},
'Sage/UI/Controls/nls/tr/Address':function(){
define('Sage/UI/Controls/nls/tr/Address',{});
},
'Sage/MainView/JobMgr/nls/tr/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/tr/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/tr/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tr/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/tr/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/tr/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/tr/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/tr/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/tr/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/tr/UserType':function(){
define('Sage/UI/nls/tr/UserType',{});
},
'Sage/QuickForms/Design/nls/tr/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/tr/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/tr/ActivityCalendar',{});
},
'Sage/Utility/nls/tr/Jobs':function(){
define('Sage/Utility/nls/tr/Jobs',{});
},
'Sage/UI/Controls/nls/tr/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/tr/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/tr/ActivityList':function(){
define('Sage/UI/nls/tr/ActivityList',{});
},
'Sage/UI/Alarms/nls/tr/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/tr/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/tr/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/tr/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/tr/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/tr/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/tr/CalendarUsersListPane':function(){
define('Sage/UI/nls/tr/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/tr/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/tr/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/tr/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/tr/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tr/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/tr/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/tr/Attachment':function(){
define('Sage/Utility/File/nls/tr/Attachment',{});
},
'Sage/QuickForms/Design/nls/tr/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/tr/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/tr/PropertyEditorContainer',{});
},
'Sage/Services/nls/tr/ReportingService':function(){
define('Sage/Services/nls/tr/ReportingService',{});
},
'Sage/MailMerge/nls/tr/Helper':function(){
define('Sage/MailMerge/nls/tr/Helper',{});
},
'Sage/UI/Dashboard/nls/tr/Dashboard':function(){
define('Sage/UI/Dashboard/nls/tr/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/tr/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tr/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/tr/PickList':function(){
define('Sage/UI/Controls/nls/tr/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/tr/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/tr/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/tr/Email':function(){
define('Sage/Utility/nls/tr/Email',{});
},
'Sage/TaskPane/nls/tr/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/tr/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/tr/TimeZoneItem':function(){
define('Sage/UI/nls/tr/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/tr/SlxEdit':function(){
define('Sage/UI/Columns/nls/tr/SlxEdit',{});
},
'Sage/Reporting/nls/tr/Enumerations':function(){
define('Sage/Reporting/nls/tr/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/tr/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/tr/ActivityListPanelConfig',{});
},
'Sage/UI/nls/tr/JobSchedulingWidget':function(){
define('Sage/UI/nls/tr/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/tr/LogOffButton':function(){
define('Sage/UI/Controls/nls/tr/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/tr/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/tr/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tr/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tr/EditEventEditor',{});
},
'Sage/MailMerge/nls/tr/Loader':function(){
define('Sage/MailMerge/nls/tr/Loader',{});
},
'Sage/UI/Controls/nls/tr/DateTimePicker':function(){
define('Sage/UI/Controls/nls/tr/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/tr/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/tr/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/tr/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/tr/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/tr/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/tr/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/tr/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/tr/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/tr/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tr/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tr/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/tr/Lookup':function(){
define('Sage/UI/Controls/nls/tr/Lookup',{});
},
'Sage/Utility/File/nls/tr/DescriptionsForm':function(){
define('Sage/Utility/File/nls/tr/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/tr/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tr/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/tr/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/tr/CommonTasksTasklet',{});
},
'Sage/Utility/nls/tr/Dashboard':function(){
define('Sage/Utility/nls/tr/Dashboard',{});
}}});
define("Sage/nls/Sage_tr", [], 1);
