require({cache:{
'Sage/Utility/File/nls/cs/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/cs/FallbackFilePicker',{});
},
'Sage/UI/nls/cs/Boolean':function(){
define('Sage/UI/nls/cs/Boolean',{});
},
'Sage/Services/nls/cs/ActivityService':function(){
define('Sage/Services/nls/cs/ActivityService',{});
},
'Sage/UI/Controls/nls/cs/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/cs/CopyToClipboard',{});
},
'Sage/Utility/nls/cs/Activity':function(){
define('Sage/Utility/nls/cs/Activity',{});
},
'Sage/QuickForms/Design/nls/cs/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/cs/DesignPanel',{});
},
'Sage/UI/nls/cs/TimelessActivitiesPane':function(){
define('Sage/UI/nls/cs/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/cs/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/cs/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/cs/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/cs/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/cs/ActivityManager':function(){
define('Sage/MainView/nls/cs/ActivityManager',{});
},
'Sage/Services/nls/cs/JobService':function(){
define('Sage/Services/nls/cs/JobService',{});
},
'Sage/QuickForms/Design/nls/cs/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/_PropertyEditor',{});
},
'Sage/Services/nls/cs/ActivityActionProcessor':function(){
define('Sage/Services/nls/cs/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/cs/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/cs/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/cs/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/cs/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/cs/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/cs/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/cs/AlarmPane':function(){
define('Sage/UI/Alarms/nls/cs/AlarmPane',{});
},
'Sage/TaskPane/nls/cs/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/cs/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/cs/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/cs/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/cs/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/cs/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/cs/FilterPanel':function(){
define('Sage/UI/Filters/nls/cs/FilterPanel',{});
},
'Sage/TaskPane/nls/cs/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/cs/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/cs/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/cs/ReportManagerFormatter',{});
},
'Sage/UI/nls/cs/OwnerType':function(){
define('Sage/UI/nls/cs/OwnerType',{});
},
'Sage/TaskPane/nls/cs/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/cs/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/cs/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/cs/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/cs/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/cs/InvoiceRTDV',{});
},
'Sage/UI/nls/cs/SDataLookup':function(){
define('Sage/UI/nls/cs/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/cs/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/RowDesigner',{});
},
'Sage/TaskPane/nls/cs/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/cs/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/cs/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/cs/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/cs/LibraryDocument':function(){
define('Sage/Utility/File/nls/cs/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/cs/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/cs/SpeedSearchLookup',{});
},
'Sage/UI/nls/cs/ConditionManager':function(){
define('Sage/UI/nls/cs/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/cs/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/cs/WidgetDefinition',{});
},
'Sage/UI/nls/cs/SearchConditionWidget':function(){
define('Sage/UI/nls/cs/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/cs/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/cs/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/cs/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/cs/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/cs/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/cs/DataSourcePanel',{});
},
'Sage/Library/nls/cs/Manager':function(){
define('Sage/Library/nls/cs/Manager',{});
},
'Sage/UI/nls/cs/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/cs/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/cs/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/cs/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/cs/Name':function(){
define('Sage/UI/Controls/nls/cs/Name',{});
},
'Sage/MainView/JobMgr/nls/cs/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/cs/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/cs/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/cs/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/cs/UpdateLeads',{});
},
'Sage/Library/nls/cs/FileHandler':function(){
define('Sage/Library/nls/cs/FileHandler',{});
},
'Sage/UI/nls/cs/ListPanel':function(){
define('Sage/UI/nls/cs/ListPanel',{});
},
'Sage/Utility/nls/cs/Sql':function(){
define('Sage/Utility/nls/cs/Sql',{});
},
'Sage/UI/Filters/nls/cs/EditFilters':function(){
define('Sage/UI/Filters/nls/cs/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/cs/DurationSelect':function(){
define('Sage/UI/Controls/nls/cs/DurationSelect',{});
},
'Sage/UI/Alarms/nls/cs/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/cs/AlarmCountDown',{});
},
'Sage/UI/nls/cs/AttachmentList':function(){
define('Sage/UI/nls/cs/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/cs/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/cs/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/cs/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/cs/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/cs/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/cs/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/cs/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/cs/Dialogs':function(){
define('Sage/UI/nls/cs/Dialogs',{});
},
'Sage/TaskPane/nls/cs/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/cs/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/cs/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/cs/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/cs/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/cs/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/cs/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/UserControlDesigner',{});
},
'Sage/Groups/nls/cs/GroupNavigator':function(){
define('Sage/Groups/nls/cs/GroupNavigator',{});
},
'Sage/Utility/File/nls/cs/AddURLAttachment':function(){
define('Sage/Utility/File/nls/cs/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/cs/EditFilterItems':function(){
define('Sage/UI/Filters/nls/cs/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/cs/DragDropWatcher':function(){
define('Sage/Utility/File/nls/cs/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/cs/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/cs/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/cs/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/cs/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/cs/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/cs/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/cs/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/cs/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/cs/ActivityScheduler':function(){
define('Sage/UI/nls/cs/ActivityScheduler',{});
},
'Sage/MainView/nls/cs/SecurityManager':function(){
define('Sage/MainView/nls/cs/SecurityManager',{});
},
'Sage/TaskPane/nls/cs/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/cs/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/cs/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/cs/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/cs/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/cs/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/cs/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/cs/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/cs/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/cs/UpdateOpportunities',{});
},
'Sage/UI/nls/cs/EditCalendarUsers':function(){
define('Sage/UI/nls/cs/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/cs/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/cs/HelpMenu':function(){
define('Sage/UI/Controls/nls/cs/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/cs/UserTasklet':function(){
define('Sage/TaskPane/nls/cs/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/cs/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/cs/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/cs/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/cs/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/cs/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/cs/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/cs/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/ColumnDesigner',{});
},
'Sage/UI/nls/cs/SearchMenuItem':function(){
define('Sage/UI/nls/cs/SearchMenuItem',{});
},
'Sage/Library/nls/cs/DocumentProperties':function(){
define('Sage/Library/nls/cs/DocumentProperties',{});
},
'Sage/UI/nls/cs/NotesHistoryList':function(){
define('Sage/UI/nls/cs/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/cs/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/cs/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/cs/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/cs/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/cs/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/cs/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/cs/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/cs/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/cs/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/cs/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/cs/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/cs/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/cs/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/cs/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/cs/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/cs/HistoryEditor',{});
},
'Sage/Groups/nls/cs/GroupManager':function(){
define('Sage/Groups/nls/cs/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/cs/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/cs/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/cs/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/cs/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/cs/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/cs/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/cs/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/cs/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/cs/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/cs/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/cs/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/cs/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/cs/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/cs/FolderHandler':function(){
define('Sage/Library/nls/cs/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/cs/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/cs/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/cs/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/cs/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/cs/EditableGrid':function(){
define('Sage/UI/nls/cs/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/cs/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/cs/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/cs/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/cs/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/cs/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/cs/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/cs/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/cs/ReportManagerUtility',{});
},
'Sage/UI/nls/cs/SpeedSearch':function(){
define('Sage/UI/nls/cs/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/cs/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/cs/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/cs/SLXPreviewGrid':function(){
define('Sage/UI/nls/cs/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/cs/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/cs/UnconfirmedPane',{});
},
'Sage/Utility/nls/cs/Utility':function(){
define('Sage/Utility/nls/cs/Utility',{});
},
'Sage/QuickForms/Design/nls/cs/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/ControlDesigner',{});
},
'Sage/UI/Controls/nls/cs/Address':function(){
define('Sage/UI/Controls/nls/cs/Address',{});
},
'Sage/MainView/JobMgr/nls/cs/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/cs/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/cs/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/cs/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/cs/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/cs/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/cs/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/cs/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/cs/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/cs/UserType':function(){
define('Sage/UI/nls/cs/UserType',{});
},
'Sage/QuickForms/Design/nls/cs/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/cs/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/cs/ActivityCalendar',{});
},
'Sage/Utility/nls/cs/Jobs':function(){
define('Sage/Utility/nls/cs/Jobs',{});
},
'Sage/UI/Controls/nls/cs/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/cs/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/cs/ActivityList':function(){
define('Sage/UI/nls/cs/ActivityList',{});
},
'Sage/UI/Alarms/nls/cs/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/cs/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/cs/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/cs/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/cs/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/cs/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/cs/CalendarUsersListPane':function(){
define('Sage/UI/nls/cs/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/cs/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/cs/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/cs/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/cs/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/cs/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/cs/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/cs/Attachment':function(){
define('Sage/Utility/File/nls/cs/Attachment',{});
},
'Sage/QuickForms/Design/nls/cs/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/cs/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/cs/PropertyEditorContainer',{});
},
'Sage/Services/nls/cs/ReportingService':function(){
define('Sage/Services/nls/cs/ReportingService',{});
},
'Sage/MailMerge/nls/cs/Helper':function(){
define('Sage/MailMerge/nls/cs/Helper',{});
},
'Sage/UI/Dashboard/nls/cs/Dashboard':function(){
define('Sage/UI/Dashboard/nls/cs/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/cs/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/cs/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/cs/PickList':function(){
define('Sage/UI/Controls/nls/cs/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/cs/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/cs/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/cs/Email':function(){
define('Sage/Utility/nls/cs/Email',{});
},
'Sage/TaskPane/nls/cs/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/cs/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/cs/TimeZoneItem':function(){
define('Sage/UI/nls/cs/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/cs/SlxEdit':function(){
define('Sage/UI/Columns/nls/cs/SlxEdit',{});
},
'Sage/Reporting/nls/cs/Enumerations':function(){
define('Sage/Reporting/nls/cs/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/cs/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/cs/ActivityListPanelConfig',{});
},
'Sage/UI/nls/cs/JobSchedulingWidget':function(){
define('Sage/UI/nls/cs/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/cs/LogOffButton':function(){
define('Sage/UI/Controls/nls/cs/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/cs/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/cs/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/cs/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/cs/EditEventEditor',{});
},
'Sage/MailMerge/nls/cs/Loader':function(){
define('Sage/MailMerge/nls/cs/Loader',{});
},
'Sage/UI/Controls/nls/cs/DateTimePicker':function(){
define('Sage/UI/Controls/nls/cs/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/cs/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/cs/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/cs/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/cs/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/cs/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/cs/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/cs/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/cs/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/cs/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/cs/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/cs/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/cs/Lookup':function(){
define('Sage/UI/Controls/nls/cs/Lookup',{});
},
'Sage/Utility/File/nls/cs/DescriptionsForm':function(){
define('Sage/Utility/File/nls/cs/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/cs/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/cs/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/cs/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/cs/CommonTasksTasklet',{});
},
'Sage/Utility/nls/cs/Dashboard':function(){
define('Sage/Utility/nls/cs/Dashboard',{});
}}});
define("Sage/nls/Sage_cs", [], 1);
