require({cache:{
'Sage/Utility/File/nls/th/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/th/FallbackFilePicker',{});
},
'Sage/UI/nls/th/Boolean':function(){
define('Sage/UI/nls/th/Boolean',{});
},
'Sage/Services/nls/th/ActivityService':function(){
define('Sage/Services/nls/th/ActivityService',{});
},
'Sage/UI/Controls/nls/th/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/th/CopyToClipboard',{});
},
'Sage/Utility/nls/th/Activity':function(){
define('Sage/Utility/nls/th/Activity',{});
},
'Sage/QuickForms/Design/nls/th/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/th/DesignPanel',{});
},
'Sage/UI/nls/th/TimelessActivitiesPane':function(){
define('Sage/UI/nls/th/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/th/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/th/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/th/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/th/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/th/ActivityManager':function(){
define('Sage/MainView/nls/th/ActivityManager',{});
},
'Sage/Services/nls/th/JobService':function(){
define('Sage/Services/nls/th/JobService',{});
},
'Sage/QuickForms/Design/nls/th/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/th/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/_PropertyEditor',{});
},
'Sage/Services/nls/th/ActivityActionProcessor':function(){
define('Sage/Services/nls/th/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/th/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/th/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/th/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/th/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/th/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/th/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/th/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/th/AlarmPane':function(){
define('Sage/UI/Alarms/nls/th/AlarmPane',{});
},
'Sage/TaskPane/nls/th/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/th/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/th/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/th/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/th/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/th/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/th/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/th/FilterPanel':function(){
define('Sage/UI/Filters/nls/th/FilterPanel',{});
},
'Sage/TaskPane/nls/th/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/th/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/th/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/th/ReportManagerFormatter',{});
},
'Sage/UI/nls/th/OwnerType':function(){
define('Sage/UI/nls/th/OwnerType',{});
},
'Sage/TaskPane/nls/th/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/th/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/th/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/th/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/th/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/th/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/th/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/th/InvoiceRTDV',{});
},
'Sage/UI/nls/th/SDataLookup':function(){
define('Sage/UI/nls/th/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/th/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/th/RowDesigner',{});
},
'Sage/TaskPane/nls/th/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/th/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/th/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/th/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/th/LibraryDocument':function(){
define('Sage/Utility/File/nls/th/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/th/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/th/SpeedSearchLookup',{});
},
'Sage/UI/nls/th/ConditionManager':function(){
define('Sage/UI/nls/th/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/th/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/th/WidgetDefinition',{});
},
'Sage/UI/nls/th/SearchConditionWidget':function(){
define('Sage/UI/nls/th/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/th/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/th/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/th/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/th/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/th/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/th/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/th/DataSourcePanel',{});
},
'Sage/Library/nls/th/Manager':function(){
define('Sage/Library/nls/th/Manager',{});
},
'Sage/UI/nls/th/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/th/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/th/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/th/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/th/Name':function(){
define('Sage/UI/Controls/nls/th/Name',{});
},
'Sage/MainView/JobMgr/nls/th/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/th/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/th/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/th/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/th/UpdateLeads',{});
},
'Sage/Library/nls/th/FileHandler':function(){
define('Sage/Library/nls/th/FileHandler',{});
},
'Sage/UI/nls/th/ListPanel':function(){
define('Sage/UI/nls/th/ListPanel',{});
},
'Sage/Utility/nls/th/Sql':function(){
define('Sage/Utility/nls/th/Sql',{});
},
'Sage/UI/Filters/nls/th/EditFilters':function(){
define('Sage/UI/Filters/nls/th/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/th/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/th/DurationSelect':function(){
define('Sage/UI/Controls/nls/th/DurationSelect',{});
},
'Sage/UI/Alarms/nls/th/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/th/AlarmCountDown',{});
},
'Sage/UI/nls/th/AttachmentList':function(){
define('Sage/UI/nls/th/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/th/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/th/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/th/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/th/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/th/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/th/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/th/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/th/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/th/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/th/Dialogs':function(){
define('Sage/UI/nls/th/Dialogs',{});
},
'Sage/TaskPane/nls/th/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/th/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/th/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/th/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/th/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/th/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/th/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/UserControlDesigner',{});
},
'Sage/Groups/nls/th/GroupNavigator':function(){
define('Sage/Groups/nls/th/GroupNavigator',{});
},
'Sage/Utility/File/nls/th/AddURLAttachment':function(){
define('Sage/Utility/File/nls/th/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/th/EditFilterItems':function(){
define('Sage/UI/Filters/nls/th/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/th/DragDropWatcher':function(){
define('Sage/Utility/File/nls/th/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/th/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/th/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/th/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/th/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/th/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/th/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/th/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/th/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/th/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/th/ActivityScheduler':function(){
define('Sage/UI/nls/th/ActivityScheduler',{});
},
'Sage/MainView/nls/th/SecurityManager':function(){
define('Sage/MainView/nls/th/SecurityManager',{});
},
'Sage/TaskPane/nls/th/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/th/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/th/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/th/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/th/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/th/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/th/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/th/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/th/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/th/UpdateOpportunities',{});
},
'Sage/UI/nls/th/EditCalendarUsers':function(){
define('Sage/UI/nls/th/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/th/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/th/HelpMenu':function(){
define('Sage/UI/Controls/nls/th/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/th/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/th/UserTasklet':function(){
define('Sage/TaskPane/nls/th/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/th/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/th/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/th/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/th/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/th/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/th/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/th/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/th/ColumnDesigner',{});
},
'Sage/UI/nls/th/SearchMenuItem':function(){
define('Sage/UI/nls/th/SearchMenuItem',{});
},
'Sage/Library/nls/th/DocumentProperties':function(){
define('Sage/Library/nls/th/DocumentProperties',{});
},
'Sage/UI/nls/th/NotesHistoryList':function(){
define('Sage/UI/nls/th/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/th/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/th/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/th/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/th/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/th/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/th/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/th/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/th/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/th/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/th/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/th/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/th/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/th/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/th/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/th/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/th/HistoryEditor',{});
},
'Sage/Groups/nls/th/GroupManager':function(){
define('Sage/Groups/nls/th/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/th/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/th/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/th/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/th/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/th/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/th/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/th/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/th/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/th/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/th/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/th/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/th/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/th/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/th/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/th/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/th/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/th/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/th/FolderHandler':function(){
define('Sage/Library/nls/th/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/th/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/th/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/th/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/th/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/th/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/th/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/th/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/th/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/th/EditableGrid':function(){
define('Sage/UI/nls/th/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/th/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/th/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/th/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/th/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/th/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/th/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/th/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/th/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/th/ReportManagerUtility',{});
},
'Sage/UI/nls/th/SpeedSearch':function(){
define('Sage/UI/nls/th/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/th/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/th/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/th/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/th/SLXPreviewGrid':function(){
define('Sage/UI/nls/th/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/th/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/th/UnconfirmedPane',{});
},
'Sage/Utility/nls/th/Utility':function(){
define('Sage/Utility/nls/th/Utility',{});
},
'Sage/QuickForms/Design/nls/th/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/ControlDesigner',{});
},
'Sage/UI/Controls/nls/th/Address':function(){
define('Sage/UI/Controls/nls/th/Address',{});
},
'Sage/MainView/JobMgr/nls/th/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/th/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/th/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/th/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/th/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/th/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/th/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/th/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/th/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/th/UserType':function(){
define('Sage/UI/nls/th/UserType',{});
},
'Sage/QuickForms/Design/nls/th/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/th/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/th/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/th/ActivityCalendar',{});
},
'Sage/Utility/nls/th/Jobs':function(){
define('Sage/Utility/nls/th/Jobs',{});
},
'Sage/UI/Controls/nls/th/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/th/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/th/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/th/ActivityList':function(){
define('Sage/UI/nls/th/ActivityList',{});
},
'Sage/UI/Alarms/nls/th/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/th/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/th/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/th/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/th/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/th/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/th/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/th/CalendarUsersListPane':function(){
define('Sage/UI/nls/th/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/th/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/th/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/th/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/th/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/th/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/th/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/th/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/th/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/th/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/th/Attachment':function(){
define('Sage/Utility/File/nls/th/Attachment',{});
},
'Sage/QuickForms/Design/nls/th/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/th/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/th/PropertyEditorContainer',{});
},
'Sage/Services/nls/th/ReportingService':function(){
define('Sage/Services/nls/th/ReportingService',{});
},
'Sage/MailMerge/nls/th/Helper':function(){
define('Sage/MailMerge/nls/th/Helper',{});
},
'Sage/UI/Dashboard/nls/th/Dashboard':function(){
define('Sage/UI/Dashboard/nls/th/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/th/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/th/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/th/PickList':function(){
define('Sage/UI/Controls/nls/th/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/th/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/th/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/th/Email':function(){
define('Sage/Utility/nls/th/Email',{});
},
'Sage/TaskPane/nls/th/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/th/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/th/TimeZoneItem':function(){
define('Sage/UI/nls/th/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/th/SlxEdit':function(){
define('Sage/UI/Columns/nls/th/SlxEdit',{});
},
'Sage/Reporting/nls/th/Enumerations':function(){
define('Sage/Reporting/nls/th/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/th/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/th/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/th/ActivityListPanelConfig',{});
},
'Sage/UI/nls/th/JobSchedulingWidget':function(){
define('Sage/UI/nls/th/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/th/LogOffButton':function(){
define('Sage/UI/Controls/nls/th/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/th/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/th/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/th/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/th/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/th/EditEventEditor',{});
},
'Sage/MailMerge/nls/th/Loader':function(){
define('Sage/MailMerge/nls/th/Loader',{});
},
'Sage/UI/Controls/nls/th/DateTimePicker':function(){
define('Sage/UI/Controls/nls/th/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/th/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/th/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/th/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/th/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/th/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/th/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/th/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/th/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/th/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/th/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/th/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/th/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/th/Lookup':function(){
define('Sage/UI/Controls/nls/th/Lookup',{});
},
'Sage/Utility/File/nls/th/DescriptionsForm':function(){
define('Sage/Utility/File/nls/th/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/th/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/th/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/th/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/th/CommonTasksTasklet',{});
},
'Sage/Utility/nls/th/Dashboard':function(){
define('Sage/Utility/nls/th/Dashboard',{});
}}});
define("Sage/nls/Sage_th", [], 1);
