require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-co/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-co/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-co/Boolean':function(){
define('Sage/UI/nls/es-co/Boolean',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-co/ActivityService':function(){
define('Sage/Services/nls/es-co/ActivityService',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-co/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-co/CopyToClipboard',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-co/Activity':function(){
define('Sage/Utility/nls/es-co/Activity',{});
},
'Sage/QuickForms/Design/nls/es/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/es-co/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/es-co/DesignPanel',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-co/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-co/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/es/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es/ContactUserAssociationEditor',{});
},
'Sage/TaskPane/User/nls/es-co/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/es-co/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-co/ActivityManager':function(){
define('Sage/MainView/nls/es-co/ActivityManager',{});
},
'Sage/Services/nls/es/JobService':function(){
define('Sage/Services/nls/es/JobService',{});
},
'Sage/Services/nls/es-co/JobService':function(){
define('Sage/Services/nls/es-co/JobService',{});
},
'Sage/QuickForms/Design/nls/es/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/_PropertyEditor',{});
},
'Sage/Services/nls/es/ActivityActionProcessor':function(){
define('Sage/Services/nls/es/ActivityActionProcessor',{});
},
'Sage/Services/nls/es-co/ActivityActionProcessor':function(){
define('Sage/Services/nls/es-co/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-co/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-co/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-co/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-co/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-co/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-co/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-co/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-co/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-co/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-co/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-co/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-co/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-co/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-co/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-co/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-co/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerFormatter',{});
},
'Sage/MainView/ReportMgr/nls/es-co/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/es-co/ReportManagerFormatter',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-co/OwnerType':function(){
define('Sage/UI/nls/es-co/OwnerType',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-co/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-co/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-co/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-co/InvoiceRTDV',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-co/SDataLookup':function(){
define('Sage/UI/nls/es-co/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/es/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/RowDesigner',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-co/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-co/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-co/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-co/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-co/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-co/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/SpeedSearchLookup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-co/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-co/SpeedSearchLookup',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-co/ConditionManager':function(){
define('Sage/UI/nls/es-co/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-co/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-co/WidgetDefinition',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-co/SearchConditionWidget':function(){
define('Sage/UI/nls/es-co/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerActions',{});
},
'Sage/MainView/JobMgr/nls/es-co/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/es-co/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/ContactLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-co/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-co/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/es/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/es-co/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/es-co/DataSourcePanel',{});
},
'Sage/Library/nls/es/Manager':function(){
define('Sage/Library/nls/es/Manager',{});
},
'Sage/Library/nls/es-co/Manager':function(){
define('Sage/Library/nls/es-co/Manager',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-co/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-co/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/es/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/es-co/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/es-co/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-co/Name':function(){
define('Sage/UI/Controls/nls/es-co/Name',{});
},
'Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/ExecutionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-co/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-co/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-co/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-co/UpdateLeads',{});
},
'Sage/Library/nls/es/FileHandler':function(){
define('Sage/Library/nls/es/FileHandler',{});
},
'Sage/Library/nls/es-co/FileHandler':function(){
define('Sage/Library/nls/es-co/FileHandler',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-co/ListPanel':function(){
define('Sage/UI/nls/es-co/ListPanel',{});
},
'Sage/Utility/nls/es/Sql':function(){
define('Sage/Utility/nls/es/Sql',{});
},
'Sage/Utility/nls/es-co/Sql':function(){
define('Sage/Utility/nls/es-co/Sql',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-co/EditFilters':function(){
define('Sage/UI/Filters/nls/es-co/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-co/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-co/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-co/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-co/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-co/AttachmentList':function(){
define('Sage/UI/nls/es-co/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es/RunJobDialog',{});
},
'Sage/MainView/JobMgr/nls/es-co/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/es-co/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-co/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-co/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/es/Dialogs':function(){
define('Sage/UI/nls/es/Dialogs',{});
},
'Sage/UI/nls/es-co/Dialogs':function(){
define('Sage/UI/nls/es-co/Dialogs',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-co/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-co/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-co/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-co/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-co/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-co/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/es/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/UserControlDesigner',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-co/GroupNavigator':function(){
define('Sage/Groups/nls/es-co/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-co/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-co/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-co/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-co/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsFormatter',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/es/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es/DragDropWatcher',{});
},
'Sage/Utility/File/nls/es-co/DragDropWatcher':function(){
define('Sage/Utility/File/nls/es-co/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/es/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/es-co/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/es-co/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/AllOpenListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-co/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-co/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectNumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-co/ActivityScheduler':function(){
define('Sage/UI/nls/es-co/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-co/SecurityManager':function(){
define('Sage/MainView/nls/es-co/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-co/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-co/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/es/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/es-co/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/es-co/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/ExportOptionsDialog',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-co/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-co/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-co/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-co/UpdateOpportunities',{});
},
'Sage/UI/nls/es/EditCalendarUsers':function(){
define('Sage/UI/nls/es/EditCalendarUsers',{});
},
'Sage/UI/nls/es-co/EditCalendarUsers':function(){
define('Sage/UI/nls/es-co/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportParametersDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-co/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-co/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-co/UserTasklet':function(){
define('Sage/TaskPane/nls/es-co/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/NumberParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-co/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-co/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-co/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-co/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/es-co/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/es-co/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/es/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/ColumnDesigner',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-co/SearchMenuItem':function(){
define('Sage/UI/nls/es-co/SearchMenuItem',{});
},
'Sage/Library/nls/es/DocumentProperties':function(){
define('Sage/Library/nls/es/DocumentProperties',{});
},
'Sage/Library/nls/es-co/DocumentProperties':function(){
define('Sage/Library/nls/es-co/DocumentProperties',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-co/NotesHistoryList':function(){
define('Sage/UI/nls/es-co/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-co/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-co/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/BooleanParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/es/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ContactTasksTasklet',{});
},
'Sage/TaskPane/nls/es-co/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/es-co/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es/_WizardDialogBase',{});
},
'Sage/MainView/ReportMgr/Common/nls/es-co/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/es-co/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-co/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-co/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-co/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-co/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-co/GroupManager':function(){
define('Sage/Groups/nls/es-co/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportsListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-co/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-co/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationButton',{});
},
'Sage/UI/Alarms/nls/es-co/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/es-co/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportWizardController',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-co/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-co/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportsUtility',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-co/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-co/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/DateParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/es/FolderHandler':function(){
define('Sage/Library/nls/es/FolderHandler',{});
},
'Sage/Library/nls/es-co/FolderHandler':function(){
define('Sage/Library/nls/es-co/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-co/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-co/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-co/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-co/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-co/EditableGrid':function(){
define('Sage/UI/nls/es-co/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es/SalesQuoteRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/es-co/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/es-co/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/es/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/es-co/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/es-co/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportWizardController',{});
},
'Sage/MainView/ReportMgr/nls/es-co/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/es-co/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerUtility',{});
},
'Sage/MainView/ReportMgr/nls/es-co/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/es-co/ReportManagerUtility',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-co/SpeedSearch':function(){
define('Sage/UI/nls/es-co/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/es/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/ReportManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-co/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-co/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-co/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-co/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-co/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-co/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-co/Utility':function(){
define('Sage/Utility/nls/es-co/Utility',{});
},
'Sage/QuickForms/Design/nls/es/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/ControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-co/Address':function(){
define('Sage/UI/Controls/nls/es-co/Address',{});
},
'Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es/JobManagerGroupContextService',{});
},
'Sage/MainView/JobMgr/nls/es-co/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/es-co/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/es/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/JobManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-co/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-co/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-co/UserType':function(){
define('Sage/UI/nls/es-co/UserType',{});
},
'Sage/QuickForms/Design/nls/es/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/ActivityCalendar',{});
},
'Sage/Utility/nls/es/Jobs':function(){
define('Sage/Utility/nls/es/Jobs',{});
},
'Sage/Utility/nls/es-co/Jobs':function(){
define('Sage/Utility/nls/es-co/Jobs',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-co/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-co/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-co/ActivityList':function(){
define('Sage/UI/nls/es-co/ActivityList',{});
},
'Sage/UI/Alarms/nls/es/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es/JobNotificationPopup',{});
},
'Sage/UI/Alarms/nls/es-co/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/es-co/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es/LeadLookupConfig',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-co/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/es-co/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es/SchedulesListPanelConfig',{});
},
'Sage/MainView/ReportMgr/nls/es-co/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/es-co/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-co/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-co/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerGroupContextService',{});
},
'Sage/MainView/ReportMgr/nls/es-co/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/es-co/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/es-co/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/es-co/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-co/Attachment':function(){
define('Sage/Utility/File/nls/es-co/Attachment',{});
},
'Sage/QuickForms/Design/nls/es/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/StringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/es/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/es-co/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/es-co/PropertyEditorContainer',{});
},
'Sage/Services/nls/es/ReportingService':function(){
define('Sage/Services/nls/es/ReportingService',{});
},
'Sage/Services/nls/es-co/ReportingService':function(){
define('Sage/Services/nls/es-co/ReportingService',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-co/Helper':function(){
define('Sage/MailMerge/nls/es-co/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-co/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-co/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-co/PickList':function(){
define('Sage/UI/Controls/nls/es-co/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditorAttendeesTab',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-co/Email':function(){
define('Sage/Utility/nls/es-co/Email',{});
},
'Sage/TaskPane/nls/es/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/es-co/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/es-co/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-co/TimeZoneItem':function(){
define('Sage/UI/nls/es-co/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-co/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-co/SlxEdit',{});
},
'Sage/Reporting/nls/es/Enumerations':function(){
define('Sage/Reporting/nls/es/Enumerations',{});
},
'Sage/Reporting/nls/es-co/Enumerations':function(){
define('Sage/Reporting/nls/es-co/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/CrystalReportConditionsDialog',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es/ActivityListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/es-co/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/es-co/ActivityListPanelConfig',{});
},
'Sage/UI/nls/es/JobSchedulingWidget':function(){
define('Sage/UI/nls/es/JobSchedulingWidget',{});
},
'Sage/UI/nls/es-co/JobSchedulingWidget':function(){
define('Sage/UI/nls/es-co/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-co/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-co/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/es-co/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/es-co/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-co/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-co/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-co/Loader':function(){
define('Sage/MailMerge/nls/es-co/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-co/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-co/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/es/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es/ReportManagerActions',{});
},
'Sage/MainView/ReportMgr/nls/es-co/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/es-co/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-co/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-co/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/es/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es/ContactUserAssociationEditor',{});
},
'Sage/MainView/Contact/nls/es-co/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/es-co/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/JobMgr/nls/es-co/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/es-co/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/es/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/es-co/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/es-co/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-co/Lookup':function(){
define('Sage/UI/Controls/nls/es-co/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-co/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-co/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/es-co/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/es-co/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-co/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-co/CommonTasksTasklet',{});
},
'Sage/Utility/nls/es/Dashboard':function(){
define('Sage/Utility/nls/es/Dashboard',{});
},
'Sage/Utility/nls/es-co/Dashboard':function(){
define('Sage/Utility/nls/es-co/Dashboard',{});
}}});
define("Sage/nls/Sage_es-co", [], 1);
