require({cache:{
'Sage/Utility/File/nls/he/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/he/FallbackFilePicker',{});
},
'Sage/UI/nls/he/Boolean':function(){
define('Sage/UI/nls/he/Boolean',{});
},
'Sage/Services/nls/he/ActivityService':function(){
define('Sage/Services/nls/he/ActivityService',{});
},
'Sage/UI/Controls/nls/he/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/he/CopyToClipboard',{});
},
'Sage/Utility/nls/he/Activity':function(){
define('Sage/Utility/nls/he/Activity',{});
},
'Sage/QuickForms/Design/nls/he/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/he/DesignPanel',{});
},
'Sage/UI/nls/he/TimelessActivitiesPane':function(){
define('Sage/UI/nls/he/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/he/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/he/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/he/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/he/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/he/ActivityManager':function(){
define('Sage/MainView/nls/he/ActivityManager',{});
},
'Sage/Services/nls/he/JobService':function(){
define('Sage/Services/nls/he/JobService',{});
},
'Sage/QuickForms/Design/nls/he/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/he/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/_PropertyEditor',{});
},
'Sage/Services/nls/he/ActivityActionProcessor':function(){
define('Sage/Services/nls/he/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/he/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/he/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/he/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/he/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/he/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/he/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/he/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/he/AlarmPane':function(){
define('Sage/UI/Alarms/nls/he/AlarmPane',{});
},
'Sage/TaskPane/nls/he/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/he/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/he/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/he/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/he/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/he/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/he/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/he/FilterPanel':function(){
define('Sage/UI/Filters/nls/he/FilterPanel',{});
},
'Sage/TaskPane/nls/he/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/he/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/he/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/he/ReportManagerFormatter',{});
},
'Sage/UI/nls/he/OwnerType':function(){
define('Sage/UI/nls/he/OwnerType',{});
},
'Sage/TaskPane/nls/he/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/he/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/he/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/he/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/he/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/he/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/he/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/he/InvoiceRTDV',{});
},
'Sage/UI/nls/he/SDataLookup':function(){
define('Sage/UI/nls/he/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/he/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/he/RowDesigner',{});
},
'Sage/TaskPane/nls/he/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/he/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/he/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/he/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/he/LibraryDocument':function(){
define('Sage/Utility/File/nls/he/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/he/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/he/SpeedSearchLookup',{});
},
'Sage/UI/nls/he/ConditionManager':function(){
define('Sage/UI/nls/he/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/he/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/he/WidgetDefinition',{});
},
'Sage/UI/nls/he/SearchConditionWidget':function(){
define('Sage/UI/nls/he/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/he/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/he/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/he/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/he/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/he/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/he/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/he/DataSourcePanel',{});
},
'Sage/Library/nls/he/Manager':function(){
define('Sage/Library/nls/he/Manager',{});
},
'Sage/UI/nls/he/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/he/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/he/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/he/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/he/Name':function(){
define('Sage/UI/Controls/nls/he/Name',{});
},
'Sage/MainView/JobMgr/nls/he/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/he/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/he/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/he/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/he/UpdateLeads',{});
},
'Sage/Library/nls/he/FileHandler':function(){
define('Sage/Library/nls/he/FileHandler',{});
},
'Sage/UI/nls/he/ListPanel':function(){
define('Sage/UI/nls/he/ListPanel',{});
},
'Sage/Utility/nls/he/Sql':function(){
define('Sage/Utility/nls/he/Sql',{});
},
'Sage/UI/Filters/nls/he/EditFilters':function(){
define('Sage/UI/Filters/nls/he/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/he/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/he/DurationSelect':function(){
define('Sage/UI/Controls/nls/he/DurationSelect',{});
},
'Sage/UI/Alarms/nls/he/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/he/AlarmCountDown',{});
},
'Sage/UI/nls/he/AttachmentList':function(){
define('Sage/UI/nls/he/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/he/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/he/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/he/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/he/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/he/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/he/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/he/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/he/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/he/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/he/Dialogs':function(){
define('Sage/UI/nls/he/Dialogs',{});
},
'Sage/TaskPane/nls/he/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/he/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/he/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/he/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/he/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/he/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/he/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/UserControlDesigner',{});
},
'Sage/Groups/nls/he/GroupNavigator':function(){
define('Sage/Groups/nls/he/GroupNavigator',{});
},
'Sage/Utility/File/nls/he/AddURLAttachment':function(){
define('Sage/Utility/File/nls/he/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/he/EditFilterItems':function(){
define('Sage/UI/Filters/nls/he/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/he/DragDropWatcher':function(){
define('Sage/Utility/File/nls/he/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/he/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/he/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/he/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/he/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/he/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/he/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/he/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/he/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/he/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/he/ActivityScheduler':function(){
define('Sage/UI/nls/he/ActivityScheduler',{});
},
'Sage/MainView/nls/he/SecurityManager':function(){
define('Sage/MainView/nls/he/SecurityManager',{});
},
'Sage/TaskPane/nls/he/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/he/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/he/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/he/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/he/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/he/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/he/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/he/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/he/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/he/UpdateOpportunities',{});
},
'Sage/UI/nls/he/EditCalendarUsers':function(){
define('Sage/UI/nls/he/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/he/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/he/HelpMenu':function(){
define('Sage/UI/Controls/nls/he/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/he/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/he/UserTasklet':function(){
define('Sage/TaskPane/nls/he/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/he/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/he/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/he/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/he/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/he/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/he/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/he/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/he/ColumnDesigner',{});
},
'Sage/UI/nls/he/SearchMenuItem':function(){
define('Sage/UI/nls/he/SearchMenuItem',{});
},
'Sage/Library/nls/he/DocumentProperties':function(){
define('Sage/Library/nls/he/DocumentProperties',{});
},
'Sage/UI/nls/he/NotesHistoryList':function(){
define('Sage/UI/nls/he/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/he/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/he/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/he/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/he/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/he/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/he/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/he/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/he/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/he/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/he/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/he/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/he/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/he/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/he/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/he/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/he/HistoryEditor',{});
},
'Sage/Groups/nls/he/GroupManager':function(){
define('Sage/Groups/nls/he/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/he/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/he/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/he/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/he/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/he/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/he/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/he/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/he/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/he/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/he/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/he/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/he/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/he/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/he/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/he/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/he/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/he/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/he/FolderHandler':function(){
define('Sage/Library/nls/he/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/he/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/he/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/he/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/he/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/he/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/he/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/he/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/he/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/he/EditableGrid':function(){
define('Sage/UI/nls/he/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/he/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/he/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/he/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/he/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/he/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/he/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/he/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/he/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/he/ReportManagerUtility',{});
},
'Sage/UI/nls/he/SpeedSearch':function(){
define('Sage/UI/nls/he/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/he/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/he/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/he/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/he/SLXPreviewGrid':function(){
define('Sage/UI/nls/he/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/he/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/he/UnconfirmedPane',{});
},
'Sage/Utility/nls/he/Utility':function(){
define('Sage/Utility/nls/he/Utility',{});
},
'Sage/QuickForms/Design/nls/he/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/ControlDesigner',{});
},
'Sage/UI/Controls/nls/he/Address':function(){
define('Sage/UI/Controls/nls/he/Address',{});
},
'Sage/MainView/JobMgr/nls/he/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/he/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/he/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/he/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/he/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/he/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/he/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/he/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/he/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/he/UserType':function(){
define('Sage/UI/nls/he/UserType',{});
},
'Sage/QuickForms/Design/nls/he/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/he/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/he/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/he/ActivityCalendar',{});
},
'Sage/Utility/nls/he/Jobs':function(){
define('Sage/Utility/nls/he/Jobs',{});
},
'Sage/UI/Controls/nls/he/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/he/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/he/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/he/ActivityList':function(){
define('Sage/UI/nls/he/ActivityList',{});
},
'Sage/UI/Alarms/nls/he/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/he/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/he/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/he/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/he/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/he/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/he/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/he/CalendarUsersListPane':function(){
define('Sage/UI/nls/he/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/he/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/he/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/he/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/he/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/he/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/he/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/he/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/he/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/he/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/he/Attachment':function(){
define('Sage/Utility/File/nls/he/Attachment',{});
},
'Sage/QuickForms/Design/nls/he/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/he/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/he/PropertyEditorContainer',{});
},
'Sage/Services/nls/he/ReportingService':function(){
define('Sage/Services/nls/he/ReportingService',{});
},
'Sage/MailMerge/nls/he/Helper':function(){
define('Sage/MailMerge/nls/he/Helper',{});
},
'Sage/UI/Dashboard/nls/he/Dashboard':function(){
define('Sage/UI/Dashboard/nls/he/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/he/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/he/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/he/PickList':function(){
define('Sage/UI/Controls/nls/he/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/he/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/he/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/he/Email':function(){
define('Sage/Utility/nls/he/Email',{});
},
'Sage/TaskPane/nls/he/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/he/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/he/TimeZoneItem':function(){
define('Sage/UI/nls/he/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/he/SlxEdit':function(){
define('Sage/UI/Columns/nls/he/SlxEdit',{});
},
'Sage/Reporting/nls/he/Enumerations':function(){
define('Sage/Reporting/nls/he/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/he/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/he/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/he/ActivityListPanelConfig',{});
},
'Sage/UI/nls/he/JobSchedulingWidget':function(){
define('Sage/UI/nls/he/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/he/LogOffButton':function(){
define('Sage/UI/Controls/nls/he/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/he/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/he/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/he/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/he/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/he/EditEventEditor',{});
},
'Sage/MailMerge/nls/he/Loader':function(){
define('Sage/MailMerge/nls/he/Loader',{});
},
'Sage/UI/Controls/nls/he/DateTimePicker':function(){
define('Sage/UI/Controls/nls/he/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/he/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/he/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/he/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/he/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/he/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/he/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/he/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/he/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/he/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/he/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/he/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/he/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/he/Lookup':function(){
define('Sage/UI/Controls/nls/he/Lookup',{});
},
'Sage/Utility/File/nls/he/DescriptionsForm':function(){
define('Sage/Utility/File/nls/he/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/he/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/he/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/he/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/he/CommonTasksTasklet',{});
},
'Sage/Utility/nls/he/Dashboard':function(){
define('Sage/Utility/nls/he/Dashboard',{});
}}});
define("Sage/nls/Sage_he", [], 1);
