require({cache:{
'Sage/Utility/File/nls/et/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/et/FallbackFilePicker',{});
},
'Sage/UI/nls/et/Boolean':function(){
define('Sage/UI/nls/et/Boolean',{});
},
'Sage/Services/nls/et/ActivityService':function(){
define('Sage/Services/nls/et/ActivityService',{});
},
'Sage/UI/Controls/nls/et/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/et/CopyToClipboard',{});
},
'Sage/Utility/nls/et/Activity':function(){
define('Sage/Utility/nls/et/Activity',{});
},
'Sage/QuickForms/Design/nls/et/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/et/DesignPanel',{});
},
'Sage/UI/nls/et/TimelessActivitiesPane':function(){
define('Sage/UI/nls/et/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/et/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/et/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/et/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/et/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/et/ActivityManager':function(){
define('Sage/MainView/nls/et/ActivityManager',{});
},
'Sage/Services/nls/et/JobService':function(){
define('Sage/Services/nls/et/JobService',{});
},
'Sage/QuickForms/Design/nls/et/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/et/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/_PropertyEditor',{});
},
'Sage/Services/nls/et/ActivityActionProcessor':function(){
define('Sage/Services/nls/et/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/et/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/et/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/et/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/et/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/et/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/et/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/et/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/et/AlarmPane':function(){
define('Sage/UI/Alarms/nls/et/AlarmPane',{});
},
'Sage/TaskPane/nls/et/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/et/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/et/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/et/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/et/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/et/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/et/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/et/FilterPanel':function(){
define('Sage/UI/Filters/nls/et/FilterPanel',{});
},
'Sage/TaskPane/nls/et/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/et/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/et/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/et/ReportManagerFormatter',{});
},
'Sage/UI/nls/et/OwnerType':function(){
define('Sage/UI/nls/et/OwnerType',{});
},
'Sage/TaskPane/nls/et/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/et/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/et/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/et/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/et/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/et/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/et/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/et/InvoiceRTDV',{});
},
'Sage/UI/nls/et/SDataLookup':function(){
define('Sage/UI/nls/et/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/et/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/et/RowDesigner',{});
},
'Sage/TaskPane/nls/et/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/et/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/et/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/et/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/et/LibraryDocument':function(){
define('Sage/Utility/File/nls/et/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/et/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/et/SpeedSearchLookup',{});
},
'Sage/UI/nls/et/ConditionManager':function(){
define('Sage/UI/nls/et/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/et/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/et/WidgetDefinition',{});
},
'Sage/UI/nls/et/SearchConditionWidget':function(){
define('Sage/UI/nls/et/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/et/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/et/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/et/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/et/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/et/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/et/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/et/DataSourcePanel',{});
},
'Sage/Library/nls/et/Manager':function(){
define('Sage/Library/nls/et/Manager',{});
},
'Sage/UI/nls/et/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/et/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/et/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/et/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/et/Name':function(){
define('Sage/UI/Controls/nls/et/Name',{});
},
'Sage/MainView/JobMgr/nls/et/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/et/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/et/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/et/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/et/UpdateLeads',{});
},
'Sage/Library/nls/et/FileHandler':function(){
define('Sage/Library/nls/et/FileHandler',{});
},
'Sage/UI/nls/et/ListPanel':function(){
define('Sage/UI/nls/et/ListPanel',{});
},
'Sage/Utility/nls/et/Sql':function(){
define('Sage/Utility/nls/et/Sql',{});
},
'Sage/UI/Filters/nls/et/EditFilters':function(){
define('Sage/UI/Filters/nls/et/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/et/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/et/DurationSelect':function(){
define('Sage/UI/Controls/nls/et/DurationSelect',{});
},
'Sage/UI/Alarms/nls/et/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/et/AlarmCountDown',{});
},
'Sage/UI/nls/et/AttachmentList':function(){
define('Sage/UI/nls/et/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/et/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/et/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/et/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/et/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/et/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/et/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/et/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/et/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/et/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/et/Dialogs':function(){
define('Sage/UI/nls/et/Dialogs',{});
},
'Sage/TaskPane/nls/et/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/et/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/et/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/et/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/et/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/et/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/et/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/UserControlDesigner',{});
},
'Sage/Groups/nls/et/GroupNavigator':function(){
define('Sage/Groups/nls/et/GroupNavigator',{});
},
'Sage/Utility/File/nls/et/AddURLAttachment':function(){
define('Sage/Utility/File/nls/et/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/et/EditFilterItems':function(){
define('Sage/UI/Filters/nls/et/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/et/DragDropWatcher':function(){
define('Sage/Utility/File/nls/et/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/et/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/et/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/et/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/et/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/et/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/et/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/et/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/et/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/et/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/et/ActivityScheduler':function(){
define('Sage/UI/nls/et/ActivityScheduler',{});
},
'Sage/MainView/nls/et/SecurityManager':function(){
define('Sage/MainView/nls/et/SecurityManager',{});
},
'Sage/TaskPane/nls/et/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/et/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/et/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/et/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/et/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/et/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/et/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/et/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/et/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/et/UpdateOpportunities',{});
},
'Sage/UI/nls/et/EditCalendarUsers':function(){
define('Sage/UI/nls/et/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/et/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/et/HelpMenu':function(){
define('Sage/UI/Controls/nls/et/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/et/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/et/UserTasklet':function(){
define('Sage/TaskPane/nls/et/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/et/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/et/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/et/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/et/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/et/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/et/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/et/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/et/ColumnDesigner',{});
},
'Sage/UI/nls/et/SearchMenuItem':function(){
define('Sage/UI/nls/et/SearchMenuItem',{});
},
'Sage/Library/nls/et/DocumentProperties':function(){
define('Sage/Library/nls/et/DocumentProperties',{});
},
'Sage/UI/nls/et/NotesHistoryList':function(){
define('Sage/UI/nls/et/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/et/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/et/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/et/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/et/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/et/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/et/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/et/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/et/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/et/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/et/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/et/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/et/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/et/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/et/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/et/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/et/HistoryEditor',{});
},
'Sage/Groups/nls/et/GroupManager':function(){
define('Sage/Groups/nls/et/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/et/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/et/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/et/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/et/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/et/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/et/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/et/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/et/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/et/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/et/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/et/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/et/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/et/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/et/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/et/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/et/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/et/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/et/FolderHandler':function(){
define('Sage/Library/nls/et/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/et/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/et/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/et/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/et/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/et/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/et/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/et/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/et/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/et/EditableGrid':function(){
define('Sage/UI/nls/et/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/et/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/et/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/et/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/et/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/et/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/et/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/et/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/et/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/et/ReportManagerUtility',{});
},
'Sage/UI/nls/et/SpeedSearch':function(){
define('Sage/UI/nls/et/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/et/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/et/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/et/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/et/SLXPreviewGrid':function(){
define('Sage/UI/nls/et/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/et/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/et/UnconfirmedPane',{});
},
'Sage/Utility/nls/et/Utility':function(){
define('Sage/Utility/nls/et/Utility',{});
},
'Sage/QuickForms/Design/nls/et/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/ControlDesigner',{});
},
'Sage/UI/Controls/nls/et/Address':function(){
define('Sage/UI/Controls/nls/et/Address',{});
},
'Sage/MainView/JobMgr/nls/et/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/et/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/et/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/et/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/et/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/et/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/et/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/et/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/et/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/et/UserType':function(){
define('Sage/UI/nls/et/UserType',{});
},
'Sage/QuickForms/Design/nls/et/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/et/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/et/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/et/ActivityCalendar',{});
},
'Sage/Utility/nls/et/Jobs':function(){
define('Sage/Utility/nls/et/Jobs',{});
},
'Sage/UI/Controls/nls/et/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/et/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/et/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/et/ActivityList':function(){
define('Sage/UI/nls/et/ActivityList',{});
},
'Sage/UI/Alarms/nls/et/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/et/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/et/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/et/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/et/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/et/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/et/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/et/CalendarUsersListPane':function(){
define('Sage/UI/nls/et/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/et/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/et/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/et/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/et/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/et/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/et/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/et/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/et/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/et/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/et/Attachment':function(){
define('Sage/Utility/File/nls/et/Attachment',{});
},
'Sage/QuickForms/Design/nls/et/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/et/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/et/PropertyEditorContainer',{});
},
'Sage/Services/nls/et/ReportingService':function(){
define('Sage/Services/nls/et/ReportingService',{});
},
'Sage/MailMerge/nls/et/Helper':function(){
define('Sage/MailMerge/nls/et/Helper',{});
},
'Sage/UI/Dashboard/nls/et/Dashboard':function(){
define('Sage/UI/Dashboard/nls/et/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/et/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/et/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/et/PickList':function(){
define('Sage/UI/Controls/nls/et/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/et/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/et/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/et/Email':function(){
define('Sage/Utility/nls/et/Email',{});
},
'Sage/TaskPane/nls/et/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/et/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/et/TimeZoneItem':function(){
define('Sage/UI/nls/et/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/et/SlxEdit':function(){
define('Sage/UI/Columns/nls/et/SlxEdit',{});
},
'Sage/Reporting/nls/et/Enumerations':function(){
define('Sage/Reporting/nls/et/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/et/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/et/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/et/ActivityListPanelConfig',{});
},
'Sage/UI/nls/et/JobSchedulingWidget':function(){
define('Sage/UI/nls/et/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/et/LogOffButton':function(){
define('Sage/UI/Controls/nls/et/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/et/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/et/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/et/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/et/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/et/EditEventEditor',{});
},
'Sage/MailMerge/nls/et/Loader':function(){
define('Sage/MailMerge/nls/et/Loader',{});
},
'Sage/UI/Controls/nls/et/DateTimePicker':function(){
define('Sage/UI/Controls/nls/et/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/et/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/et/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/et/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/et/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/et/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/et/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/et/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/et/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/et/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/et/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/et/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/et/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/et/Lookup':function(){
define('Sage/UI/Controls/nls/et/Lookup',{});
},
'Sage/Utility/File/nls/et/DescriptionsForm':function(){
define('Sage/Utility/File/nls/et/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/et/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/et/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/et/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/et/CommonTasksTasklet',{});
},
'Sage/Utility/nls/et/Dashboard':function(){
define('Sage/Utility/nls/et/Dashboard',{});
}}});
define("Sage/nls/Sage_et", [], 1);
