require({cache:{
'Sage/Utility/File/nls/sv/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sv/FallbackFilePicker',{});
},
'Sage/UI/nls/sv/Boolean':function(){
define('Sage/UI/nls/sv/Boolean',{});
},
'Sage/Services/nls/sv/ActivityService':function(){
define('Sage/Services/nls/sv/ActivityService',{});
},
'Sage/UI/Controls/nls/sv/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sv/CopyToClipboard',{});
},
'Sage/Utility/nls/sv/Activity':function(){
define('Sage/Utility/nls/sv/Activity',{});
},
'Sage/QuickForms/Design/nls/sv/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sv/DesignPanel',{});
},
'Sage/UI/nls/sv/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sv/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/sv/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/sv/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/sv/ActivityManager':function(){
define('Sage/MainView/nls/sv/ActivityManager',{});
},
'Sage/Services/nls/sv/JobService':function(){
define('Sage/Services/nls/sv/JobService',{});
},
'Sage/QuickForms/Design/nls/sv/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/_PropertyEditor',{});
},
'Sage/Services/nls/sv/ActivityActionProcessor':function(){
define('Sage/Services/nls/sv/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/sv/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sv/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sv/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sv/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sv/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sv/AlarmPane',{});
},
'Sage/TaskPane/nls/sv/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sv/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sv/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sv/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sv/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sv/FilterPanel':function(){
define('Sage/UI/Filters/nls/sv/FilterPanel',{});
},
'Sage/TaskPane/nls/sv/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sv/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportManagerFormatter',{});
},
'Sage/UI/nls/sv/OwnerType':function(){
define('Sage/UI/nls/sv/OwnerType',{});
},
'Sage/TaskPane/nls/sv/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sv/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sv/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sv/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv/InvoiceRTDV',{});
},
'Sage/UI/nls/sv/SDataLookup':function(){
define('Sage/UI/nls/sv/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sv/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/RowDesigner',{});
},
'Sage/TaskPane/nls/sv/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sv/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sv/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sv/LibraryDocument':function(){
define('Sage/Utility/File/nls/sv/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/SpeedSearchLookup',{});
},
'Sage/UI/nls/sv/ConditionManager':function(){
define('Sage/UI/nls/sv/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sv/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sv/WidgetDefinition',{});
},
'Sage/UI/nls/sv/SearchConditionWidget':function(){
define('Sage/UI/nls/sv/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sv/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/sv/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/sv/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sv/DataSourcePanel',{});
},
'Sage/Library/nls/sv/Manager':function(){
define('Sage/Library/nls/sv/Manager',{});
},
'Sage/UI/nls/sv/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sv/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sv/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sv/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sv/Name':function(){
define('Sage/UI/Controls/nls/sv/Name',{});
},
'Sage/MainView/JobMgr/nls/sv/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sv/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sv/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sv/UpdateLeads',{});
},
'Sage/Library/nls/sv/FileHandler':function(){
define('Sage/Library/nls/sv/FileHandler',{});
},
'Sage/UI/nls/sv/ListPanel':function(){
define('Sage/UI/nls/sv/ListPanel',{});
},
'Sage/Utility/nls/sv/Sql':function(){
define('Sage/Utility/nls/sv/Sql',{});
},
'Sage/UI/Filters/nls/sv/EditFilters':function(){
define('Sage/UI/Filters/nls/sv/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sv/DurationSelect':function(){
define('Sage/UI/Controls/nls/sv/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sv/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sv/AlarmCountDown',{});
},
'Sage/UI/nls/sv/AttachmentList':function(){
define('Sage/UI/nls/sv/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sv/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/sv/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/sv/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sv/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sv/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sv/Dialogs':function(){
define('Sage/UI/nls/sv/Dialogs',{});
},
'Sage/TaskPane/nls/sv/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sv/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sv/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sv/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sv/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sv/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/UserControlDesigner',{});
},
'Sage/Groups/nls/sv/GroupNavigator':function(){
define('Sage/Groups/nls/sv/GroupNavigator',{});
},
'Sage/Utility/File/nls/sv/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sv/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sv/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sv/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/sv/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sv/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/sv/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sv/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sv/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sv/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/sv/ActivityScheduler':function(){
define('Sage/UI/nls/sv/ActivityScheduler',{});
},
'Sage/MainView/nls/sv/SecurityManager':function(){
define('Sage/MainView/nls/sv/SecurityManager',{});
},
'Sage/TaskPane/nls/sv/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sv/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sv/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sv/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/sv/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/sv/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/sv/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sv/UpdateOpportunities',{});
},
'Sage/UI/nls/sv/EditCalendarUsers':function(){
define('Sage/UI/nls/sv/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/sv/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sv/HelpMenu':function(){
define('Sage/UI/Controls/nls/sv/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sv/UserTasklet':function(){
define('Sage/TaskPane/nls/sv/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/sv/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sv/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sv/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sv/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sv/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sv/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sv/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/ColumnDesigner',{});
},
'Sage/UI/nls/sv/SearchMenuItem':function(){
define('Sage/UI/nls/sv/SearchMenuItem',{});
},
'Sage/Library/nls/sv/DocumentProperties':function(){
define('Sage/Library/nls/sv/DocumentProperties',{});
},
'Sage/UI/nls/sv/NotesHistoryList':function(){
define('Sage/UI/nls/sv/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/sv/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sv/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/sv/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/sv/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/sv/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/sv/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/sv/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sv/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sv/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sv/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/HistoryEditor',{});
},
'Sage/Groups/nls/sv/GroupManager':function(){
define('Sage/Groups/nls/sv/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/sv/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/sv/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/sv/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sv/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/sv/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sv/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/sv/FolderHandler':function(){
define('Sage/Library/nls/sv/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sv/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sv/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sv/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sv/EditableGrid':function(){
define('Sage/UI/nls/sv/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/sv/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sv/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/sv/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sv/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportManagerUtility',{});
},
'Sage/UI/nls/sv/SpeedSearch':function(){
define('Sage/UI/nls/sv/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/sv/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/sv/SLXPreviewGrid':function(){
define('Sage/UI/nls/sv/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sv/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sv/UnconfirmedPane',{});
},
'Sage/Utility/nls/sv/Utility':function(){
define('Sage/Utility/nls/sv/Utility',{});
},
'Sage/QuickForms/Design/nls/sv/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sv/Address':function(){
define('Sage/UI/Controls/nls/sv/Address',{});
},
'Sage/MainView/JobMgr/nls/sv/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/sv/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/sv/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sv/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/sv/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/sv/UserType':function(){
define('Sage/UI/nls/sv/UserType',{});
},
'Sage/QuickForms/Design/nls/sv/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityCalendar',{});
},
'Sage/Utility/nls/sv/Jobs':function(){
define('Sage/Utility/nls/sv/Jobs',{});
},
'Sage/UI/Controls/nls/sv/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sv/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sv/ActivityList':function(){
define('Sage/UI/nls/sv/ActivityList',{});
},
'Sage/UI/Alarms/nls/sv/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/sv/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/sv/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/sv/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/sv/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sv/CalendarUsersListPane':function(){
define('Sage/UI/nls/sv/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/sv/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sv/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sv/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sv/Attachment':function(){
define('Sage/Utility/File/nls/sv/Attachment',{});
},
'Sage/QuickForms/Design/nls/sv/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/sv/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sv/PropertyEditorContainer',{});
},
'Sage/Services/nls/sv/ReportingService':function(){
define('Sage/Services/nls/sv/ReportingService',{});
},
'Sage/MailMerge/nls/sv/Helper':function(){
define('Sage/MailMerge/nls/sv/Helper',{});
},
'Sage/UI/Dashboard/nls/sv/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sv/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sv/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sv/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sv/PickList':function(){
define('Sage/UI/Controls/nls/sv/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/sv/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/sv/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/sv/Email':function(){
define('Sage/Utility/nls/sv/Email',{});
},
'Sage/TaskPane/nls/sv/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sv/TimeZoneItem':function(){
define('Sage/UI/nls/sv/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sv/SlxEdit':function(){
define('Sage/UI/Columns/nls/sv/SlxEdit',{});
},
'Sage/Reporting/nls/sv/Enumerations':function(){
define('Sage/Reporting/nls/sv/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/sv/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/sv/ActivityListPanelConfig',{});
},
'Sage/UI/nls/sv/JobSchedulingWidget':function(){
define('Sage/UI/nls/sv/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/sv/LogOffButton':function(){
define('Sage/UI/Controls/nls/sv/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/sv/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/sv/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sv/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sv/EditEventEditor',{});
},
'Sage/MailMerge/nls/sv/Loader':function(){
define('Sage/MailMerge/nls/sv/Loader',{});
},
'Sage/UI/Controls/nls/sv/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sv/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/sv/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/sv/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/sv/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sv/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/sv/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/sv/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/sv/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/sv/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sv/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sv/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sv/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sv/Lookup':function(){
define('Sage/UI/Controls/nls/sv/Lookup',{});
},
'Sage/Utility/File/nls/sv/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sv/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sv/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sv/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sv/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sv/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sv/Dashboard':function(){
define('Sage/Utility/nls/sv/Dashboard',{});
}}});
define("Sage/nls/Sage_sv", [], 1);
