require({cache:{
'Sage/Utility/File/nls/ve/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ve/FallbackFilePicker',{});
},
'Sage/UI/nls/ve/Boolean':function(){
define('Sage/UI/nls/ve/Boolean',{});
},
'Sage/Services/nls/ve/ActivityService':function(){
define('Sage/Services/nls/ve/ActivityService',{});
},
'Sage/UI/Controls/nls/ve/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ve/CopyToClipboard',{});
},
'Sage/Utility/nls/ve/Activity':function(){
define('Sage/Utility/nls/ve/Activity',{});
},
'Sage/QuickForms/Design/nls/ve/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ve/DesignPanel',{});
},
'Sage/UI/nls/ve/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ve/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ve/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ve/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/ve/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/ve/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/ve/ActivityManager':function(){
define('Sage/MainView/nls/ve/ActivityManager',{});
},
'Sage/Services/nls/ve/JobService':function(){
define('Sage/Services/nls/ve/JobService',{});
},
'Sage/QuickForms/Design/nls/ve/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/_PropertyEditor',{});
},
'Sage/Services/nls/ve/ActivityActionProcessor':function(){
define('Sage/Services/nls/ve/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ve/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ve/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ve/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ve/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ve/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ve/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ve/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ve/AlarmPane',{});
},
'Sage/TaskPane/nls/ve/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ve/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ve/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ve/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ve/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ve/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ve/FilterPanel':function(){
define('Sage/UI/Filters/nls/ve/FilterPanel',{});
},
'Sage/TaskPane/nls/ve/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ve/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/ve/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/ve/ReportManagerFormatter',{});
},
'Sage/UI/nls/ve/OwnerType':function(){
define('Sage/UI/nls/ve/OwnerType',{});
},
'Sage/TaskPane/nls/ve/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ve/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ve/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ve/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ve/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ve/InvoiceRTDV',{});
},
'Sage/UI/nls/ve/SDataLookup':function(){
define('Sage/UI/nls/ve/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ve/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/RowDesigner',{});
},
'Sage/TaskPane/nls/ve/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ve/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ve/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ve/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ve/LibraryDocument':function(){
define('Sage/Utility/File/nls/ve/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ve/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ve/SpeedSearchLookup',{});
},
'Sage/UI/nls/ve/ConditionManager':function(){
define('Sage/UI/nls/ve/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ve/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ve/WidgetDefinition',{});
},
'Sage/UI/nls/ve/SearchConditionWidget':function(){
define('Sage/UI/nls/ve/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ve/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/ve/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ve/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ve/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/ve/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ve/DataSourcePanel',{});
},
'Sage/Library/nls/ve/Manager':function(){
define('Sage/Library/nls/ve/Manager',{});
},
'Sage/UI/nls/ve/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ve/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ve/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ve/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ve/Name':function(){
define('Sage/UI/Controls/nls/ve/Name',{});
},
'Sage/MainView/JobMgr/nls/ve/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ve/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ve/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ve/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ve/UpdateLeads',{});
},
'Sage/Library/nls/ve/FileHandler':function(){
define('Sage/Library/nls/ve/FileHandler',{});
},
'Sage/UI/nls/ve/ListPanel':function(){
define('Sage/UI/nls/ve/ListPanel',{});
},
'Sage/Utility/nls/ve/Sql':function(){
define('Sage/Utility/nls/ve/Sql',{});
},
'Sage/UI/Filters/nls/ve/EditFilters':function(){
define('Sage/UI/Filters/nls/ve/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ve/DurationSelect':function(){
define('Sage/UI/Controls/nls/ve/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ve/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ve/AlarmCountDown',{});
},
'Sage/UI/nls/ve/AttachmentList':function(){
define('Sage/UI/nls/ve/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ve/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/ve/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/ve/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ve/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ve/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ve/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ve/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ve/Dialogs':function(){
define('Sage/UI/nls/ve/Dialogs',{});
},
'Sage/TaskPane/nls/ve/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ve/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ve/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ve/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ve/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ve/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ve/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/UserControlDesigner',{});
},
'Sage/Groups/nls/ve/GroupNavigator':function(){
define('Sage/Groups/nls/ve/GroupNavigator',{});
},
'Sage/Utility/File/nls/ve/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ve/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ve/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ve/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/ve/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ve/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/ve/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ve/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/ve/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ve/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ve/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ve/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ve/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ve/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/ve/ActivityScheduler':function(){
define('Sage/UI/nls/ve/ActivityScheduler',{});
},
'Sage/MainView/nls/ve/SecurityManager':function(){
define('Sage/MainView/nls/ve/SecurityManager',{});
},
'Sage/TaskPane/nls/ve/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ve/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ve/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ve/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ve/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ve/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/ve/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/ve/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/ve/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ve/UpdateOpportunities',{});
},
'Sage/UI/nls/ve/EditCalendarUsers':function(){
define('Sage/UI/nls/ve/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/ve/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ve/HelpMenu':function(){
define('Sage/UI/Controls/nls/ve/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ve/UserTasklet':function(){
define('Sage/TaskPane/nls/ve/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/ve/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ve/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ve/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ve/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ve/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ve/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ve/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/ColumnDesigner',{});
},
'Sage/UI/nls/ve/SearchMenuItem':function(){
define('Sage/UI/nls/ve/SearchMenuItem',{});
},
'Sage/Library/nls/ve/DocumentProperties':function(){
define('Sage/Library/nls/ve/DocumentProperties',{});
},
'Sage/UI/nls/ve/NotesHistoryList':function(){
define('Sage/UI/nls/ve/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/ve/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ve/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ve/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/ve/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/ve/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/ve/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/ve/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/ve/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ve/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/ve/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ve/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ve/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ve/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ve/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ve/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ve/HistoryEditor',{});
},
'Sage/Groups/nls/ve/GroupManager':function(){
define('Sage/Groups/nls/ve/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ve/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ve/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/ve/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/ve/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/ve/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ve/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ve/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ve/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/ve/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ve/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ve/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ve/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ve/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/ve/FolderHandler':function(){
define('Sage/Library/nls/ve/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ve/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ve/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ve/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ve/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ve/EditableGrid':function(){
define('Sage/UI/nls/ve/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/ve/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ve/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/ve/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ve/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/ve/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/ve/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ve/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/ve/ReportManagerUtility',{});
},
'Sage/UI/nls/ve/SpeedSearch':function(){
define('Sage/UI/nls/ve/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/ve/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ve/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/ve/SLXPreviewGrid':function(){
define('Sage/UI/nls/ve/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ve/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ve/UnconfirmedPane',{});
},
'Sage/Utility/nls/ve/Utility':function(){
define('Sage/Utility/nls/ve/Utility',{});
},
'Sage/QuickForms/Design/nls/ve/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ve/Address':function(){
define('Sage/UI/Controls/nls/ve/Address',{});
},
'Sage/MainView/JobMgr/nls/ve/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/ve/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ve/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ve/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ve/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/ve/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ve/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ve/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ve/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/ve/UserType':function(){
define('Sage/UI/nls/ve/UserType',{});
},
'Sage/QuickForms/Design/nls/ve/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ve/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ve/ActivityCalendar',{});
},
'Sage/Utility/nls/ve/Jobs':function(){
define('Sage/Utility/nls/ve/Jobs',{});
},
'Sage/UI/Controls/nls/ve/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ve/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ve/ActivityList':function(){
define('Sage/UI/nls/ve/ActivityList',{});
},
'Sage/UI/Alarms/nls/ve/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/ve/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/ve/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/ve/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/ve/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/ve/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ve/CalendarUsersListPane':function(){
define('Sage/UI/nls/ve/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/ve/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/ve/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/ve/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ve/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ve/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ve/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ve/Attachment':function(){
define('Sage/Utility/File/nls/ve/Attachment',{});
},
'Sage/QuickForms/Design/nls/ve/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/ve/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ve/PropertyEditorContainer',{});
},
'Sage/Services/nls/ve/ReportingService':function(){
define('Sage/Services/nls/ve/ReportingService',{});
},
'Sage/MailMerge/nls/ve/Helper':function(){
define('Sage/MailMerge/nls/ve/Helper',{});
},
'Sage/UI/Dashboard/nls/ve/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ve/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ve/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ve/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ve/PickList':function(){
define('Sage/UI/Controls/nls/ve/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/ve/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/ve/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/ve/Email':function(){
define('Sage/Utility/nls/ve/Email',{});
},
'Sage/TaskPane/nls/ve/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ve/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ve/TimeZoneItem':function(){
define('Sage/UI/nls/ve/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ve/SlxEdit':function(){
define('Sage/UI/Columns/nls/ve/SlxEdit',{});
},
'Sage/Reporting/nls/ve/Enumerations':function(){
define('Sage/Reporting/nls/ve/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/ve/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/ve/ActivityListPanelConfig',{});
},
'Sage/UI/nls/ve/JobSchedulingWidget':function(){
define('Sage/UI/nls/ve/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/ve/LogOffButton':function(){
define('Sage/UI/Controls/nls/ve/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/ve/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/ve/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ve/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ve/EditEventEditor',{});
},
'Sage/MailMerge/nls/ve/Loader':function(){
define('Sage/MailMerge/nls/ve/Loader',{});
},
'Sage/UI/Controls/nls/ve/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ve/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/ve/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/ve/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/ve/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ve/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/ve/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/ve/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/ve/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/ve/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ve/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ve/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ve/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ve/Lookup':function(){
define('Sage/UI/Controls/nls/ve/Lookup',{});
},
'Sage/Utility/File/nls/ve/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ve/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ve/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ve/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ve/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ve/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ve/Dashboard':function(){
define('Sage/Utility/nls/ve/Dashboard',{});
}}});
define("Sage/nls/Sage_ve", [], 1);
