require({cache:{
'Sage/Utility/File/nls/xh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/xh/FallbackFilePicker',{});
},
'Sage/UI/nls/xh/Boolean':function(){
define('Sage/UI/nls/xh/Boolean',{});
},
'Sage/Services/nls/xh/ActivityService':function(){
define('Sage/Services/nls/xh/ActivityService',{});
},
'Sage/UI/Controls/nls/xh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/xh/CopyToClipboard',{});
},
'Sage/Utility/nls/xh/Activity':function(){
define('Sage/Utility/nls/xh/Activity',{});
},
'Sage/QuickForms/Design/nls/xh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/xh/DesignPanel',{});
},
'Sage/UI/nls/xh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/xh/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/xh/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/xh/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/xh/ActivityManager':function(){
define('Sage/MainView/nls/xh/ActivityManager',{});
},
'Sage/Services/nls/xh/JobService':function(){
define('Sage/Services/nls/xh/JobService',{});
},
'Sage/QuickForms/Design/nls/xh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/_PropertyEditor',{});
},
'Sage/Services/nls/xh/ActivityActionProcessor':function(){
define('Sage/Services/nls/xh/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/xh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/xh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/xh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/xh/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/xh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/xh/AlarmPane',{});
},
'Sage/TaskPane/nls/xh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/xh/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/xh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/xh/FilterPanel':function(){
define('Sage/UI/Filters/nls/xh/FilterPanel',{});
},
'Sage/TaskPane/nls/xh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/xh/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportManagerFormatter',{});
},
'Sage/UI/nls/xh/OwnerType':function(){
define('Sage/UI/nls/xh/OwnerType',{});
},
'Sage/TaskPane/nls/xh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/xh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/xh/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/xh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh/InvoiceRTDV',{});
},
'Sage/UI/nls/xh/SDataLookup':function(){
define('Sage/UI/nls/xh/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/xh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/RowDesigner',{});
},
'Sage/TaskPane/nls/xh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/xh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/xh/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/xh/LibraryDocument':function(){
define('Sage/Utility/File/nls/xh/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/SpeedSearchLookup',{});
},
'Sage/UI/nls/xh/ConditionManager':function(){
define('Sage/UI/nls/xh/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/xh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/xh/WidgetDefinition',{});
},
'Sage/UI/nls/xh/SearchConditionWidget':function(){
define('Sage/UI/nls/xh/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/xh/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/xh/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/xh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/xh/DataSourcePanel',{});
},
'Sage/Library/nls/xh/Manager':function(){
define('Sage/Library/nls/xh/Manager',{});
},
'Sage/UI/nls/xh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/xh/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/xh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/xh/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/xh/Name':function(){
define('Sage/UI/Controls/nls/xh/Name',{});
},
'Sage/MainView/JobMgr/nls/xh/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/xh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/xh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/xh/UpdateLeads',{});
},
'Sage/Library/nls/xh/FileHandler':function(){
define('Sage/Library/nls/xh/FileHandler',{});
},
'Sage/UI/nls/xh/ListPanel':function(){
define('Sage/UI/nls/xh/ListPanel',{});
},
'Sage/Utility/nls/xh/Sql':function(){
define('Sage/Utility/nls/xh/Sql',{});
},
'Sage/UI/Filters/nls/xh/EditFilters':function(){
define('Sage/UI/Filters/nls/xh/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/xh/DurationSelect':function(){
define('Sage/UI/Controls/nls/xh/DurationSelect',{});
},
'Sage/UI/Alarms/nls/xh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/xh/AlarmCountDown',{});
},
'Sage/UI/nls/xh/AttachmentList':function(){
define('Sage/UI/nls/xh/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/xh/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/xh/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/xh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/xh/Dialogs':function(){
define('Sage/UI/nls/xh/Dialogs',{});
},
'Sage/TaskPane/nls/xh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/xh/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/xh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/xh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/UserControlDesigner',{});
},
'Sage/Groups/nls/xh/GroupNavigator':function(){
define('Sage/Groups/nls/xh/GroupNavigator',{});
},
'Sage/Utility/File/nls/xh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/xh/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/xh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/xh/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/xh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/xh/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/xh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/xh/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/xh/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/xh/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/xh/ActivityScheduler':function(){
define('Sage/UI/nls/xh/ActivityScheduler',{});
},
'Sage/MainView/nls/xh/SecurityManager':function(){
define('Sage/MainView/nls/xh/SecurityManager',{});
},
'Sage/TaskPane/nls/xh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/xh/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/xh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/xh/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/xh/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/xh/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/xh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/xh/UpdateOpportunities',{});
},
'Sage/UI/nls/xh/EditCalendarUsers':function(){
define('Sage/UI/nls/xh/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/xh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/xh/HelpMenu':function(){
define('Sage/UI/Controls/nls/xh/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/xh/UserTasklet':function(){
define('Sage/TaskPane/nls/xh/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/xh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/xh/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/xh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/xh/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/xh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/xh/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/xh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/ColumnDesigner',{});
},
'Sage/UI/nls/xh/SearchMenuItem':function(){
define('Sage/UI/nls/xh/SearchMenuItem',{});
},
'Sage/Library/nls/xh/DocumentProperties':function(){
define('Sage/Library/nls/xh/DocumentProperties',{});
},
'Sage/UI/nls/xh/NotesHistoryList':function(){
define('Sage/UI/nls/xh/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/xh/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/xh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/xh/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/xh/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/xh/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/xh/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/xh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/xh/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/xh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/xh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/HistoryEditor',{});
},
'Sage/Groups/nls/xh/GroupManager':function(){
define('Sage/Groups/nls/xh/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/xh/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/xh/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/xh/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/xh/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/xh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/xh/FolderHandler':function(){
define('Sage/Library/nls/xh/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/xh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/xh/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/xh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/xh/EditableGrid':function(){
define('Sage/UI/nls/xh/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/xh/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/xh/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/xh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/xh/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportManagerUtility',{});
},
'Sage/UI/nls/xh/SpeedSearch':function(){
define('Sage/UI/nls/xh/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/xh/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/xh/SLXPreviewGrid':function(){
define('Sage/UI/nls/xh/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/xh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/xh/UnconfirmedPane',{});
},
'Sage/Utility/nls/xh/Utility':function(){
define('Sage/Utility/nls/xh/Utility',{});
},
'Sage/QuickForms/Design/nls/xh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/ControlDesigner',{});
},
'Sage/UI/Controls/nls/xh/Address':function(){
define('Sage/UI/Controls/nls/xh/Address',{});
},
'Sage/MainView/JobMgr/nls/xh/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/xh/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/xh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/xh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/xh/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/xh/UserType':function(){
define('Sage/UI/nls/xh/UserType',{});
},
'Sage/QuickForms/Design/nls/xh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityCalendar',{});
},
'Sage/Utility/nls/xh/Jobs':function(){
define('Sage/Utility/nls/xh/Jobs',{});
},
'Sage/UI/Controls/nls/xh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/xh/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/xh/ActivityList':function(){
define('Sage/UI/nls/xh/ActivityList',{});
},
'Sage/UI/Alarms/nls/xh/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/xh/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/xh/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/xh/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/xh/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/xh/CalendarUsersListPane':function(){
define('Sage/UI/nls/xh/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/xh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/xh/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/xh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/xh/Attachment':function(){
define('Sage/Utility/File/nls/xh/Attachment',{});
},
'Sage/QuickForms/Design/nls/xh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/xh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/xh/PropertyEditorContainer',{});
},
'Sage/Services/nls/xh/ReportingService':function(){
define('Sage/Services/nls/xh/ReportingService',{});
},
'Sage/MailMerge/nls/xh/Helper':function(){
define('Sage/MailMerge/nls/xh/Helper',{});
},
'Sage/UI/Dashboard/nls/xh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/xh/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/xh/PickList':function(){
define('Sage/UI/Controls/nls/xh/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/xh/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/xh/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/xh/Email':function(){
define('Sage/Utility/nls/xh/Email',{});
},
'Sage/TaskPane/nls/xh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/xh/TimeZoneItem':function(){
define('Sage/UI/nls/xh/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/xh/SlxEdit':function(){
define('Sage/UI/Columns/nls/xh/SlxEdit',{});
},
'Sage/Reporting/nls/xh/Enumerations':function(){
define('Sage/Reporting/nls/xh/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/xh/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/xh/ActivityListPanelConfig',{});
},
'Sage/UI/nls/xh/JobSchedulingWidget':function(){
define('Sage/UI/nls/xh/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/xh/LogOffButton':function(){
define('Sage/UI/Controls/nls/xh/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/xh/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/xh/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/EditEventEditor',{});
},
'Sage/MailMerge/nls/xh/Loader':function(){
define('Sage/MailMerge/nls/xh/Loader',{});
},
'Sage/UI/Controls/nls/xh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/xh/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/xh/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/xh/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/xh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/xh/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/xh/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/xh/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/xh/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/xh/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/xh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/xh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/xh/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/xh/Lookup':function(){
define('Sage/UI/Controls/nls/xh/Lookup',{});
},
'Sage/Utility/File/nls/xh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/xh/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/xh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/xh/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/xh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/CommonTasksTasklet',{});
},
'Sage/Utility/nls/xh/Dashboard':function(){
define('Sage/Utility/nls/xh/Dashboard',{});
}}});
define("Sage/nls/Sage_xh", [], 1);
