require({cache:{
'Sage/Utility/File/nls/zh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh/FallbackFilePicker',{});
},
'Sage/UI/nls/zh/Boolean':function(){
define('Sage/UI/nls/zh/Boolean',{});
},
'Sage/Services/nls/zh/ActivityService':function(){
define('Sage/Services/nls/zh/ActivityService',{});
},
'Sage/UI/Controls/nls/zh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh/CopyToClipboard',{});
},
'Sage/Utility/nls/zh/Activity':function(){
define('Sage/Utility/nls/zh/Activity',{});
},
'Sage/QuickForms/Design/nls/zh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh/DesignPanel',{});
},
'Sage/UI/nls/zh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityEditor',{});
},
'Sage/TaskPane/User/nls/zh/ContactUserAssociationEditor':function(){
define('Sage/TaskPane/User/nls/zh/ContactUserAssociationEditor',{});
},
'Sage/MainView/nls/zh/ActivityManager':function(){
define('Sage/MainView/nls/zh/ActivityManager',{});
},
'Sage/Services/nls/zh/JobService':function(){
define('Sage/Services/nls/zh/JobService',{});
},
'Sage/QuickForms/Design/nls/zh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor',{});
},
'Sage/Services/nls/zh/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/zh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPane',{});
},
'Sage/TaskPane/nls/zh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/zh/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh/FilterPanel',{});
},
'Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportManagerFormatter':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportManagerFormatter',{});
},
'Sage/UI/nls/zh/OwnerType':function(){
define('Sage/UI/nls/zh/OwnerType',{});
},
'Sage/TaskPane/nls/zh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV',{});
},
'Sage/UI/nls/zh/SDataLookup':function(){
define('Sage/UI/nls/zh/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/zh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/RowDesigner',{});
},
'Sage/TaskPane/nls/zh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zh/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh/LibraryDocument',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/SpeedSearchLookup':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/SpeedSearchLookup',{});
},
'Sage/UI/nls/zh/ConditionManager':function(){
define('Sage/UI/nls/zh/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/zh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh/WidgetDefinition',{});
},
'Sage/UI/nls/zh/SearchConditionWidget':function(){
define('Sage/UI/nls/zh/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zh/JobManagerActions':function(){
define('Sage/MainView/JobMgr/nls/zh/JobManagerActions',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/ContactLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/ContactLookupConfig',{});
},
'Sage/QuickForms/Design/nls/zh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh/DataSourcePanel',{});
},
'Sage/Library/nls/zh/Manager':function(){
define('Sage/Library/nls/zh/Manager',{});
},
'Sage/UI/nls/zh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/zh/Name':function(){
define('Sage/UI/Controls/nls/zh/Name',{});
},
'Sage/MainView/JobMgr/nls/zh/ExecutionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh/ExecutionsListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/zh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh/UpdateLeads',{});
},
'Sage/Library/nls/zh/FileHandler':function(){
define('Sage/Library/nls/zh/FileHandler',{});
},
'Sage/UI/nls/zh/ListPanel':function(){
define('Sage/UI/nls/zh/ListPanel',{});
},
'Sage/Utility/nls/zh/Sql':function(){
define('Sage/Utility/nls/zh/Sql',{});
},
'Sage/UI/Filters/nls/zh/EditFilters':function(){
define('Sage/UI/Filters/nls/zh/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh/AlarmCountDown',{});
},
'Sage/UI/nls/zh/AttachmentList':function(){
define('Sage/UI/nls/zh/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zh/RunJobDialog':function(){
define('Sage/MainView/JobMgr/nls/zh/RunJobDialog',{});
},
'Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/Dialogs':function(){
define('Sage/UI/nls/zh/Dialogs',{});
},
'Sage/TaskPane/nls/zh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/zh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UserControlDesigner',{});
},
'Sage/Groups/nls/zh/GroupNavigator':function(){
define('Sage/Groups/nls/zh/GroupNavigator',{});
},
'Sage/Utility/File/nls/zh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh/EditFilterItems',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportsFormatter':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportsFormatter',{});
},
'Sage/Utility/File/nls/zh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh/DragDropWatcher',{});
},
'Sage/QuickForms/Design/nls/zh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh/DesignSurface',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zh/AllOpenListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zh/AllOpenListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/MultiselectNumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/MultiselectNumberParameterEditor',{});
},
'Sage/UI/nls/zh/ActivityScheduler':function(){
define('Sage/UI/nls/zh/ActivityScheduler',{});
},
'Sage/MainView/nls/zh/SecurityManager':function(){
define('Sage/MainView/nls/zh/SecurityManager',{});
},
'Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/zh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService',{});
},
'Sage/MainView/ReportMgr/Common/nls/zh/ExportOptionsDialog':function(){
define('Sage/MainView/ReportMgr/Common/nls/zh/ExportOptionsDialog',{});
},
'Sage/MainView/Opportunity/nls/zh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh/UpdateOpportunities',{});
},
'Sage/UI/nls/zh/EditCalendarUsers':function(){
define('Sage/UI/nls/zh/EditCalendarUsers',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportParametersDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportParametersDialog',{});
},
'Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/UserTasklet':function(){
define('Sage/TaskPane/nls/zh/UserTasklet',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/NumberParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/NumberParameterEditor',{});
},
'Sage/UI/Alarms/nls/zh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh/OpportunityStatistics',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportConditionEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportConditionEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/zh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ColumnDesigner',{});
},
'Sage/UI/nls/zh/SearchMenuItem':function(){
define('Sage/UI/nls/zh/SearchMenuItem',{});
},
'Sage/Library/nls/zh/DocumentProperties':function(){
define('Sage/Library/nls/zh/DocumentProperties',{});
},
'Sage/UI/nls/zh/NotesHistoryList':function(){
define('Sage/UI/nls/zh/NotesHistoryList',{});
},
'Sage/MainView/ReportMgr/nls/zh/HistoryListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh/HistoryListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/BooleanParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/BooleanParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UrlControlDesigner',{});
},
'Sage/TaskPane/nls/zh/ContactTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/ContactTasksTasklet',{});
},
'Sage/MainView/ReportMgr/Common/nls/zh/_WizardDialogBase':function(){
define('Sage/MainView/ReportMgr/Common/nls/zh/_WizardDialogBase',{});
},
'Sage/MainView/JobMgr/nls/zh/SchedulesListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh/SchedulesListPanelConfig',{});
},
'Sage/Utility/File/nls/zh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/HistoryEditor',{});
},
'Sage/Groups/nls/zh/GroupManager':function(){
define('Sage/Groups/nls/zh/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportsListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportsListPanelConfig',{});
},
'Sage/UI/Alarms/nls/zh/JobNotificationButton':function(){
define('Sage/UI/Alarms/nls/zh/JobNotificationButton',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportWizardController':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportWizardController',{});
},
'Sage/MainView/JobMgr/nls/zh/JobDefinitionsListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh/JobDefinitionsListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/RecurringEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportsUtility':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportsUtility',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/DateRangeParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/DateRangeParameterEditor',{});
},
'Sage/MainView/ReportMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/DateParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/DateParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor',{});
},
'Sage/Library/nls/zh/FolderHandler':function(){
define('Sage/Library/nls/zh/FolderHandler',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/EditableGrid':function(){
define('Sage/UI/nls/zh/EditableGrid',{});
},
'Sage/MainView/IntegrationContract/nls/zh/SalesQuoteRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/SalesQuoteRTDV',{});
},
'Sage/MainView/SecurityMgr/nls/zh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh/SecurityProfile',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportWizardController':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportWizardController',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportManagerUtility':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportManagerUtility',{});
},
'Sage/UI/nls/zh/SpeedSearch':function(){
define('Sage/UI/nls/zh/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/ReportManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/ReportManagerTasksTasklet',{});
},
'Sage/UI/nls/zh/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh/UnconfirmedPane',{});
},
'Sage/Utility/nls/zh/Utility':function(){
define('Sage/Utility/nls/zh/Utility',{});
},
'Sage/QuickForms/Design/nls/zh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Address':function(){
define('Sage/UI/Controls/nls/zh/Address',{});
},
'Sage/MainView/JobMgr/nls/zh/JobManagerGroupContextService':function(){
define('Sage/MainView/JobMgr/nls/zh/JobManagerGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/OwnerControlDesigner',{});
},
'Sage/TaskPane/nls/zh/JobManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/JobManagerTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityEditorAttendeesTab',{});
},
'Sage/UI/nls/zh/UserType':function(){
define('Sage/UI/nls/zh/UserType',{});
},
'Sage/QuickForms/Design/nls/zh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar',{});
},
'Sage/Utility/nls/zh/Jobs':function(){
define('Sage/Utility/nls/zh/Jobs',{});
},
'Sage/UI/Controls/nls/zh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/ActivityList':function(){
define('Sage/UI/nls/zh/ActivityList',{});
},
'Sage/UI/Alarms/nls/zh/JobNotificationPopup':function(){
define('Sage/UI/Alarms/nls/zh/JobNotificationPopup',{});
},
'Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/LeadLookupConfig':function(){
define('Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh/LeadLookupConfig',{});
},
'Sage/MainView/ReportMgr/nls/zh/SchedulesListPanelConfig':function(){
define('Sage/MainView/ReportMgr/nls/zh/SchedulesListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportManagerGroupContextService':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportManagerGroupContextService',{});
},
'Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zh/Attachment':function(){
define('Sage/Utility/File/nls/zh/Attachment',{});
},
'Sage/QuickForms/Design/nls/zh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/GenericControlDesigner',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/StringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/StringParameterEditor',{});
},
'Sage/QuickForms/Design/nls/zh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh/PropertyEditorContainer',{});
},
'Sage/Services/nls/zh/ReportingService':function(){
define('Sage/Services/nls/zh/ReportingService',{});
},
'Sage/MailMerge/nls/zh/Helper':function(){
define('Sage/MailMerge/nls/zh/Helper',{});
},
'Sage/UI/Dashboard/nls/zh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zh/PickList':function(){
define('Sage/UI/Controls/nls/zh/PickList',{});
},
'Sage/MainView/ActivityMgr/nls/zh/HistoryEditorAttendeesTab':function(){
define('Sage/MainView/ActivityMgr/nls/zh/HistoryEditorAttendeesTab',{});
},
'Sage/Utility/nls/zh/Email':function(){
define('Sage/Utility/nls/zh/Email',{});
},
'Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/zh/TimeZoneItem':function(){
define('Sage/UI/nls/zh/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/zh/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh/SlxEdit',{});
},
'Sage/Reporting/nls/zh/Enumerations':function(){
define('Sage/Reporting/nls/zh/Enumerations',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportConditionsDialog':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/CrystalReportConditionsDialog',{});
},
'Sage/Extensions/Activity/ListPanelOverrides/nls/zh/ActivityListPanelConfig':function(){
define('Sage/Extensions/Activity/ListPanelOverrides/nls/zh/ActivityListPanelConfig',{});
},
'Sage/UI/nls/zh/JobSchedulingWidget':function(){
define('Sage/UI/nls/zh/JobSchedulingWidget',{});
},
'Sage/UI/Controls/nls/zh/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ReportMgr/Crystal/nls/zh/MultiselectStringParameterEditor':function(){
define('Sage/MainView/ReportMgr/Crystal/nls/zh/MultiselectStringParameterEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EditEventEditor',{});
},
'Sage/MailMerge/nls/zh/Loader':function(){
define('Sage/MailMerge/nls/zh/Loader',{});
},
'Sage/UI/Controls/nls/zh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh/DateTimePicker',{});
},
'Sage/MainView/ReportMgr/nls/zh/ReportManagerActions':function(){
define('Sage/MainView/ReportMgr/nls/zh/ReportManagerActions',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPopup',{});
},
'Sage/MainView/Contact/nls/zh/ContactUserAssociationEditor':function(){
define('Sage/MainView/Contact/nls/zh/ContactUserAssociationEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor',{});
},
'Sage/MainView/JobMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/JobMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Lookup':function(){
define('Sage/UI/Controls/nls/zh/Lookup',{});
},
'Sage/Utility/File/nls/zh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/CommonTasksTasklet',{});
},
'Sage/Utility/nls/zh/Dashboard':function(){
define('Sage/Utility/nls/zh/Dashboard',{});
}}});
define("Sage/nls/Sage_zh", [], 1);
