define((
{ yestText: 'Sì',
  noText: 'No',
  confirmOverwriteFileMsg: 'Hai un file importazione attualmente selezionato. Vuoi sovrascriverlo?',
  importProgressCaption: 'Risultati del processo di importazione',
  lblPrimaryProgress: 'Elaborazione del file di importazione attendere prego...',
  lblTotalRecords: 'Totale record:',
  lblTotalRecordsProcessed: 'Elaborati:',
  lblTotalRecordsImported: 'Importati:',
  lblTotalRecordsMerged: 'Uniti:',
  lblTotalDuplicates: 'Duplicati:',
  lblTotalProjectedDuplicates: 'Duplicati previsti:',
  lblDuplicateRate: 'Percentuale duplicati:',
  lblTotalErrors: 'Errori:',
  calculatingText: 'Calcolo in corso attendere prego...',
  importStatusProcessing: 'Elaborazione in corso',
  importStatusCompleted: 'Completato',
  abortImportProcessStatus: 'Interrompi',
  btnCancelText: 'Interrompi',
  btnCloseText: 'Chiudi',
  lblImportHistoryLinkText: 'Per visualizzare i risultati della cronologia importazione fare clic sul numero qui sotto:',
  lblImportLinkNumber: 'Numero Importazione: ',
  errorRequestImportHistory: 'Si è verificato un errore esecuzione della richiesta di esecuzione sdata per endpoint importHistory.' }
));