define((
{ titleText: 'Avanzate',
  appearanceText: 'Aspetto',
  behaviorText: 'Comportamento',
  controlInfoText: 'Info sul controllo',
  dataText: 'Dati',
  allowMultiplesText: 'Consente la selezione multipla:',
  allowMultiplesTooltipText: 'Permette di selezionare più di un elemento.',
  canEditTextText: 'Possibile modificare il testo:',
  canEditTextTooltipText: 'Consente utente di digitare un valore.',
  controlIdText: 'ID Controllo:',
  controlIdTooltipText: 'Identificatore per questo controllo.',
  controlLabelPlacementText: 'Posizione Etichetta:',
  controlLabelPlacementTooltipText: 'Posizione etichetta in relazione al controllo.',
  controlTypeText: 'Tipo di controllo:',
  controlTypeTooltipText: 'Tipo di controllo Saleslogix.',
  defaultDataBindingText: 'Data Bindings:',
  defaultDataBindingTooltipText: 'Campo nel database utilizzato da questo controllo.',
  displayModeText: 'Display Mode:',
  displayModeTooltipText: 'Modalità di visualizzazione del controllo: casella di testo, collegamenti ipertestuali o testo normale.',
  enabledText: 'Abilitato:',
  enabledTooltipText: 'Consente utente di interagire con questo controllo.',
  maxLengthText: 'Max Length:',
  maxLengthTooltipText: 'Numero massimo di caratteri che utente può inserire.',
  mustExistInListText: 'elemento deve esistere:',
  mustExistInListTooltipText: 'Richiede che un valore inserito debba essere sulla lista.',
  pickListNameText: 'Nome Elenco di Selezione:',
  pickListNameTooltipText: 'Nome elenco di valori che utente può selezionare da quando inserisce i dati.',
  requiredText: 'Obbligatorio:',
  requiredTooltipText: 'Richiede un valore durante il salvataggio di dati.',
  storageModeText: 'Modalità di archiviazione:',
  storageModeTooltipText: 'Come il valore viene archiviato: testo, Id o codice.',
  visibleText: 'Visibile:',
  visibleTooltipText: 'Mostra o nasconde questo controllo nella form.',
  labelPlacementText: { left: 'Sinistra', right: 'Destra', top: 'Top', none: 'Nessuno' },
  displayModeTypeText: 
   { AsControl: 'Come Controllo',
     AsText: 'Come Testo',
     AsHyperlink: 'Come Collegam. ipertestuale' },
  storageModeTypeText: { Text: 'Testo', Id: 'ID', Code: 'Codice' },
  pickListRequestErrorText: 'Impossibile recuperare gli elenchi di selezione dal server.' }
));