define({
    lblCreateSchedule: 'Создать расписание задания для запуска',
    lblEveryText: 'Каждый',
    lblOnText: 'в',
    lblOnTheText: 'в',
    lblAtText: 'в',
    lblMinutesPastHour: 'мин. после часа',
    lblFromTimeText: 'Выполнять с',
    lblToTimeText: 'по',
    lblMinutesFrequency: 'мин.',
    lblHourlyFrequency: 'ч.',
    lblDailyFrequency: 'дн.',
    lblWeekDayFrequency: 'будний день',
    lblWeeklyFrequency: 'нед.',
    lblMonthlyFrequency: 'мес.',
    lblYearlyFrequency: 'г.',
    lblSunday: 'Воскресенье',
    lblMonday: 'Понедельник',
    lblTuesday: 'Вторник',
    lblWednesday: 'Среда',
    lblThursday: 'Четверг',
    lblFriday: 'Пятница',
    lblSaturday: 'Суббота',
    lblFirstDay: '1',
    lblSecondDay: '2',
    lblThirdDay: '3',
    lblFourthDay: '4',
    lblCronExpressionText: 'Cron-выражение',
    txtInvalidScheduleTitle: 'Неверный Расписание',
    txtInvalidDatesMessage: 'Время окончания должно быть после времени начала. Пожалуйста, исправьте эту информацию, прежде чем продолжить.',
    txtInvalidScheduleTime: 'Начальная и конечная раз указанные предотвратит этот график запуск. Пожалуйста, исправьте эту информацию, прежде чем продолжить.',
    txtInvalidStartDate: 'Дата начала требуется. Пожалуйста, указать дату начала, прежде чем продолжить.',
    txtInvalidEndDate: 'Дата окончания не требуется. Введи Конечная дата, прежде чем продолжить.'
});