define({
    lblCreateSchedule: 'Создать расписание задания для запуска',
    lblEveryText: 'Каждый',
    lblOnText: 'в',
    lblOnTheText: 'в',
    lblAtText: 'в',
    lblMinutesPastHour: 'мин. после часа',
    lblFromTimeText: 'Выполнять с',
    lblToTimeText: 'по',
    lblMinutesFrequency: 'мин.',
    lblHourlyFrequency: 'ч.',
    lblDailyFrequency: 'дн.',
    lblWeekDayFrequency: 'будний день',
    lblWeeklyFrequency: 'нед.',
    lblMonthlyFrequency: 'мес.',
    lblYearlyFrequency: 'г.',
    lblSunday: 'Воскресенье',
    lblMonday: 'Понедельник',
    lblTuesday: 'Вторник',
    lblWednesday: 'Среда',
    lblThursday: 'Четверг',
    lblFriday: 'Пятница',
    lblSaturday: 'Суббота',
    lblFirstDay: '1',
    lblSecondDay: '2',
    lblThirdDay: '3',
    lblFourthDay: '4',
    lblCronExpressionText: 'Cron-выражение',
    txtInvalidScheduleTitle: 'Invalid Schedule',
    txtInvalidDatesMessage: 'The end time must be after the start time. Please correct this information before continuing.',
    txtInvalidScheduleTime: 'The start and end times specified will prevent this schedule from running. Please correct this information before continuing.',
    txtInvalidStartDate: 'A start date is required. Please specify a start date before continuing.',
    txtInvalidEndDate: 'A end date is required. Please specify a end date before continuing'
});