define({
    lblCreateSchedule: 'Crea pianificazione lavori da eseguire',
    lblEveryText: 'Ogni',
    lblOnText: 'di',
    lblOnTheText: 'il',
    lblAtText: 'a',
    lblMinutesPastHour: 'minuti dopo ora',
    lblFromTimeText: 'Esegui da',
    lblToTimeText: 'a',
    lblMinutesFrequency: 'minuti',
    lblHourlyFrequency: 'ora/e',
    lblDailyFrequency: 'giorno',
    lblWeekDayFrequency: 'giorno feriale',
    lblWeeklyFrequency: 'settimana',
    lblMonthlyFrequency: 'mese',
    lblYearlyFrequency: 'anno',
    lblSunday: 'Domenica',
    lblMonday: 'Lunedì',
    lblTuesday: 'Martedì',
    lblWednesday: 'Mercoledì',
    lblThursday: 'Giovedì',
    lblFriday: 'Venerdì',
    lblSaturday: 'Sabato',
    lblFirstDay: 'primo',
    lblSecondDay: 'secondo',
    lblThirdDay: 'terzo',
    lblFourthDay: 'quarto',
    lblCronExpressionText: 'Espressione Cron',
    txtInvalidScheduleTitle: 'Orario Valido',
    txtInvalidDatesMessage: "L'ora di fine deve essere successiva all'ora di inizio. Si prega di correggere queste informazioni prima di continuare.",
    txtInvalidScheduleTime: 'I tempi di inizio e di fine specificate impediranno questa pianificazione esecuzione. Si prega di correggere queste informazioni prima di continuare.',
    txtInvalidStartDate: 'È necessaria una data di inizio. Si prega di specificare una data di inizio prima di continuare.',
    txtInvalidEndDate: 'È necessaria una data di fine. Si prega di specificare una data di fine prima di continuare.'
});