define({
    lblCreateSchedule: 'Créer un planning de tâches à exécuter',
    lblEveryText: 'Tous les',
    lblOnText: 'le',
    lblOnTheText: 'le',
    lblAtText: 'à',
    lblMinutesPastHour: 'minutes après heure',
    lblFromTimeText: 'Exécuter depuis',
    lblToTimeText: 'vers',
    lblMinutesFrequency: 'minutes',
    lblHourlyFrequency: 'heure(s)',
    lblDailyFrequency: 'jour',
    lblWeekDayFrequency: 'jour de la semaine',
    lblWeeklyFrequency: 'semaine',
    lblMonthlyFrequency: 'mois',
    lblYearlyFrequency: 'année',
    lblSunday: 'Dimanche',
    lblMonday: 'Lundi',
    lblTuesday: 'Mardi',
    lblWednesday: 'Mercredi',
    lblThursday: 'Jeudi',
    lblFriday: 'Vendredi',
    lblSaturday: 'Samedi',
    lblFirstDay: 'premier',
    lblSecondDay: 'deuxième',
    lblThirdDay: 'troisième',
    lblFourthDay: 'quatrième',
    lblCronExpressionText: 'Expression Cron',
    txtInvalidScheduleTitle: 'Horaire Valide',
    txtInvalidDatesMessage: "L'heure de fin doit être postérieure à l'heure de début. S'il vous plaît corriger ces informations avant de continuer.",
    txtInvalidScheduleTime: "Les heures de début et de fin spécifiées seront empêcher ce programme de s'exécuter. S'il vous plaît corriger ces informations avant de continuer.",
    txtInvalidStartDate: "Une date de démarrage est nécessaire. S'il vous plaît spécifier une date de début avant de poursuivre.",
    txtInvalidEndDate: "A la date de fin est nécessaire. S'il vous plaît spécifier une date de fin avant de poursuivre."
});