define((
{ contractText: 'Contrat',
  contractRequiredText: 'Vous devez sélectionner un contrat',
  sdataUrlText: 'URL SData',
  titleText: 'Titre',
  usernameText: 'Nom utilisateur',
  passwordText: 'Mot de passe',
  logOnText: 'Connexion',
  urlRequiredText: 'Vous devez saisir une URL SData',
  urlImproperFormatText: 'Format de URL SData non valide. Exemple : http://localhost/sdata/slx/dynamic/-/',
  customNoAuthText1: 'Impossible de traiter votre demande. Les informations concernant autorisation de ce flux sont incorrectes ou introuvables.',
  customNoAuthText2: 'Veuillez mettre à jour votre nom utilisateur et votre mot de passe pour :',
  feedText: 'Flux SData',
  urlAuthenticationText: 'Saisissez un flux SData personnalisé',
  selectFeedText: 'Sélectionnez un flux',
  nextText: 'Suivant&gt;',
  warningText: 'Informations',
  invalidWhereText: 'Clause "Where" non valide. Vérifiez que la clause "Where" ne contient pas erreur. Pour plus informations, consultez la rubrique "Création une clause Where".',
  failedToLoadUrlText: 'Échec du chargement du flux demandé. Sélectionnez un autre flux ou contactez administrateur système.',
  noFeedSelectedText: 'Vous avez sélectionné aucun type de champ',
  resourceText: 'Ressource',
  whereText: 'Clause Where',
  previousText: '&lt;Précédent',
  noResourceSelectedText: 'Sélectionnez une ressource',
  noColumnsSelectedText: 'Sélectionnez une ou plusieurs colonnes à afficher dans le widget.',
  limitRangeText: 'Saisissez une valeur comprise entre 1 et 100',
  testText: 'Test',
  cancelText: 'Annuler',
  finishText: 'Terminer',
  exampleQueryText1: 'Exemple :',
  exampleQueryText2: 'adresse IP de la machine',
  exampleQueryText3: 'numéro du port',
  exampleWhereText: 'En savoir plus',
  numberRecordsText: 'Enregistrements visibles',
  sageSalesLogixDynamic: 'Saleslogix Dynamic Entity',
  sageSalesLogixSystem: 'Saleslogix System',
  selectColumnsFromText: 'Colonnes disponibles :',
  selectedColumnsFromText: 'Colonnes sélectionnées :' }
));