define({
    lblCreateSchedule: 'Créer un planning de tâches à exécuter',
    lblEveryText: 'Tous les',
    lblOnText: 'le',
    lblOnTheText: 'le',
    lblAtText: 'à',
    lblMinutesPastHour: 'minutes après heure',
    lblFromTimeText: 'Exécuter depuis',
    lblToTimeText: 'vers',
    lblMinutesFrequency: 'minutes',
    lblHourlyFrequency: 'heure(s)',
    lblDailyFrequency: 'jour',
    lblWeekDayFrequency: 'jour de la semaine',
    lblWeeklyFrequency: 'semaine',
    lblMonthlyFrequency: 'mois',
    lblYearlyFrequency: 'année',
    lblSunday: 'Dimanche',
    lblMonday: 'Lundi',
    lblTuesday: 'Mardi',
    lblWednesday: 'Mercredi',
    lblThursday: 'Jeudi',
    lblFriday: 'Vendredi',
    lblSaturday: 'Samedi',
    lblFirstDay: 'premier',
    lblSecondDay: 'deuxième',
    lblThirdDay: 'troisième',
    lblFourthDay: 'quatrième',
    lblCronExpressionText: 'Expression Cron',
    txtInvalidScheduleTitle: 'Invalid Schedule',
    txtInvalidDatesMessage: 'The end time must be after the start time. Please correct this information before continuing.',
    txtInvalidScheduleTime: 'The start and end times specified will prevent this schedule from running. Please correct this information before continuing.',
    txtInvalidStartDate: 'A start date is required. Please specify a start date before continuing.',
    txtInvalidEndDate: 'A end date is required. Please specify a end date before continuing'
});