define((
{ titleText: 'Avancé',
  appearanceText: 'Apparence',
  behaviorText: 'Comportement',
  controlInfoText: 'Info contrôle',
  dataText: 'Données',
  buttonToolTipText: 'Info-bulle de bouton :',
  buttonToolTipTooltipText: 'info-bulle à afficher lorsque utlisateur déplace le curseur de la souris sur la partie bouton du contrôle.',
  controlIdText: 'ID de contrôle :',
  controlIdTooltipText: 'Identifiant pour ce contrôle.',
  controlLabelPlacementText: 'Placement des étiquettes :',
  controlLabelPlacementTooltipText: 'Position des étiquettes par rapport au contrôle.',
  controlTypeText: 'Type de contrôle :',
  controlTypeTooltipText: 'Type de contrôle Saleslogix.',
  defaultDataBindingText: 'Associations de données :',
  defaultDataBindingTooltipText: 'Champ(s) de données dans la base de données utilisée par ce contrôle.',
  displayModeText: 'Mode affichage :',
  displayModeTooltipText: 'Mode affichage du contrôle : zone de texte, lien hypertexte ou texte brut.',
  enabledText: 'Activé :',
  enabledTooltipText: 'Permet à utilisateur interagir avec ce contrôle.',
  requiredText: 'Obligatoire :',
  requiredTooltipText: 'Requiert une valeur lors de enregistrement des données.',
  timelessText: 'Heure indéfinie :',
  timelessTooltipText: 'Utiliser la date sans heure et sans conversion DST.',
  visibleText: 'Visible :',
  visibleTooltipText: 'Afficher ou masquer ce contrôle sur le formulaire.',
  labelPlacementText: { left: 'Gauche', right: 'Droite', top: 'Haut', none: 'Aucun' },
  displayModeTypeText: 
   { AsControl: 'Comme contrôle',
     AsText: 'Comme texte',
     AsHyperlink: 'Comme lien hypertexte' } }
));