define((
{ dlgReportScheduleDetails_Schedule_Title: 'Aggiungi/Modifica pianificazione',
  dlgReportScheduleDetails_RunReport_Title: 'Esegui rapporto',
  txtReportType_Caption: 'Tipo rapporto',
  txtReportName_Caption: 'Nome rapporto',
  txtOutputFormat_Caption: 'Formato',
  txtRunAs_Caption: 'Esegui come',
  txtScheduleName_Caption: 'Nome pianificazione',
  txtScheduleDescription_Caption: 'Descrizione',
  cmbScheduleFrequency_Caption: 'Frequenza',
  cmbArchive_Caption: 'Archivia rapporti più vecchi di',
  dtStartTime_Caption: 'Esegui dal',
  dtEndTime_Caption: 'Esegui al',
  txtRepeatCount_Caption: 'Numero ripetizioni',
  txtRepeatInterval_Caption: 'Intervallo ripetizione',
  cmdOK_Caption: 'OK',
  cmdCancel_Caption: 'Annulla',
  tabSchedule_Caption: 'Dettagli pianificazione',
  txtOnDemandScheduleName: 'Su richiesta',
  txtReportSuccessfullyScheduled: 'Rapporto pianificato.',
  dlgScheduleReport_Title: 'Pianifica rapporto',
  txtName: 'Nome',
  txtSelectUser: 'Seleziona utente',
  txtOK: 'OK' }
));