define((
{ titleScheduleText: 'Planification un événement',
  titleEditText: 'Modifier un événement',
  lblDayTypeText: 'Type de jour :',
  lblStartDateText: 'Date de début :',
  lblEndDateText: 'Date de fin :',
  lblUserText: 'Utilisateur :',
  lookupUserText: 'Rechercher un utilisateur',
  lblCategoryText: 'Catégorie :',
  lblLocationText: 'Emplacement :',
  lblDescriptionText: 'Description :',
  btnOkayText: 'OK',
  btnCancelText: 'Annuler',
  btnHelpText: 'Aide',
  eventTypeActiveText: 'Actif',
  eventTypeBusinessTripText: 'Voyage affaires',
  eventTypeConferenceText: 'Conférence',
  eventTypeHolidayText: 'Congés',
  eventTypeOffText: 'Désactivé',
  eventTypeTradeShowText: 'Salon commercial',
  eventTypeUnavailableText: 'Non disponible',
  eventTypeVacationText: 'Vacances',
  errorText: 'Impossible de créer événement car une erreur est produite.',
  invaildDatesText: 'La date de fin ne peut être antérieure à la date de début.',
  nameText: 'Nom' }
));